### ISSUE TITLE
Notice (Important)

### ISSUE THREAD

**Issue by IISweePII** [TesseractTeam/Tesseract#1]
The Tesseract server software has been reverted to a recent commit, thanks to @xZeroMCPE for doing that part. I do not know what has happened, but the server software was deleted from GitHub and it did not exist for a good amount of time. Everything is all good now, and we can resume committing to this software as normal :)

**Comment by remotevase** [comment]
Hello all! We are working on contacting Github Support as well so that the wiki and other repos are also restored (wingproxy and php binaries...)

**Comment by IISweePII** [comment]
That's good :)

**Comment by ImagicalGamer** [comment]
Me and Apple made the executive decision as the founders of this project to discontinue it. Please do not make ANOTHER repo.

**Comment by Nought57** [comment]
Why project to discontinue??

**Comment by ImagicalGamer** [comment]
Commit and makes PR's to PMMP or Genisys, continue those softwares. There is no need for another server software in PHP. Thats how the original pocketmine died.

**Comment by Nought57** [comment]
I understand, but many problem.

**Comment by Nought57** [comment]
another server software in PHP not alone the Tesseract.

**Comment by Nought57** [comment]
Missing

**Comment by AppleDevelops** [comment]
@ImagicalGamer Let them keep it, it doesn't matter to us if it dies or not. We focus on our stuff they focus on their stuff.

**Comment by AppleDevelops** [comment]
It's already had a good enough start that they can continue it

**Comment by Nought57** [comment]
Need Tesseract Project.

**Comment by xZeroMCPE** [comment]
Well continues
