### ISSUE TITLE
Are you going to redevelop Tesseract?

### ISSUE THREAD

**Issue by shdudwns** [TesseractTeam/Tesseract#1]
Are you going to redevelop Tesseract?
@DrewD3V

**Comment by DrewD3V** [comment]
I'm actually not going to update it to 1.2 until a later version comes out. Pretty much maintaining older versions.

**Comment by shdudwns** [comment]
Why not support 1.2.x?
@DrewD3V

**Comment by DrewD3V** [comment]
I'd rather not make it a long term thing.

**Comment by shdudwns** [comment]
Does it support only 1.1.x?
@DrewD3V

**Comment by shdudwns** [comment]
And how do you join the team?

**Comment by DrewD3V** [comment]
It doesn't support 1.1.x, it supports 1.0.x as of rn and there is a branch that supports 0.16.x. I'm on the team because I founded Tesseract.

**Comment by shdudwns** [comment]
I would like to join TesseractTeam
@DrewD3V
