### ISSUE TITLE
I AM OUT, cya! -_-

### ISSUE THREAD

**Issue by NFGamerMC** [TesseractTeam/Tesseract#1002]
[removed due to ----]

**Comment by MCPEGamerJPatGitHub** [comment]
@NFGamerMC I can just make a test server if I want to. Linux has a lot of money too. Your help means nothing

**Comment by NFGamerMC** [comment]
1. I'm not bragging about cash
2. What did I do to you
3. How am I the bad guy
4. Linux broke Tesseract!

**Comment by Prisane** [comment]
You disrupt order and broke Tesseract and you talk too much. You deserve to be banned.

**Comment by NFGamerMC** [comment]
Tesseract is DEAD! This software is not stable, not under the correct management, and has terribly unhelpful owners. If you care this much about Tesseract then you have other issues to worry about

**Cant people move on, also @jrodr10 broke Tesseract because he was scaredthat it would die, so he decided to kill it faster!**

**Comment by NFGamerMC** [comment]
Also, it is called standing up. Not "talking to much"

**Comment by Prisane** [comment]
You are constantly spamming and acting childly. This not called standing up.

**Comment by NFGamerMC** [comment]
Welp, I'm heading over to BlueLight and going to spread Tesseract awareness. **When I'm don't with this there will be nothing left!**

**Comment by Prisane** [comment]
Good luck and bye. :)

**Comment by MCPEGamerJPatGitHub** [comment]
lol he doesn't know that Bluelight is the most messed up spoon of PocketMine

**Comment by AppleDevelops** [comment]
Stop the constant spamming

**Comment by NFGamerMC** [comment]
Okay, please read my comment on the other one

**Comment by jrodr10** [comment]
Thought I banned this guy already. 🙄 @AppleDevelops bruh did you unban him

**Comment by AppleDevelops** [comment]
@jrodr10 I can't ban anyone since your takeover
