### ISSUE TITLE
jrodr10

### ISSUE THREAD

**Issue by NFGamerMC** [TesseractTeam/Tesseract#1003]
Hello,
I would just like to say I am leaving Tesseract. 

**Remember: I will always return and when I retry here will be nothing left!**

**Comment by AppleDevelops** [comment]
Cya

**Comment by NFGamerMC** [comment]
This is not meant to be spam, also can you kick jrodr10. I don't care if you don't add me back I just want him out

**Comment by NFGamerMC** [comment]
Okay, I will stop spamming. Please make Tesseract right though. 100's of servers are depending on it

**Comment by TDMidkwhatisxd** [comment]
apple, welcome back <3
