### ISSUE TITLE
World generator.

### ISSUE THREAD

**Issue by seetch** [TesseractTeam/Tesseract#1004]
Can we create a normal generator? For example, Nukkit.

**Comment by Qimie** [comment]
A bit hard. But its not impossible. @NycuRO tried the best

**Comment by NycuRO** [comment]
Sorry, i'm not create one generator for one fucking stealer.

**Comment by AppleDevelops** [comment]
Oh whale

**Comment by ralphblogz** [comment]
Hmm... I think by putting a plugin inside the software... :/

Like ManyWorlds

**Comment by Qimie** [comment]
Can we focused on vanilla features first!?!?!!!

**Comment by MalakasPlayzMC** [comment]
Try this: https://github.com/Ad5001/BetterGen

**Comment by Qimie** [comment]
I forgot that Ad made that plugin
