### ISSUE TITLE
Nether

### ISSUE THREAD

**Issue by Shadow166050** [TesseractTeam/Tesseract#1005]
#### Problem description
Nether is a regular world with a red sky

#### Steps to reproduce the issue
Generate a nether world

#### OS and versions

* Tesseract: Tesseract-1.2.1 RottenApple
* PHP: 7.0.3
* Server OS: Ubuntu
* Game version: 1.0.7
* Server host: MinersPlanet
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files
n/a
```
```

**Comment by NycuRO** [comment]
Hahahahaahhahahahaha, easy to fix.

**Comment by Shadow166050** [comment]
Then fix it instead of laughing

**Comment by lowingly** [comment]
When I go to the nether：
Warning: assert(): Unhandled player action 14 from lowing failed in C:\Users\COCOD\Desktop\4.24\src\pocketmine\Player.php on line 2586

The client will always show:
Generating map ...

Look forward to repair。O-O！

**Comment by NycuRO** [comment]
Hehe, isn't this problem for generating :P

**Comment by caspervanneck** [comment]
@NycuRO fix it if its easy

**Comment by NycuRO** [comment]
@caspervanneck I'm not create PR for one fucking stealer, sorry.

**Comment by AppleDevelops** [comment]
And we don't need your contribution

**Comment by NycuRO** [comment]
He's fucking stealer of your project :P

**Comment by NycuRO** [comment]
For me , he suck my dick

**Comment by jrodr10** [comment]
We are all on the same side here lol, little trouble in paradise never hurt anyone. You don't have to contribute if you don't want to but if you don't this project will die. I'm not experienced with PHP much I'm merly here to ensure this repo isn't deleted again. My primarily language is Java or C++(working on the c++ part xD)

**Comment by jrodr10** [comment]
@NycuRO ^

**Comment by Shadow166050** [comment]
I reported a bug an instead of a fix i get a childish argument smh

**Comment by AppleDevelops** [comment]
I'm gonna work on it later

**Comment by TorchPE** [comment]
The project will die anyways. You are just accelerating the death! Now give Apple back the repo. NF told me all about you

**Comment by bioaim4** [comment]
I wish they will stop acting like there developers and give the repo back to the real Owners this repo will die on next update it don't even work already.

**Comment by caspervanneck** [comment]
@TorchPE nope

**Comment by IrishPacks** [comment]
To make it where they spawn in after changing dimensions, make sure to send a PlayStatusPacket.
