### ISSUE TITLE
how to import world from MCPE?

### ISSUE THREAD

**Issue by arfianadam** [TesseractTeam/Tesseract#1006]
I tried duplicating the world inside `worlds` folder. but it still couldn't load the imported world and generated a new one instead. how to import world from mcpe?

**Comment by MCPEGamerJPatGitHub** [comment]
@arfianadam only PC maps are supported

**Comment by jrodr10** [comment]
What he said^

**Comment by NFGamerMC** [comment]
Use MCEdit

**Comment by NFGamerMC** [comment]
You can convert MCPE to Tesseract on it
