### ISSUE TITLE
Who is the offical owner of tesseract before it was taken over?

### ISSUE THREAD

**Issue by Fabiansigala** [TesseractTeam/Tesseract#1007]
If the owner sees this please contact me I have some questions

**Comment by Pogogo007** [comment]
@AppleDevelops and @ImagicalGamer

**Comment by ISRAPIL** [comment]
Don't @Pogogo007

**Comment by Pogogo007** [comment]
I never said i was Owner i said Apple and Imagical Gamer

**Comment by Pogogo007** [comment]
I never said i was Owner i said Apple and Imagical Gamer

**Comment by jrodr10** [comment]
Y

**Comment by ImagicalGamer** [comment]
Me and @AppleDevelops

**Comment by AppleDevelops** [comment]
Me and @ImagicalGamer

**Comment by Fabiansigala** [comment]
@AppleDevelops and @ImagicalGamer agicalgamermight be able to get all your hard work back contact me now! Fabiansigala@yahoo.com

**Comment by jrodr10** [comment]
Lol

**Comment by TorchPE** [comment]
Liar! Apple and Imagical did

**Comment by Fabiansigala** [comment]
@AppleDevelops and @ImagicalGamer go to https://github.com/TesseractTeam/Tesseract/issues/1018
