### ISSUE TITLE
Updating the PHP Bin

### ISSUE THREAD

**Issue by PragaKart67z** [TesseractTeam/Tesseract#101]
How and where can I find the bin file to update PHP on my server? I am using Linux so if you tell me the SSH commands I can figure it out. I am trying to update the PHP version and haven't been successful in doing so. If someone would leave a detailed tutorial it would be greatly appreciated.

**Comment by xZeroMCPE** [comment]
@PragaKart67z  Try this, https://bintray.com/package/files/pocketmine/PocketMine/Unix-PHP-Binaries

It has all kind of bins, for different os, etc
