### ISSUE TITLE
the furnace can be opened in create mode

### ISSUE THREAD

**Issue by lowingly** [TesseractTeam/Tesseract#1017]
Creation mode: the furnace can be opened.
I think it should not be opened in create mode？ O_O？

Tesseract-1.2.1 (代号 "RottenApple")
PHP 版本: 7.0.8
API: 3.0.1 (iTX API 版本 {%1})
Minecraft PE v1.0.7 (protocol 版本
Protocol version: 10
WINDOW 8

**Comment by jrodr10** [comment]
So can chests thoe. Only if limited creative isn't toggled

**Comment by ImagicalGamer** [comment]
Please enable limited creative, this isnt an issue.

**Comment by lowingly** [comment]
Yes, the limited creative is true.
but I still could open the furnace.

**Comment by caspervanneck** [comment]
its working for me

**Comment by lowingly** [comment]
Maybe my description is unclear. Look at the picture.....
![161c21ae40818914e95c059108983cfb](https://cloud.githubusercontent.com/assets/18659344/25429439/fd0f9c98-2a46-11e7-94ad-c7e6bce1754c.png)
![65ee503aca458beb137247f2c70142cb](https://cloud.githubusercontent.com/assets/18659344/25429440/007f41a8-2a47-11e7-8227-ee3c8c4d1434.png)

I can open it....when the limited creative: true

**Comment by caspervanneck** [comment]
confirmed

**Comment by EricaValgas** [comment]
Go here now https://github.com/TesseractTeam/Tesseract/issues/1038

**Comment by jrodr10** [comment]
🤔
