### ISSUE TITLE
PRIVATE CHAT WITH OFFICAL OWNERS ABOUT TESSERACT!!!!!

### ISSUE THREAD

**Issue by Fabiansigala** [TesseractTeam/Tesseract#1018]
I want a private char with the REAL AND `OFFICIAL` OWNERS @AppleDevelops and @ImagicalGamer  if you see this please reply I have very important news about Tesseract

**Comment by Fabiansigala** [comment]
I have made a team called TesseractBackups were if something happens there will be backups of Tesseract backupp and the back up is before Linux took over!I

@AppleDevelops , Me , @ImagicalGamer Have Owned to edit the backups to try to keep yesterday alive


Httos://Github.com/TesseractBackups

**Comment by Fabiansigala** [comment]
Of you want me to add anyone else tell me

**Comment by Driesboy** [comment]
its https://github.com/TesseractBackups

**Comment by Fabiansigala** [comment]
Yes

**Comment by Fabiansigala** [comment]
I just need help uploading the .github and src files

**Comment by ZaneWalter** [comment]
Can someone send me the link to tesseract v1.0.7.phar file. Please.

**Comment by jrodr10** [comment]
Another one lol ur legit the 3rd person to try lol

**Comment by Fabiansigala** [comment]
We now are trying to fix the files.
