### ISSUE TITLE
Where is the .phar file

### ISSUE THREAD

**Issue by ZaneWalter** [TesseractTeam/Tesseract#1019]
Hello Developers. I have searched the entire page for Tesseract.phar file but couldnt find it. Can anyone of you provide a link as to how to download it. To be exact the Tesseract v1.0.7.phar file

**Comment by jrodr10** [comment]
Will add later today

**Comment by ZaneWalter** [comment]
Please doI so I need it really bad.

**Comment by bioaim4** [comment]
Download the zip file extract the src file replace your pocketmine-mp.phar file with it make sure you have devtools plugin run the server it should work then do /makeserver or makeserver in console

**Comment by ZaneWalter** [comment]
Nope doesn't work. I tried that.

**Comment by bioaim4** [comment]
If you have twitter contact me at bioaim4 I can send you a 100% working phar because this one is all broken

**Comment by ZaneWalter** [comment]
I have twitter its @zaneCM

**Comment by caspervanneck** [comment]
@ZaneWalter https://111-73522113-gh.circle-artifacts.com/0/tmp/circle-artifacts.QO36Z6y/Tesseract_1.2.1.phar
