### ISSUE TITLE
Player  can't move after proxy teleportation

### ISSUE THREAD

**Issue by Henning-Klatt** [TesseractTeam/Tesseract#102]
After the teleport the player can not move, but he can look around. Besides, his hand is like crazy. Im using the [SynapsePM](https://github.com/iTXTech/SynapsePM) proxy plugin with [Nemisys](https://github.com/iTXTech/Nemisys) proxy. Hope you can fix it!

**Comment by remotevase** [comment]
This is a confirmed bug with SynapsePM. To solve the problem, turn loading screen off. In addition, I have a question: how do you use SynapsePM on Tesseract?

**Comment by Henning-Klatt** [comment]
I've installed the Plugin and boom, it works :D
After i turned the loading screen off everything works fine ^^

**Comment by remotevase** [comment]
yeah but how do you use nemysis on windows?
