### ISSUE TITLE
Resource Pack + Sound Support from Fork.

### ISSUE THREAD

**Issue by caspervanneck** [TesseractTeam/Tesseract#1035]
all code is opensoarce https://github.com/caspervanneck/ImagicalMine

player spawning is working but resource packs are not working

@AppleDevelops @jrodr10

**Comment by Driesboy** [comment]
sound or resource pack support can be added from my bad fork

**Comment by caspervanneck** [comment]
dankje driesboy ik heb ook veel spell fouten

**Comment by jrodr10** [comment]
👀 link to your sound commit on ur fork

**Comment by TacosYum** [comment]
https://github.com/caspervanneck/ImagicalMine/commit/1a3b6c6eaedc826db3d0d8bae72e67f079ab2202

**Comment by EricaValgas** [comment]
Go here now https://github.com/TesseractTeam/Tesseract/issues/1038

**Comment by imjayl** [comment]
How to add texturepack on server?

**Comment by NFGamerMC** [comment]
You need PMMP. Tesseract got rid of that as it wasn't stable

**Comment by jrodr10** [comment]
#999 @caspervanneck fix this please make a PR Thank you

**Comment by jrodr10** [comment]
Do not add resource packs till we can further test them on an alternative branch
