### ISSUE TITLE
OWNERS GO HERE NOW!!!!! 

### ISSUE THREAD

**Issue by EricaValgas** [TesseractTeam/Tesseract#1038]
Someone made this github.com/TesseractBackups
Go there now someone is making tesseract alive again LETS ALL HELP HIM/HER

**Comment by EricaValgas** [comment]
@AppleDevelops and @ImagicalGamer GO HERE NOW!!!!!!!!!!!

**Comment by Fabiansigala** [comment]
Chill

**Comment by Fabiansigala** [comment]
And don't spam

**Comment by caspervanneck** [comment]
@Fabiansigala @EricaValgas why do you steal Tesseract

**Comment by KairusDarkSeeker** [comment]
Omfg skids spotted

**Comment by Fabiansigala** [comment]
@caspervanneck I am not.

**Comment by caspervanneck** [comment]
@Fabiansigala i think its over for me

**Comment by Fabiansigala** [comment]
@caspervanneck ?

**Comment by Fabiansigala** [comment]
@caspervanneck what's over?

**Comment by caspervanneck** [comment]
take a look
#1040

**Comment by Fabiansigala** [comment]
@caspervanneck oh...

**Comment by jrodr10** [comment]
Lol this is stupid and a waste of time

**Comment by imjayl** [comment]
jrodr10 i just want to know how to make Tesseract.phar from zip file

**Comment by EoflaOE** [comment]
@imjayl You can download DevTools plugin and copy it to plugins folder, then do /nameserver whenever the server is on.
