### ISSUE TITLE
AsyncTasks crashes the server

### ISSUE THREAD

**Issue by KairusDarkSeeker** [TesseractTeam/Tesseract#1039]
#### Problem description

When you're scheduling an AsyncTask, the server crashes. 

#### Steps to reproduce the issue

Schedule an AsyncTask

#### OS and versions

* Tesseract: 1.2.1
* PHP: 7.0.15
* Server OS: Ubuntu 16.04.2 LTS
* Game version: 1.0.7
* Server host: [Ovh](https://ovh.com)
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

![Imgur](http://i.imgur.com/TP3y4FB.png)

**Comment by caspervanneck** [comment]
yes its a bug

**Comment by caspervanneck** [comment]
i have it to

**Comment by xISRAPILx** [comment]
You can not use core methods in this task!

**Comment by IrishPacks** [comment]
Are you calling API methods from your onRun method? Because if so, this is your fault not the software.

**Comment by ImagicalGamer** [comment]
This isnt a Tesseract issue. You cannot call Server::getInstance() from within another thread.

**Comment by KairusDarkSeeker** [comment]
@ImagicalGamer I didn't used Server::getInstance() on my task

**Comment by KairusDarkSeeker** [comment]
@IrishPacks I'm calling the api methods from the onCompletion() and what's weird is cURL & file_get_contents() crashes the server from fetching a file

**Comment by Assblocker** [comment]
harvey hans <3
