### ISSUE TITLE
Imminent end

### ISSUE THREAD

**Issue by CaitiffMCPE** [TesseractTeam/Tesseract#1040]
An ancient proverb says : _"Foolish is the soldier ... who knows NOT the face of his enemy ... for all of his weapons will prove useless under the weight of his ignorance"_.

This mysterious **_new_** cast member LinuxLogo... has me wondering... WHAT his motivation is... :)

**Comment by CaitiffMCPE** [comment]
His innocence is too cute, far too cute to understand a piece of code.

**Comment by CaitiffMCPE** [comment]
You can't stop me from kicking this off PMMP

**Comment by CaitiffMCPE** [comment]
Accept defeat.

**Comment by CaitiffMCPE** [comment]
Love how all you can do is close this issue. You are too powerless now. Once you are infront of my eyes, you stand no chance

**Comment by CaitiffMCPE** [comment]
And you call yourself devs. How pathetic. Even Gamer doesn't possess 1% of what I do but still... this is ridiculous. I suppose I should fix things by my self

**Comment by caspervanneck** [comment]
@CaitiffMCPE shut up!

**Comment by CaitiffMCPE** [comment]
I was not talking directly to you @caspervanneck . By "you" I meant the one who had the nerve to even try stealing this repo - not to mention he actually managed to. Try to shape up, you are not involved in this

**Comment by CaitiffMCPE** [comment]
If Linux doesn't return this then I will just have to kick this off which is "easy peazy lemon squeezy". And I know he won't do so, so I am doing it. It is not like he can stop me anyway. It is not like he can come at me. No chance

**Comment by CaitiffMCPE** [comment]
How ironic, it was someone of your own team that notified me about this. Feeling bad to be betrayed, huh? I can be anywhere

**Comment by caspervanneck** [comment]
@CaitiffMCPE sorry and i know that its better to have AppleDevelops as owner and dont like it that it is stollen

**Comment by AppleDevelops** [comment]
@CaitiffMCPE I'd like to see you try to take this repo

**Comment by jrodr10** [comment]
@AppleDevelops if that person can crack 2FA then she or he should code for us 😂

**Comment by AppleDevelops** [comment]
@jrodr10 There is no us.
