### ISSUE TITLE
In survival bow dont work

### ISSUE THREAD

**Issue by Iktaniyalol** [TesseractTeam/Tesseract#1044]
* Tesseract: latest 1.2.1 protocol 107
* PHP: 7.0.9
* Server OS: CentOS 6.8 x86_64
* Game version:  1.0.7
* Server host: dedic on colocation
No plugins. When I in survival gamemode, I can not shoot.

**Comment by PluginBOXone** [comment]
OK. I'll take a look

**Comment by jrodr10** [comment]
@PluginBOXone did you find anything

**Comment by PluginBOXone** [comment]
I can shoot and I am using the latest version too! (You can test it on my server: IP: cyberzone-pe.net Port: 19132) Are you using the W10 edition or Pocket Edition?

**Comment by jrodr10** [comment]
False issue, Get the lastest update!
