### ISSUE TITLE
RakLib Crash Issue

### ISSUE THREAD

**Issue by ObeyBeastJj23** [TesseractTeam/Tesseract#1045]
#### Problem description
Server shows as always on, even if i turn it off on the server host website. No one can join when its "online". Raklib crashes?

 [Network] Stopped interface pocketmine\network\RakLibInterface due to RakLib Thread crashed

#### Steps to reproduce the issue
I really dont know, it just happened

#### OS and versions
I have tried joining on Win 10 and Android
* Tesseract: 1.2.1-RottenApple
* PHP: 7.0.3
* Server OS: Unknown
* Game version: 1.0.7
* Server host: - Removed -
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files
- Removed -
```
```

**Comment by ObeyBeastJj23** [comment]
Resolved by me -

**Comment by PluginBOXone** [comment]
Do you use Linux? If yes, how do you start and stop your server! Because many people make the misstake.

**Comment by jrodr10** [comment]
Reboot your VPS or Dedicated Server. sometimes the thread gets stuck if you leave the putty client open and it disconnects due to inactivity

**Comment by PluginBOXone** [comment]
And install screen with: apt-get install screen

**Comment by EoflaOE** [comment]
It seems that apt-get needs to be root in order to do that with apt. In order to install, you must either be root or use sudo apt-get install screen.
