### ISSUE TITLE
Doneky is not implemented.

### ISSUE THREAD

**Issue by GamakCZ** [TesseractTeam/Tesseract#1046]
#### Problem description

I am trying to spawn donkey, but it does not work.

#### Steps to reproduce the issue

Put the donkey egg.

#### OS and versions

* Tesseract: 1.2.1 Rooten Apple
* PHP: 7
* Server OS: Linux
* Game version: 1.0.7
* Server host: FakaHeda.eu (VPS)
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
-
```

**Comment by PluginBOXone** [comment]
Is there spawning nothing or something like a pig?

**Comment by ImagicalGamer** [comment]
If Donekey's were a mob I would implement them :)
