### ISSUE TITLE
OP's can't join!!

### ISSUE THREAD

**Issue by ZaneWalter** [TesseractTeam/Tesseract#1047]
There is this major bug that is causing the OP's to not bypass and connect to server in whitelist!! Before the update everything was fine an OPs were able to connect to server in whitelist but after the update it would no longer let them connect. Plz fix the issue.

**Comment by jrodr10** [comment]
You have to whitelist anyone who needs to be on the whitelist. They are not automatically added to whitelist upon being op'ed

**Comment by ZaneWalter** [comment]
I have them added still no good.

**Comment by PluginBOXone** [comment]
Are you using Leet or any other hosting platform?

**Comment by ZaneWalter** [comment]
Not at all using Leet. Im using server.pro

**Comment by PluginBOXone** [comment]
Ok. Go into your Console and make /whitelist add YourMCname

**Comment by PluginBOXone** [comment]
Wait. What for **plugins** do you use on your Server?

**Comment by ZaneWalter** [comment]
Umm I forgot to mention this but I tried this. I tried it like 10 times. It would say in the console that as an example Added ZaneWalter to server Whitelist" but when I try to logon the server it would give give me error saying Server is down for maintenance. I would then have to /whitelist off (without / in console)then reconnect and do /whitelist on in game. 

Plugins:
 Plugins (65): BuyXP v1.0.0, BuilderHelper v1.0.3, NewSName v0.0.1, SimpleNoSpam v2.0.0, EconomyAPI v2.0.9, SlapperRotation v1.0.1, ExtraCommands v0.2, TimeCommander v2.1, CombatLogger v1.2.0, SignChanger v1, superBAR v1.6.2, How v1.0.1, ServerMail v0.0.2, DevTools v1.10.0, BetterAdvencedTools v1, EconomyAirport v2.0.4, NameCorrector v1.0.0#build010, FactionsPro v0.1#Beta, MineReset v2.3, PurePerms v1.3.7, BlockBoost v1.0.0, ProxyFirewall v1.0.0, PocketGuard v2.1.1, CommandTracker v1.1, ItemCasePE v1.0.8, DoorLocker v1.0, EconomyShop v2.0.7, EconomySell v2.0.7, CustomAlerts v1.6, AdvancedKits v5.1, EPCooldown v1.0.0, EconomyLand v2.0.9, NoDrops v1.1, ServerAuth v2.13, VoteBan v1.0.3, ReasonWL v2, EssentialsPE v2.0.0, ChatLogin v1.4, SkinStealer v1.0.0, ClearLagg v1.1.0, WorldProtect v2.2.0, VoteReward v3.0.2, iProtector v3.1b, ManyWorlds v2.1.0, ItemCloud v1.3, Slapper v1.3.4, CheckID v1.0-Alpha, Parkour v1.5.2, PlayerSelector v1, Vault v0.1, RealTime v2.1.1, Sell v2, Rotater v1.1.0, TapToDo v2.2.1, NoTP v1.0.5, MegaBan v1.2.4, ItemEffects v2.5.0, WorldEditPotato v1.5, NickName vDeBe, AccidentCaps v0.0.1, PlanB v1.4 Security, AntiVoid v1.0.0, MyPlot v1.1.3, RankUp v0.3.1, PureChat v1.4.0

**Comment by PluginBOXone** [comment]
Rename your plugin-folder to "plugins_old" and restart your server and try it again!

**Comment by PluginBOXone** [comment]
Working?

**Comment by ZaneWalter** [comment]
Idk what it was but i reinstalled all my plugins, deleted and reinstalled the Tesseract.phar file and now everything works. Thanks for the help developers. Closing issue!!

**Comment by PluginBOXone** [comment]
You're welcome!
