### ISSUE TITLE
CAN'T JOIN ON WINDOWS 10 WHIT MY LOCAL SERVER!!

### ISSUE THREAD

**Issue by LewBr** [TesseractTeam/Tesseract#1048]
#### Problem description
CAN'T JOIN ON WINDOWS 10 WHIT MY LOCAL SERVER!!

#### Steps to reproduce the issue
CAN'T JOIN ON WINDOWS 10 WHIT MY LOCAL SERVER IT COMES A MESSAGE ON THE GAME BUT THAT ISN'T A ISSUE BECAUSE DOESN'T SAY ANYTHING ON THE CONSOLE!!!

#### OS and versions

* Tesseract: This server is running Tesseract-1.2.0 Ruby
* PHP: 7.0.11
* Server OS: Minecraft PE v1.1.0.0
* Game version: Windows 10, 1.0.7
* Server host: Home computer
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files
http://prntscr.com/f30y8w
```
```

**Comment by MCPEGamerJPatGitHub** [comment]
Cannot reproduce. Make sure you have the latest stable version installed.

**Comment by MasterOfTheRealm** [comment]
Its due to pureperms. I had the same issue but once i removed pureperms it worked perfectly.

**Comment by LewBr** [comment]
I remove all plugins and i reset all configs and still not working!! fuck
