### ISSUE TITLE
PurePerms Compatibility 

### ISSUE THREAD

**Issue by jrodr10** [TesseractTeam/Tesseract#1049]
-->

* Tesseract: 1.2.1
* PHP: 7.0.14
* Server OS: Ubuntu 16.04
* Game version: 1.0.7
* Server host: OVH

<--

#### Problem description

So you all know, Tesseract has been not allowing people to connect when the plugin PurePerms is in the server. i need you guys to figure out what the cause is. if you dont want to fix it fine ill find someone to fix it but please just figure out the cause so i can have someone work on it with some speed

 Thank you
 Sincerely, LinuxLogo, 
 TesseractTeam, Owner

**Comment by ImagicalGamer** [comment]
PurePerms needs to become compatible with Tesseract not the other way around.

**Comment by jrodr10** [comment]
We are the ones who broke something thoe..

**Comment by jrodr10** [comment]
@ImagicalGamer

**Comment by ImagicalGamer** [comment]
PurePerms is outdated, we updated Tesseract.

**Comment by TheAz928** [comment]
@jrodr10 @ImagicalGamer I got a fix, I removed some codes from PurePerm itself and it got fixed...I think PreLoginEvent is messed up, take a look

**Comment by MCPEGamerJPatGitHub** [comment]
@jrodr10 @ImagicalGamer the pureperm plugin is broken not Tesseract.

**Comment by imjayl** [comment]
@MCPEGamerJPatGithub  But the pureperm works on 1.0.6 it means something is broke in tesseract 1.0.7

**Comment by TheAz928** [comment]
@imjayl @MCPEGamerJPatGithub can anyone check for errors at "PlayerPreLoginEvent"? Or I've to do that?

**Comment by MasterOfTheRealm** [comment]
Tesseract is the problem though. Pureperms works on 1.0.6 without any issues.

**Comment by Assblocker** [comment]
works fine, what u noobs talking bout?

**Comment by caspervanneck** [comment]
@Assblocker  its not working so.....

**Comment by PluginBOXone** [comment]
The funny thing is that i am using the newest version from Tesseract AND PurePerms + PureChat and everything working fine

**Comment by ImagicalGamer** [comment]
Tesseract isnt built to support certain plugins, fix PurePerms. No one broke Tesseract, they merely updated it.

**Comment by jrodr10** [comment]
Do not close my issues @ImagicalGamer

**Comment by jrodr10** [comment]
ah fk it

**Comment by Fabiansigala** [comment]
What if we update PurePurms?
Let's fork it and update it

**Comment by Fabiansigala** [comment]
Try this I updated it and changed the code it should work

**Comment by AppleDevelops** [comment]
Don't tag me in this, I don't support anything to do with linux.

**Comment by Fabiansigala** [comment]
Xd

**Comment by Fabiansigala** [comment]
True dat

**Comment by AppleDevelops** [comment]
All I say is Tesseract is f***ed

**Comment by Nought57** [comment]
Change of Owner without notice, Unknown commit (1.1.0 support), Diminished motivation of developers, and more. Tesseract was over from the beginning.

**Comment by Nought57** [comment]
Tesseract celebrated

**Comment by Fabiansigala** [comment]
@AppleDevelops XD
