### ISSUE TITLE
Xbox login required

### ISSUE THREAD

**Issue by Chaostix404** [TesseractTeam/Tesseract#105]
#### Problem description

When Players Join ,It Keeps Saying "Xbox login required"
Even If The Player Had Logged In To Xbox

#### OS and versions

* Tesseract:Crystal
* PHP:7.0.3
* Server OS:Ubuntu
* Game version: 1.0.0
* Server host:Virmach
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by remotevase** [comment]
Make the server offline

**Comment by remotevase** [comment]
As in turn online mode off
