### ISSUE TITLE
Spectator can fire projectiles if they hack to become creative

### ISSUE THREAD

**Issue by diamond-gold** [TesseractTeam/Tesseract#1050]
#### Problem description

^^

#### Steps to reproduce the issue

Download any hacking app, on server set gamemode to spectator and use the app to set your gamemode to creative client side, then you will be able to get anything, such as snowball, bow and you can use it

#### OS and versions

* Tesseract:Latest commit d662269
* PHP:7
* Server OS:win 8.1
* Game version: 1.0.7
* Server host:Home PC
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by jrodr10** [comment]
@ImagicalGamer confirmed?

**Comment by ImagicalGamer** [comment]
Yes.

**Comment by imjayl** [comment]
Disable allow cheat in Tesseract.yml so that they can't hack items using toolbox

**Comment by diamond-gold** [comment]
@imjayl Its already set to false

**Comment by Qimie** [comment]
Just make if player in spectator all projectiles fire event disable. (For server-side)

**Comment by jrodr10** [comment]
Toolbox is discontinued so um hacks aren't a thing anymore

**Comment by diamond-gold** [comment]
Omggggg how can you leave the vulnerability there just be cause hacks are no longer a thing?? Im pretty sure hacks will somehow come back.

**Comment by Qimie** [comment]
Toolbox is being updated sometimes.
