### ISSUE TITLE
Bows not working

### ISSUE THREAD

**Issue by Assblocker** [TesseractTeam/Tesseract#1051]
#### Problem description

Bows not working, no arrow is thrown from bow
#### Steps to reproduce the issue

Just try to shoot an arrow
#### OS and versions

* Tesseract: Tesseract 1.2.1 RottenApple
* PHP: 7.0.10
* Server OS: Linus/Ubuntu
* Game version: 1.0.7
* Server host: VG
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
None
```

**Comment by PluginBOXone** [comment]
Do you have any plugins on your Server?

**Comment by Iktaniyalol** [comment]
I wrote a similar complaint, but it was closed. Are you seriously? Not alone I have such a problem

**Comment by Iktaniyalol** [comment]
I decided to watch the latest updates and realized that my bows did not work because of this line in Player.php
if ($ this-> isSurvival () and (! $ This-> inventory-> contains (Item :: get (Item :: ARROW, -1) or $ bow-> hasEnchantment (22))) {
To solve this problem, I had to change the line to
 if ($ this-> isSurvival () and! $ This-> inventory-> contains (Item :: get (Item :: ARROW, -1))) {
I dont know why, but this solve my problem

**Comment by diamond-gold** [comment]
Correct code should be
if ($ this-> isSurvival () and ! $ This-> inventory-> contains (Item :: get (Item :: ARROW, -1) and !$bow-> hasEnchantment (22)) {

**Comment by MCPEGamerJPatGitHub** [comment]
I have no issue with bows, you are doing something wrong :)

**Comment by diamond-gold** [comment]
Might be because the bow have enchantment infinity, according to the original code, it will break if the bow hasEnchantment(22)

**Comment by AppleDevelops** [comment]
Here's a simple fix for it. https://github.com/ArufaTeam/Arufa/commit/b12f4fbfb7fdb8e02629e31bc024bddfb0ab3f6f

**Comment by diamond-gold** [comment]
Ohh i forgot for infinity you need at least 1 arrow in your inventory

**Comment by Assblocker** [comment]
what @Iktaniyalol said worked, what @AppleDevelops said didn't -_- ok bye

**Comment by AppleDevelops** [comment]
@Assblocker, isn't it odd how you say it doesn't work but you didn't remove the original code and input the new? Very simple but I forgot that the TesseractTeam is full of idiots

**Comment by EoflaOE** [comment]
By the way, on bug description, there is no "Linus" OS but there is "Linux" made by Linus Torvalds.

**Comment by Assblocker** [comment]
No i m using linus
