### ISSUE TITLE
Void

### ISSUE THREAD

**Issue by ZaneWalter** [TesseractTeam/Tesseract#1052]
Idk if this problem is with me but for some reason whenever a player falls down in the void they donot die nor they get fall damage. Their "y" coordinate shows -40 and nothing happens. Also I have tried testing it by changing my current world folder to worlds_old. Still no luck.

These are all the plugins im using.
Plugins (59): BuyXP v1.0.0, BuilderHelper v1.0.3, NewSName v0.0.1, SimpleNoSpam v2.0.0, EconomyAPI v2.0.9, SlapperRotation v1.0.1, ExtraCommands v0.2, TimeCommander v2.1, CombatLogger v1.2.0, SignChanger v1, superBAR v1.6.2, How v1.0.1, ServerMail v0.0.2, DevTools v1.10.0, BetterAdvencedTools v1, EconomyAirport v2.0.4, NameCorrector v1.0.0#build010, FactionsPro v0.1#Beta, MineReset v2.3, PurePerms v1.3.7, Schematic_Loader v0.1, ProxyFirewall v1.0.0, Functions v1.2.1, PocketGuard v2.1.1, CommandTracker v1.1, ItemCasePE v1.0.8, DoorLocker v1.0, EconomyShop v2.0.7, EconomySell v2.0.7, CustomAlerts v1.6, AdvancedKits v5.1, EPCooldown v1.0.0, EconomyLand v2.0.9, ServerAuth v2.13, ReasonWL v2, EssentialsPE v2.0.0, ChatLogin v1.4, SkinStealer v1.0.0, ClearLagg v1.1.0, WorldProtect v2.2.0, VoteReward v3.0.2, iProtector v3.1b, ManyWorlds v2.1.0, ItemCloud v1.3, SW_svile v0.7dev, Slapper v1.3.4, CheckID v1.0-Alpha, PlayerSelector v1, RealTime v2.1.1, Sell v2, Rotater v1.1.0, TapToDo v2.2.1, NoTP v1.0.5, MegaBan v1.2.4, ItemEffects v2.5.0, WorldEditPotato v1.5, MyPlot v1.1.3, RankUp v0.3.1, PureChat v1.4.0

**Comment by diamond-gold** [comment]
Try removing all plugins and see if it works, pretty sure its plugin's fault

**Comment by LordJoshie** [comment]
nah, I dunno... I get this also in some of my worlds, and I look at his plugs compared to mine and I don't think thats whats causing it...

**Comment by PluginBOXone** [comment]
1. Rename your Plugin-folder to "plugins_old" 2. restart your server 3. Try it again.
~~~
If this won't work for you set your Spawn Protection to 0

**Comment by ZaneWalter** [comment]
I found the fix. For me it was iProtector plugin which was causing the problem.

Fix:
In config.yml file of iProtector make sure that these flags for unprotected areas are as follows:


# Config file for iProtector by LDX;

# Settings for unprotected areas in worlds without specific settings:
Default:

  # Keep players from getting hurt?
  God: false

  # Keep players from editing the world?
  Edit: false

  # Keep players from touching blocks and activating things like chests?
  Touch: false

# Settings for unprotected areas in individual worlds:
Worlds:

  Spawn:

    # Keep players from getting hurt?
    God: false

    # Keep players from editing the world?
    Edit: false

    # Keep players from touching blocks and activating things like chests?
    Touch: false

Mine were at first kind of messed up but when i changed all flags to false it started working that is void started to function and kill people

**Comment by jrodr10** [comment]
@PluginBOXone okay to close?

**Comment by PluginBOXone** [comment]
@jrodr10 jep :)
