### ISSUE TITLE
The same problem like #1017 but with hoppers

### ISSUE THREAD

**Issue by mihnea91** [TesseractTeam/Tesseract#1054]
#### Problem description
You can store creative items in hoppers. I have activeated restricted-creative option from tesseract.yml and you can;t open furnance/chest... inventoies but you cand open the hopper inventory

#### Steps to reproduce the issue
simple, enter in gamemode creative pun a hooper and open it 

#### OS and versions

* Tesseract: Tesseract-1.2.1 RottenApple
* PHP: 7.0.16
* Server OS: ubuntu 14
* Game version: 1.0.7
* Server host: 188.212.103.32:19132
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by PluginBOXone** [comment]
Try to set LimitedCreative on off

**Comment by mihnea91** [comment]
I tried, and now its ON and i saw that the furnance glitch was fixed but you still can acces the hopper inventory from creative

**Comment by ZaneWalter** [comment]
Yes i know for a fact that hoppers can be opened in creative mode even if limited creative is on or off. I think there is a problem with trapped chests too (unconfirmed).

**Comment by ImagicalGamer** [comment]
Hoppers aren't completed yet.
