### ISSUE TITLE
Health glitch

### ISSUE THREAD

**Issue by Assblocker** [TesseractTeam/Tesseract#1055]
#### Problem description

When pvping, the player doesn't see his health getting lesser, the health bar stays the same even after dying, check this video - https://vimeo.com/215854605
#### Steps to reproduce the issue

pvp
#### OS and versions

* Tesseract: 1.2.1
* PHP: 7.0.10
* Server OS: linux
* Game version: 1.0.7
* Server host: vg
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
none
```

**Comment by Assblocker** [comment]
Sorry it works, i was using what @AppleDevelops did in that stupid arufa commit, works now dw

**Comment by AppleDevelops** [comment]
I didn't say copy everything genius. Tesseract will never be good
