### ISSUE TITLE
Pardoncid?

### ISSUE THREAD

**Issue by HipsterAF** [TesseractTeam/Tesseract#1059]
#### Problem description

pardoncid command missing
#### Steps to reproduce the issue

no /pardoncid ?
#### OS and versions

* Tesseract: 1.2.1
* PHP: 7.0.10
* Server OS: Linux
* Game version: 1.0.7
* Server host: VG
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
none
```

**Comment by akaSnapy** [comment]
You can delete them manually, go on your ftp and find "banned-cids.txt" open it and remove the player u want to unban:) then reload the server
