### ISSUE TITLE
[Offer] Do you want to make new web?

### ISSUE THREAD

**Issue by ondraczsk** [TesseractTeam/Tesseract#106]
I create web for you, like nukkit.io. You can choose design from html5up.net and i make the web.You have to say what is in there has to be

Hosting: On my vps: Web ( elywing.tk )
Or free hosting-hostinger.cz Web ( elywing.esy.es )

My work: clearskybeta.esy.es
atgames.tk

Sorry for my english

Of course, all is free :D

**Comment by remotevase** [comment]
no
