### ISSUE TITLE
Discourse?

### ISSUE THREAD

**Issue by NFGamerMC** [TesseractTeam/Tesseract#1061]
Hello,
Before I was kicked I contacted Discource to get a free Hosted Forum as we are open-source, check this if you are interested. https://imgur.com/gallery/NjWCF

This is not meant to be spam but this is a chance, also jrodr10 your tesseractteam.me could use this.

**Comment by AppleDevelops** [comment]
lol Tesseract

**Comment by NFGamerMC** [comment]
?

**Comment by jrodr10** [comment]
no thanks @NFGamerMC
