### ISSUE TITLE
Can't join the game..

### ISSUE THREAD

**Issue by paulzzh** [TesseractTeam/Tesseract#1063]
[Tesseract] [23:08:56] INFO> 
┌─────────────────────────────────────────────────┐  -- Loaded: Properties and Configuration --
│                                                 │    Date: Fri, May 05, 2017, 23:08 CST
│   _______                                _      │    Version: 1.2.1 Codename: RottenApple
│  |__   __|                              | |     │    MCPE: v1.1.0 Protocol: 112
│     | | ___  ___ ___  ___ _ __ __ _  ___| |_    │    IP:  Port: 19132
│     | |/ _ \/ __/ __|/ _ \ '__/ _` |/ __| __|   │    Query: 0.0.0.0
│     | |  __/\__ \__ \  __/ | | (_| | (__| |_    │    SSL Extension: true
│     |_|\___||___/___/\___|_|  \__,_|\___|\__|   │    Authentication: online mode/secure
│                                                 │  ------------------------------------------
│                                                 │    API Version: 3.0.1
│   Support: github.com/TesseractTeam/Tesseract   │    Language: eng
│					          │    Package: src
└─────────────────────────────────────────────────┘  ------------------------------------------
[Tesseract] [23:08:56] INFO> Starting remote control listener
[Tesseract] [23:08:56] INFO> RCON running on 0.0.0.0:19132
[Tesseract] [23:08:56] INFO> Everything seems to be alright! Server started!
[Tesseract] [23:08:56] INFO> Loading recipes...
[Tesseract] [23:08:56] INFO> Preparing level "world"
[Tesseract] [23:08:56] INFO> Preparing level "nether"
[Tesseract] [23:08:56] INFO> Starting GS4 status listener
[Tesseract] [23:08:56] INFO> Query running on 0.0.0.0:19132
[Tesseract] [23:08:56] INFO> Default game type: Survival Mode
[Tesseract] [23:08:56] INFO> Done (0.727s)! For help, type "help" or "?"

Warning: zlib_decode(): data error in /storage/emulated/0/PocketMine/src/pocketmine/network/protocol/LoginPacket.php on line 65

Warning: assert(): Expected 4 bytes, got 0 failed in /storage/emulated/0/PocketMine/src/pocketmine/utils/Binary.php on line 36

Warning: unpack(): Type V: not enough input, need 4, have 0 in /storage/emulated/0/PocketMine/src/pocketmine/utils/Binary.php on line 237

Notice: Trying to get property of non-object in /storage/emulated/0/PocketMine/src/pocketmine/network/protocol/LoginPacket.php on line 71

Warning: assert(): Expected 4 bytes, got 0 failed in /storage/emulated/0/PocketMine/src/pocketmine/utils/Binary.php on line 36

Warning: unpack(): Type V: not enough input, need 4, have 0 in /storage/emulated/0/PocketMine/src/pocketmine/utils/Binary.php on line 237

Notice: Undefined offset: 1 in /storage/emulated/0/PocketMine/src/pocketmine/network/protocol/LoginPacket.php on line 154

Notice: Undefined offset: 2 in /storage/emulated/0/PocketMine/src/pocketmine/network/protocol/LoginPacket.php on line 154

Notice: Uninitialized string offset: 0 in /storage/emulated/0/PocketMine/src/pocketmine/network/protocol/LoginPacket.php on line 159

Notice: Uninitialized string offset: 0 in /storage/emulated/0/PocketMine/src/pocketmine/network/protocol/LoginPacket.php on line 160

Notice: Uninitialized string offset: 48 in /storage/emulated/0/PocketMine/src/pocketmine/network/protocol/LoginPacket.php on line 161

Notice: Uninitialized string offset: 48 in /storage/emulated/0/PocketMine/src/pocketmine/network/protocol/LoginPacket.php on line 162
[Tesseract] [23:09:19] INFO> [/127.0.0.1:44050] logged out due to Login timeout

**Comment by Pogogo007** [comment]
Linux the dumbass changed the version to 1.1.0 even tho it isnt out yet...

**Comment by TheRoyalBlock** [comment]
Why the hell did he do that? No one will ever know.

**Comment by Crypthu97** [comment]
Warning: zlib_decode(): data error in C:\Users\pc\Desktop\Tesseract-master\src\pocketmine\network\Network.php on line 241

 :/

**Comment by jrodr10** [comment]
use https://github.com/jrodr10/Tesseract-1 till this is updated to 1.1.0 sorry about that i was told 1.1.0 was out!

**Comment by AppleDevelops** [comment]
No one wants to use this shit lol I added sounds in my spoon

**Comment by DerddyDert** [comment]
Is this were things fall apart?? Ugh sound and the ability to connect sounds like a dream right about now

**Comment by AppleDevelops** [comment]
I'd try [Arufa](https://github.com/ArufaTeam/Arufa)

**Comment by DarkYusuf13** [comment]
Try to join another version like 1.0.8

**Comment by caspervanneck** [comment]
@AppleDevelops tesseract is f**ckt

**Comment by caspervanneck** [comment]
We all know that

**Comment by caspervanneck** [comment]
fixt
