### ISSUE TITLE
Tesseract is almost dead

### ISSUE THREAD

**Issue by caspervanneck** [TesseractTeam/Tesseract#1066]
@jrodr10 can get owner because i dont whant it dead

**Comment by SuperMaXAleX** [comment]
It's too late. The things what Linux did broken everything on tesseract.

**Comment by caspervanneck** [comment]
nope @SuperMaXAleX am bissy whit reverting it

**Comment by Crypthu97** [comment]
No server file can be used all PE server community dead!

**Comment by caspervanneck** [comment]
nope @Crypthu97 its just dead

**Comment by jrodr10** [comment]
We could just revert to a working phar and fix the bugs one at a time

**Comment by LordJoshie** [comment]
are you guys retarded ? .... 

at ANY given moment, you can easily just ask me for a copy of Tess from when it worked with both sounds, and without.... 

or, to see it all in action for yourself, go visit my sloppy server purecraftpe... 

I run tesseract on all except my mobland server, which I use Pocketmine for. 

:)  Tess isn't dead, just has an INCREDIBLY unorganized dev 'team' ...

**Comment by imjayl** [comment]
Don't tell that this is going to die. Im a plugin developer. I just want to help. Just tell me how to make a tesseract.phar from a zip file? Devtools isnt working to me.

**Comment by AppleDevelops** [comment]
Tesseract is dead, I only use my other software that isn't shit

**Comment by LordJoshie** [comment]
@AppleDevelops uh, mind sharing your software with me ?

You know how to reach me on Kik. :)

**Comment by AppleDevelops** [comment]
@LordJoshie It's [here](https://github.com/ArufaTeam/Arufa)

**Comment by LordJoshie** [comment]
Love it ! xD

**Comment by Assblocker** [comment]
@LordJoshie so greedy
