### ISSUE TITLE
where is the phar

### ISSUE THREAD

**Issue by thekillerby** [TesseractTeam/Tesseract#1071]
where is the phar

**Comment by Fabiansigala** [comment]
@thekillerby will be added soon...

**Comment by diygun** [comment]
Hi , This is just source code , if you have server in linux or windows , you can just replace your PocketMine-MP.phar by the src directories . If you have PocketMine in android you need convert it to .phar with "phar" app in the PlayStore.
I'm French so sorry for my English if it isn't good. I hope help you

**Comment by caspervanneck** [comment]
or use the circleci @thekillerby

**Comment by caspervanneck** [comment]
but you need login white github
