### ISSUE TITLE
Enchants

### ISSUE THREAD

**Issue by ObeyBeastJj23** [TesseractTeam/Tesseract#1072]
#### Problem description

When using the AutoInv plugin on tesseract the player can get infinate items because enchantments like efficiency dont work fully and keep lagging back the block so auto inv sees it as the player has just broke this block, lets give them the block in their inventory. I have had to remove enchanting tables because of this and i cant remove AutoInv as its a prison server and people wouldnt be able to play right without it

#### Steps to reproduce the issue

Enchant Pickaxe with Efficiency 5 (or any other level)
Have AutoInv installed
Try to mine a block but when it appears to break, stop then try to mine it again

#### OS and versions

* Tesseract: 1.2.1 Rotten Apple
* PHP: 7.0.3
* Server OS: ??
* Game version: 1.0.7
* Server host: ScalaCube
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by MCPEGamerJPatGitHub** [comment]
It's a plugin issue, and you can make a prison server without that plugin :)
