### ISSUE TITLE
Spam on my Console

### ISSUE THREAD

**Issue by LewBr** [TesseractTeam/Tesseract#1073]
#### Problem description
Spam every fucking second on my Console

#### Steps to reproduce the issue
08.05 20:51:19 [Multicraft] Skipped 3 lines due to rate limit (30/s)
08.05 20:51:19 [Server] INFO [Tesseract] [21:51:19] INFO> 
08.05 20:51:35 [Server] INFO [Tesseract] [21:51:35] INFO> 
08.05 20:51:52 [Server] INFO [Tesseract] [21:51:52] INFO> 
08.05 20:52:08 [Server] INFO [Tesseract] [21:52:08] INFO> 
08.05 20:52:25 [Server] INFO [Tesseract] [21:52:25] INFO> 
08.05 20:52:41 [Server] INFO [Tesseract] [21:52:41] INFO> 
08.05 20:52:57 [Server] INFO [Tesseract] [21:52:57] INFO> 
and this doesn't have any message before the INFO >

#### OS and versions

* Tesseract: 1.2.1 RottenApple,
* PHP: 7.0.3
* Server OS: MultiCraft
* Game version: 1.0.8
* Server host: EnviousHost
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by jrodr10** [comment]
Multi craft error, I can't reproduce this.
