### ISSUE TITLE
Item Damage

### ISSUE THREAD

**Issue by HipsterAF** [TesseractTeam/Tesseract#1075]
#### Problem description

Diamond pickaxe's damage reduces too slow, hardly any change. The pickaxe doesn't expire ever.
#### Steps to reproduce the issue

Keep mining with a diamond pickaxe, will stay forever.
#### OS and versions

* Tesseract: 1.2.1 rottenapple
* PHP: 7.0.10
* Server OS: Linux
* Game version: 1.0.7
* Server host: VG
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
None
```

**Comment by caspervanneck** [comment]
this is known but pmmp fixt already but i cant commit so i cant help

**Comment by CortexPE** [comment]
That's why Pull Requests are invented...
So people can commit into Repositories 😂 (But will still need someone to merge the commit)

**Comment by jrodr10** [comment]
@caspervanneck

**Comment by jrodr10** [comment]
Pull request a fix
