### ISSUE TITLE
Food bar

### ISSUE THREAD

**Issue by Assblocker** [TesseractTeam/Tesseract#1076]
#### Problem description

Food bar doesn't get low ever 
#### Steps to reproduce the issue

Keep playing the food bar won't get low
#### OS and versions

* Tesseract: 1.2.1 rottentomato
* PHP: 7.0.10
* Server OS: Linux
* Game version: 1.0.7
* Server host: VG
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
None
```

**Comment by AppleDevelops** [comment]
Damn that must suck

**Comment by jrodr10** [comment]
Try running around

**Comment by ImagicalGamer** [comment]
Food works fine for me

**Comment by RateekMCPE** [comment]
It's work ^^.
