### ISSUE TITLE
Why do not you develop TESSERACT? I want to be active again.

### ISSUE THREAD

**Issue by shdudwns** [TesseractTeam/Tesseract#1081]
Please re-develop.
And will you add the red stone and fishing features, the block installation sound and the note block sound? This is what many people want.

@IISweePII  @ImagicalGamer @jrodr10 @Nought57 @PluginBOXone @RateekMCPE @Wxngja @AppleDevelops Please come back.

**Comment by jdongel2004** [comment]
You can develop Tesseract forked.

**Comment by Qimie** [comment]
We r developing but Linux is kinda stupid lets just say that.

**Comment by caspervanneck** [comment]
@Qimie i know

**Comment by AppleDevelops** [comment]
Don't worry 
https://github.com/ServerSoftwares/Arufa

**Comment by archie426** [comment]
@AppleDevelops Spooners never give up -_-

**Comment by AppleDevelops** [comment]
@archie426 and dick riders never stop dickriding

**Comment by archie426** [comment]
@AppleDevelops Nah its fine you don't need another description of yourself, I gave you one already

**Comment by AppleDevelops** [comment]
I mean dick riders are the definitions of the people who always say one person is correct. I do not stick with one person, nor do I ever say that they are correct, on the other hand, always say dktapps is right and always want to stick with him.

**Comment by archie426** [comment]
@AppleDevelops Probably because he is most of the time and doesn't copy code from other projects
