### ISSUE TITLE
Dosen't work AsyncTask

### ISSUE THREAD

**Issue by Nerahikada** [TesseractTeam/Tesseract#1082]
#### Problem description
Can't use AsyncTask from plugin.

#### Steps to reproduce the issue
Make a plugin useing AsyncTask.

#### OS and versions
* Tesseract: Latest version
* Server OS: Windows 10
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files
```
CRITICAL> BadMethodCallException: "Cannot serialize Server instance" (EXCEPTION) in "/src/pocketmine/Server" at line 2737
```

**Comment by ImagicalGamer** [comment]
You don't know how to use AsyncTasks, you cannot import a server instance on a new thread.
