### ISSUE TITLE
Can it help you to add sound??

### ISSUE THREAD

**Issue by G2PCraft** [TesseractTeam/Tesseract#1086]
It is a old tesseract version
https://github.com/TesseractTeam/Tesseract/tree/a191454266fcaca96f821598a2636e636a0e7b59

**Comment by MalakasPlayzMC** [comment]
Just use BlueLight. It's better than Tesseract

**Comment by AppleDevelops** [comment]
Just use PMMP, it's better than BlueLight and Tesseract
