### ISSUE TITLE
The new phar is missing

### ISSUE THREAD

**Issue by MistakingManx** [TesseractTeam/Tesseract#1087]
... idk how this Issue thing works...

#### OS and versions

* Tesseract:
* PHP:
* Server OS:
* Game version: 
* Server host:
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by MistakingManx** [comment]
Windows
I want 1.0.8 but its 1.0.5

**Comment by ImagicalGamer** [comment]
@jrodr10
