### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by ManiakMCPE** [TesseractTeam/Tesseract#1088]
Disconnected due to "timeout"

Players connecting to my KitPvP get disconnected due to timeout but it doesn't happen on any of my other servers, even if they have the same plugins.
I don't know what is causing it but I am pretty sure it is something in the software.

**Comment by jrodr10** [comment]
If you could provide a crashdump or backtrace that'd be nice

**Comment by ImagicalGamer** [comment]
Please use the correct template.
