### ISSUE TITLE
Please develop again tesseract

### ISSUE THREAD

**Issue by shdudwns** [TesseractTeam/Tesseract#1092]
I would appreciate it if the developers got together again and started development.

@AppleDevelops

**Comment by AppleDevelops** [comment]
It'd be nice if I could get the repo back

**Comment by ImagicalGamer** [comment]
I'm getting the repo back tonight or tomorrow @AppleDevelops  :)

**Comment by AppleDevelops** [comment]
I've heard multiple rumors from former owners :)

**Comment by shdudwns** [comment]
Please develop tesseract again.I don't want to use it. My motive is because I am good at calligraphy, so I have no rek.
@AppleDevelops @ImagicalGamer

**Comment by poustmal** [comment]
This problem should stop with tesseract,I'm not using it anymore,but its the only software with better performance(I think,maybe I'm wrong,idk) and more stable a bit.
