### ISSUE TITLE
Rails, Minecarts, Monster Eggs, Horse Armors, etc.?

### ISSUE THREAD

**Issue by infinity-pe** [TesseractTeam/Tesseract#1094]
#### Problem description

I noticed that there are a few blocks and other things missing:
Rails, Minecarts (they are added, but don't work), Stone Monster Eggs, Horse Armors, Saddle, Name Tag, Lead, Redstone Repeater/Comparator, Pistons, Observer, Rabbit Hide, Carrot on a Stick and Lingering Potions.

#### OS and versions

* Tesseract: 1.2.1.2
* PHP: 7.0.3
* Server OS: Debian 8.0
* Game version: 1.0.8 PE
* Server host: HK-Hosting
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

None.

**Comment by LagHD** [comment]
Most of these go into the redstone category.
Redstone causes huge amounts of lag so it was removed sadly
Hopefully it'll get added soon tho! 
Anyways, I'm looking forward towards 1.1

**Comment by infinity-pe** [comment]
But Stone Monster Eggs, Horse Armors, Saddle, Name Tag, Lead, Rabbit Hide, Carrot on a Stick and Lingering Potions weren't added yet.
If they add it, then the Creative will be soon complete! (except redstone things)

**Comment by LagHD** [comment]
They'll need to fix The entity sitting position first bc then you'll be sitting on the ground if u attempt to ride something

**Comment by RateekMCPE** [comment]
Wait ^^ :)

**Comment by junkdude** [comment]
@jrodr10 doesnt know how sorry

**Comment by Qimie** [comment]
Linux is shit. He closes almost all things
