### ISSUE TITLE
Some useful functions missing

### ISSUE THREAD

**Issue by TheAz928** [TesseractTeam/Tesseract#1096]
I saw that in Transcation.php and BaseTranscation.php, there is one function missing.
You guys should add $transcation->getSourceItem();
You can see on PMMP latest BaseTranscation.php and Transaction.php

**Comment by XxParkerGamesxX** [comment]
Alright we will fix this

**Comment by SuperMaXAleX** [comment]
Welcome on Tesseract.

**Comment by TheAz928** [comment]
@SuperMaXAleX  ?

**Comment by daniktheboss** [comment]
This is not PMMP.

**Comment by jrodr10** [comment]
Done
