### ISSUE TITLE
Sounds dont work

### ISSUE THREAD

**Issue by XxParkerGamesxX** [TesseractTeam/Tesseract#1098]
#### OS and versions

* Tesseract: 1.2.1
* PHP: 3.0.1
* Server OS: DONT KNOW
* Game version: 1.0.9
* Server host: FadeHost
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

``` There is no sounds what so ever and in order for me to use this software ever again I need sounds added and the Mob AI needs to be perfect ty
```

**Comment by ImagicalGamer** [comment]
Any other info we already know?
