### ISSUE TITLE
why cant i place blocks at my back ?

### ISSUE THREAD

**Issue by arsenicblast** [TesseractTeam/Tesseract#1099]
#### Problem description
 Blocks are disappearing when I put a block on my back

#### Steps to reproduce the issue
 Play Minecraft,Sneak,Look Downwards,Put blocks on your back.This is because I have skyblock on my server and there is only one thing to do to go accross to another island

#### OS and versions

* Tesseract:
* PHP: PHP7
* Server OS: Windows 8
* Game version: 1.0.7
* Server host:
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Qimie** [comment]
Its a bug... But if u use split control that shouldnt be happening

On May 21, 2017 10:54 AM, "arsenicblast" <notifications@github.com> wrote:
>
> Problem description
> Blocks are disappearing when I put a block on my back
> Steps to reproduce the issue
> Play Minecraft,Sneak,Look Downwards,Put blocks on your back.This is
because I have skyblock on my server and there is only one thing to do to
go accross to another island
