### ISSUE TITLE
The game crashes when I joining to the server.

### ISSUE THREAD

**Issue by Bombaasa** [TesseractTeam/Tesseract#11]
Latest tesseract version from github (v1.1)
 
The game crashes when players joining to the server.
Suncing pack with server... and then crash
 
Console output:
[Tesseract] [10:00:29] INFO> Nickname[/86.98.148.201:39158] [ClientID: -8998798848447516062] logged in with entity id 7 at (MapName, 134.8693, 73.2, -141.4632)
Warning: zlib_decode(): data error in phar:///home/minecraft-pe-3/server/PocketMine-MP phar/src/pocketmine/network/Network.php on line 236
[Tesseract] [10:00:40] INFO> Nickname[/86.98.148.201:39158] logged out due to timeout

**Comment by Shadow166050** [comment]
Means your not updated

**Comment by AppleDevelops** [comment]
That's an outdated player.
