### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by AppleDevelops** [TesseractTeam/Tesseract#110]
#### Problem description

Using commands incorrectly shows ommand.example.usage

#### Steps to reproduce the issue

use a command incorrectly
#### OS and versions

* Tesseract: All versions
* PHP: 7.0.12
* Server OS: Windows 10
* Game version: 1.0.0
* Server host: Home PC
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by ankitmaharjan252** [comment]
This bug is on ElyWing too!

**Comment by Nought57** [comment]
I fixed that. Successfully working now.
