### ISSUE TITLE
Unable to connect to world

### ISSUE THREAD

**Issue by arsenicblast** [TesseractTeam/Tesseract#1101]
#### Problem description
 Other players cant join my server until I go to query
Ps. No crashdump or something

Router : Hitron Technology
My PortForwarding steps : 
CommonApplication : -SERVICES-
Application name : Minecraft PE
(port range)
Public : 19132
Private : 19132
Protocol : TCP/UDP
Ip address : secret
Enable : Checked

#### Steps to reproduce the issue
 I open the server
I wont join the server for 10-20 minutes
then i will tell my friends to join 
They are unable to connect to world
Then I go to query
afk and tell them to join
they can join

#### OS and versions

* Tesseract:
* PHP:7
* Server OS:Win8/PE
* Game version: 1.0.7
* Server host: Home computer
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by arsenicblast** [comment]
I can also send my pocketmine.yml and tesseract.yml if needed

**Comment by MCPEGamerJPatGitHub** [comment]
Update your Tesseract version.

**Comment by AppleDevelops** [comment]
Without knowing any of the information, this issue will be marked as invalid.
