### ISSUE TITLE
can't download Tesseract´s phar file 

### ISSUE THREAD

**Issue by tom758258** [TesseractTeam/Tesseract#1104]
can't download Tesseract´s phar file 

display:no such artifact

**Comment by EoflaOE** [comment]
The wiki might be outdated. You have one cure:

- [Download from here, Tesseract 1.2.1](https://circleci-tkn.rhcloud.com/api/v1/project/TesseractTeam/Tesseract/tree/master/latest/artifacts/Tesseract_1.2.1.phar)
