### ISSUE TITLE
Recipe Problem

### ISSUE THREAD

**Issue by XDqrkneZ** [TesseractTeam/Tesseract#1107]
#### OS and versions

* Tesseract:  Tesseract-1.2.1 RottenApple
* PHP: 7.0.4
* Server OS: Protocol version: 107 API: 3.0.1
* Game version: 1.0.8
* Server host: OVH
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

"Symbol does not appear in the shape: X" (EXCEPTION) in "/src/pocketmine/inventory/ShapedRecipe" at line 99"

What is the shape if "X" isn't?
```
```

**Comment by XDqrkneZ** [comment]
I am trying to add a new item

$this->getServer()->getCraftingManager()->registerRecipe((new ShapedRecipe(Item::get(Item::GOLDEN_APPLE, 2, 1)->setCustomName(TF::GOLD . 'Golden Head'),
                    "XXX",
                    "XYX",
                    "XXX"
                ))->setIngredient("X", Item::get(Item::GOLD_INGOT, 0, 8))->setIngredient("Y", Item::get(Item::SKULL, 3, 1)));
            }

**Comment by SuperMaXAleX** [comment]
Issues are issues about the software, not from plugins.

**Comment by AppleDevelops** [comment]
Plugin issue.
