### ISSUE TITLE
This software shouldn't be discontinued for idiot reasons

### ISSUE THREAD

**Issue by poustmal** [TesseractTeam/Tesseract#1108]
Ok.I'm using bluelight and I'm playing a bit minecraft for now,but I think tesseract can be better than the other software with some changes (items,etc.).Bluelight sometimes with copy-pastes,was deleting items or thing idk.

**Comment by poustmal** [comment]
I'm boring maybe,but continue tesseract and @jrd10,give the tesseract back to the developers,and if they break tesseract,just report them and spam idk,think it like a minecraft server.A server without good builders can't be so cool,so and tesseract can't be fine without developers.

**Comment by jrodr10** [comment]
Lol not a chance i'd rather it die

**Comment by poustmal** [comment]
....fine...but I don't want to use another software,only bluelight but it needs many things pr performances,because its like pmmp

**Comment by AppleDevelops** [comment]
@jrodr10 You're ruining a great software, you've only been a dick to the actual developers. You can't code, copy and paste, and start drama because you want to own everything in MC:PE. Guess what Linux? You're almost 21, you need to get out of your mom's house and get a fucking life.

**Comment by shdudwns** [comment]
@AppleDevelops @jrodr10 Please start development again

**Comment by shdudwns** [comment]
And does tesseract have multicore functionality? Or should I fix it in pocketmine.yml? Please let me use multi core

**Comment by jdongel2004** [comment]
@shdudwns Are you saying that you want to develop this software again? (상황에 맞는 소리 하세요)

**Comment by SuperMaXAleX** [comment]
Tesseract has been totally broken. Multi-core functionality doesn't exist, they killed resource packs so there aren't sounds and many others things who no longer work.

**Comment by AppleDevelops** [comment]
^^ That's why I've been using PMMP, a small sacrifice of no classic crafting is alright with me.

**Comment by AppleDevelops** [comment]
I'd be able to make Tesseract decent, but Linux fucked it over.
