### ISSUE TITLE
Login Timeout

### ISSUE THREAD

**Issue by ChaostixZix** [TesseractTeam/Tesseract#1109]
I Use Tesseract 1.2.1
RottenApple

When A Player join The Server, It Say Disconeccted, But in The Console, It Says Login Timeout

**Comment by Crypt97** [comment]
yes :(

**Comment by AppleDevelops** [comment]
Without knowing any of the information, this is considered invalid.

**Comment by ZizzyZizzy** [comment]
We see this all the time on our server hosting. A **BAD/OUTDATED PLUGIN** is causing this issue, not Pocketmine.

**FIX/Troubleshoot:**
Stop the server, rename the plugins folder to plugins.disabled, and then start the server and you should be able to connect just fine. Now add the plugins back in, **one at a time**, restart the server, and  then try to connect again.

When you are no longer able to connect, you've found the plugin that is causing the issue.
