### ISSUE TITLE
Random Reboot

### ISSUE THREAD

**Issue by TacosYum** [TesseractTeam/Tesseract#111]
#### Problem description
it tells me this and reboots every 5 min API Server Returned
 Error Message: Monthly Request Limit Reached when 
TacosYum tried to connect
[Tesseract] [19:31:43] CRITICAL> Shutting down serv
er to prevent blacklisting on API Database

#### Steps to reproduce the issue
Start the server

#### OS and versions
* Tesseract: b744e2c
* PHP: 7
* Server OS: Ubuntu 15.10
* Game version:  1.0.1
* Server host: BlueLeaf
It's a VPS located in France <br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files
Plugins: Crit
ical v1, CommandTracker v1.1, PurePerms v1.3.7,
 JoinQuit-Mute v1.0.2, TimeCommander v2.1, Back
Death v1.0.0, AntiVoid v1.0.0, VIPSlots v0.0.4,
 AntiSpam v1.3, iProtector v3.1b, SimpleAuth v1
.7.2, BuyCraft v1.2.2, PeacefulSpawn v2.5, Serv
erMail v0.0.2, ServerChannels v1.2, VoteReward 
v3.0.2, pHomes v0.8.0, NetherChests v1.1.1, End
erPearl v1.2.3, SimpleAuthHelper v2.0.4, Entity
Killer v1.0.0, BasicHUD v1.0.6, VPNGuard v1.0.5
, AntiAbusiveEnchants v1, PureChat v1.4.0
```
```

**Comment by AppleDevelops** [comment]
jhuhn                                               fgggggggggggggggggggggggggggggggggggddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd

**Comment by xZeroMCPE** [comment]
Maybe its "VPNGuard":

"Error Message: Monthly Request Limit Reached when
TacosYum tried to connect"

Appears first, then server shutdown..

Try removing "VPNGuard".

**Comment by KnightOfEnder** [comment]
Is there a way to turn VPNGuard off cause that a inportant plugin

**Comment by KnightOfEnder** [comment]
I have remove the file and the server looks to run I'm seeing if it reboot on it own still

**Comment by KnightOfEnder** [comment]
But now this shows what is it 
![screenshot_2017-01-10-21-57-43](https://cloud.githubusercontent.com/assets/24853541/21853350/a8326672-d80e-11e6-80f6-4a56e54bb7df.png)

**Comment by KnightOfEnder** [comment]
New issues on this server to when server stop it remove all enchanted off every gear on it

**Comment by xZeroMCPE** [comment]
You sure your using Tesseract...?

**Comment by KnightOfEnder** [comment]
Yes bro im went to use Tesseract-master unzip it all done the normal stuff went on server and all enchanted stuff is normal now so I had to move all back to Elywing

**Comment by xZeroMCPE** [comment]
@KnightOfEnder Please open another issue for each bugs you've found. So we can keep track of it..
