### ISSUE TITLE
What happen in this repo?

### ISSUE THREAD

**Issue by jdongel2004** [TesseractTeam/Tesseract#1111]
#### OS and versions

* Tesseract:
* PHP:
* Server OS:
* Game version: 
* Server host:
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```
@AppleDevelops Are you backup this repo? Issues and commit are backed!

**Comment by AppleDevelops** [comment]
I'm here and I'm fixing everything
