### ISSUE TITLE
Report for a server, which is using Tesseract

### ISSUE THREAD

**Issue by Akuroma** [TesseractTeam/Tesseract#1113]
#### Problem description
The MCPE-Server Antoxia.net is using Tesseract. The owner of the network edited the /version-command and put in very bad words.

#### Steps to reproduce the issue
Try talking to the Owner (FunnyBuddys).
![da7x3kbwsaa8v4u](https://cloud.githubusercontent.com/assets/19476909/26592043/db873908-455f-11e7-9a30-9d47778570da.jpg)

#### OS and versions

* Tesseract:
* PHP:
* Server OS:
* Game version: 
* Server host:
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by AppleDevelops** [comment]
Get in contact with the owner please.
