### ISSUE TITLE
Pvp Dose not work

### ISSUE THREAD

**Issue by Shadow166050** [TesseractTeam/Tesseract#1118]
You cannot be hurt or hurt any player

**Comment by jrodr10** [comment]
@AppleDevelops this guy thinks he is jesus lol

**Comment by Shadow166050** [comment]
For what reporting a bug?

**Comment by jrodr10** [comment]
I mean not being able to die and i was joking. (Not like i had to explain myself lmao)

**Comment by AppleDevelops** [comment]
Without knowing any information or how to reproduce this, I cannot help.

**Comment by Shadow166050** [comment]
There was not error given, just load it on a server and punch someone

**Comment by AppleDevelops** [comment]
Looks fine to me.
The second client was lagging which is why it looks like it didn't receive knockback.
[Image](http://imgur.com/GR1TDEA.gifv)

**Comment by Crypt97** [comment]
This problem does not affect all players just say. 
But unfortunately there is a server where there is a player.
