### ISSUE TITLE
Issue causing lag

### ISSUE THREAD

**Issue by Shadow166050** [TesseractTeam/Tesseract#1119]
30.05 20:06:58 [Server] INFO [Tesseract] [00:06:58] CRITICAL> Could not tick level "world": Call to a member function getValue() on null
30.05 20:06:58 [Server] INFO [Tesseract] [00:06:58] CRITICAL> Could not tick level "world": Call to undefined method pocketmine\item\enchantment\Enchantment::getEnchantMaxLevel()

**Comment by junkdude** [comment]
linux this is a legit issue bud, should probably fix it
