### ISSUE TITLE
PMMP and AntiCheat

### ISSUE THREAD

**Issue by junkdude** [TesseractTeam/Tesseract#1120]
First off anticheat need's to be removed with the upcoming update of MCPE 1.1. Reasoning is inventories will be handled server-side so there is no way people can cheat, please remove it. Next PMMP just added PlayerDataSaveEvent. Could you port that over

**Comment by Qimie** [comment]
1st Apple is trying to remove it as he say on his Twitter. 2nd I dont have
answer for that one.

**Comment by AppleDevelops** [comment]
I've done what I wanted to do for the public, I have retired from Tesseract.

**Comment by junkdude** [comment]
@Qimie no @jrodr10 added it back in....idk why

**Comment by Qimie** [comment]
Freak him

**Comment by jrodr10** [comment]
Anti cheat will be removed on 1.1 update till then we need it.

**Comment by junkdude** [comment]
u r retarted then
