### ISSUE TITLE
PurePerms Incompatibility

### ISSUE THREAD

**Issue by MasterOfTheRealm** [TesseractTeam/Tesseract#1121]
Most people doesn't use Tesseract because of its incompatibility with pureperms. Can someone make them  compatible again?

**Comment by MasterOfTheRealm** [comment]
And btw before anyone starts talking about how Tesseract was updated and pureperms was not.
Please note that pureperms works fine in all the other server softwares and it worked till Tesseract 1.0.6.

**Comment by Qimie** [comment]
If the plugin doesnt get updated, its the plugin fault not the software.
Can u tell me the error message? Ill try fix

**Comment by AppleDevelops** [comment]
Actually, it's affected most softwares. You can use an older version of PurePerms to hopefully fix that.

**Comment by jrodr10** [comment]
Plugin issue

**Comment by Qimie** [comment]
I think its because Tesseract has bump its API & PurePerms dont suppirt it.

**Comment by jrodr10** [comment]
Warning: yaml_parse(): scanning error encountered during parsing: found characte                                                                                r that cannot start any token (line 132, column 1), context while scanning for t                                                                                he next token (line 132, column 1) in /home/DRv2/pvp/src/pocketmine/utils/Config                                                                                .php on line 143

Warning: yaml_parse(): scanning error encountered during parsing: found characte                                                                                r that cannot start any token (line 132, column 1), context while scanning for t                                                                                he next token (line 132, column 1) in /home/DRv2/pvp/src/pocketmine/utils/Config                                                                                .php on line 143

**Comment by MasterOfTheRealm** [comment]
Most softwares? weird they worked fine for me and yes an old version of pureperms works perfectly

**Comment by FunnyBuddys** [comment]
I think the Problem is by PurePerms. You should open a Issue there.

**Comment by EoflaOE** [comment]
The yaml parsing error occurred with and without PurePerms, with or without plugins.

**Comment by daniktheboss** [comment]
Plugin error. CLOSE

**Comment by jrodr10** [comment]
Issue needs to be resolved, Ik it's a plugin error but can we fork a pureperms plugin and update it specifically for Tesseract

**Comment by AppleDevelops** [comment]
I mean you can't Linux

**Comment by brianzp** [comment]
Before i shifted to pmmp (best decision so far) my PurePerms plugin worked with Tesseract. Idk if it still will. Might as well test it on a test server.
