### ISSUE TITLE
Particle bug

### ISSUE THREAD

**Issue by Crypt97** [TesseractTeam/Tesseract#1123]
#### Problem description
Video: https://youtu.be/cSD0CNTknec

#### Steps to reproduce the issue
1 watch video: https://youtu.be/cSD0CNTknec
 
It is just an enchanted break

**Comment by jrodr10** [comment]
Interesting..

**Comment by jrodr10** [comment]
More on the subject please and thanks

**Comment by Crypt97** [comment]
If a player is in an enchanted dress and falls high, then this is the problem with the video

**Comment by daniktheboss** [comment]
Not reproducable. 99% sure this is plugin fault. Try without any plugins
