### ISSUE TITLE
PlayerLogoutEvent Screwup

### ISSUE THREAD

**Issue by jrodr10** [TesseractTeam/Tesseract#1125]
#### Problem description
Server crashes on player disconnect

#### Steps to reproduce the issue
1. Join game
2. Leave game
3. Watch CLI

#### OS and versions

* Tesseract: 1.3.0
* PHP: 7.0.17
* Server OS: Ubuntu 17.04
* Game version: MCPE 1.0.9 (Protocol 107)
* Server host: DarkRealms Network Dedicated Server

```
```

**Comment by jrodr10** [comment]
This is unconfirmed as it was sent to me on our discord channel

**Comment by NFGamerMC** [comment]
Will Test..

**Comment by EoflaOE** [comment]
There is no such event as "PlayerLogoutEvent" but there is "PlayerQuitEvent".

**Comment by jrodr10** [comment]
Eh same poop lol that's what I meant
