### ISSUE TITLE
BUCKET DUPLICATE GLITCH #urgent

### ISSUE THREAD

**Issue by XDqrkneZ** [TesseractTeam/Tesseract#1126]
#### OS and versions

* Tesseract: Tesseract-1.2.1 RottenApple
* PHP: 7.0.3
* Server OS: API 3.0.1
* Game version: 1.0.7
* Server host: OVH
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

when you have buckets stacked and you collect lava.. all the buckets will be filled lava too so this is glitch that must be fixed ASAP because players can duplicate lava to grief the server & make big lag freezes
```
```

**Comment by XDqrkneZ** [comment]
I think making buckets not stack is the best

**Comment by akaSnapy** [comment]
This is fixed on PMMP, just use PMMP instead of a fork.

**Comment by XDqrkneZ** [comment]
@akaSnapy dont have idea how to make .phar from src :(

**Comment by akaSnapy** [comment]
smh, git clone the repo,(use src as software) add devtools in ur plugins folder and start the server, when done do makeserver .
(If u clone the pmmp repo u have to copy it recursive so do -> git clone --recursive and repo)

**Comment by akaSnapy** [comment]
VOTE THIS SO TESSERACT WILL GO BACK TO REAL OWNERS -> https://twitter.com/AppleDevelops/status/870868977282686980
