### ISSUE TITLE
I can't get drop item!(survival only)

### ISSUE THREAD

**Issue by sinnrinn** [TesseractTeam/Tesseract#1127]
#### Steps to reproduce the issue
I can't write English well, and can't understand English well.
Because I'm Japanese.
So, there are a lot of mistakes in my English.
I'm sorry.

#### OS and versions

* Tesseract:latest
* PHP:7.0.3
* Server OS:Ubuntu 16.10 LTS
* Game version: v1.0.9
* Server host:
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files
ワールド "world" をチェックすることができませんでした: Argument 1 passed to pocketmine\inventory\BaseInventory::canAddItem() must be an instance of pocketmine\item\Item, null given, called in /home/sinnrinn0798/pmmp/src/pocketmine/Player.php on line 1389

I can't get drop item. But it's survival only! why? I think there are mistakes in this src. Please release bug fix ver.

```
```

**Comment by FunnyBuddys** [comment]
Do you have any Plugins, that can Block the Dropevent?

**Comment by Qimie** [comment]
That can Block the Drop event sounds funny to me. U should say Cancel.

**Comment by Iktaniyalol** [comment]
I agree with this issue. I have this problem too

**Comment by FunnyBuddys** [comment]
Send us a Pluginlist. I think, the problem is in one of your plugins.

**Comment by Iktaniyalol** [comment]
But i have not rhis problem before

**Comment by FunnyBuddys** [comment]
Before what? We need more Details.

**Comment by Iktaniyalol** [comment]
I speak english very bad. Before this problem. Plugins before and now not changes. Now I have this problem

**Comment by FunnyBuddys** [comment]
You updated Tesseract and now you have this Problem?

**Comment by Iktaniyalol** [comment]
Yes

**Comment by sinnrinn** [comment]
These is plugins.
[Tesseract] [10:53:03] INFO> KeepInventory v1.2.0 を読み込み中...
[Tesseract] [10:53:03] INFO> removeItem v1.0.0 を読み込み中...
[Tesseract] [10:53:03] INFO> Music v1.71 を読み込み中...
[Tesseract] [10:53:03] INFO> ServerInfo v1.6.9 を読み込み中...
[Tesseract] [10:53:03] INFO> Lightning v1.1.0 を読み込み中...
[Tesseract] [10:53:03] INFO> otu v1.2.3 を読み込み中...
[Tesseract] [10:53:03] INFO> EWorldLoader v1.0.0 を読み込み中...
[Tesseract] [10:53:03] INFO> EconomyPShop v2.0.2 を読み込み中...
[Tesseract] [10:53:03] INFO> NoTNT v1.0.0 を読み込み中...
[Tesseract] [10:53:03] INFO> SimpleMacros v0.3 を読み込み中...
[Tesseract] [10:53:03] INFO> iProtector v3.1b を読み込み中...
[Tesseract] [10:53:03] INFO> JoinQuitPopup v1.2 を読み込み中...
[Tesseract] [10:53:03] INFO> ItemCloud v1.3 を読み込み中...
[Tesseract] [10:53:03] INFO> TapID v1 を読み込み中...
[Tesseract] [10:53:03] INFO> IronDoor v0.4 を読み込み中...
[Tesseract] [10:53:03] INFO> EconomyAPI v2.0.9 を読み込み中...
[Tesseract] [10:53:03] INFO> ImputSigner v1.0.1 を読み込み中...
[Tesseract] [10:53:03] INFO> EconomyShop v2.0.7 を読み込み中...
[Tesseract] [10:53:03] INFO> TimeCommander v2.1 を読み込み中...
[Tesseract] [10:53:03] INFO> KillBearBoyshk v3.0.0 を読み込み中...
[Tesseract] [10:53:03] INFO> NKVD v1 を読み込み中...
[Tesseract] [10:53:03] INFO> DevTools v1.10.0 を読み込み中...
[Tesseract] [10:53:03] INFO> FireProtection v1.0 を読み込み中...
[Tesseract] [10:53:03] INFO> PVPitem v0.1 を読み込み中...
[Tesseract] [10:53:03] INFO> BanItem v2.1 を読み込み中...
[Tesseract] [10:53:03] INFO> iControlU v1.3 を読み込み中...
[Tesseract] [10:53:03] INFO> ViewerName v4.3 を読み込み中...
[Tesseract] [10:53:03] INFO> SimpleMessages v1.2 を読み込み中...
[Tesseract] [10:53:03] INFO> PopupDisplayer v2.0.1 を読み込み中...
[Tesseract] [10:53:03] INFO> [PopupDisplayer] Plugin Enabled
[Tesseract] [10:53:03] INFO> EconomyJob v2.0.4 を読み込み中...
[Tesseract] [10:53:03] INFO> worldbackup v1.0 を読み込み中...
[Tesseract] [10:53:03] DEVELOPER> Loading plugin: mail v1.0.0
[Tesseract] [10:53:03] DEVELOPER> Loading plugin: xyz v1.0.1
[Tesseract] [10:53:03] INFO> [xyz] /xyz は読み込まれました
[Tesseract] [10:53:03] DEVELOPER> Loading plugin: SignPortal v1.1.2
[Tesseract] [10:53:03] DEVELOPER> Loading plugin: TapToDo v2.2.1
[Tesseract] [10:53:03] INFO> EconomySell v2.0.7 を読み込み中...
[Tesseract] [10:53:03] INFO> EconomyTax v2.0.3 を読み込み中...
[Tesseract] [10:53:03] INFO> EconomyCasino v2.0.2 を読み込み中...
[Tesseract] [10:53:03] INFO> EconomyAirport v2.0.4 を読み込み中...
[Tesseract] [10:53:03] INFO> SimpleWarp v2.1.0 を読み込み中...
Mmm......
I'm can't understand issues plugin. And I fix some plugins. If you can't find issues plugins, my fix plugins is bad......?

**Comment by MCPEGamerJPatGitHub** [comment]
日本語で説明されて頂いて結構ですので、わかる限り状況をご説明ください。

**Comment by FunnyBuddys** [comment]
KeepInventory / remoteitem / iProtector can cancel the Dropevent

**Comment by sinnrinn** [comment]
To MCPEGameJPatGitHub
では申し訳ないですが日本語で。
わたしはいくつかのプラグインを自分で少し改造して使用しています。と、いっても日本語化だけなのですが……。
そちらも関係してる可能性がありますかね？
To FunnyBuddys
Oh,really? But I need KeepInventory. Please teach me other KeepInventory.

**Comment by louise76** [comment]
maybe remove the remoteitem?

**Comment by sinnrinn** [comment]
Yes. I'm going to remove the removeItem.
I'll tring that.

**Comment by jrodr10** [comment]
Reopen if needed, I see this issue isn't active
