### ISSUE TITLE
Update to 1.1?

### ISSUE THREAD

**Issue by BlawoHD** [TesseractTeam/Tesseract#1128]

**Comment by AffanStarPure** [comment]
I need 1.1.0 x 1.1.1 for tesseract phar I cannot use different versions

**Comment by junkdude** [comment]
linux doesnt know how

**Comment by FunnyBuddys** [comment]
The Update to 1.1.X will coming in the next Days.

**Comment by NFGamerMC** [comment]
Nope

**Comment by XDqrkneZ** [comment]
@junkdude lmfao he ruined this shit

**Comment by akaSnapy** [comment]
This fork is died, there's no active or capable devs to keep it up.(when pmmp gets the inventory rewrite no one will use this anymore)

**Comment by LagHD** [comment]
@akaSnapy maybe if the official owners became owners again, it'd be much better

**Comment by akaSnapy** [comment]
@LagHD Yeah, apple is better than shit linux, apple really deserves to get tesseract back

**Comment by akaSnapy** [comment]
VOTE THIS SO TESSERACT WILL GO BACK TO REAL OWNERS -> https://twitter.com/AppleDevelops/status/870868977282686980

**Comment by FunnyBuddys** [comment]
@NFGamerMC Denied my Pull Request for the Pre-Support for 1.1

**Comment by SuperKali** [comment]
When the update is available in 1.1.0?

**Comment by FunnyBuddys** [comment]
@SuperKali The Staff of Tesseract now are not able to update to 1.1 the Original Owners will come back in the next Hours/Days.

**Comment by junkdude** [comment]
no they wont

**Comment by CookieCode** [comment]
@FunnyBuddys Great ! They will finally come back! The wait begin to be long.

**Comment by jrodr10** [comment]
Just need to fix the query then boom update to 1.1.0 done

**Comment by daniktheboss** [comment]
Close. This is a very unneeded "issue"

**Comment by intagaming** [comment]
So that we can't track the progress?

**Comment by daniktheboss** [comment]
progress? lol this should not have a progress... this should be done in one try not multiple

**Comment by intagaming** [comment]
The 1.1.0 "one-try" for now is NOT working even.

**Comment by jrodr10** [comment]
Finish this conversation in #1141

**Comment by Qimie** [comment]
Use PMMP

**Comment by daniktheboss** [comment]
kill yourself if you use pmmp

**Comment by EoflaOE** [comment]
@daniktheboss It is not nice to say that.

**Comment by daniktheboss** [comment]
its not nice to recommend other software here

**Comment by EoflaOE** [comment]
Thanks. We will delete or edit user's comment involving other server software in the future.

Lenovo TAB3 7 Essential

On Jun 5, 2017 8:53 PM, Daniktheboss <notifications@github.com> wrote:

its not nice to recommend other software here

**Comment by daniktheboss** [comment]
your not a developer so please. stop pissing other REAL devs off
