### ISSUE TITLE
Color

### ISSUE THREAD

**Issue by MrAlecsesDev** [TesseractTeam/Tesseract#1130]
Hi, guys! I have one problem: I cant edit biome color in new core. Please, help me. :) I really need it

**Comment by FunnyBuddys** [comment]
Do you have a Crash Dump, an error message or something else?

**Comment by akaSnapy** [comment]
VOTE THIS SO TESSERACT WILL GO BACK TO REAL OWNERS -> https://twitter.com/AppleDevelops/status/870868977282686980

**Comment by Lazerplayz** [comment]
#GiveTesseractBack

**Comment by daniktheboss** [comment]
Not enough info. CLOSE

**Comment by jrodr10** [comment]
What danik said

**Comment by Qimie** [comment]
He say CLOSE u idiot.
