### ISSUE TITLE
SIGN NOW! 

### ISSUE THREAD

**Issue by AppleDevelops** [TesseractTeam/Tesseract#1132]
Hey Everyone,
Sign this on "change.org" to keep Tesseract strong

https://twitter.com/AppleDevelops/status/870868977282686980

**Comment by louise76** [comment]
sign, sealed and delivered. well actually just shared. lol

**Comment by Lazerplayz** [comment]
#GiveTesseractBack

**Comment by FunnyBuddys** [comment]
👍

**Comment by RateekMCPE** [comment]
#GiveTesseractBack

**Comment by NFGamerMC** [comment]
#GiveBackTesseract
