### ISSUE TITLE
.

### ISSUE THREAD

**Issue by akaSnapy** [TesseractTeam/Tesseract#1133]
.

**Comment by Lazerplayz** [comment]
#GiveTesseractBack

**Comment by louise76** [comment]
retweeted 
#GiveTesseractBack

**Comment by G2PCraft** [comment]
#GiveTesseractBack

**Comment by ivan691** [comment]
#GiveTesseractBack

**Comment by G2PCraft** [comment]
@akaSnapy I have question who is real owner.

**Comment by Qimie** [comment]
AppleDevelops & ImagicalGamer

**Comment by RateekMCPE** [comment]
#GiveTesseractBack

**Comment by xAomSKR** [comment]
#GiveTesseractBack

**Comment by akaSnapy** [comment]
U didnt got balls to keep it open bitch

**Comment by Qimie** [comment]
Yeah. Bc he or she knows if apple got the repo back he is gonna be removed
from staffs.

**Comment by NFGamerMC** [comment]
I was added he to reduce SPAM and your constant issues are not helpful. You already have a big top issue that says to sign. I had signed myself. I am not staff also I am a slave for LinuxLogo.
