### ISSUE TITLE
VOTE THIS SO TESSERACT WILL GO BACK  TO REAL OWNERS -> https://twitter.com/AppleDevelops/status/870868977282686980

### ISSUE THREAD

**Issue by akaSnapy** [TesseractTeam/Tesseract#1134]
VOTE THIS SO TESSERACT WILL GO BACK  TO REAL OWNERS -> https://twitter.com/AppleDevelops/status/870868977282686980VOTE THIS SO TESSERACT WILL GO BACK  TO REAL OWNERS -> https://twitter.com/AppleDevelops/status/870868977282686980VOTE THIS SO TESSERACT WILL GO BACK  TO REAL OWNERS -> https://twitter.com/AppleDevelops/status/870868977282686980VOTE THIS SO TESSERACT WILL GO BACK  TO REAL OWNERS -> https://twitter.com/AppleDevelops/status/870868977282686980VOTE THIS SO TESSERACT WILL GO BACK  TO REAL OWNERS -> https://twitter.com/AppleDevelops/status/870868977282686980VOTE THIS SO TESSERACT WILL GO BACK  TO REAL OWNERS -> https://twitter.com/AppleDevelops/status/870868977282686980VOTE THIS SO TESSERACT WILL GO BACK  TO REAL OWNERS -> https://twitter.com/AppleDevelops/status/870868977282686980VOTE THIS SO TESSERACT WILL GO BACK  TO REAL OWNERS -> https://twitter.com/AppleDevelops/status/870868977282686980VOTE THIS SO TESSERACT WILL GO BACK  TO REAL OWNERS -> https://twitter.com/AppleDevelops/status/870868977282686980VOTE THIS SO TESSERACT WILL GO BACK  TO REAL OWNERS -> https://twitter.com/AppleDevelops/status/870868977282686980VOTE THIS SO TESSERACT WILL GO BACK  TO REAL OWNERS -> https://twitter.com/AppleDevelops/status/870868977282686980VOTE THIS SO TESSERACT WILL GO BACK  TO REAL OWNERS -> https://twitter.com/AppleDevelops/status/870868977282686980VOTE THIS SO TESSERACT WILL GO BACK  TO REAL OWNERS -> https://twitter.com/AppleDevelops/status/870868977282686980VOTE THIS SO TESSERACT WILL GO BACK  TO REAL OWNERS -> https://twitter.com/AppleDevelops/status/870868977282686980VOTE THIS SO TESSERACT WILL GO BACK  TO REAL OWNERS -> https://twitter.com/AppleDevelops/status/870868977282686980VOTE THIS SO TESSERACT WILL GO BACK  TO REAL OWNERS -> https://twitter.com/AppleDevelops/status/870868977282686980VOTE THIS SO TESSERACT WILL GO BACK  TO REAL OWNERS -> https://twitter.com/AppleDevelops/status/870868977282686980VOTE THIS SO TESSERACT WILL GO BACK  TO REAL OWNERS -> https://twitter.com/AppleDevelops/status/870868977282686980

**Comment by NFGamerMC** [comment]
I was added he to reduce SPAM and your constant issues are not helpful. You already have a big top issue that says to sign. I had signed myself. I am not staff also I am a slave for LinuxLogo.

**Comment by Qimie** [comment]
Linux sucks. So are u.
