### ISSUE TITLE
UPDATE 1.1 please

### ISSUE THREAD

**Issue by Obamavn99** [TesseractTeam/Tesseract#1135]
#### OS and versions

* Tesseract:
* PHP:
* Server OS:
* Game version: 
* Server host:
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by BlawoHD** [comment]
Check #1128

**Comment by EoflaOE** [comment]
Duplicate of #1128. Tesseract for MCPE 1.1 will be coming in few days. By the way this issue will be closed because there is not enough info.
