### ISSUE TITLE
some plugins dont work

### ISSUE THREAD

**Issue by Pitstopers** [TesseractTeam/Tesseract#1138]
when i test this plugin https://poggit.pmmp.io/p/PlayerVaults/v1.0 and went ingame and did /pv it did not work so i texted the owner of the plugin on pmmp he said this No. If I support tesseract, I'll have people telling me to support other spoons too and that will take a lot of time. Plus tesseract is poorly coded and is taken over by people who have no idea what they're doing. then he said Then tell tesseract to stop changing things so much and keep up with the pocketmine plugins if they think they are better than pocketmine. so can you please fix this issue

**Comment by jdongel2004** [comment]
Tesseract has different code.

**Comment by Pitstopers** [comment]
can they still add it tho

**Comment by junkdude** [comment]
u r dumb

**Comment by Pitstopers** [comment]
Junkdude do you code tesseract no last time I checked how do you know what they can add and not

**Comment by MrReskill** [comment]
Pocketmine has a different architecture and functions

**Comment by junkdude** [comment]
pit its literally for api 3.5 thats different then this one

**Comment by jrodr10** [comment]
PMMP has different functions, and have changed the original pocketmine architecture to their liking, we have far more functions then them but most plugins nowadays follow PMMP, due to our lack of developers. @Pitstopers it is possible to add their random functions but it would be pointless.

**Comment by daniktheboss** [comment]
This is not server software fault. PMMP is not the god of server softwares. Tell the plugin dev to support tesseract or edit the plugin yourself. CLOSE

**Comment by jrodr10** [comment]
What he said
