### ISSUE TITLE
1.1 Logout Timeout

### ISSUE THREAD

**Issue by PixelOG** [TesseractTeam/Tesseract#1141]
#### Problem description
[Tesseract] [11:59:22] INFO> [/118.93.139.166:1025] logged out due to Login timeout

#### OS and versions

* Tesseract:1.3.0 unity
* PHP:7.0.13
* Server OS:windows 10 local pc
* Game version: v1.1.0.55
* Server host:local
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

``` no c dump just unable to join caused by timeout....
```

**Comment by PixelOG** [comment]
no c dump just unable to join

**Comment by daniktheboss** [comment]
Please give me admin so i can ban people like this

**Comment by PixelOG** [comment]
if your just going to be ignorant fine...

**Comment by alair069** [comment]
@PixelOG It's happening the same with me.

**Comment by PixelOG** [comment]
i know ive tried every fork only pmmp works...

**Comment by Whatevr** [comment]
oh come on, its the players problem for not logging in within the time limit. danik isnt being ignorant, this isnt an issue with tesseract at all!

**Comment by PixelOG** [comment]
no its not show me a server with working tesseract 1.1 then....

**Comment by daniktheboss** [comment]
your dumb... this "issue" is part of 1.1 update

**Comment by PixelOG** [comment]
well pmmp and bluelight works perfectly...

**Comment by daniktheboss** [comment]
because they updated their software to 1.1 -.-

**Comment by PixelOG** [comment]
oh i thought tesseract was updated to 1.1 ....

**Comment by xRazvan9** [comment]
This error is and in my server....i have mcpe 1.1

**Comment by Crypt97** [comment]
Pmmp and bluelight full bug ....

**Comment by Obamavn99** [comment]
i have the same problem

**Comment by EoflaOE** [comment]
Same problem for me

**Comment by jrodr10** [comment]
May have fixed this try again.

**Comment by andris155** [comment]
Login work on Tesseract-1.1 branch, but have some bug. Move, commands, inventory etc.. not work.. :/

**Comment by jrodr10** [comment]
moving doesnt work?

**Comment by AppleDevelops** [comment]
Try moving to PMMP, this shit is broken

**Comment by Qimie** [comment]
Ur wrong Apple. Try to move to a software that doesnt has Linux related to
it. XD

**Comment by G2PCraft** [comment]
@AppleDevelops please make the Tesseract not broken anymore please!

**Comment by PixelOG** [comment]
yeah many server depend on tesseract...

**Comment by MasterOfTheRealm** [comment]
Login Timeout here as well
even with no plugins, when joining the server even before the server loads on my device, i get disconnected.

**Comment by andris155** [comment]
PMMP PocketMine-MP not support enchants, Ender Chests, potions. Very unusable, and missing some blocks. :(

**Comment by jrodr10** [comment]
I wish I were as smart as that dumb ass kid named Apple when it comes to PHP. ._. @AppleDevelops hoe ._.

**Comment by HipsterAF** [comment]
Then why did remove other owners @jrodr10 like wtf

**Comment by SuperKali** [comment]
Resolved in https://github.com/TesseractTeam/Tesseract/tree/tesseract-1.1 There are still bugs to fix
!

**Comment by Crypt97** [comment]
Join and Crash !! xDDD nice server file

**Comment by SuperKali** [comment]
Lol @Crypt97

**Comment by SuperKali** [comment]
This is what happens to me!
![screenshot_20170606-194100](https://user-images.githubusercontent.com/19473898/26846951-a45b0986-4afb-11e7-8e84-890ab2dd1175.jpg)

**Comment by andris155** [comment]
![068d96b0-4a4c-11e7-85f1-3db7a14d75c3](https://user-images.githubusercontent.com/8324198/26847236-8dc6182c-4afc-11e7-906e-cdb2ddf888e6.png)

**Comment by SuperKali** [comment]
@andris155 At least the players can enter the game.
There will be something still to be implemented in the version.

**Comment by SuperKali** [comment]
Probably something with the loading of the worlds, I'm not sure!

**Comment by AppleDevelops** [comment]
@jrodr10 I know a lot more than PHP, more than the pedophile that calls himself owner.

**Comment by PixelOG** [comment]
Amen

**Comment by Qimie** [comment]
I hope the guy that stole the repo from Apple and acting like he knows
about PHP a lot and better than Apple, DIE IRL. #GetRektLinux

On Jun 7, 2017 9:06 AM, "PixelOG" <notifications@github.com> wrote:

Amen

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/TesseractTeam/Tesseract/issues/1141#issuecomment-306656741>,
or mute the thread

**Comment by SuperKali** [comment]
Oh yes! Resolve this bug..
![screenshot_20170607-182002](https://user-images.githubusercontent.com/19473898/26889480-9f0ea2e0-4bae-11e7-8611-d895f93b4bf7.jpg)

**Comment by jrodr10** [comment]
Fixed 1.1.0 Issues by becoming a pmmp spoon with Tesseract Features if anything is missing please make an issue form Thanks <3

**Comment by AppleDevelops** [comment]
Ran out of copy and pasting ideas Linux?

**Comment by Qimie** [comment]
Yeah. I hope LinuxLogo dies irl and in game. I really hate copy cats that
stole things and admit hes and acting good at it. Eg. LinuxLogo. Idk Eglish
anymore
