### ISSUE TITLE
Does anyone have the 1.1 .phar file?

### ISSUE THREAD

**Issue by DeathRaven359** [TesseractTeam/Tesseract#1146]
I apologize in advance for how inept I must seem as I do not know how to use /makeserver on DevTools.

**Comment by daniktheboss** [comment]
There is no official way right now

**Comment by DeathRaven359** [comment]
Oh. Can someone then compile the current source code for me, unless it is stated that it does not work?

**Comment by brianzp** [comment]
I have PocketMine-MP.phar file which is supported to work with McPe v1.1.0 also multiple enchnats are fixed in it by me.

**Comment by DeathRaven359** [comment]
Does it allow loading old API plugins?

**Comment by brianzp** [comment]
I am afraid that it does not. It only allows api 3.0.0-APHA5

**Comment by jrodr10** [comment]
You'd just type ms in the server console to make the phar but 1.1 isn't done for Tesseract yet

**Comment by Qimie** [comment]
1. Download the src and use it.
2. Run /makeserver in the console. Without /
3. Check the DevTools folder in the plugin folder.

On Jun 5, 2017 10:09 PM, "LavaBucketDEV" <notifications@github.com> wrote:
>
> I apologize in advance for how inept I must seem as I do not know how to
use /makeserver on DevTools.
