### ISSUE TITLE
1.1 Version not work!

### ISSUE THREAD

**Issue by BexiPE** [TesseractTeam/Tesseract#1148]
I Join whit version 1.1 but it doesnt work!

**Comment by brianzp** [comment]
That's because just changing the protocol version will not allow the server to run. If it does then players would not be able to connect. There are other files too which need changes. We need the Official Owners of this repo back to fix it.

**Comment by BexiPE** [comment]
How long does it take?

**Comment by brianzp** [comment]
I literally dont know. Its upto Linux as to when he gives back this repo to its official owners...

**Comment by BexiPE** [comment]
There are softwares which are on the 1.1? (except MP)

**Comment by jdongel2004** [comment]
@BexiPE Rocky, BlueLight

**Comment by jrodr10** [comment]
@BexiPE GenisysPro.

**Comment by jrodr10** [comment]
Repeat #1141
