### ISSUE TITLE
Client can't join the server (my English is poor, I am sorry. I am from Russia)

### ISSUE THREAD

**Issue by XCreaTivic** [TesseractTeam/Tesseract#1150]
#### Problem description

Client can't join the server. Raklib enabled.

#### OS and versions

* Tesseract: Tesseract-1.3.0 Unity
* PHP: 7.0.3
* Server OS: Ubuntu
* Game version: v1.1.0.55
* Server host: VDS
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```
[Tesseract] [23:46:03] INFO>
┌─────────────────────────────────────────────────┐  -- Loaded: Properties and Configuration --
│                                                 │    Date: Mon, June 05, 2017, 23:46 MSK
│   _______                                _      │    Version: 1.3.0 Codename: Unity
│  |__   __|                              | |     │    MCPE: v1.1.0.55 Protocol: 113
│     | | ___  ___ ___  ___ _ __ __ _  ___| |_    │    IP: 194.67.215.249 Port: 19132
│     | |/ _ \/ __/ __|/ _ \ '__/ _` |/ __| __|   │    Query: 0.0.0.0
│     | |  __/\__ \__ \  __/ | | (_| | (__| |_    │    SSL Extension: false
│     |_|\___||___/___/\___|_|  \__,_|\___|\__|   │    Authentication: offline mode/insecure
│                                                 │  ------------------------------------------
│                                                 │    API Version: 3.0.0-ALPHA3
│   Support: github.com/TesseractTeam/Tesseract   │    Language: eng
│          │    Package: src
└─────────────────────────────────────────────────┘  ------------------------------------------
[Tesseract] [23:46:04] INFO> Starting remote control listener
[Tesseract] [23:46:04] INFO> RCON running on 0.0.0.0:19132
[Tesseract] [23:46:04] INFO> Everything seems to be alright! Server started!
[Tesseract] [23:46:04] INFO> Loading recipes...
[Tesseract] [23:46:04] INFO> Loading WorldEdit+ v0.01
[Tesseract] [23:46:04] INFO> Loading ManyWorlds v2.0.3
[Tesseract] [23:46:04] DEVELOPER> Loading plugin: GameXAuth v1.0.0
[Tesseract] [23:46:04] DEVELOPER> Loading plugin: XSuperSmashMobs v4.3
[Tesseract] [23:46:04] NOTICE> Level "world" not found
[Tesseract] [23:46:04] INFO> Preparing level "world"
[Tesseract] [23:46:04] NOTICE> Spawn terrain for level "world" is being generated in the background
[Tesseract] [23:46:05] INFO> Preparing level "nether"
[Tesseract] [23:46:05] INFO> Enabling WorldEdit+ v0.01
[Tesseract] [23:46:05] INFO> Enabling ManyWorlds v2.0.3
[Tesseract] [23:46:05] DEVELOPER> Enabling GameXAuth v1.0.0
[Tesseract] [23:46:05] DEVELOPER> Enabling XSuperSmashMobs v4.3
[Tesseract] [23:46:05] INFO> Enabling..
[Tesseract] [23:46:05] INFO> Starting GS4 status listener
[Tesseract] [23:46:05] INFO> Query running on 0.0.0.0:19132
[Tesseract] [23:46:05] INFO> Default game type: Survival Mode
[Tesseract] [23:46:05] INFO> Done (2.007s)! For help, type "help" or "?"

**Comment by ZizzyZizzy** [comment]
Ditto.  Created .phar from the latest source (several hours ago) and you cannot join. No plugins, just the .phar running.

**Comment by Pizzahaet** [comment]
Tesseract doesn't support 1.1 you can blame Linux for that

**Comment by jrodr10** [comment]
Tesseract does not yet support 1.1.x yet @XCreaTivic

**Comment by jrodr10** [comment]
You can check on our conversation regarding this topic at #1141

**Comment by ZizzyZizzy** [comment]
Thanks..didn't see the other issue. I assumed since the 1.1 changes were merged with the master that Tesseract was ready.

Different repo, different procedures.

**Comment by ZloyNick** [comment]
Ой, это же Ахор)0))0
