### ISSUE TITLE
Error player join

### ISSUE THREAD

**Issue by MrSmileCH** [TesseractTeam/Tesseract#1155]
Problem description

[Server] Warning: assert(): Still 1 bytes unread in pocketmine\network\protocol\MovePlayerPacket failed in phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/pocketmine/network/Network.php on line 256

#### OS and versions
* Tesseract: Tesseract-1.2.0 Ruby
* PHP: 7.0.3
* Server OS: android
* Game version: 1.1.0.55
* Server host: local

**Comment by Qimie** [comment]
More details pls. Like ur plugin and etc
