### ISSUE TITLE
Read this

### ISSUE THREAD

**Issue by G2PCraft** [TesseractTeam/Tesseract#1156]
Please undo every update to 1.1.0.55

**Comment by Qimie** [comment]
Wait until Apple gets the repo back

**Comment by jrodr10** [comment]
Apple isn't getting the repo back.. do you even check twitter bro lol @Qimie

**Comment by AppleDevelops** [comment]
@jrodr10 Nor do I want this messed up shit back from you

**Comment by Qimie** [comment]
Ik. Thats why Apple has a new repo AND ITS ANTI-LINUX

**Comment by AppleDevelops** [comment]
Actually his spoon of PMMP is a spoon of TesseractPM

**Comment by G2PCraft** [comment]
@jrodr10 did you khow you is suck develop for erver. Don't cry man.
