### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by G2PCraft** [TesseractTeam/Tesseract#1158]
[Tesseract] [15:00:00] [error] >  @jrodr10 is noob on line 1.

**Comment by jrodr10** [comment]
Don't open retarded comments as issues. If you want to contact me email me at admin@darkrealms.net! Furthermore if you do something stupid like this agin you'll be banned from the repo. And if you don't care.. guess what I don't care about you not caring it's gonna happen anyway..

**Comment by Qimie** [comment]
Ban me plz. Suckers
