### ISSUE TITLE
some plugins did not work

### ISSUE THREAD

**Issue by StormCraftMCPE** [TesseractTeam/Tesseract#1159]
Some plugins did not work, Including EssentialsPE Plugin

**Comment by jrodr10** [comment]
[EssentialsPE_v2.0.0.zip](https://github.com/TesseractTeam/Tesseract/files/1060336/EssentialsPE_v2.0.0.zip)

I fixed Essentials...can you provide more information with actual bugs..

**Comment by jrodr10** [comment]
Any other questions.. or plugins???

**Comment by TDMidkwhatisxd** [comment]
ummm, is this more stable than bluelight? I don't see tesseract.yml in resources. Is a pmmp clone?
