### ISSUE TITLE
Allowed memory size

### ISSUE THREAD

**Issue by BexiPE** [TesseractTeam/Tesseract#1160]
Server crashed:

Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 131072 bytes)
File: /src/pocketmine/nbt/NBT
Line: 249
Type: E_ERROR

**PLS FIX THIS!**

**Comment by jrodr10** [comment]
I'm not sure how to reproduce this, what steps did you take to see this error.

**Comment by BexiPE** [comment]
Its Crashed by my QSG Plugin xD.
But in a Older version this not Crash.

**Comment by BexiPE** [comment]
It crash each 1 Hour and 30 Minutes whit 0 Players my Server has 12gb.

**Comment by jrodr10** [comment]
Update if same error let me know, if not close this.

**Comment by BexiPE** [comment]
Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 131072 bytes)
File: /src/pocketmine/nbt/NBT
Line: 249
Type: E_ERROR

It was Crash for 1 min.

**Comment by BexiPE** [comment]
And this error is new I use my Plugin about 1 Year and it is never crashing but about the version 1.0.0 is this Crashing wtf? Rip Coding for MP

**Comment by jrodr10** [comment]
Okay what plugin send me it through email to admin@darkrealms.net it may just be your plugin

**Comment by BexiPE** [comment]
So I have it send ^^. 👍

**Comment by TDMidkwhatisxd** [comment]
so dumb. It gets fixed in pocketmine.yml.

main-hard-limit: 1024 to main-hard-limit: 0 , and finish.
IT stops because it used more ram that you allowed to the server.

Linux really? you didn't know this?

**Comment by BexiPE** [comment]
fix it the Crashes?

**Comment by TDMidkwhatisxd** [comment]
main hard limit put 0, it limit your server to crash if use more than 1gb ram lol

**Comment by Qimie** [comment]
Give more detail like plugins etc. Does any1 read the tempate b4 submitting
a issue?

**Comment by jrodr10** [comment]
Lmao I didn't think it was a ram issue as it's talkin about the NBT though this kid doesn't follow the issue format soooooo

**Comment by TDMidkwhatisxd** [comment]
NBT could not use any more Ram , that's all. FK the logic.
