### ISSUE TITLE
DispatchCommand it does not work

### ISSUE THREAD

**Issue by BexiPE** [TesseractTeam/Tesseract#1162]
My Plugin has ah function whit Dispatch Command but it is not work!
Tesseract v 1.0.7 it did work.
**Fix it Pls**

**Comment by BexiPE** [comment]
Fix? xD

**Comment by Qimie** [comment]
Plugin Issue? #Close

**Comment by jrodr10** [comment]
Unless it's a missing function that was in the old tesseract lol @Qimie

**Comment by jrodr10** [comment]
You're the most helpful unhelpful little fuck @Qimie
