### ISSUE TITLE
Binary

### ISSUE THREAD

**Issue by majovec** [TesseractTeam/Tesseract#1163]
13:15:17 [CRITICAL] Unhandled exception executing command 'lobby' in lobby: Argument 1 passed to pocketmine\utils\Binary::writeLShort() must be of the type integer, string given, called in /root/Creative/src/pocketmine/utils/BinaryStream.php on line 148
13:15:17 [CRITICAL] TypeError: "Argument 1 passed to pocketmine\utils\Binary::writeLShort() must be of the type integer, string given, called in /root/Creative/src/pocketmine/utils/BinaryStream.php on line 148" (EXCEPTION) in "/src/pocketmine/utils/Binary" at line 162
   

In 1.0.9 Binary nice work and now not

**Comment by Qimie** [comment]
Linux Brokes everything. #TesseractsDead

**Comment by majovec** [comment]
Yes :( #TesseractsDead

**Comment by Qimie** [comment]
U have Twitter? If u have imma tell u a software that isnt dead as Linux.

**Comment by majovec** [comment]
@Fylkacz

**Comment by jrodr10** [comment]
It's not even close to broken?

**Comment by majovec** [comment]
broken i only wrote /lobby  ( in old tesssearct send player to lobby server ) and console only send this crash and don't transfering player ..
