### ISSUE TITLE
I can't damage the mobs

### ISSUE THREAD

**Issue by SerezhaIvanov** [TesseractTeam/Tesseract#1166]
#### Problem description

I can't damage the mobs

#### Steps to reproduce the issue

Hit the mob

#### OS and versions

* Tesseract Version: 1.3.0 Unity
* PHP: 7
* Server OS: Ubuntu
* Game version: 1.1.0.55
* Server host: ihor.ru
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```
22:12:41 [CRITICAL] Error: "Undefined class constant 'SHARPNESS'" (EXCEPTION) in "/src/pocketmine/item/Tool" at line 56
22:12:41 [CRITICAL] Error: "Undefined class constant 'SHARPNESS'" (EXCEPTION) in "/src/pocketmine/item/Tool" at line 56
22:12:41 [CRITICAL] Error: "Undefined class constant 'SHARPNESS'" (EXCEPTION) in "/src/pocketmine/item/Tool" at line 56
22:12:41 [CRITICAL] Error: "Undefined class constant 'SHARPNESS'" (EXCEPTION) in "/src/pocketmine/item/Tool" at line 56
22:12:41 [CRITICAL] Error: "Undefined class constant 'SHARPNESS'" (EXCEPTION) in "/src/pocketmine/item/Tool" at line 56
22:12:41 [CRITICAL] Error: "Undefined class constant 'SHARPNESS'" (EXCEPTION) in "/src/pocketmine/item/Tool" at line 56
22:12:41 [CRITICAL] Error: "Undefined class constant 'SHARPNESS'" (EXCEPTION) in "/src/pocketmine/item/Tool" at line 56
22:12:41 [CRITICAL] Error: "Undefined class constant 'SHARPNESS'" (EXCEPTION) in "/src/pocketmine/item/Tool" at line 56
22:12:41 [CRITICAL] Error: "Undefined class constant 'SHARPNESS'" (EXCEPTION) in "/src/pocketmine/item/Tool" at line 56

**Comment by EoflaOE** [comment]
Please try again in new version of Tesseract
