### ISSUE TITLE
New bug with Enchanted stuff

### ISSUE THREAD

**Issue by KnightOfEnder** [TesseractTeam/Tesseract#117]
#### Problem description
When server (minecraft pe) is open on Tesseract-master (once unzip on ssh client) every last enchanted item on the server losses it enchantments (showing in a Youtube video by me) so I went to make more with a enchant table, then put the item in a chest. But when I open cheat 1 second after the item had also loss it enchantment and went back to normal gear.

#### Steps to reproduce the issue
<load a Mcpe server up with the Tesseract-master.zip stuff and see if it happens.

#### OS and versions
* Tesseract: Crystal
* PHP: 7.0.3
* Server OS: ??? Don't know what that is
* Game version: 1.0
* Server host: VPN from blueleafhosting (android phone)

<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```
Item That enchanted
![screenshot_2017-01-12-00-21-55](https://cloud.githubusercontent.com/assets/24853541/21871940/567885b0-d85d-11e6-8f4c-5444d46421ad.png)
Place item in chest
![screenshot_2017-01-12-00-22-21](https://cloud.githubusercontent.com/assets/24853541/21871944/5a560914-d85d-11e6-8435-ee33819e0b99.png)
Close chest and open and u can see np enchanted item now
![screenshot_2017-01-12-00-22-03](https://cloud.githubusercontent.com/assets/24853541/21871948/5e3afb70-d85d-11e6-97bf-4f49225cfe7e.png)

**Comment by KnightOfEnder** [comment]
So is it fix or ???

**Comment by AppleDevelops** [comment]
It is fixed

**Comment by AppleDevelops** [comment]
try latest version

**Comment by KnightOfEnder** [comment]
So reinstall tesseract-master ? To apply fox

**Comment by AppleDevelops** [comment]
Yes
