### ISSUE TITLE
 Tripwire hook bug

### ISSUE THREAD

**Issue by andris155** [TesseractTeam/Tesseract#1175]
#### Problem description

 Tripwire hook bug

#### Steps to reproduce the issue

1. Place Tripwire hook

#### OS and versions

* Tesseract Version: 1.3.0 Unity
* PHP: 7.0.17
* Server OS: Windows 10 Creators Update
* Game version: 1.1.0.55
* Server host: My PC
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

![screenshot_20170609-002116](https://user-images.githubusercontent.com/8324198/26953294-c845203e-4ca9-11e7-8ee9-48aa12144e23.png)

**Comment by jrodr10** [comment]
i dont see the bug...
