### ISSUE TITLE
Plugins not loading with latest version

### ISSUE THREAD

**Issue by FienixEC** [TesseractTeam/Tesseract#1177]
#### not sure if im not doing something right, but using the latest Src folder, my server loads fine, however none of my plugins load, all are 3.0.0-ALPHA6. not sure if this is a known issue being fixed, dont see anyone post a similar issue, so im posting this to hopefully resolve my issue, as i am a tesseract fan over pmmp. thank you!

 Loaded latest tess. Src started server, 0 plugins load.

#### OS and versions

* Tesseract Version: 1.3.0 Unity
* PHP:
* Server OS: Linux
* Game version: 1.1.0.55
* Server host:
Private dedicated host<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```N/A
```

**Comment by jrodr10** [comment]
Try changing your plugins back to their original API also can I have a plugin list, as I cannot reproduce this using the latest version

**Comment by FienixEC** [comment]
Most of my plugins have api 3.0.1/3.0.0-ALPHA4-ALPHA6
and here is the list:
BanItem
BlockSniffer
ChatTagPE
EconomyAPI
EconomyJob
EconomyLand
EconomyProperty
EconomySell
EssentialsPE
FactionsPro
MSpawns
MagicWE_v0.2.6
MyPlot
PlayerSizer_v0.3
PortalsPE
PureChat
PurePerms
RankPoints
RankSetGo
TapToDo
Tesseract
VoteReward-maste
WorldProtect-master
superBAR_v1.6.0

**Comment by AppleDevelops** [comment]
@jrodr10 You really fucked up

**Comment by FienixEC** [comment]
Umm....okay? Lol.
