### ISSUE TITLE
Effects Conflicting with my plugin. Fix this.

### ISSUE THREAD

**Issue by jrodr10** [TesseractTeam/Tesseract#1179]
17:48:43 [CRITICAL] TypeError: "Argument 3 passed to pocketmine\entity\Effect::__construct() must be an instance of pocketmine\utils\Color, integer given, 
called in phar:///home/PRIVATE_DO_NOT_TOUCH/21/plugins/SD.phar/src/SDEffect/Task.php on line 34" (EXCEPTION) in "/src/pocketmine/entity/Effect" at line 144

**Comment by mal0ne-23** [comment]
Show your code:

`src/SDEffect/Task.php (line 34)`

It seems like this isn't a core issue, but rather a plugin issue, constructing an Effect incorrectly. You shouldn't have to construct an effect anyways, just do this:

`$effect = Effect::getEffect(Effect::EFFECT_CONSTANT)->setDuration((int) 20 * $seconds)->setAmplifier((int) 1)->setVisible((bool) false);`

Might be a good idea to disallow plugins constructing new effect classes, not really sure though this is just a quick look over at your issue.
