### ISSUE TITLE
woohoo

### ISSUE THREAD

**Issue by mal0ne-23** [TesseractTeam/Tesseract#1180]
glad u got ur shit back from that @jrodr10 cunt

**Comment by mal0ne-23** [comment]
now invite me to the repo and make me owner pls

**Comment by jrodr10** [comment]
Your welcome 👌🏼

**Comment by AppleDevelops** [comment]
@jrodr10 Stop acting like the hero

**Comment by jdongel2004** [comment]
Mute.

**Comment by CortexPE** [comment]
Me just need write perms...
I'll add a lot of stuff... ("Advanced Server Software")
(^_^)

**Comment by Pizzahaet** [comment]
no fucking way? About fucking time it is back to the og owners!!

**Comment by TDMidkwhatisxd** [comment]
apple plans to delete it, he was trying to delete all forks(trick forks owners) at once, but failed.
I think jrodr10 don't lie, but he has no skillz in programing.

**Comment by LagHD** [comment]
Someone should make a replica of this, just in case this gets deleted...

**Comment by LinuxLogo** [comment]
Already got it covered lol

**Comment by LinuxLogo** [comment]
60% chance he will just delete this lol

**Comment by Qimie** [comment]
So whos the new owner of this repo now?

**Comment by caspervanneck** [comment]
@jrodr10 is tish dead i hope all the bugss will be fixt

**Comment by AppleDevelops** [comment]
I’m owner now, but it’s not deleted

**Comment by LinuxLogo** [comment]
Not yet lol

**Comment by jdongel2004** [comment]
@AppleDevelops why you can't delete it?
