### ISSUE TITLE
Ender Pearl bug

### ISSUE THREAD

**Issue by SerezhaIvanov** [TesseractTeam/Tesseract#1182]
#### Problem description

Ender Pearl don't work.

#### Steps to reproduce the issue

Right click ender Pearl.

#### OS and versions

* Tesseract Version: 1.3.0 Unity
* PHP: 7
* Server OS: Ubuntu
* Game version: 1.1.0.55
* Server host: ihor.ru
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

`Errors don't found.``
```

**Comment by SuperKali** [comment]
confirmed! 
Even pearl enders do not work for me

**Comment by EoflaOE** [comment]
Ender pearl have been added, but it does not have any code for throwing so it will not work.
