### ISSUE TITLE
CreativeLimiter ?

### ISSUE THREAD

**Issue by StormCraftMCPE** [TesseractTeam/Tesseract#1183]
Bugs Creative Limiter ,Open Chest & Drop item In gamemode Survival

**Comment by StormCraftMCPE** [comment]
in gamemode creative ,me Is Typo xD

**Comment by EoflaOE** [comment]
- Could you please give us more information?

**Comment by StormCraftMCPE** [comment]
1.When I'm in the Creative gamemode, when I open the Chest, the Chest is open, it does not happen when the previous version of Tesseract

2. when player is gamemode Creative And Holding a Blocks, then Player change Gamemode To survival, Blocks Tesebut Become 64/1 stacks, please fix this Bug

**Comment by EoflaOE** [comment]
1. Tesseract will no longer have Limited creative. 
2. What do you mean by "Tesebut"?

**Comment by StormCraftMCPE** [comment]
Me Indonesia ,And Me Use google translate

**Comment by akaSnapy** [comment]
Ok so, he wanted to say Theres no limited creative so you are able to drop items from creative mode, also to open chests,ender chests hoppers n stuff while you are on creative mode.
