### ISSUE TITLE
isArmor() bug

### ISSUE THREAD

**Issue by SerezhaIvanov** [TesseractTeam/Tesseract#1184]
#### Problem description

When I check the item if it is armor I have an error.

#### Steps to reproduce the issue

Use code isArmor()
#### OS and versions

* Tesseract Version: 1.3.0 Unity
* PHP: 7
* Server OS: Ubuntu
* Game version: 1.1.0.55
* Server host: ihor.ru
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

``When I check the object if it is armor I have an error.`
```

**Comment by DanilZz** [comment]
согласен, ядро стало говном!

**Comment by DonkihotD** [comment]
Сирожа, ты че

**Comment by Bruno99** [comment]
Сирожа угар

**Comment by SerezhaIvanov** [comment]
15:10:10 [CRITICAL] Error: "Call to undefined method pocketmine\item\Chestplate
:isArmor()" (EXCEPTION) in "/plugins/API/src/SIvanov/API/Events" at line 111

**Comment by EoflaOE** [comment]
Serez, It is a plugin coding error. Could you send me a copy of this plugin on Discord?

**Comment by EoflaOE** [comment]
I will investigate where is the issue

**Comment by EoflaOE** [comment]
@Bruno99 Why are you laughing? Stop this
