### ISSUE TITLE
Please Fix :((

### ISSUE THREAD

**Issue by huybinh2009** [TesseractTeam/Tesseract#1185]
[CRITICAL] TypeError: "Argument 1 passed to pocketmine\Player::sendPosition() must be an instance of pocketmine\math\Vector3, null given, called in C:\Users\Administrator\Desktop\ge\src\pocketmine\Player.php on line 2155" (EXCEPTION) in "/src/pocketmine/Player" at line 3833

**Comment by MalakasPlayzMC** [comment]
Give us more information...
