### ISSUE TITLE
Tesseract Death????

### ISSUE THREAD

**Issue by BogdanMakarchuk** [TesseractTeam/Tesseract#1187]
Yes?? No???

**Comment by Qimie** [comment]
Yes. Still. Kinda. Maybe. Probably. Definitely. No. I guess.

**Comment by jdongel2004** [comment]
No. I think start developing again after two or three days.

**Comment by BogdanMakarchuk** [comment]
@jdongel2004, code PMMP-_-

**Comment by GamakCZ** [comment]
I can also use PocketMine or Genisys(https://github.com/GenisysPro/GenisysPro)

**Comment by skylightpe** [comment]
On PocketMine enchant not work.

**Comment by BexiPE** [comment]
Its not realy Death but the Version is in Alpha and has Some Bugs ^^

**Comment by shdudwns** [comment]
link https://github.com/AppleDevelops/TesseractPM or https://github.com/NewTesseractTeam/NewTesseract

**Comment by TheRoyalBlock** [comment]
Actually, Looks like linux gave proper ownership of Tesseract back. Nice!

**Comment by andris155** [comment]
The Pocketmine very unusable missing some blocks, tile, enitity-s etc. The GenisysPro good alternative.

**Comment by andris155** [comment]
I forked PocketMine and added some blocks and tiles from Genisys and Tesseract code.
https://github.com/andris155/PocketMine-TOC

**Comment by ImagicalGamer** [comment]
I bought the ownership back, Linux didn't give shit.

**Comment by TheRoyalBlock** [comment]
@ImagicalGamer Ouch... I thought he actually gave something back for once and I was in a state of disbelief
