### ISSUE TITLE
not working devtools

### ISSUE THREAD

**Issue by suslik1234** [TesseractTeam/Tesseract#1190]
devtools is not working. although the kernel version 1.0.9 everything worked
 [INFO] Enabling DevTools v1.11.3
22:21:29 [CRITICAL] ErrorException: "Array to string conversion" (EXCEPTION) in "/src/pocketmine/plugin/PluginDescription" at line 133
22:21:29 [INFO] Disabling DevTools v1.11.3

**Comment by andris155** [comment]
Please use DevTools 1.11.2
