### ISSUE TITLE
Make Server issue

### ISSUE THREAD

**Issue by Shadow166050** [TesseractTeam/Tesseract#1191]
[Tesseract] [22:15:31] INFO> An unknown error occurred while attempting to perform this command
[Tesseract] [22:15:31] CRITICAL> Unhandled exception executing command 'makeserver' in makeserver: Class pocketmine\network\mcpe\protocol\ProtocolInfo not found
[Tesseract] [22:15:31] CRITICAL> ClassNotFoundException: "Class pocketmine\network\mcpe\protocol\ProtocolInfo not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144

Run makeserver with Devtools

**Comment by Shadow166050** [comment]
Or can you just add makeserver back to Tesseract commands

**Comment by AppleDevelops** [comment]
When Tesseract is out of it's random beta
