### ISSUE TITLE
.phar file?

### ISSUE THREAD

**Issue by XDqrkneZ** [TesseractTeam/Tesseract#1194]
#### Steps to reproduce the issue

where can i get the latest .phar?

#### OS and versions

* Tesseract Version: 1.3.0 Unity
* PHP:
* Server OS:
* Game version: 1.1.0.55
* Server host:
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Lazerplayz** [comment]
Please read the README.md for this type of information!

**Comment by akaSnapy** [comment]
This is a stupid Issue, not even one. You can use devtools to compile it.

**Comment by akaSnapy** [comment]
@AppleDevelops Close this please

**Comment by jdongel2004** [comment]
use circleci or devtools

**Comment by HipsterAF** [comment]
Just start the server with src folder and do /ms on console and find your .phar in plugins/tesseract folder

**Comment by XDqrkneZ** [comment]
@hipsteraf you are the best
