### ISSUE TITLE
Inventory Bug

### ISSUE THREAD

**Issue by Shadow166050** [TesseractTeam/Tesseract#1195]
#### Problem description
Opening your inventory crashes your game

#### Steps to reproduce the issue
Open Inventory

* Tesseract Version: 1.3.0 Unity
* PHP:
* Server OS:
* Game version: 1.1.0.55
* Server host: Me

Tested on Windows10 NOT MOBILE 
```

**Comment by HipsterAF** [comment]
Reproduced
