### ISSUE TITLE
BatchPacket

### ISSUE THREAD

**Issue by HipsterAF** [TesseractTeam/Tesseract#1199]
#### Problem description

Error when tried to join with no plugins
[Tesseract] [11:11:58] CRITICAL> TypeError: "Argument 1 passed to pocketmine\network\CompressBatchedTask::__construct() must be an instance of pocketmine\network\z, string given, called in F:\PocketMine-MP\src\pocketmine\Server.php on line 2054" (EXCEPTION) in "/src/pocketmine/network/CompressBatchedTask" at line 35
#### Steps to reproduce the issue

Try to join
#### OS and versions

* Tesseract Version: 1.3.0 Unity
* PHP: 7.0.19
* Server OS: Linux
* Game version: 1.1.0.55
* Server host: VG
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by AppleDevelops** [comment]
oh shit lol
