### ISSUE TITLE
Freezes

### ISSUE THREAD

**Issue by Pizzahaet** [TesseractTeam/Tesseract#120]
#### Problem description
Players are pvping at our warp spawn then after a while they freeze but chat continues as normal and they can still get damaged but the damaging is like a few hits at a time

#### Steps to reproduce the issue
Not sure how to reproduce it 

#### OS and versions

* Tesseract: Tesseract-1.0.0dev Crystal
* PHP: 7.0.3
* Server OS: Not sure
* Game version: 1.0.0
* Server host: MinersPlanet
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files
I have a error message I think has something to do with it 
12.01 13:44:07 [Server] INFO [Tesseract] [13:44:07] CRITICAL> Could not tick level "FactionsSpawn": Call to a member function getValue() on null

**Comment by remotevase** [comment]
What format is the world? .mcr  or .mca or .mcapm?

**Comment by remotevase** [comment]
That may have something to do with it.

**Comment by remotevase** [comment]
Fixed

**Comment by AppleDevelops** [comment]
That's not it @remotevase

**Comment by remotevase** [comment]
No? I gtg though cuz im doin this from school durin lunch

**Comment by remotevase** [comment]
Pretty sure that it works now

**Comment by remotevase** [comment]
because yesterday about 16 hours ago, I did not have this issue...

**Comment by Pizzahaet** [comment]
It's a .mca world

**Comment by Pizzahaet** [comment]
Hopefully you can get this fixed I want to be able to use Tesseract...

**Comment by remotevase** [comment]
Works perfectly fine on my test server.

**Comment by remotevase** [comment]
Never mind, I've been playing for 15 minutes and now it froze... Aww damn it

**Comment by AppleDevelops** [comment]
Cannot reproduce issue

**Comment by remotevase** [comment]
I can reproduce it when using Windows 10.  Cannot reproduce on Android or iOS (yes, I tested all three)

**Comment by remotevase** [comment]
Wait never mind I tested 7 hours ago, and there are new commits that may have fixed it
