### ISSUE TITLE
Warnings Everytime A Command Is Run.

### ISSUE THREAD

**Issue by MasterOfTheRealm** [TesseractTeam/Tesseract#1202]
#### Problem description

Warning: assert(): Still 3 bytes unread in pocketmine\network\protocol\CommandStepPacket failed in C:\Users\Realm\Documents\Compressed\New folder (2)\Installation-Binariesx86-master\src\pocketmine\network\Network.php on line 257

#### Steps to reproduce the issue

Run A Command.

#### OS and versions

* Tesseract Version: 1.3.0 Unity
* PHP: 7.0.19
* Server OS: Windows 7
* Game version: 1.1.0.55
* Server host:
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by HipsterAF** [comment]
Can't reproduce, are you using the latest build?

**Comment by AppleDevelops** [comment]
Unable to reproduce
