### ISSUE TITLE
There is a bug with the MyPlot plugin

### ISSUE THREAD

**Issue by huybinh2009** [TesseractTeam/Tesseract#1203]
CRITICAL> Exception: "Unable to open database: unable to open database file" (EXCEPTION) in "/plugins/MyPlot_raw/src/MyPlot/provider/SQLiteDataProvider" at line 22

**Comment by HipsterAF** [comment]
report this on myplot issues, not here #close

**Comment by huybinh2009** [comment]
ohm sorry
