### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by HipsterAF** [TesseractTeam/Tesseract#1205]
#### Problem description

Sound is broken
#### OS and versions

* Tesseract Version: 1.3.0 Unity
* PHP: 7.0.19
* Server OS: Linux
* Game version: 1.1.0.55
* Server host: VG
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by jdongel2004** [comment]
Not yet

**Comment by HipsterAF** [comment]
is this ever gonna get fixed?
