### ISSUE TITLE
Block getting destroyed

### ISSUE THREAD

**Issue by HipsterAF** [TesseractTeam/Tesseract#1206]
#### Problem description

Can't see the block getting destroyed, it just gets destroyed like in creative
#### Steps to reproduce the issue

Break a block
#### OS and versions

* Tesseract Version: 1.3.0 Unity
* PHP: 7.0.19
* Server OS: Linux
* Game version: 1.1.0.55
* Server host: VG
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Shadow166050** [comment]
Blocks take the same time to break but there is no animation when it breaks

**Comment by HipsterAF** [comment]
Yea exactly

**Comment by HipsterAF** [comment]
nvm i fixed this
