### ISSUE TITLE
Bugs found

### ISSUE THREAD

**Issue by Shadow166050** [TesseractTeam/Tesseract#1208]
#### Problem description
When placing blocks if you have more then 1 it will place them all as 1

#### Steps to reproduce the issue
Place block

#### OS and versions
TESTED ON WINDOWS 10

* Tesseract Version: 1.3.0 Unity
* PHP:
* Server OS:
* Game version: 1.1.0.55
* Server host:

```

**Comment by Shadow166050** [comment]
Textures are broken 

http://imgur.com/a/xBp2v

(sorry about the HUD)

**Comment by HipsterAF** [comment]
can't reproduce

**Comment by Shadow166050** [comment]
I was placing dirt

**Comment by HipsterAF** [comment]
Nah works for me, try placing without any plugins
