### ISSUE TITLE
Please welcome... OUR NEW TODO LIST!

### ISSUE THREAD

**Issue by remotevase** [TesseractTeam/Tesseract#121]
[I, @remotevase have just figured out how the projects system works! This is in my opinion AMAZING. I am now migrating all of the ToDo lists from all of my repositories to the projects tab! It has an amazing new interface and is great for keeping track of stuff! All of the items from the old ToDo list have been added to the new ToDo list! This entire post is a link to the new ToDo list, so don't hesitate to click! Tell me what you all think!](https://github.com/TesseractTeam/Tesseract/projects/1)

**Comment by remotevase** [comment]
[This is our current top priority, because it is a major bug that stops the player from being able to join the server.](https://github.com/TesseractTeam/Tesseract/projects/1#card-1364684)

**Comment by remotevase** [comment]
[Remember to Scroll on the bottom! There are 4 categories: ToDo, In Progress, Completed, Long Term Project, and Impossible To Fix :(

More will come soon. PLEASE GIVE FEEDBACK!](https://github.com/TesseractTeam/Tesseract/projects/1)

**Comment by Nought57** [comment]
It is hard to use depending on the terminal. but, I think it's a good idea. I decided to use Projects function.
