### ISSUE TITLE
Chest bug

### ISSUE THREAD

**Issue by teram1001** [TesseractTeam/Tesseract#1212]
#### Problem description
put something in the chest, it keeps coming out.

#### OS and versions

* Tesseract Version: 1.3.0 Unity
* PHP:
* Server OS:
* Game version: 1.1.0.55
* Server host:
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Shadow166050** [comment]
Could not reproduce
