### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by ivan691** [TesseractTeam/Tesseract#1214]
2017-06-13 [Tesseract] [15:15:59] INFO> Pie[/*.*.*.*:8019] logged out due to timeout
And MC Win10 Edition crashes

**Comment by EoflaOE** [comment]
Are you using the latest build?

**Comment by ivan691** [comment]
Yes

**Comment by Shadow166050** [comment]
Works fine for me

**Comment by akaSnapy** [comment]
Same for me.
