### ISSUE TITLE
How to compile with DevTools

### ISSUE THREAD

**Issue by MalakasPlayzMC** [TesseractTeam/Tesseract#1215]
The title says it

**Comment by EoflaOE** [comment]
What do you want to compile? Server? If it is the server, do /ms or /makeserver

**Comment by MalakasPlayzMC** [comment]
How? I want to create a phar of the latest build

**Comment by EoflaOE** [comment]
Do you have DevTools installed?

**Comment by AppleDevelops** [comment]
DevTools is built into the server, just use makeserver

**Comment by MalakasPlayzMC** [comment]
When I do makeserver it creates a file in the plugins/devtools that is same with the one I opened to start the server...

**Comment by MasterOfTheRealm** [comment]
I think the file is named Tesseract in your plugins folder

**Comment by Shadow166050** [comment]
just run command "ms" - Close this issue
