### ISSUE TITLE
BinaryStream.php

### ISSUE THREAD

**Issue by SuperKali** [TesseractTeam/Tesseract#1217]
13:27:01 [CRITICAL] Could not tick level "FZ-1": Argument 1 passed to pocketmine\utils\Binary::writeVarInt() must be of the type integer, float given, called in /root/NetworkGamesPE/src/pocketmine/utils/BinaryStream.php on line 301

**Comment by HipsterAF** [comment]
You need to enabled debug in pocketmine.yml and send the backtrace

**Comment by AppleDevelops** [comment]
I already know the issue, just seeing if I can fix it real quick

**Comment by SuperKali** [comment]
@HipsterAF ok
