### ISSUE TITLE
Return this commit

### ISSUE THREAD

**Issue by ivan691** [TesseractTeam/Tesseract#1218]
self::$list[self::NOTEBLOCK] = Noteblock::class;

Return:
self::$list[self::NOTEBLOCK] = NoteBlock::class;

It crashes

**Comment by ZloyNick** [comment]
Когда тапаешь на нб, или как?

Описывай, хотя бы, при каком действии крашится.

**Comment by ivan691** [comment]
Как бы вообще при запуске сервера

**Comment by HipsterAF** [comment]
#close this
