### ISSUE TITLE
You Back?

### ISSUE THREAD

**Issue by NFGamerMC** [TesseractTeam/Tesseract#1219]
Hi Apple. I understand that this is not the place to do this but is Jon still in the org? I see no tweets saying “I’m giving Tesseract back to Drew”. If so I would like you too check your notifications on twitter from me.

Least annoying way possible,
Nathaniel

**Comment by NFGamerMC** [comment]
@AppleDevelops Just a annoying ping.

**Comment by Shadow166050** [comment]
This is not an issue in the issue sections please dont post here unless you have an issue

**Comment by NFGamerMC** [comment]
Says you, you cannot even use punctuation.

**Comment by Shadow166050** [comment]
Are you pleased now? No wonder apple dose not check notifications from you :)

**Comment by NFGamerMC** [comment]
The fact that You warship him is the issue. You should really learn how to code. Now mind your own business and leave.

**Comment by NFGamerMC** [comment]
Your plugins are all forked.

**Comment by Shadow166050** [comment]
I do learn to code ASK apple kid. All my plugins are Private i'm not dumb so kids like you wont take them. And for the fact i've NEVER worshiped apple. Please talk again when you have common sense

**Comment by NFGamerMC** [comment]
Show Proof. Such as a image that shows a lock icon becide a repo. Show proof of I will assume you are lying and that yiu have a face like Bajan

**Comment by NFGamerMC** [comment]
Key word is “learn” you probably don’t even know how to call a function.

**Comment by Shadow166050** [comment]
http://imgur.com/a/jbRXV

Yes because i don't know how to code. When i've coded 80% of my server. Hard to be a ConfictPE Dev without knowing how to code.

**Comment by NFGamerMC** [comment]
Point Taken. What I don’t understand is why you get into conversations like this. I had told you to leave. Why not go bother the issue under me? You are not a owner of ConflictPE

**Comment by Shadow166050** [comment]
All i posted was that you posted an issue that was not an issue. Your the start of this argument. Also i am a Owner of ConflictPE as you can ask anyone associated with them

**Comment by NFGamerMC** [comment]
I can make issues if I want. You cannot stop me. Now go back to annoying the issue under me.

**Comment by Shadow166050** [comment]
Please post relevant issues next time. Its quite funny how quickly people shut up when you prove them wrong.
