### ISSUE TITLE
Why PurePerms cause crashs ?

### ISSUE THREAD

**Issue by CookieCode** [TesseractTeam/Tesseract#1221]
Please give me a solution ! I really need this on my server.

**Comment by HipsterAF** [comment]
Change playerloginevent to playerjoinevent on PPListener.php in pureperms

**Comment by CookieCode** [comment]
Don't work :/ "[CRITICAL]: ReflectionException: "Class _64FF00\PurePerms\PlayerJoinEvent  does not exist" (EXCEPTION) in "/src/pocketmine/plugin/PluginManager" at line 689"

**Comment by HipsterAF** [comment]
Use this i guess - https://github.com/poggit-orphanage/PurePerms

**Comment by FienixEC** [comment]
whoop! Did your first suggestion @HipsterAF and the change worked, @CookieCode theres about 4 areas the change needs to be made in within that file. anyways thanks @HipsterAF
