### ISSUE TITLE
Much error

### ISSUE THREAD

**Issue by armagadon159753** [TesseractTeam/Tesseract#1223]
![screenshot_2017-06-13-21-58-59](https://user-images.githubusercontent.com/25569806/27102548-eacbd140-5085-11e7-8449-f333f60a1257.png)

**Comment by Shadow166050** [comment]
Please list how you got the error, but it looks like a plugin issue.

**Comment by armagadon159753** [comment]
Can you check my plugin https://pastebin.com/fHRVSpPd

**Comment by Shadow166050** [comment]
https://codeshare.io/ayDBNo

Try that, your using the Entity PrimedTNT but you dont state at the top with use pocketmine\entity\PrimedTNT;

**Comment by Shadow166050** [comment]
I made another fix, you did  $snowball = Entity::createEntity("PrimedTNT", $player->getlevel(), $nbt, $player);

when TNT isnt a projectile so you only need $snowball = Entity::createEntity("PrimedTNT", $player->getlevel(), $nbt);

**Comment by armagadon159753** [comment]
Tgs dont forget to fix warning and i have few problem with m'y Skyblock plugin.

**Comment by armagadon159753** [comment]
Can hiu seend  my  bin postbin plz
