### ISSUE TITLE
Random issue

### ISSUE THREAD

**Issue by Shadow166050** [TesseractTeam/Tesseract#1227]
13.06 16:54:22 [Server] INFO Warning: zlib_decode(): data error in phar:///custom-phar.phar/src/pocketmine/network/Network.php on line 253

Console spams the message above 

* Tesseract Version: 1.3.0 Unity
* PHP:
* Server OS:
* Game version: 1.1.0.55
* Server host:

```

**Comment by HipsterAF** [comment]
This happens when someone tries to login with an outdated client and it's not serious, happens in pmmp too, #close
