### ISSUE TITLE
SendTitle error 1.1.0

### ISSUE THREAD

**Issue by LewBr** [TesseractTeam/Tesseract#1229]
#### Problem description
SendTitle

#### Steps to reproduce the issue

wtf

#### OS and versions

* Tesseract Version: 1.3.0 Unity
* PHP: 7
* Server OS: MultiCraft
* Game version: 1.1.0.55
* Server host: NetherBox
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
13.06 17:12:42 [Server] INFO /17:12:42 [CRITICAL] Could not execute task pg\Auth\Tasks\PopupTipTick: Call to undefined method pocketmine\Player::sendTitle()
13.06 17:12:42 [Server] INFO /17:12:42 [CRITICAL] Error: "Call to undefined method pocketmine\Player::sendTitle()" (EXCEPTION) in "/LeoHarduCore/src/pg/Auth/Tasks/PopupTipTick" at line 16
```

**Comment by Shadow166050** [comment]
Make sure you plugin matches the code. 

Do sendTitleText

close issue

**Comment by AppleDevelops** [comment]
it's addtitle
