### ISSUE TITLE
[POLL] Move entity files around?

### ISSUE THREAD

**Issue by AppleDevelops** [TesseractTeam/Tesseract#123]
The files would be much cleaner and easier to work with.

Thumbs up = Yes
Thumbs down = No

**Comment by Nought57** [comment]
That's a good idea. Add move entity by Teseract.yml??

**Comment by AppleDevelops** [comment]
Yep!

**Comment by Nought57** [comment]
It's a great idea!

**Comment by xZeroMCPE** [comment]
Or maybe something like Entity.yml

To make things more organized.

**Comment by remotevase** [comment]
Great Idea!!!

**Comment by remotevase** [comment]
[Added](https://github.com/TesseractTeam/Tesseract/projects/1#card-1374550)
