### ISSUE TITLE
More languages

### ISSUE THREAD

**Issue by eemu2005** [TesseractTeam/Tesseract#124]
When comes few more languages like a Finnish? Cuz im finn.

- [ ] Finnish

**Comment by AppleDevelops** [comment]
We'd add Finnish but from my best knowledge, none of us know it.

**Comment by Nought57** [comment]
I create Finnish language file. But, May be it is incomplete.

**Comment by eemu2005** [comment]
okay.

**Comment by eemu2005** [comment]
@Nought57 check this website http://en.bab.la/dictionary/finnish-english/#.
It will be helpful to you.

**Comment by remotevase** [comment]
Done
