### ISSUE TITLE
Server Crashed

### ISSUE THREAD

**Issue by LordJoshie** [TesseractTeam/Tesseract#125]
#### Problem description

2017-01-14 [Tesseract] [19:39:57] CRITICAL> pocketmine\utils\ChunkException: "Invalid subchunk index 8!" (EXCEPTION) in "/src/pocketmine/level/format/Chunk" at line 108
2017-01-14 [Tesseract] [19:39:57] EMERGENCY> An unrecoverable error has occurred and the server has crashed. Creating a crash dump
2017-01-14 [Tesseract] [19:39:57] EMERGENCY> Please upload the "/home/purecraftpeconsole/Desktop/PureCraftPEv2/crashdumps/CrashDump_Sat_Jan_14-19.39.57-CST_2017.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.

#### Steps to reproduce the issue

Running build #22ab782 you can recreate this issue using numerous plugins and players on a setup server.

#### OS and versions

* Tesseract: 22ab782
* PHP: 7.0.2
* Server OS: Ubuntu 15.10
* Game version: MCPE:Win10
* Server host: OVH Canada.
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```
Tesseract Crash Dump Sat Jan 14 19:39:57 CST 2017

Error: Invalid subchunk index 8!
File: /src/pocketmine/level/format/Chunk
Line: 108
Type: notice

Code:
[99] 		$this->x = $chunkX;
[100] 		$this->z = $chunkZ;
[101] 
[102] 		$this->height = $provider !== null ? ($provider->getWorldHeight() >> 4) : 16;
[103] 
[104] 		$this->emptySubChunk = new EmptySubChunk();
[105] 
[106] 		foreach($subChunks as $y => $subChunk){
[107] 			if($y < 0 or $y >= $this->height){
[108] 				throw new ChunkException("Invalid subchunk index $y!");
[109] 			}
[110] 			if($subChunk->isEmpty()){
[111] 				$this->subChunks[$y] = $this->emptySubChunk;
[112] 			}else{
[113] 				$this->subChunks[$y] = $subChunk;
[114] 			}
[115] 		}
[116] 
[117] 		for($i = 0; $i < $this->height; ++$i){
[118] 			if(!isset($this->subChunks[$i])){

Backtrace:
#0 /src/pocketmine/level/generator/PopulationTask(169): pocketmine\level\format\Chunk::fastDeserialize(NULL , pocketmine\level\format\io\region\McRegion object)
#1 /src/pocketmine/scheduler/AsyncPool(151): pocketmine\level\generator\PopulationTask->onCompletion(pocketmine\Server object)
#2 /src/pocketmine/scheduler/ServerScheduler(268): pocketmine\scheduler\AsyncPool->collectTasks(boolean)
#3 /src/pocketmine/Server(2785): pocketmine\scheduler\ServerScheduler->mainThreadHeartbeat(integer 28252)
#4 /src/pocketmine/Server(2481): pocketmine\Server->tick(boolean)
#5 /src/pocketmine/Server(2360): pocketmine\Server->tickProcessor(boolean)
#6 /src/pocketmine/Server(1908): pocketmine\Server->start(boolean)
#7 /src/pocketmine/PocketMine(473): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string /home/purecraftpeconsole/Desktop/PureCraftPEv2/, string /home/purecraftpeconsole/Desktop/PureCraftPEv2/, string /home/purecraftpeconsole/Desktop/PureCraftPEv2/plugins/, string unknown)

Tesseract version: 0000000000000000000000000000000000000000 [Protocol 100; API 3.0.0]
uname -a: Linux vps60265.vps.ovh.ca 4.2.0-18-generic #22-Ubuntu SMP Fri Nov 6 18:25:50 UTC 2015 x86_64
PHP version: 7.0.2
Zend version: 3.0.0
OS : Linux, linux

Server uptime: 23 minutes 35 seconds
Number of loaded worlds: 7
Players online: 23/75

Loaded plugins:
DevTools 1.11.0 by PocketMine Team for API(s) 3.0.0-ALPHA1
EconomyAPI 2.0.9 by onebone for API(s) 2.0.0
FolderPluginLoader 1.1.0 by  for API(s) 1.12.0
EconomyShop 2.0.7 by onebone for API(s) 1.12.0
EconomyAirport 2.0.4 by onebone for API(s) 1.12.0
WorldProtect 2.2.0 by aliuly for API(s) 1.10.0, 1.12.0
KeepInventory 1.0.2 by Aster for API(s) 1.0.0, 2.0.0
TapToDo 2.2.1 by Falk for API(s) 1.0.0
EconomySell 2.0.7 by onebone for API(s) 1.12.0
TimeCommander 2.1 by LDX for API(s) 1.0.0, 2.0.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
CombatLogger 1.2.0 by Lambo for API(s) 1.12.0
RestartMe 1.2.0 by Gamecrafter for API(s) 1.10.0
ItemCloud 1.3 by onebone for API(s) 1.4.0
BuyCraft 1.2.2 by Falkirks for API(s) 1.0.0
GameTime 1 by FaigerSYS for API(s) 1.13.0, 2.0.0
AntiAbusiveEnchants 1 by SavionLegendZzz for API(s) 1.12.0
AntiSpam 1.3 by xBeastMode for API(s) 2.0.0
Alias 1.2.0 by ZacHack for API(s) 1.12.0
EssentialsPE 2.0.0 by LegendsOfMCPE Team for API(s) 2.0.0
CapsLimit 1.1.0 by deot for API(s) 1.10.0
PopupAlerts 1.3 by EvolSoft for API(s) 1.12.0
BlockSniffer 1.0.0 by DRedDogPE for API(s) 1.12.0
SimpleAuth 1.7.2 by PocketMine Team, shoghicp for API(s) 2.0.0
BasicHUD 1.0.6 by aliuly for API(s) 2.0.0
superBAR 1.5.1 by FaigerSYS for API(s) 1.13.0, 2.0.0
MineReset 2.2 by Falk for API(s) 1.0.0, 2.0.0
Broadcaster 1.16 by EvolSoft for API(s) 3.0.0-ALPHA1
CrateKeys 1.0.5 by CDFalcon, CDFalcon for API(s) 1.13.0
NetherChests2 1.1.1 by aliuly for API(s) 3.0.0-ALPHA1
BanItem 2.2 by LDX for API(s) 1.0.0, 2.0.0
ServerHub 0.1 BETA by ImagicalGamer for API(s) 1.0.0, 2.0.0
ItemCasePE 1.0.8 by aliuly for API(s) 1.10.0, 1.13.0
AdvancedKits 5.0b1 by luca28pet for API(s) 2.0.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
PocketGuard 2.1.1 by MinecrafterJPN for API(s) 2.0.0
ManyWorlds 2.0.3 by aliuly for API(s) 2.0.0, 1.13.0
PrizeWin 1.0.6 by LilCrispy2o9/Angelo Vidrio for API(s) 1.10.0
VoteReward 3.0.2 by LDX for API(s) 1.12.0, 2.0.0
TakeOver 1.0.0 by XFuryMCPE for API(s) 1.12.0, 2.0.0
NetherChests3 1.1.1 by aliuly for API(s) 3.0.0-ALPHA1
EconomyLand 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.12.0, 1.13.0, 2.0.0
TopVoter 1.1.6 by SalmonDE for API(s) 2.0.0
PvP-Stats 1.3 by Jack Noordhuis (CrazedMiner) for API(s) 1.12.0
JoinCommands 1.5 by Array for API(s) 1.0.0
Genisys-DevTools 1 by PocketMine Team & iTX Technologies LLC for API(s) 2.0.0
iProtector 3.1b by LDX for API(s) 1.9.0, 2.0.0
PmChair 1.2 by maru for API(s) 1.12.0, 1.13.0, 2.0.0
ChestRefill 1.1 by Falkirks for API(s) 2.0.0
MagicWE 0.1.12 by thebigsmileXD for API(s) 1.12.0
FactionsPro 1.3.2 by PureCraftPE for API(s) 1.12.0
NetherChests 1.1.1 by aliuly for API(s) 3.0.0-ALPHA1
BloodFX 1.1.0 by hoyinm14mc & CyberCube-HK Team for API(s) 1.12.0
HeadHunter 1.0.0 by BukkitPlaysMC for API(s) 1.0.0
Parkour 3 by Driesboy for API(s) 1.0.0, 2.0.0
PurePerms 1.3.7 by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0
SafeFly 1.0.0 by Sean_M for API(s) 1.0.0
NoVoid 0.3 by rirititi for API(s) 1.0.0
Help 1 by Muqsit for API(s) 1.13.1, 2.0.0
CommandTracker 1.1 by Scott Handley for API(s) 1.10.0
WordBlocker 1.0.0 by ankitmaharjan252, AndreTheGamer for API(s) 1.13.2
EconomyPShop 2.0.0 by onebone for API(s) 1.6.0, 1.7.0
SimpleAuthHelper 2.0.4 by aliuly for API(s) 1.12.0
RankUp 0.3.1 by Falkirks for API(s) 1.4.0
MyPlot 1 by Wies and Exxarion for API(s) 1.0.0
GrabBag 2.5.0 by aliuly for API(s) 1.10.0, 1.11.0, 1.12.0, 2.0.0
PureChat 1.4.0 by 64FF00 for API(s) 1.13.0, 2.0.0
SimpleWarp 2.1.0 by Falkirks for API(s) 3.0.0-ALPHA1
SimplePortals 0.0.5 by Falkirks for API(s) 1.10.0, 2.0.0

**Comment by AppleDevelops** [comment]
McRegion does not have support for 1.0. Use Anvil
