### ISSUE TITLE
/fill and /area not working or showing

### ISSUE THREAD

**Issue by KnightOfEnder** [TesseractTeam/Tesseract#127]
#### Problem description
/Fill and /area not showing in Server command for Op players. On console /area says use command in game and /fill show up as unknowing command. But I've got the files that make them work. 

#### Steps to reproduce the issue
Don't how to show u 

#### OS and versions

* Tesseract: Crystal
* PHP: 7
* Server OS:
* Game version: 1.0
* Server host: VPS backupsy ( android)
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by AppleDevelops** [comment]
What plugin are you using?

**Comment by KnightOfEnder** [comment]
I've fix the area problem. /fill working to now
