### ISSUE TITLE
InventoryPickupItemEvent isn`t working??

### ISSUE THREAD

**Issue by fuyutsuki** [TesseractTeam/Tesseract#128]
#### Problem description

InventoryPickupItemEvent isn`t working??

#### Steps to reproduce the issue

I chose an item by chest but it does not react.
```php
public function onPickup(InventoryPickupItemEvent $e){
　echo "pickup";
}
```

Nothing is output...

#### OS and versions

* Tesseract: latest
* PHP: 7.0.13
* Server OS: Win10
* Game version: Minecraft:PE v1.0.1
* Server host: localhost
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
nothing
```

**Comment by remotevase** [comment]
This is very strange, but I do not know what you are trying to accomplish... 
I know 1 reason why it is definitely not working:
The "echo" function is not supported in MCPE Server Plugins. Use the logger command. Once you have done that, tell me if the problem still is there.

**Comment by fuyutsuki** [comment]
I did not understanded InventoryPickupItemPacket.
Echo is to check if the processing goes to the event.

please remove tags, sorry.

**Comment by remotevase** [comment]
I'm sorry, I don't understand. If you want it to display a message when an Item is picked up, then use the $this->logger("") command with adequate setup. There is no problem with the packet (I just checked)

**Comment by fuyutsuki** [comment]
I am looking for an event or packet when I picked an item from the chest.
But InventoryPickupItemEvent was different from that event...

**Comment by remotevase** [comment]
I do not know. Figure it out yourself.

**Comment by fuyutsuki** [comment]
Ok, sorry.

**Comment by remotevase** [comment]
Sorry if that sounds rude ^^

**Comment by fuyutsuki** [comment]
I'm sorry.

**Comment by Nought57** [comment]
@fuyutsukiI think I should look it up after understanding the event. Because, Events and packets are deeply involved.

**Comment by Nought57** [comment]
@fuyutsuki I'm not familiar with Packet. I don't know if it is useful. But, I think that InventoryActionPacket could be used. This packet is called during Inventory operation.

**Comment by fuyutsuki** [comment]
@Nought57 Ok, I'll try it. Thank you.
