### ISSUE TITLE
Bow bug

### ISSUE THREAD

**Issue by vzlomka76** [TesseractTeam/Tesseract#129]
#### OS and versions

* Tesseract:https://github.com/TesseractTeam/Tesseract/commit/b3785ca05c5dc4365b0b40fdaa08dd3748e04632
* PHP: 7.0.6
* Server OS: Ubuntu 16.04
* Game version: 1.0.0
<br><br>
Video:
http://radikal.ru/video/l0631grJofE

```
```

**Comment by remotevase** [comment]
Hm.... This has something to do with a problem in the release code. Are there any console errors?

**Comment by vzlomka76** [comment]
@remotevase no, i check elywing code, there is all the same, but it works

**Comment by remotevase** [comment]
So the bow works in Elywing, but does not work in Tesseract? That is very very strange...

**Comment by remotevase** [comment]
@Nought57 You have confirmed it? I have not...

**Comment by Nought57** [comment]
@remotevase Sry, label change miss.

**Comment by Nought57** [comment]
This Bug is Plugin Problem. Please check your plugin.

**Comment by remotevase** [comment]
plugin? How do you know?

**Comment by Nought57** [comment]
This is my hypothesis. I could not confirm it in the standard server state. (I using latest version.) It looks like it was caused by a plugin.

**Comment by AppleDevelops** [comment]
No it's a bug I fixed it on Elywing

**Comment by Driesboy** [comment]
confirm

**Comment by Driesboy** [comment]
its a bug!

**Comment by remotevase** [comment]
Oh, my... Then @AppleDevelops can you fix it here? or do you not care about tesseract any more...

**Comment by xZeroMCPE** [comment]
Fixed

**Comment by remotevase** [comment]
Great!

**Comment by remotevase** [comment]
And now, we are back to being the least buggy software with 0 BUGS!

**Comment by Nought57** [comment]
There is no bug in the pocketmine code. Who created the bug? Another question remains. Bugs were not found in the verification of the two. That is very very strange. I'm worried that the cause is not clear.

**Comment by remotevase** [comment]
No, unfortunately it is not clear, you are correct... That's just the way things go when using genisys as the base.

**Comment by Nought57** [comment]
No worries. Fixed Player Arrow.

**Comment by remotevase** [comment]
:+1:
