### ISSUE TITLE
Warning at player.php

### ISSUE THREAD

**Issue by armagadon159753** [TesseractTeam/Tesseract#13]
![screenshot_2017-06-18-23-22-20](https://user-images.githubusercontent.com/25569806/27264379-4605f518-547d-11e7-8343-bcfa0dd47205.png)

**Comment by AppleDevelops** [comment]
Give me some info on what you were doing.

**Comment by AppleDevelops** [comment]
Will fix later.

**Comment by AppleDevelops** [comment]
Wrong button

**Comment by armagadon159753** [comment]
When i try to join m'y island (SkyBlock plugin) ClientCrash and console say this
