### ISSUE TITLE
Rewrite lang files

### ISSUE THREAD

**Issue by AppleDevelops** [TesseractTeam/Tesseract#131]
The lang files we have now are pre-0.16.0 and are buggy. I'll credit a separate branch where I will rewrite some lang files. This will cause issues with some plugins

**Comment by Nought57** [comment]
Code quotes brought many bugs. If there is a fatal bug, the value of many functions will go down. I think this is a serious problem.

**Comment by Nought57** [comment]
Code quotes brought many bugs. If there is a fatal bug, the value of many functions will go down. There are too many bugs and we can not fix it. I think this is a serious problem.

**Comment by Driesboy** [comment]
dutch?

**Comment by remotevase** [comment]
[Added to projects list.](https://github.com/TesseractTeam/Tesseract/projects/1#card-1398221)
