### ISSUE TITLE
Level bug

### ISSUE THREAD

**Issue by daniktheboss** [TesseractTeam/Tesseract#133]
#### Problem description
[Tesseract] [11:21:21] CRITICAL> Could not tick level "world": Class pocketmine\level\FullChunkDataPacket not found

#### Steps to reproduce the issue
Join the server

#### OS and versions
* Tesseract:  0.0Dev
* PHP: 7
* Server OS: windows
* Game version: 1.0.0
* Server host: windows 
#### Crashdump, backtrace, memory dumps, plugins list or other files
[Tesseract] [11:21:21] CRITICAL> Could not tick level "world": Class pocketmine\level\FullChunkDataPacket not found

**Comment by daniktheboss** [comment]
Also pre made maps dont work

**Comment by remotevase** [comment]
World format?

**Comment by daniktheboss** [comment]
i deleted all maps. It was generated with tesseract

**Comment by remotevase** [comment]
Hmm...

**Comment by AppleDevelops** [comment]
Test in latest commit
