### ISSUE TITLE
Command not found!

### ISSUE THREAD

**Issue by ISRAPIL** [TesseractTeam/Tesseract#136]
# Please help!!!

Do сommands, some of them work and others do not ... Writes "command not found". In plugin.yml he added 2 commands, and operates only 1(xyz). Cases in PlaerChatEvent and, PlayerCommandPreproccesEvent - anyway!

**code:**
```
	public function onCommand(CommandSender $sender, Command $cmd, $label, array $args){
		if($command->getName() == "xyz"){
			$x = $sender->getX();
			$y = $sender->getY();
			$z = $sender->getZ();
			$sender->sendMessage("X: $x \nY: $y \nZ: $z");
		}
		if($command->getName() == "wtp"){
		$level = $this->getServer()->getLevelByName($args[0]);
			$sender->teleport(new Position($level->getSafeSpawn()->getX(), $level->getSafeSpawn()->getY(), $level->getSafeSpawn()->getZ(), $level));
		}
	}
```

**Comment by ISRAPIL** [comment]
Ohh, my bad English...

**Comment by kek228** [comment]
I am doing сommands, some of them are working and others not ... Server writes me "command not found". In plugin.yml I added 2 commands, and operates only 1(xyz). I use switch in PlayerChatEvent and PlayerCommandPreproccesEvent - but it doesn't work anyway!

(I think it's more good english)

**Comment by kek228** [comment]
so, as i understood, his commands doesn't work

**Comment by Driesboy** [comment]
yeah but its a bug with alot plugins!

**Comment by remotevase** [comment]
Check the spelling of the classes and make sure that it is not generating an error.

**Comment by ISRAPIL** [comment]
Самое странное, что команда работает если поставить "." перед знаком "/"


@remotevase 
@Driesboy

**Comment by Nought57** [comment]
@ISRAPIL This bug caused by plugin. plugin call to undefined function "$command". Please rewrite plugin code. Fix public function onCommand "Command $cmd -> Command $command".

**Comment by ISRAPIL** [comment]
@Nought57 
That I'm just trying to replace at PlayerCommandPreprocessEvent ...

**Comment by ISRAPIL** [comment]
@Nought57 You hurried to the closure of the issue.

**Comment by Nought57** [comment]
@ISRAPIL I did not notice that I wanted to use PlayerCommandPreproccesEvent by looking at the code.
#142 but, I will help if you are in trouble.
