### ISSUE TITLE
Crashdump

### ISSUE THREAD

**Issue by Iktaniyalol** [TesseractTeam/Tesseract#137]
Tesseract Crash Dump Fri Jan 20 02:31:23 MSK 2017

Error: Call to a member function sendContents() on null
File: /src/pocketmine/Player
Line: 1071
Type: notice

Code:
[1062] 		if($this->getHealth() <= 0){
[1063] 			$pk = new RespawnPacket();
[1064] 			$pos = $this->getSpawn();
[1065] 			$pk->x = $pos->x;
[1066] 			$pk->y = $pos->y;
[1067] 			$pk->z = $pos->z;
[1068] 			$this->dataPacket($pk);
[1069] 		}
[1070] 
[1071] 		$this->inventory->sendContents($this);
[1072] 		$this->inventory->sendArmorContents($this);
[1073] 	}
[1074] 
[1075] 	protected function orderChunks(){
[1076] 		if($this->connected === false){
[1077] 			return false;
[1078] 		}
[1079] 
[1080] 		Timings::$playerChunkOrderTimer->startTiming();
[1081] 

Backtrace:
#0 /src/pocketmine/Player(1909): pocketmine\Player->sendNextChunk(boolean)
#1 /src/pocketmine/Server(2738): pocketmine\Player->checkNetwork(boolean)
#2 /src/pocketmine/Server(2428): pocketmine\Server->tick(boolean)
#3 /src/pocketmine/Server(2307): pocketmine\Server->tickProcessor(boolean)
#4 /src/pocketmine/Server(1856): pocketmine\Server->start(boolean)
#5 /src/pocketmine/PocketMine(469): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string /home/sftpmine/mine/ram1024/, string /home/sftpmine/mine/ram1024/, string /home/sftpmine/mine/ram1024/plugins/, string unknown)

Tesseract version: 0000000000000000000000000000000000000000 [Protocol 100; API 3.0.0]
PHP version: 7.0.9
Zend version: 3.0.0
OS : Linux, linux

Server uptime: 4 hours 43 minutes 21 seconds
Number of loaded worlds: 6
Players online: 0/100
* Tesseract: 1.0.0dev Crystal protocol version 100 API 3.0.0
* PHP: 7.0.9
* Server OS: Linux
* Game version: 1.0.0.16
* Server host: Linux CentOS 6.8 x86_64

**Comment by ankitmaharjan252** [comment]
Any plugins?

**Comment by Iktaniyalol** [comment]
Loaded plugins:
EconomyPShop 2.0.2 by onebone for API(s) 3.0.0, 2.0.0, 2.1.0
Jail Alpha0.3.0.1 by hoyinm14mc for API(s) 2.0.0, 3.0.0-ALPHA1
MagicWE 0.2.7 by thebigsmileXD for API(s) 1.13.0, 2.0.0
CreativeItemsPlus 1.0.1 by MCPEPIG for API(s) 2.0.0
MotdMCPE 1 by LDX for API(s) 1.12.0
aPassport 1 by AlexBrin for API(s) 2.0.0
GroupSetting 1 by Cheloveck for API(s) 2.0.0
SAutoMine Alpha_0.1 by Sergey_Dertan for API(s) 1.8.0
Super_Block_By_Dakadegenerat1 2.2.8 by Dakadegenerat1 for API(s) 1.12.0
BanMsg max by FixPlug for API(s) 2.0.0, 3.0.0
AddEf 4 by FixPlug for API(s) 2.0.0
Sigara 2 by FixPlug for API(s) 2.0.0
Coffe 2 by FixPlug for API(s) 2.0.0
Lottery beta by israpil for API(s) 1.1.0
WorldGuardian 1.6.1 by mamayadesu for API(s) 1.12.0, 2.0.0
vLoD 1 by vVAlnextVv for API(s) 1.13.0, 2.0.0, 2.1.0
SVape 1.0.1 by Святослав Дубровский for API(s) 1.13.0
SlapperRotation 1.0.1 by jojoe77777 for API(s) 2.0.0
SlapperCache 1.0.0 by jojoe77777 for API(s) 2.0.0
SAptek 1.0.1 by Святослав Дубровский for API(s) 1.13.0
PvpBooster 1.0.0 by DarkYusuf13 for API(s) 2.0.0
Parkour 1.1.0 by jdcraft for API(s) 2.0.0, 2.1.0
NoDrops 1.1 by SavionLegendZzz, thebigsmileXD for API(s) 1.12.0
FWarps 0.0.1 by  for API(s) 1.0.0
FlagSpiral 2.1.1-Beta INFOMCPE.RU EDITION by xBeastMode for API(s) 2.0.0
MultiProtection 1 by FaigerSYS for API(s) 2.0.0, 3.0.0
AntiVPN 2 by gistrec for API(s) 2.0.0
EnderCrystal 1 by frago9876543210 for API(s) 1.0.0, 2.0.0, 3.0.0, 3.0.0-ALPHA1
Slapper 1.3.2 by jojoe77777 for API(s) 3.0.0-ALPHA1
HereAuth 1.0-Dev#229 by PEMapModder for API(s) 2.0.0
Tir 0.1 by AutoRacing for API(s) 1.12.0
LuckyCases 1 by MaxFreeze for API(s) 2.0.0
BubbleGum 1 by MaxFreeze for API(s) 2.0.0
BlockMoney 1 by CykaBlyad for API(s) 2.0.0
msHELP 1 by MakStashkevich for API(s) 1.13.1, 2.0.0
NetherChests 1.0.0 by aliuly for API(s) 1.12.0
AlwaysSpawn 2.2.2 by Philip Shilling for API(s) 1.12.0
eSize 1 by devFelix for API(s) 2.0.0
ItemCasePE 1.0.8 by aliuly for API(s) 2.0.0, 2.1.0
SW_svile 0.6dev by svile for API(s) 2.0.0
EssentialsPE 2.0.0 by LegendsOfMCPE Team for API(s) 2.1.0, 2.0.0
ToolsPE 1 by paetti for API(s) 1.0.0
ColorMatch 1.1.2 by CreeperFace for API(s) 1.12.0
ManyWorlds 2.1.0 by aliuly for API(s) 2.0.0
BlockID Final by MCYasha for API(s) 1.12.0
ClearLagg 0.0.1 by LDX for API(s) 1.8.0
InvSee 0.0.1 by tschrock (tschrock123@gmail.com) for API(s) 1.0.0
aHotbar 1.2 by AlexBrin for API(s) 1.10.0
PurePerms 1.4.0-INDEV by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0
TapToDo 2.2.1 by Falk for API(s) 1.0.0
SpleefPE 1.0.0 by thebigsmileXD for API(s) 1.0.0
NoHungerInWorld 0.2 by Kelvinlolz for API(s) 2.0.0
KillMoney 0.1 by Hamooz0001 for API(s) 2.0.0
IPLogger 1.3 by PEMapModder for API(s) 1.0.0
GMOneCommand 1 by MCYasha for API(s) 1.12.0
FZ_FlyPen 1.0.0 by ForZz for API(s) 2.0.0
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
CTF_DODO 1.1.0 by KaitoDoDo for API(s) 1.0.0, 1.1.0, 2.0.0
coords 1.0.1 by kenygamer for API(s) 1.0.0
CommandTracker 1.1 by Scott Handley for API(s) 1.10.0
BlockCmdPE 1.0.1 by Vaivez66 for API(s) 1.12.0, 2.0.0
BanItem 2.2 by LDX for API(s) 1.0.0, 2.0.0
aTopPlayers 1 by AlexBrin for API(s) 2.0.0
AntiCheat 2.5.1 by DarkWav (Developer), Pav155 (Config Designer) for API(s) 5.0.0, 4.0.0, 3.0.0, 2.0.0, 1.0.0
AdvancedKits 4.0.1 by luca28pet for API(s) 1.12.0
1vs1 0.0.5 by  for API(s) 1.0.0, 1.1.0
RealTime 2.1.1 by Guillaume351 for API(s) 1.0.0
Свадьбы 1 by Bisector for API(s) 1.10.0
undrCommandTracker 1 by  for API(s) 2.0.0
WearArmorFast 1.0.0 by khavmc for API(s) 2.0.0
FAntiDamage 0.2 by Fermix for API(s) 2.0.0
EconomySell 2.0.7 by onebone for API(s) 3.0.0, 2.0.0, 2.1.0
EconomyAuction 2.0.2 by onebone for API(s) 3.0.0, 2.0.0, 2.1.0
EconomyShop 2.0.7 by onebone for API(s) 3.0.0, 2.0.0, 2.1.0
PureChat 1.4.0 by 64FF00 for API(s) 1.13.0, 2.0.0
MyPlot 1 by Wies and Exxarion for API(s) 1.0.0,2.0.0Loaded plugins:
EconomyPShop 2.0.2 by onebone for API(s) 3.0.0, 2.0.0, 2.1.0
Jail Alpha0.3.0.1 by hoyinm14mc for API(s) 2.0.0, 3.0.0-ALPHA1
MagicWE 0.2.7 by thebigsmileXD for API(s) 1.13.0, 2.0.0
CreativeItemsPlus 1.0.1 by MCPEPIG for API(s) 2.0.0
MotdMCPE 1 by LDX for API(s) 1.12.0
aPassport 1 by AlexBrin for API(s) 2.0.0
GroupSetting 1 by Cheloveck for API(s) 2.0.0
SAutoMine Alpha_0.1 by Sergey_Dertan for API(s) 1.8.0
Super_Block_By_Dakadegenerat1 2.2.8 by Dakadegenerat1 for API(s) 1.12.0
BanMsg max by FixPlug for API(s) 2.0.0, 3.0.0
AddEf 4 by FixPlug for API(s) 2.0.0
Sigara 2 by FixPlug for API(s) 2.0.0
Coffe 2 by FixPlug for API(s) 2.0.0
Lottery beta by israpil for API(s) 1.1.0
WorldGuardian 1.6.1 by mamayadesu for API(s) 1.12.0, 2.0.0
vLoD 1 by vVAlnextVv for API(s) 1.13.0, 2.0.0, 2.1.0
SVape 1.0.1 by Святослав Дубровский for API(s) 1.13.0
SlapperRotation 1.0.1 by jojoe77777 for API(s) 2.0.0
SlapperCache 1.0.0 by jojoe77777 for API(s) 2.0.0
SAptek 1.0.1 by Святослав Дубровский for API(s) 1.13.0
PvpBooster 1.0.0 by DarkYusuf13 for API(s) 2.0.0
Parkour 1.1.0 by jdcraft for API(s) 2.0.0, 2.1.0
NoDrops 1.1 by SavionLegendZzz, thebigsmileXD for API(s) 1.12.0
FWarps 0.0.1 by  for API(s) 1.0.0
FlagSpiral 2.1.1-Beta INFOMCPE.RU EDITION by xBeastMode for API(s) 2.0.0
MultiProtection 1 by FaigerSYS for API(s) 2.0.0, 3.0.0
AntiVPN 2 by gistrec for API(s) 2.0.0
EnderCrystal 1 by frago9876543210 for API(s) 1.0.0, 2.0.0, 3.0.0, 3.0.0-ALPHA1
Slapper 1.3.2 by jojoe77777 for API(s) 3.0.0-ALPHA1
HereAuth 1.0-Dev#229 by PEMapModder for API(s) 2.0.0
Tir 0.1 by AutoRacing for API(s) 1.12.0
LuckyCases 1 by MaxFreeze for API(s) 2.0.0
BubbleGum 1 by MaxFreeze for API(s) 2.0.0
BlockMoney 1 by CykaBlyad for API(s) 2.0.0
msHELP 1 by MakStashkevich for API(s) 1.13.1, 2.0.0
NetherChests 1.0.0 by aliuly for API(s) 1.12.0
AlwaysSpawn 2.2.2 by Philip Shilling for API(s) 1.12.0
eSize 1 by devFelix for API(s) 2.0.0
ItemCasePE 1.0.8 by aliuly for API(s) 2.0.0, 2.1.0
SW_svile 0.6dev by svile for API(s) 2.0.0
EssentialsPE 2.0.0 by LegendsOfMCPE Team for API(s) 2.1.0, 2.0.0
ToolsPE 1 by paetti for API(s) 1.0.0
ColorMatch 1.1.2 by CreeperFace for API(s) 1.12.0
ManyWorlds 2.1.0 by aliuly for API(s) 2.0.0
BlockID Final by MCYasha for API(s) 1.12.0
ClearLagg 0.0.1 by LDX for API(s) 1.8.0
InvSee 0.0.1 by tschrock (tschrock123@gmail.com) for API(s) 1.0.0
aHotbar 1.2 by AlexBrin for API(s) 1.10.0
PurePerms 1.4.0-INDEV by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0
TapToDo 2.2.1 by Falk for API(s) 1.0.0
SpleefPE 1.0.0 by thebigsmileXD for API(s) 1.0.0
NoHungerInWorld 0.2 by Kelvinlolz for API(s) 2.0.0
KillMoney 0.1 by Hamooz0001 for API(s) 2.0.0
IPLogger 1.3 by PEMapModder for API(s) 1.0.0
GMOneCommand 1 by MCYasha for API(s) 1.12.0
FZ_FlyPen 1.0.0 by ForZz for API(s) 2.0.0
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
CTF_DODO 1.1.0 by KaitoDoDo for API(s) 1.0.0, 1.1.0, 2.0.0
coords 1.0.1 by kenygamer for API(s) 1.0.0
CommandTracker 1.1 by Scott Handley for API(s) 1.10.0
BlockCmdPE 1.0.1 by Vaivez66 for API(s) 1.12.0, 2.0.0
BanItem 2.2 by LDX for API(s) 1.0.0, 2.0.0
aTopPlayers 1 by AlexBrin for API(s) 2.0.0
AntiCheat 2.5.1 by DarkWav (Developer), Pav155 (Config Designer) for API(s) 5.0.0, 4.0.0, 3.0.0, 2.0.0, 1.0.0
AdvancedKits 4.0.1 by luca28pet for API(s) 1.12.0
1vs1 0.0.5 by  for API(s) 1.0.0, 1.1.0
RealTime 2.1.1 by Guillaume351 for API(s) 1.0.0
Свадьбы 1 by Bisector for API(s) 1.10.0
undrCommandTracker 1 by  for API(s) 2.0.0
WearArmorFast 1.0.0 by khavmc for API(s) 2.0.0
FAntiDamage 0.2 by Fermix for API(s) 2.0.0
EconomySell 2.0.7 by onebone for API(s) 3.0.0, 2.0.0, 2.1.0
EconomyAuction 2.0.2 by onebone for API(s) 3.0.0, 2.0.0, 2.1.0
EconomyShop 2.0.7 by onebone for API(s) 3.0.0, 2.0.0, 2.1.0
PureChat 1.4.0 by 64FF00 for API(s) 1.13.0, 2.0.0
MyPlot 1 by Wies and Exxarion for API(s) 1.0.0,2.0.0

**Comment by ankitmaharjan252** [comment]
When did you got the error? Like startup, command?

**Comment by Iktaniyalol** [comment]
crash occurs by itself. Even when empty server, and the server has been running for a few hours - crash occurs

**Comment by ankitmaharjan252** [comment]
I think the error is occuring from a plugin! Try removing all plugin and try running your server!

**Comment by Iktaniyalol** [comment]
i try it.

**Comment by ankitmaharjan252** [comment]
You already tried?

**Comment by Iktaniyalol** [comment]
No. I will try it.(I dont speak English)

**Comment by ankitmaharjan252** [comment]
Oh okay.

**Comment by TDMidkwhatisxd** [comment]
Sedcontents() crash is wen u use this
OnJoinPlayerEvent
Kick()

Use on prelogin

**Comment by ankitmaharjan252** [comment]
Thats probably a plugin error!

**Comment by remotevase** [comment]
Most likely

**Comment by xZeroMCPE** [comment]
I think it has to do with trying to send a specific content to a player which seems to be offline.

It does't seem to be the server software, but instead, its the plugin.

**Comment by Nought57** [comment]
I could not confirm the phenomenon. Possible causes are plugins.

**Comment by remotevase** [comment]
@Nought57 this is 98% definitely a plugin error
