### ISSUE TITLE
[REQUEST] I want an event.

### ISSUE THREAD

**Issue by fuyutsuki** [TesseractTeam/Tesseract#138]
#### Problem description

I want an event when I picked an item from the chest inventory.

I want to make a plugin using it...

**Comment by ISRAPIL** [comment]
_**[InventoryTransactionEvent](https://github.com/TesseractTeam/Tesseract/blob/master/src/pocketmine/event/inventory/InventoryTransactionEvent.php)**_

**Comment by fuyutsuki** [comment]
Oh, ok thanks!! and I`m sorry.

**Comment by Nought57** [comment]
@fuyutsuki When using InventoryTransactionEvent, you need to check the picked an item from the chest inventory. TransactionQueue helps to write this code.

**Comment by fuyutsuki** [comment]
solved! thanks!
