### ISSUE TITLE
Entity Error

### ISSUE THREAD

**Issue by TheAppleGamer** [TesseractTeam/Tesseract#14]
#### Steps to reproduce the issue

I have no idea how I got this
#### OS and versions

* Tesseract: 4bc2fb1
* PHP: 7.0.12
* Server OS: Windows 10
* Game version: 0.16.1

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
Warning: Illegal offset type in isset or empty in Entity.php on line 483

```

**Comment by IISweePII** [comment]
I was looking at the code, most likely its the isset($this->effects[$effectId]); on that line you mentioned, since that is a thing used for arguments (args)
