### ISSUE TITLE
Chto za huyna?

### ISSUE THREAD

**Issue by AuroRacing** [TesseractTeam/Tesseract#141]
Huli pered commandami nada pisat .? Vi shto ohueli? Pizdi davno ne poluchli? A nu bistro fixed! ./command => /command

**Comment by kek228** [comment]
buyniy slavik odobryaet

**Comment by ankitmaharjan252** [comment]
Please talk in english cause there are many people that do not understand that language!

**Comment by ISRAPIL** [comment]
@ankitmaharjan252 Pashol nahuy))) Sorry

**Comment by remotevase** [comment]
This issue will be reopened when we can understand you.
