### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by ISRAPIL** [TesseractTeam/Tesseract#142]
# Please help!!!

Do сommands, some of them work and others do not ... Writes "command not found". In plugin.yml he added 2 commands, and operates only 1(xyz). Cases in PlaerChatEvent and, PlayerCommandPreproccesEvent - anyway!

in the console everything is fine, but in the game, should be put "." before "/"... 
It is not in the code

**code:**
```
	public function onCommand(CommandSender $sender, Command $command, $label, array $args){
		if($command->getName() == "xyz"){
			$x = $sender->getX();
			$y = $sender->getY();
			$z = $sender->getZ();
			$sender->sendMessage("X: $x \nY: $y \nZ: $z");
		}
		if($command->getName() == "wtp"){
		$level = $this->getServer()->getLevelByName($args[0]);
			$sender->teleport(new Position($level->getSafeSpawn()->getX(), $level->getSafeSpawn()->getY(), $level->getSafeSpawn()->getZ(), $level));
		}
	}
```

**Comment by AuroRacing** [comment]
Pashol von, eto my territory!

**Comment by TDMidkwhatisxd** [comment]
Genisys fixed this, u should copy/paste

**Comment by remotevase** [comment]
@TDMidkwhatisxd what commit is it?

**Comment by ISRAPIL** [comment]
@TDMidkwhatisxd

**Comment by TDMidkwhatisxd** [comment]
I worked all day on my server, i really dont have time 😃 ! 
I reseted server and needed to do some changes: on myplot to can generate plots... Etc!
If u dont find until tomorow i send link 😀

Now i need to fix more stuff 😱

**Comment by Nought57** [comment]
@ISRAPIL This code is not written to use PlayerCommandPreproccesEvent and PlaerChatEvent. This is an example using PlayerCommandPreproccesEvent. but, Because it is a simple code, there is a possibility that an error will be given depending on usage.
**code:**
```
function playerCommand(PlayerCommandPreprocessEvent $event){
        $player = $event->getPlayer();
        $name = $player->getName();
        $message= $event->getMessage();
        if($message[0] === "/"){
                $command = explode(" ", substr($message, 1));
                if(isset($command[1])){
                        switch ($command){
                                case "xyz":
                                        $player->sendMessage("X: ".$player->getX()." \nY: ".$player->getY()." \nZ: ".$player->getZ()."");
                                break;
                                case "wtp":
                                        $subcommand = explode(" ", substr($command, 4));
                                        $level = $this->getServer()->getLevelByName($args[0]);
                                        $sender->teleport(new Position($level->getSafeSpawn()->getX(), $level->getSafeSpawn()->getY(), $level->getSafeSpawn()->getZ(), $level));
                                break;
                         }
                }   
        }
 }
```

**Comment by ISRAPIL** [comment]
@Nought57 I even tried to, anyway.

**Comment by ISRAPIL** [comment]
@Nought57 
![image](https://cloud.githubusercontent.com/assets/23585651/22174376/45a40b18-dfee-11e6-8ed0-6b72c6760b5e.png)
![image](https://cloud.githubusercontent.com/assets/23585651/22174378/4ce9345c-dfee-11e6-914c-617853343bd0.png)

![image](https://cloud.githubusercontent.com/assets/23585651/22174384/62671bfa-dfee-11e6-88ce-4e5cdd129054.png)

**Comment by Nought57** [comment]
@ISRAPIL It is necessary to register the command separately. Such usage is not PlayerCommandPreproccesEvent. As an example of the PlayerCommandPreproccesEvent, Check status and Disable command etc. Usually use public function onCommand(CommandSender $sender, Command $command, $label, array $args).

**Comment by Nought57** [comment]
This is plugin Issues. Please use public function onCommand(CommandSender $sender, Command $command, $label, array $args).

**Comment by Nought57** [comment]
This is plugin Issues. Please use public function onCommand(CommandSender $sender, Command $command, $label, array $args).

**Comment by Nought57** [comment]
Why, use PlayerCommandPreproccesEvent.

**Comment by Nought57** [comment]
Why, use PlayerCommandPreproccesEvent.

**Comment by ISRAPIL** [comment]
@Nought57 
I'm in the moment of creation of screenshots I used onCommand to show you that the command working on the console, and the player does not! What would they have worked in the game, you have to put the "." before "/".
./wtp it works, but simply /wtp no!

**Comment by AuroRacing** [comment]
@Nought57

Are you ahuel tam?

**Comment by Nought57** [comment]
@ISRAPIL "simply command not working problem" can see even the another plugin?

**Comment by Nought57** [comment]
@AuroRacing Sry, What is ahuel tam?

**Comment by ISRAPIL** [comment]
@Nought57 
Another command /sw  as well, and this is another plugin that others work, and if I only put . to the /

**Comment by ISRAPIL** [comment]
@Nought57 
ahuel tam - it's a bad words ...

**Comment by Nought57** [comment]
@AuroRacing I'm incompetent person from your perspective. but, Just a word can do harm to a person.

**Comment by Nought57** [comment]
@ISRAPIL  I'm sorry, I can't do anything for you. my server (latest version) successfully working...

**Comment by Nought57** [comment]
#141 win10 Edition client bug. command does not working.

**Comment by remotevase** [comment]
@TDMidkwhatisxd yes, please send link whenvever u can

**Comment by Driesboy** [comment]
same bug on this plugin 

https://github.com/NL-4-DEVS/Pets

**Comment by NemanjaMAX** [comment]
Close this, all seenms fine.

**Comment by ISRAPIL** [comment]
What should I do? :-(

**Comment by ISRAPIL** [comment]
@Nought57 On android exact same error...

**Comment by TDMidkwhatisxd** [comment]
https://github.com/iTXTech/Genisys/commit/2e13c6d4645f5cffbcece4bccc55418d10d0320d

**Comment by TDMidkwhatisxd** [comment]
https://github.com/iTXTech/Genisys/commit/4a7844f3ec2fe73b2b47db3705462a7a1e442338

**Comment by TDMidkwhatisxd** [comment]
Both of them fix commands! Last one is were dktapps forgot to dellete one more stuff! xD

**Comment by Nought57** [comment]
@ISRAPIL I did a test with the latest version but could not confirm it.

**Comment by Nought57** [comment]
@TDMidkwhatisxd That part has been fixed in the past.

**Comment by remotevase** [comment]
Thanks anyways, I can no longer replicate this issue.

**Comment by remotevase** [comment]
@AppleDevelops we only open confirmed issues. Neither myself nor @Nought57 could confirm this, therefore we can close it.

**Comment by AppleDevelops** [comment]
@remotevase Last time I checked I founded this repo.

**Comment by Nought57** [comment]
@remotevase At least I could not confirm. but, It exists as an unknown bug.

**Comment by ISRAPIL** [comment]
This bug does not appear at all, my friend it's OK
@Nought57  @remotevase   @Driesboy

**Comment by ISRAPIL** [comment]
# ______________PROBLEM SOLVED______________
**_The problem was in the synapse, but I decided it!_**

```
		$player->sendCommandData();
		$player->recalculatePermissions();
```
