### ISSUE TITLE
item frames dupe glitch -_-

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [TesseractTeam/Tesseract#143]
If u try to break a itemframe on a protected land , and it have a item in it, it will drop that item!
But the big problem is, even if that item drop, it still exist in item frame :0 , so there is a dupe glitch!

**Comment by TDMidkwhatisxd** [comment]
Copy tile from elywing!

**Comment by Enrick3344** [comment]
That's a Plugin problem I think.

**Comment by TDMidkwhatisxd** [comment]
How can iprotect glich frames?
Anyway, i used a old frame tile to make it stop working! Now u cant put anything in it!

**Comment by Enrick3344** [comment]
Iprotect may cause that issue. try removing it. I dont think the plugin is updated to API3

**Comment by TDMidkwhatisxd** [comment]
Dude are u crazy? Pff! This glich is in all Teseract servers! 
How the heck , event is canceled and blocks drop + the block from frames are not removed!
If you dont know im talking about stfu!

I see that devs ignore this issue, imma close to help them make the Server bug free so they can brag about it!

**Comment by Nought57** [comment]
You need to provide the information needed to developer.

**Comment by Nought57** [comment]
You need to provide the information needed to developer.

**Comment by Nought57** [comment]
Please use template.

**Comment by Nought57** [comment]
Please use template.

**Comment by remotevase** [comment]
We should find a way to fix this, but how...

**Comment by remotevase** [comment]
Other than reverse engineering the client code, of course, because that usually results in even more bugs XP

**Comment by TDMidkwhatisxd** [comment]
Just remove item frames function! It is not needed anyway!
//Until you find a fix//

**Comment by remotevase** [comment]
Somebdy?

**Comment by AppleDevelops** [comment]
Wait a seconds, you can cancel the function of item frames

**Comment by AppleDevelops** [comment]
Please test with latest commit

**Comment by AppleDevelops** [comment]
@TDMidkwhatisxd Still able to be reproduced?

**Comment by TDMidkwhatisxd** [comment]
I only saw players reproducing the glitch, they just dont wanna to tell me the steps! 
I was trying for a long time with teseract older versions to reproduce but no use!

So i will remove frames from my servers! 
From what i saw on youtube, even realms have problems with frames! 

So i will close the issue, becouse is just pointless if i cant reproduce :(
