### ISSUE TITLE
Ender Chest?

### ISSUE THREAD

**Issue by Enrick3344** [TesseractTeam/Tesseract#145]
#### Problem description

 So I don't know if it's because it's not done yet, but I tried the new commit and The Ender Chest is not there and i tried giving it to me and still can't place it.

#### OS and versions

* Tesseract: f9c5c39
* PHP: 7.0.14
* Server OS: 
* Game version: 1.0.1
* Server host: VPS
<br><br>

**Comment by AppleDevelops** [comment]
They haven't been registered

**Comment by Nought57** [comment]
Sry, I haven't added EnderChest yet. I'm creating a new Inventory.

**Comment by remotevase** [comment]
It is not an issue is just enhancement, and it is already added to the projects tab, @Appledevelops. Therefore, this can be closed.
