### ISSUE TITLE
The snowball hangs in the air, and ender pearl

### ISSUE THREAD

**Issue by EmreTr1** [TesseractTeam/Tesseract#148]
![screenshot_2017-01-23-20-35-16](https://cloud.githubusercontent.com/assets/13833030/22220752/a00db448-e1b8-11e6-9a1e-0b8e0e3d2883.png)

**Comment by EpicSteve33** [comment]
I do not have this issue, maybe try to provide more information about what your hosting the server on because it could be lag caused by whatever your hosting on

**Comment by AppleDevelops** [comment]
You've failed to provide any information on this issue. I will reopen it when there is more info.

**Comment by IISweePII** [comment]
I will test this and see if this issue is there

**Comment by remotevase** [comment]
Its not

**Comment by EpicSteve33** [comment]
I'm pretty sure they are trying to host the server on something like a phone or an old pc because I have never experienced anything like that

**Comment by remotevase** [comment]
Neither have I.
