### ISSUE TITLE
Implementing anticheat like pmmp

### ISSUE THREAD

**Issue by Driesboy** [TesseractTeam/Tesseract#152]
#### Problem description

https://github.com/pmmp/PocketMine-MP/tree/api3/anti-cheat-api

#### Steps to reproduce the issue

/
#### OS and versions

* Tesseract: /
* PHP:/
* Server OS:/
* Game version: /
* Server host:/
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Nought57** [comment]
The Anti-Cheat (Anti-Fly) function was deleted in exchange for the implementation of Elytra. but, There is also a way not to delete Anti-Cheat (Anti-Fly) even if Elytra is implemented. There seems to be a bug and other reasons. From this, it is considered that there is no plan to re-implement. Please implement with plugin.

**Comment by Nought57** [comment]
I added it to the project list.

**Comment by Nought57** [comment]
I added it to the project list.
