### ISSUE TITLE
SpawnExperienceOrbPacket

### ISSUE THREAD

**Issue by AppleDevelops** [TesseractTeam/Tesseract#154]
Still 13 bytes unread in pocketmine\network\protocol\SpawnExperienceOrbPacket failed in phar:///custom-phar-php-7.0.3.phar/src/pocketmine/network/Network.php on line 237

It tends to fail a lot and it is top priority now.

**Comment by remotevase** [comment]
Hmm, before this, I didn't even know what this packet existed!

**Comment by remotevase** [comment]
@TesseractTeam/software Someone

**Comment by remotevase** [comment]
Not top priority because we have the other issue that actually crashes the server as opposed to simply failing. #153 is incredibly important. Work on that first @Appl
