### ISSUE TITLE
Nether...

### ISSUE THREAD

**Issue by NemanjaMAX** [TesseractTeam/Tesseract#155]
#### Problem description
If level "nether" created,its spam something on console,and u cannot go in nether :D Idk are its fixed,cuz I tryied it last 2/commits ago @remotevase 
#### OS and versions

* Tesseract: Latest
* PHP: 7
* Server OS: Server OS?
* Game version: 1.0.0
* Server host: Local Host 2gb ram
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by remotevase** [comment]
I'm not sure about this... Definitely has something to do with chunks, @AppleDevelops?

**Comment by NemanjaMAX** [comment]
[Tesseract] [23:23:02] INFO> PocketMineMaster[/192.168.0.10:54350] [ClientID: 3.2764859161627E+16] logged in with entity id 1 at (Hub, 167.4639, 68.1234, 174.6036)
[Tesseract] [23:23:04] INFO> [23:23:04] PocketMineMaster joined the game.
[Tesseract] [23:24:26] NOTICE> Level "nether" not found
[Tesseract] [23:24:26] NOTICE> Level "nether" not found
[Tesseract] [23:24:28] NOTICE> Level "nether" not found
[Tesseract] [23:24:28] NOTICE> Level "nether" not found
[Tesseract] [23:24:28] NOTICE> Level "nether" not found
[Tesseract] [23:24:28] NOTICE> Level "nether" not found
[Tesseract] [23:24:28] NOTICE> Level "nether" not found
[Tesseract] [23:24:28] NOTICE> Level "nether" not found
[Tesseract] [23:24:28] NOTICE> Level "nether" not found
[Tesseract] [23:24:28] NOTICE> Level "nether" not found
[Tesseract] [23:24:28] NOTICE> Level "nether" not found
[Tesseract] [23:24:28] NOTICE> Level "nether" not found
[Tesseract] [23:24:28] NOTICE> Level "nether" not found
[Tesseract] [23:24:28] NOTICE> Level "nether" not found
[Tesseract] [23:24:28] NOTICE> Level "nether" not found
[Tesseract] [23:24:28] NOTICE> Level "nether" not found
[Tesseract] [23:24:28] NOTICE> Level "nether" not found
[Tesseract] [23:24:28] NOTICE> Level "nether" not found
[Tesseract] [23:24:28] NOTICE> Level "nether" not found
[Tesseract] [23:24:28] NOTICE> Level "nether" not found
[Tesseract] [23:24:28] NOTICE> Level "nether" not found
[Tesseract] [23:24:28] NOTICE> Level "nether" not found
[Tesseract] [23:24:28] NOTICE> Level "nether" not found
[Tesseract] [23:24:28] NOTICE> Level "nether" not found
[Tesseract] [23:24:28] NOTICE> Level "nether" not found
[Tesseract] [23:24:28] NOTICE> Level "nether" not found
[Tesseract] [23:24:29] NOTICE> Level "nether" not found
[Tesseract] [23:24:29] NOTICE> Level "nether" not found
[Tesseract] [23:24:29] NOTICE> Level "nether" not found
[Tesseract] [23:24:29] NOTICE> Level "nether" not found
[Tesseract] [23:24:29] NOTICE> Level "nether" not found
[Tesseract] [23:24:29] NOTICE> Level "nether" not found
[Tesseract] [23:24:29] NOTICE> Level "nether" not found
[Tesseract] [23:24:29] NOTICE> Level "nether" not found
[Tesseract] [23:24:29] NOTICE> Level "nether" not found
[Tesseract] [23:24:29] NOTICE> Level "nether" not found
[Tesseract] [23:24:29] NOTICE> Level "nether" not found
[Tesseract] [23:24:29] NOTICE> Level "nether" not found
[Tesseract] [23:24:29] NOTICE> Level "nether" not found
[Tesseract] [23:24:29] NOTICE> Level "nether" not found
[Tesseract] [23:24:29] NOTICE> Level "nether" not found
[Tesseract] [23:24:29] NOTICE> Level "nether" not found
[Tesseract] [23:24:29] NOTICE> Level "nether" not found
[Tesseract] [23:24:29] NOTICE> Level "nether" not found
[Tesseract] [23:24:29] NOTICE> Level "nether" not found
[Tesseract] [23:24:30] NOTICE> Level "nether" not found
[Tesseract] [23:24:30] NOTICE> Level "nether" not found
[Tesseract] [23:24:30] NOTICE> Level "nether" not found
[Tesseract] [23:24:30] NOTICE> Level "nether" not found
[Tesseract] [23:24:30] NOTICE> Level "nether" not found
[Tesseract] [23:24:30] NOTICE> Level "nether" not found
[Tesseract] [23:24:30] NOTICE> Level "nether" not found
[Tesseract] [23:24:30] NOTICE> Level "nether" not found
[Tesseract] [23:24:30] NOTICE> Level "nether" not found
[Tesseract] [23:24:30] NOTICE> Level "nether" not found
[Tesseract] [23:24:30] NOTICE> Level "nether" not found
[Tesseract] [23:24:30] NOTICE> Level "nether" not found
[Tesseract] [23:24:30] NOTICE> Level "nether" not found
[Tesseract] [23:24:30] NOTICE> Level "nether" not found
[Tesseract] [23:24:30] NOTICE> Level "nether" not found
[Tesseract] [23:24:30] NOTICE> Level "nether" not found
[Tesseract] [23:24:30] NOTICE> Level "nether" not found
[Tesseract] [23:24:30] NOTICE> Level "nether" not found
[Tesseract] [23:24:30] NOTICE> Level "nether" not found
[Tesseract] [23:24:30] NOTICE> Level "nether" not found
[Tesseract] [23:24:31] NOTICE> Level "nether" not found
[Tesseract] [23:24:31] NOTICE> Level "nether" not found
[Tesseract] [23:24:31] NOTICE> Level "nether" not found
[Tesseract] [23:24:31] NOTICE> Level "nether" not found
[Tesseract] [23:24:31] NOTICE> Level "nether" not found
[Tesseract] [23:24:31] NOTICE> Level "nether" not found
[Tesseract] [23:24:31] NOTICE> Level "nether" not found
[Tesseract] [23:24:31] NOTICE> Level "nether" not found
[Tesseract] [23:24:31] NOTICE> Level "nether" not found
[Tesseract] [23:24:31] NOTICE> Level "nether" not found
[Tesseract] [23:24:31] NOTICE> Level "nether" not found
[Tesseract] [23:24:31] NOTICE> Level "nether" not found
[Tesseract] [23:24:31] NOTICE> Level "nether" not found
[Tesseract] [23:24:31] NOTICE> Level "nether" not found
[Tesseract] [23:24:31] NOTICE> Level "nether" not found
[Tesseract] [23:24:31] NOTICE> Level "nether" not found
[Tesseract] [23:24:31] NOTICE> Level "nether" not found
[Tesseract] [23:24:31] NOTICE> Level "nether" not found
[Tesseract] [23:24:31] NOTICE> Level "nether" not found
[Tesseract] [23:24:31] NOTICE> Level "nether" not found
[Tesseract] [23:24:32] NOTICE> Level "nether" not found
[Tesseract] [23:24:32] NOTICE> Level "nether" not found
[Tesseract] [23:24:32] NOTICE> Level "nether" not found
[Tesseract] [23:24:32] NOTICE> Level "nether" not found
[Tesseract] [23:24:32] NOTICE> Level "nether" not found
[Tesseract] [23:24:32] NOTICE> Level "nether" not found
[Tesseract] [23:24:32] NOTICE> Level "nether" not found
[Tesseract] [23:24:32] NOTICE> Level "nether" not found
[Tesseract] [23:24:32] NOTICE> Level "nether" not found
[Tesseract] [23:24:32] NOTICE> Level "nether" not found
[Tesseract] [23:24:32] NOTICE> Level "nether" not found
[Tesseract] [23:24:32] NOTICE> Level "nether" not found
[Tesseract] [23:24:32] NOTICE> Level "nether" not found
[Tesseract] [23:24:32] NOTICE> Level "nether" not found
[Tesseract] [23:24:32] NOTICE> Level "nether" not found
[Tesseract] [23:24:32] NOTICE> Level "nether" not found
[Tesseract] [23:24:32] NOTICE> Level "nether" not found
[Tesseract] [23:24:32] NOTICE> Level "nether" not found
[Tesseract] [23:24:32] NOTICE> Level "nether" not found
[Tesseract] [23:24:32] NOTICE> Level "nether" not found
[Tesseract] [23:24:32] NOTICE> Level "nether" not found
[Tesseract] [23:24:33] NOTICE> Level "nether" not found
[Tesseract] [23:24:33] NOTICE> Level "nether" not found
[Tesseract] [23:24:33] NOTICE> Level "nether" not found
[Tesseract] [23:24:33] NOTICE> Level "nether" not found
[Tesseract] [23:24:33] NOTICE> Level "nether" not found
[Tesseract] [23:24:33] NOTICE> Level "nether" not found
[Tesseract] [23:24:33] NOTICE> Level "nether" not found
[Tesseract] [23:24:33] NOTICE> Level "nether" not found
[Tesseract] [23:24:33] NOTICE> Level "nether" not found
[Tesseract] [23:24:33] NOTICE> Level "nether" not found
[Tesseract] [23:24:33] NOTICE> Level "nether" not found
[Tesseract] [23:24:33] NOTICE> Level "nether" not found
[Tesseract] [23:24:33] NOTICE> Level "nether" not found
[Tesseract] [23:24:33] NOTICE> Level "nether" not found
[Tesseract] [23:24:33] NOTICE> Level "nether" not found
[Tesseract] [23:24:33] NOTICE> Level "nether" not found
[Tesseract] [23:24:33] NOTICE> Level "nether" not found
[Tesseract] [23:24:33] NOTICE> Level "nether" not found
[Tesseract] [23:24:33] NOTICE> Level "nether" not found
[Tesseract] [23:24:34] NOTICE> Level "nether" not found
[Tesseract] [23:24:34] NOTICE> Level "nether" not found
[Tesseract] [23:24:34] NOTICE> Level "nether" not found
[Tesseract] [23:24:34] NOTICE> Level "nether" not found
[Tesseract] [23:24:34] NOTICE> Level "nether" not found
[Tesseract] [23:24:34] NOTICE> Level "nether" not found
[Tesseract] [23:24:34] NOTICE> Level "nether" not found
[Tesseract] [23:24:34] NOTICE> Level "nether" not found
[Tesseract] [23:24:34] NOTICE> Level "nether" not found
[Tesseract] [23:24:34] NOTICE> Level "nether" not found
[Tesseract] [23:24:34] NOTICE> Level "nether" not found
[Tesseract] [23:24:34] NOTICE> Level "nether" not found
[Tesseract] [23:24:34] NOTICE> Level "nether" not found
[Tesseract] [23:24:34] NOTICE> Level "nether" not found
[Tesseract] [23:24:34] NOTICE> Level "nether" not found
[Tesseract] [23:24:34] NOTICE> Level "nether" not found
[Tesseract] [23:24:34] NOTICE> Level "nether" not found
[Tesseract] [23:24:34] NOTICE> Level "nether" not found
[Tesseract] [23:24:34] NOTICE> Level "nether" not found
[Tesseract] [23:24:34] NOTICE> Level "nether" not found
[Tesseract] [23:24:35] NOTICE> Level "nether" not found
[Tesseract] [23:24:35] NOTICE> Level "nether" not found
[Tesseract] [23:24:35] NOTICE> Level "nether" not found
[Tesseract] [23:24:35] NOTICE> Level "nether" not found
[Tesseract] [23:24:35] NOTICE> Level "nether" not found
[Tesseract] [23:24:35] NOTICE> Level "nether" not found
[Tesseract] [23:24:35] NOTICE> Level "nether" not found
[Tesseract] [23:24:35] NOTICE> Level "nether" not found
[Tesseract] [23:24:35] NOTICE> Level "nether" not found
[Tesseract] [23:24:35] NOTICE> Level "nether" not found
[Tesseract] [23:24:35] NOTICE> Level "nether" not found
[Tesseract] [23:24:35] NOTICE> Level "nether" not found
[Tesseract] [23:24:35] NOTICE> Level "nether" not found
[Tesseract] [23:24:35] NOTICE> Level "nether" not found
[Tesseract] [23:24:35] NOTICE> Level "nether" not found
[Tesseract] [23:24:35] NOTICE> Level "nether" not found
[Tesseract] [23:24:35] NOTICE> Level "nether" not found
[Tesseract] [23:24:35] NOTICE> Level "nether" not found
[Tesseract] [23:24:35] NOTICE> Level "nether" not found
[Tesseract] [23:24:35] NOTICE> Level "nether" not found
[Tesseract] [23:24:36] NOTICE> Level "nether" not found
[Tesseract] [23:24:36] NOTICE> Level "nether" not found
[Tesseract] [23:24:36] NOTICE> Level "nether" not found
Yup,its dont generate it automaticaly,I deleted all (not plugins) and start,all again just turn off weather and this code popup in console

**Comment by remotevase** [comment]
okay, simple hack: copy your main world, and rename it "nether".

**Comment by NemanjaMAX** [comment]
Man,I don't want "hacks" I want real nether,and I belive if I use ither nether,all ppls will,be allowed to put water bucket in nether...

**Comment by NemanjaMAX** [comment]
And its not spam always,only if u stay in portal (ID 90)

**Comment by NemanjaMAX** [comment]
@remotevase Can u give me rank like member to I can add tag to my issue like Bug

**Comment by NemanjaMAX** [comment]
Wow I ask too much ahahah,make label to Confirmed and Bug

**Comment by NemanjaMAX** [comment]
Bro,can u help me with plugin,its show 1 error.idk hiw to fix it...

**Comment by NemanjaMAX** [comment]
File: /src/spl/BaseClassLoader
Line: 131
Type: notice

THIS CRASH WAS CAUSED BY A PLUGIN

Code:
[122] 
[123] 			if(method_exists($name, "onClassLoaded") and (new ReflectionClass($name))->getMethod("onClassLoaded")->isStatic()){
[124] 				$name::onClassLoaded();
[125] 			}
[126] 			
[127] 			$this->classes[] = $name;
[128] 
[129] 			return true;
[130] 		}elseif($this->getParent() === null){
[131] 			throw new ClassNotFoundException("Class $name not found");
[132] 		}
[133] 
[134] 		return false;
[135] 	}
[136] 
[137] 	/**
[138] 	 * Returns the path for the class, if any
[139] 	 *
[140] 	 * @param string $name
[141] 	 *

**Comment by NemanjaMAX** [comment]
Can I get help why its this error,cuz its BaseClassLoader

**Comment by AppleDevelops** [comment]
@remotevase In what way is this a chunk issue? It simple does not load up at start. I can add that back in, I removed it for faster speeds.

**Comment by AppleDevelops** [comment]
Anyways if you were to modify your world and name it nether, it'd look like this.
![minecraft_ windows 10 edition 1_26_2017 8_39_20 pm](https://cloud.githubusercontent.com/assets/17461354/22357645/96bcf01a-e407-11e6-9b88-a56b92f9add3.png)

**Comment by remotevase** [comment]
@AppleDevelops a of stuff related to a world is a chunk issue, so I just automatically assumed it was that lol

**Comment by NemanjaMAX** [comment]
So i'll make genisys server...Make nether than copy it...

**Comment by remotevase** [comment]
IDK if that will work, but try it

**Comment by remotevase** [comment]
@AppleDevelops please add it back in.
