### ISSUE TITLE
Items

### ISSUE THREAD

**Issue by Iktaniyalol** [TesseractTeam/Tesseract#156]
When issued Statement items (/ give example) the subject appears in your inventory when you tap on any block. I have one right?
* Tesseract: 1.0.0dev Crystal protocol version 100 API 3.0.0
* PHP: 7.0.9
* Server OS: Linux
* Game version: 1.0.2.1
* Server host: Linux CentOS 6.8 x86_64:

**Comment by remotevase** [comment]
I will reopen this when you edit the post and make it easier to understand

**Comment by Iktaniyalol** [comment]
But i am not speak English..I dont know how to explain

**Comment by remotevase** [comment]
okay, type in your native language, then I'll translate for you

**Comment by remotevase** [comment]
Please just do it, don't argue XD

**Comment by Iktaniyalol** [comment]
Когда я выдаю себе предмет через команду /give,  то его нету в инвентаре. Чтобы он появился, приходится нажимать на любой блок.

**Comment by Iktaniyalol** [comment]
I can record video..

**Comment by xZeroMCPE** [comment]
Sure do what.

**Comment by Iktaniyalol** [comment]
as I can, write and send

**Comment by xZeroMCPE** [comment]
ok

**Comment by remotevase** [comment]
It says 
> When I give myself a subject through a command / give, then it is not present in the inventory. To make it appear, it is necessary to click on any block.

**Comment by Iktaniyalol** [comment]
Video https://youtu.be/FasWMvp1VXQ

**Comment by remotevase** [comment]
Hmm... This is incredibly strange... Maybe deal with it for now and we'll try fixing?

**Comment by remotevase** [comment]
Its not urgent XD

**Comment by Iktaniyalol** [comment]
if it's a real bug, then waiting fix)

**Comment by AnkitM252** [comment]
Cannot reproduce with tesseract 4c9f1661ad546191e13dae6c07532376c4b6cb7a

**Comment by Iktaniyalol** [comment]
Can i ask you? it is still a god, or is it just me that?

**Comment by remotevase** [comment]
Could not reproduce

**Comment by Iktaniyalol** [comment]
that is, is it just me?
I find it hard to understand English)

**Comment by remotevase** [comment]
does not happen

**Comment by AnkitM252** [comment]
Yes it is just you
