### ISSUE TITLE
TUT | How to make your server start faster

### ISSUE THREAD

**Issue by NemanjaMAX** [TesseractTeam/Tesseract#157]
@remotevase Do not close this,this is helpful,its start 22secconds faster...

Here is the tutorial...
https://youtu.be/hrC9vCv5e9g

**Comment by NemanjaMAX** [comment]
Add Helpful label, please.
Cuz this is special php, on my last php tesseract with same plugins start in 29~32secconds
Now in 8.**

**Comment by NemanjaMAX** [comment]
http://imgur.com/V5lZiol

**Comment by NemanjaMAX** [comment]
It's works for me,do not hate PLEASE...
See photo

**Comment by remotevase** [comment]
Tesseract is not meant to run on mobile, but I will give it a try on PC when I get a chance. Just remind me. Then I will add to readme if it works.

**Comment by remotevase** [comment]
Thank you for this tutorial, though

**Comment by NemanjaMAX** [comment]
Np, its work for me :) I,don't want liar....
Its from 30-35 to 5-10s now on 40plugins

**Comment by NemanjaMAX** [comment]
@remotevase  BlueLight is Japanese xompany,they have 1.0.0 so u can rewritte some codes 👍

**Comment by remotevase** [comment]
👍
