### ISSUE TITLE
PureChat bug

### ISSUE THREAD

**Issue by Driesboy** [TesseractTeam/Tesseract#160]
#### Problem description

you cannot see the nametag on join
#### Steps to reproduce the issue

use purechat default format etc
give a player a rank
leave and rejoin
#### OS and versions

* Tesseract: 8c7e07af61
* PHP: 7.0.14
* Server OS: Windows Vista & Mac OSX
* Game version: 1.0.2
* Server host: Home
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by NemanjaMAX** [comment]
Plugin Issue

**Comment by Driesboy** [comment]
NO it works on pmmp

**Comment by NemanjaMAX** [comment]
Close it immediately please

**Comment by NemanjaMAX** [comment]
Idc,this is nit pmmp

**Comment by NemanjaMAX** [comment]
Not same code man

**Comment by Driesboy** [comment]
NO ITS A FORK

**Comment by Driesboy** [comment]
and what i will say onjoin changenametagg() dont work!!!

**Comment by NemanjaMAX** [comment]
BUT REWRITTEN
