### ISSUE TITLE
Floating Text Error.

### ISSUE THREAD

**Issue by bulutsun** [TesseractTeam/Tesseract#161]
I add the first flying piece and when I add the second one is deleted first. No error code. How to fix?
-->
* Tesseract:
* PHP: 7.0
* Server OS: Windows
* Game version: 1.0.0

**Comment by remotevase** [comment]
This is a plugin problem.

**Comment by bulutsun** [comment]
All attachments have the same problem.

**Comment by bulutsun** [comment]
Hey please help

**Comment by remotevase** [comment]
Unfortunately, we are the software. It is not our problem if a plugin does not work.

**Comment by bulutsun** [comment]
Oh okey thanks...

**Comment by remotevase** [comment]
Please report the issue on the plugin's github page, not ours. Thank you!
