### ISSUE TITLE
Logout giving God mode ?

### ISSUE THREAD

**Issue by KnightOfEnder** [TesseractTeam/Tesseract#163]
#### Problem description
I've been getting reports from players that. Players have been doing /logout then attacking players but because they done that they take no knockback or damage but they can damage players who are log in. Also they don't get kick out for it. Is there a way to disable the logout command.
#### OS and versions

* Tesseract: Crystal
* PHP: 7
* Server OS: 
* Game version: 1.0.2
* Server host: backupsy
<br>Android phone<br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by caspervanneck** [comment]
plugin eror its  (not a server software eror)

**Comment by AppleDevelops** [comment]
Plugin issue
