### ISSUE TITLE
Did apple leave?

### ISSUE THREAD

**Issue by remotevase** [TesseractTeam/Tesseract#164]
Just wondering, Did @AppleDevelops quit this project?

**Comment by AnkitM252** [comment]
I don't think so. I think he is making it locally and fix many bugs in kust one commit.

**Comment by AppleDevelops** [comment]
You don't question whether I left or not.

**Comment by remotevase** [comment]
Just making sure.

**Comment by remotevase** [comment]
Well, now you did... Now you left XD
