### ISSUE TITLE
Tablist doesnt Refresh after a Player disconnected from the server

### ISSUE THREAD

**Issue by Bluplayz** [TesseractTeam/Tesseract#165]
#### OS and versions

* Tesseract:
* PHP:
* Server OS:
* Game version: 
* Server host:
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by AppleDevelops** [comment]
Are you using Essentials?

**Comment by remotevase** [comment]
I Tested. With Essentials I experience this, without Essentials it works just fine.

**Comment by Bluplayz** [comment]
i only have my own plugins on it xD
