### ISSUE TITLE
InventoryTransactionEvent not work

### ISSUE THREAD

**Issue by Enes5519** [TesseractTeam/Tesseract#166]
InventoryTransactionEvent TargetItem alyaws from PlayerInventory

**Comment by remotevase** [comment]
I do not understand.

**Comment by Nought57** [comment]
Sry, I could not confirm it. Successfully working now.

**Comment by Enes5519** [comment]
https://youtu.be/vixEgqPZ1fY => Please Watch

**Comment by remotevase** [comment]
What? That is strange... Don't have time to test, though. @Nought57

**Comment by Enes5519** [comment]
Please update mcpe packet @remotevase

**Comment by remotevase** [comment]
Done by @AppleDevelops

**Comment by AppleMinerHD** [comment]
Yea it doesent work good..
You can test it with the BedWars Plugin from BluPlayz...
