### ISSUE TITLE
Beacon Bug

### ISSUE THREAD

**Issue by NemanjaMAX** [TesseractTeam/Tesseract#167]
#### OS and versions
<!---
Use the 
* Tesseract: Latest
* PHP: 7.0.14
* Server OS:
* Game version: 1.0.2
* Server host: PocketServer
Beacon light disappears after player rejoin (just for re-joined player,not for all)

**Comment by NemanjaMAX** [comment]
When player rejoin, beacon light disappear (Just for that player,not for all)

**Comment by LordJoshie** [comment]
I don't have this issue. 

I am on the latest Tess build...always. 

I am hosting off of Ubuntu 15.10, and playing off Windows 10. 

I just disconnected on my server, and reconnected.... still seeing my beautiful bacon :) (beacon)

**Comment by AnkitM252** [comment]
I think it happens with glowstone too

**Comment by NemanjaMAX** [comment]
Its on my tesseract,and PocketMine dev 1.6.2 (leet) too..
