### ISSUE TITLE
Windows 10 Edition not work and Not Spawn MOBS

### ISSUE THREAD

**Issue by Romezzn** [TesseractTeam/Tesseract#168]
First of all, I would like to thank you for your work, I know that not many people do it properly and I hope you continue for a long time, THANK YOU FOR THIS GREAT JOB

[Tesseract] [11:10:41] INFO> -----Server information-----
[Tesseract] [11:10:41] INFO> This server is running Tesseract-1.0.0dev Crystal
[Tesseract] [11:10:41] INFO> PHP version: 7.0.9
[Tesseract] [11:10:41] INFO> API: 3.0.0
[Tesseract] [11:10:41] INFO> Target client: Minecraft PE v1.0.2.1
[Tesseract] [11:10:41] INFO> Protocol version: 100

* Tesseract:Las
* PHP:7.0.9
* Server OS: Windows
* Game version: 1.0.2 Android and Windows 10 edition
* Server host: on Home computer 

My Server run in Windows 10 work fine on android and not work on windows 10 edition last version

in the world dont spawn mobs of any type,
I do not know if this is due to some server problem or some bad configuration

attached my server.properties

#Properties Config file
#Mon Jan 30 10:50:03 GMT 2017
server-name=MCPE CLR
motd=MCPE CLR
server-port=19132
online-mode=off
level-name=262632
level-type=DEFAULT
gamemode=0
max-players=20
spawn-protection=16
announce-player-achievements=off
white-list=off
enable-query=on
enable-rcon=off
allow-flight=off
spawn-animals=on
spawn-mobs=on
force-gamemode=off
hardcore=off
pvp=on
difficulty=3
generator-settings=
level-seed=
rcon.password=FtlP6foY0U
auto-save=on

**Comment by LordJoshie** [comment]
ding dong.... mobs are disabled on server softwares for PE at the moment for instability reasons, and that it was never properly implemented anyways... Tess is working on a branch for this. 

You're likely using the Master branch which doesn't have them. 

The only actual issue here, is your level of understanding and comprehension of whats written on the screen in front of you.

**Comment by LordJoshie** [comment]
Also.... you're showing your rcon password... if anyone wanted to, they could look up your server, then connect to your rcon, and OP themselves, and grief your server.... I'd advise taking that one out next time xD

**Comment by TDMidkwhatisxd** [comment]
That was funny 😱😂
Search some plugins for mobs! Or pets!
