### ISSUE TITLE
[POLL] Remove pocketmine.yml?

### ISSUE THREAD

**Issue by AppleDevelops** [TesseractTeam/Tesseract#169]
Should we move everything to tesseract.yml?

**Comment by jrodr10** [comment]
yes

**Comment by remotevase** [comment]
no. People will be wondering "Where did pocketmine.yml go?" if we do that, and we will lose popularity...

**Comment by AppleDevelops** [comment]
Lol @remotevase that is the funniest thing I've ever heard

**Comment by remotevase** [comment]
??? I did that with devmine...

**Comment by Sandertv** [comment]
It's quite disrespectful towards PocketMine and breaks quite some stuff when changing server softwares. I don't recommend it.

**Comment by AppleDevelops** [comment]
@Sandertv That's true
