### ISSUE TITLE
Player lie

### ISSUE THREAD

**Issue by erkam2002** [TesseractTeam/Tesseract#170]
#### Problem description

Player lie if he death not always
#### OS and versions

* Tesseract: newest
* PHP: 7.0.15
* Server OS: Debian 8
* Game version: 1.0.2
* Server host: ?
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

![screenshot 60](https://cloud.githubusercontent.com/assets/16340573/22517151/81a08106-e8a8-11e6-8453-50b1077ce478.png)

**Comment by daniktheboss** [comment]
Close

**Comment by remotevase** [comment]
@daniktheboss The other team members will tell, not you. Sorry!

**Comment by daniktheboss** [comment]
Lmao....

**Comment by Driesboy** [comment]
dont have this bug btw
