### ISSUE TITLE
Please add this....

### ISSUE THREAD

**Issue by NemanjaMAX** [TesseractTeam/Tesseract#175]
Please create working app for win7 hosting (Like PocketMine PHP7 or ImagicalMine)

**Comment by EmreTr1** [comment]
@AppleDevelops please add real bow shooting

**Comment by AnkitM252** [comment]
You mean installer?

**Comment by remotevase** [comment]
We will create an installer when we have time. For now, use the installation guide in our wiki. I have added this to the projects tab.
