### ISSUE TITLE
Having big problem!

### ISSUE THREAD

**Issue by anassyazani** [TesseractTeam/Tesseract#176]
I cant create my server cuz this message keep on coming up
[Tesseract] [06:06:30] CRITICAL> Error: "Call to undefined method pocketmine\tile\Tile::init()" (EXCEPTION) in "/src/pocketmine/Server" at line 1731
[Tesseract] [06:06:30] EMERGENCY> An unrecoverable error has occurred and the server has crashed. Creating a crash dump

**Comment by AppleDevelops** [comment]
I'm having trouble reproducing this issue

**Comment by anassyazani** [comment]
So its the problem with the file?

**Comment by AppleDevelops** [comment]
I tried loading up my server a lot, and no issues, can you give a plugin list?

**Comment by anassyazani** [comment]
which plugins?

**Comment by AppleDevelops** [comment]
Just list all of the plugins from the crashdump

**Comment by anassyazani** [comment]
It says..CrashDump_Fri_Feb..4 same file

On 4 Feb 2017 8:12 am, "Apple" <notifications@github.com> wrote:

Just list all of the plugins from the crashdump

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/TesseractTeam/Tesseract/issues/176#issuecomment-277397774>,
or mute the thread

**Comment by AppleDevelops** [comment]
Example in the crashdump file
Loaded plugins:
DevTools 1.11.1 by PocketMine Team for API(s) 2.0.0, 3.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0-ALPHA3

**Comment by anassyazani** [comment]
Heres what it say inside the file
Tesseract Crash Dump Fri Feb 3 08:39:36 CST 2017

Error: Call to undefined method pocketmine\tile\Tile::init()
File: /src/pocketmine/Server
Line: 1731
Type: notice

Code:
[1722] $this->network = new Network($this);
[1723] $this->network->setName($this->getMotd());
[1724]
[1725]
[1726] Timings::init();
[1727]
[1728] $this->consoleSender = new ConsoleCommandSender();
[1729] $this->commandMap = new SimpleCommandMap($this);
[1730]
[1731] Tile::init();
[1732] Entity::init();
[1733] InventoryType::init();
[1734] Block::init();
[1735] Enchantment::init();
[1736] Item::init();
[1737] Biome::init();
[1738] Effect::init();
[1739] Attribute::init();
[1740] EnchantmentLevelTable::init();
[1741] Color::init();

Backtrace:

Tesseract version: 0000000000000000000000000000000000000000 [Protocol 101;
API 3.0.0]
uname -a: Linux localhost 3.10.9-10038913 #1 SMP PREEMPT Wed Dec 7 20:04:41
KST 2016 armv7l
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, android

Server uptime: 7 minutes 1 seconds
Number of loaded worlds: 0
Players online: 0/3

Loaded plugins:


On 4 Feb 2017 8:15 am, "Anas Syazani" <anassyazani26@gmail.com> wrote:

It says..CrashDump_Fri_Feb..4 same file


On 4 Feb 2017 8:12 am, "Apple" <notifications@github.com> wrote:

Just list all of the plugins from the crashdump

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/TesseractTeam/Tesseract/issues/176#issuecomment-277397774>,
or mute the thread

**Comment by TDMidkwhatisxd** [comment]
Maybe in pocketmine.yml  is Mcregion set as default!

**Comment by AppleDevelops** [comment]
Still reproducible on latest commit?

**Comment by remotevase** [comment]
No. It seems to work fine.

**Comment by remotevase** [comment]
Shall we close?
