### ISSUE TITLE
Acacia crafts not work

### ISSUE THREAD

**Issue by andris155** [TesseractTeam/Tesseract#178]
#### Problem description

Acacia crafts not work

#### Steps to reproduce the issue

Acacia crafts not work

#### OS and versions

* Tesseract: https://github.com/TesseractTeam/Tesseract/tree/e531bfcf33b74e62ddc31449066e991625b8185f
* PHP: 7.0.15 genisys script
* Server OS: Ubuntu 14.04 lts
* Game version: Android
* Server host: InfinityHosting VPS
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

![screenshot_20170203-224800](https://cloud.githubusercontent.com/assets/8324198/22609883/33b5a676-ea63-11e6-91d8-3c5ac4b393b3.png)

**Comment by remotevase** [comment]
I am also unable to reproduce.
