### ISSUE TITLE
CURRENT_PROTOCOL.

### ISSUE THREAD

**Issue by ISRAPIL** [TesseractTeam/Tesseract#179]
**Please add it!!! Silly Genisys, good function deleted...**

[https://github.com/iTXTech/Genisys/commit/b6cec51144660c82cb6dfe43c534ea93fdebcc6a](https://github.com/iTXTech/Genisys/commit/b6cec51144660c82cb6dfe43c534ea93fdebcc6a)

Sorry for my bad English...

**Comment by Driesboy** [comment]
https://github.com/iTXTech/Genisys/commit/32786734a9fa0fcd08a6304cdaf3c09f673a4d1b

**Comment by remotevase** [comment]
Invalid. It works perfectly fine without it.
