### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by anassyazani** [TesseractTeam/Tesseract#182]
I fixed my old prob..Its cuz i downloaded wrong file but something happen to me.I sucsessfully create my server but when i want to join it said"You need authenticate to Xbox live".I did login and do everythin but it keep on saying the same thing..

**Comment by remotevase** [comment]
2 solutions:
In server.properties turn the setting "ONLINe" to off. Or,
In MCPE login with xbox live on the main page where it says sign in.
