### ISSUE TITLE
MULTY PROTOCOL(100 and 101)

### ISSUE THREAD

**Issue by ISRAPIL** [TesseractTeam/Tesseract#183]
**Please add it!!! Silly Genisys, good function deleted...**

[https://github.com/iTXTech/Genisys/commit/b6cec51144660c82cb6dfe43c534ea93fdebcc6a](https://github.com/iTXTech/Genisys/commit/b6cec51144660c82cb6dfe43c534ea93fdebcc6a)

Why are you so quickly close the question?
Sorry for my bad English...

**Comment by AppleDevelops** [comment]
It's a hack. We're trying to get rid of hacks

**Comment by remotevase** [comment]
Thank you, @AppleDevelops. Consider this matter finalized.

**Comment by remotevase** [comment]
Stop spamming our issues, @ISRAPIL.
