### ISSUE TITLE
How to load old map?

### ISSUE THREAD

**Issue by ivan691** [TesseractTeam/Tesseract#184]
My old map cant load.. how to fix it

**Comment by Driesboy** [comment]
nice its like
my old car don't start what can i do
BUY A NEW CAR

**Comment by Skull3x** [comment]
@ivan691 Your problem could be the result of chunk errors, you could try experimenting with the chunks in MCEdit or you can just "Buy a new car"

**Comment by ivan691** [comment]
nice joke

**Comment by AnkitM252** [comment]
True! The old map was not supported after the 1.0.0 update.
But there may be the options to use it again!

**Comment by ivan691** [comment]
Which options?

**Comment by AnkitM252** [comment]
I said may be! Go search!

**Comment by remotevase** [comment]
@AnkitM252 Tesseract has a built in feature to auto convert maps. His problem is just a broken chunk. Use a different map. Or use what is suggested by others above. Not tesseract problem.
