### ISSUE TITLE
SkyPvP item bug

### ISSUE THREAD

**Issue by andris155** [TesseractTeam/Tesseract#185]
#### Problem description

SkyPvP item bug

#### Steps to reproduce the issue

https://www.youtube.com/watch?v=ZyGVb1x7_ZI

#### OS and versions

* Tesseract: https://github.com/TesseractTeam/Tesseract/tree/e531bfcf33b74e62ddc31449066e991625b8185f
* PHP: 7.0.15 genisys script
* Server OS: Ubuntu 14.04 lts
* Game version: Android
* Server host: InfinityHosting VPS
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
none
```

**Comment by KennFatt** [comment]
FloatingInventory and Inventory transaction is messed up.
