### ISSUE TITLE
Add AntiFly stuff, forgot to add.

### ISSUE THREAD

**Issue by andris155** [TesseractTeam/Tesseract#186]
#### Problem description

Fly hack works perfectly allow-flight=off

#### Steps to reproduce the issue

use fly hack

#### OS and versions

* Tesseract: https://github.com/TesseractTeam/Tesseract/tree/e531bfcf33b74e62ddc31449066e991625b8185f
* PHP: 7.0.15 genisys script
* Server OS: Ubuntu 14.04 lts
* Game version: Android
* Server host: InfinityHosting VPS
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

![16523909_875938899212807_1449588565_o](https://cloud.githubusercontent.com/assets/8324198/22622382/99fcc056-eb38-11e6-83d1-d5c1c6d5ba8f.png)

**Comment by AppleDevelops** [comment]
I might have reversed the switch by accident

**Comment by remotevase** [comment]
XD

**Comment by AppleDevelops** [comment]
Oh shoot, I never even coded in the antifly stuff

**Comment by remotevase** [comment]
Wow XD

**Comment by andris155** [comment]
This is the fly protection code?
https://github.com/iTXTech/Genisys/blob/master/src/pocketmine/Player.php#L1799

**Comment by remotevase** [comment]
Added to [projects](https://github.com/TesseractTeam/Tesseract/projects/2)
