### ISSUE TITLE
Enderchest item bug

### ISSUE THREAD

**Issue by andris155** [TesseractTeam/Tesseract#187]
#### Problem description

Enderchest item bug

#### Steps to reproduce the issue

https://www.youtube.com/watch?v=V7PbhlI4hBs

#### OS and versions

* Tesseract: https://github.com/TesseractTeam/Tesseract/tree/e531bfcf33b74e62ddc31449066e991625b8185f
* PHP: 7.0.15 genisys script
* Server OS: Ubuntu 14.04 lts
* Game version: Android
* Server host: InfinityHosting VPS
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Lazerplayz** [comment]
This happens only on Windows10?

**Comment by remotevase** [comment]
probably

**Comment by AppleDevelops** [comment]
Reproduced on classic gui

**Comment by remotevase** [comment]
I am also able to reproduce this. It is a problem with regular chests as well (Not only enderchest)
