### ISSUE TITLE
EndTag error

### ISSUE THREAD

**Issue by andris155** [TesseractTeam/Tesseract#188]
#### Problem description

EndTag

#### Steps to reproduce the issue

I don't know.

#### OS and versions

* Tesseract: https://github.com/TesseractTeam/Tesseract/tree/e531bfcf33b74e62ddc31449066e991625b8185f
* PHP: 7.0.15 genisys script
* Server OS: Ubuntu 14.04 lts
* Game version: Android
* Server host: InfinityHosting VPS
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
2017-02-04 [12:28:49] [CRITICAL]: Error: "Cannot use object of type pocketmine\nbt\tag\EndTag as array" (EXCEPTION) in "/src/pocketmine/Player" at line 1960
```

**Comment by remotevase** [comment]
Unable to reproduce.

**Comment by AppleDevelops** [comment]
Without being able to reproduce this I'd say it is marked unconfirmed until confirmed

**Comment by remotevase** [comment]
Very likely a plugin error.

**Comment by Driesboy** [comment]
i dont have this error
