### ISSUE TITLE
Respawn bug

### ISSUE THREAD

**Issue by andris155** [TesseractTeam/Tesseract#189]
#### Problem description

Respawn bug

#### Steps to reproduce the issue

https://youtu.be/LoGUAYb6wog

#### OS and versions

* Tesseract: https://github.com/TesseractTeam/Tesseract/tree/e531bfcf33b74e62ddc31449066e991625b8185f
* PHP: 7.0.15 genisys script
* Server OS: Ubuntu 14.04 lts
* Game version: Android
* Server host: InfinityHosting VPS
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
None
```

**Comment by Iktaniyalol** [comment]
I have this problem too

**Comment by remotevase** [comment]
Hmm.... Try without plugins, and try running the command "/setworldspawn" at the spawn point ,then report back to me.

**Comment by Lazerplayz** [comment]
This issue still happens even if you have no plugins active I tested it on my test server it is a bug.

**Comment by remotevase** [comment]
o ok

**Comment by Lazerplayz** [comment]
Or it could be because of using MSpawns because of its when die and instead of spawning to the hub world you go to the world you died in so it glitches out.

**Comment by Iktaniyalol** [comment]
Before I havenot MSpawn, and this bug seldom appears

**Comment by Lazerplayz** [comment]
Any other /spawn or /hub plugin?

**Comment by Iktaniyalol** [comment]
It had not been

**Comment by remotevase** [comment]
Should be able to close, yes? Numerous people cannot reproduce.

**Comment by Lazerplayz** [comment]
I tested it this bug doesn't happen anymore.
