### ISSUE TITLE
Terrain Generator Boring

### ISSUE THREAD

**Issue by anassyazani** [TesseractTeam/Tesseract#190]
Why the server is so empty? No tree,hill,cave or nothing..Its just like a flat world with water..How do I build house with my friend etc if no resorces

**Comment by remotevase** [comment]
This is a problem with a boring and unnatural terrain generation. @AppleDevelops can we update it?

**Comment by NemanjaMAX** [comment]
@anassyazani You can generate world in classic offline mcpe,than found it in games folder,delete all just dont touch region an lv dat

**Comment by xinghao2003** [comment]
mcpe generate the leveldb map... pm not support

**Comment by remotevase** [comment]
@xinghao2003 easy to convert it

**Comment by Iktaniyalol** [comment]
I advise you to create a map on the PC version. Better to version 1.10.2 or higher. there is the same format - anvil, but I is mcregion

**Comment by remotevase** [comment]
Fixed in latest
