### ISSUE TITLE
Not an issue. 

### ISSUE THREAD

**Issue by LordJoshie** [TesseractTeam/Tesseract#192]
Just wondering why this plugin works on the official PocketMine, but not this fork. 
If there is a way to add compatibility, I would appreciate that. 

https://github.com/SalmonDE/StatsPE

Thank you for the work you do.

**Comment by SalmonDE** [comment]
I think we should first discuss that in the issue at my repository

**Comment by LordJoshie** [comment]
Lol.... read post at your repo. 

xD uhm, sorry Tess. I meant for a different plugin ... derp.

**Comment by LordJoshie** [comment]
I meant this plugin.... 

https://github.com/SalmonDE/TopVoter
