### ISSUE TITLE
New generator error

### ISSUE THREAD

**Issue by AydarTop** [TesseractTeam/Tesseract#194]
Hello. I have a problem this latest build Tesseract core. Server crashing

Tesseract Crash Dump Mon Feb 6 15:41:49 MSK 2017

Error: Class pocketmine\level\generator\normal\populator\Sugarcane not found
File: /src/spl/BaseClassLoader
Line: 131
Type: notice

**Comment by Iktaniyalol** [comment]
I have this bug too. Fix please, server dont want start....

**Comment by lsw46** [comment]
You can rename the file in pocketmine\level\generator\normal\populator\SugarCane 
rename SugarCane to Sugarcane
