### ISSUE TITLE
EnderDragon Windows10

### ISSUE THREAD

**Issue by Enrick3344** [TesseractTeam/Tesseract#196]
#### Problem description

When I summon EnderDragon on my server They do the dying effect, so they get red and disappear. My staffs use a phone so the Minecraft PE version for Mobile and the dragon stay for them but not for the users of Windows10.

#### Steps to reproduce the issue

Summon an EnderDragon on Windows10 Version of MCPE

#### OS and versions

* Tesseract: 8595198 / Crystal
* PHP: 7.0.3
* Server OS: Windows 10
* Game version: 1.0.2.1
* Server host: VPS
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by remotevase** [comment]
Works for me on my test server Win10 and Android. I was the only one playing on both instances. Maybe its a bug if multiple people are playing?

**Comment by Enrick3344** [comment]
I will try when I'm Alone

**Comment by Enrick3344** [comment]
Just tested and it really does not work for me. Maybe i have a config set wrong or something.

**Comment by remotevase** [comment]
Bump

**Comment by Enrick3344** [comment]
What does that mean @remotevase

**Comment by daniktheboss** [comment]
Apple, this happened yesterday, you spawned a dragon I didn't see. .. confirmed

**Comment by remotevase** [comment]
"Bump" means I am bumping it so that @AppleDevelops does not ignore it. IDK why this fails.

**Comment by intagaming** [comment]
This is simple. You need to add the health attribute to the dragon first. See the "boss bar"?
There's nothing wrong with the server.

**Comment by AppleDevelops** [comment]
EnderDragons were removed due to their issues
