### ISSUE TITLE
Bug effect

### ISSUE THREAD

**Issue by BreadixWorld** [TesseractTeam/Tesseract#197]
#### Problem descriptio
There is a problem. The effect is number 2 (deceleration) Slows ever before rejoining the server. please fix

#### Steps to reproduce the issue
Null

#### OS and versions

* Tesseract: [Protocol 100; API 3.0.0] 
* PHP: 7.0.14
* Server OS: Linux, linux
* Game version: 1.0
* Server host:
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by remotevase** [comment]
Hard to understand

**Comment by BreadixWorld** [comment]
The effect of number 2 is not reset

**Comment by remotevase** [comment]
Works for me. Unconfirmed

**Comment by xZeroMCPE** [comment]
Unconfirmed, Will be closed for now.
