### ISSUE TITLE
TPS - Load Not Accurate.

### ISSUE THREAD

**Issue by LordJoshie** [TesseractTeam/Tesseract#198]
No need to put in all the extra info you ask for...

The issue is simple, and I'm sure everyone is experiencing the same thing... 

TPS - 20 
Load - %0

Always... no fluctuation or anything. 

Just wondering, because monitoring usage and tps was a habit of mine.

**Comment by xZeroMCPE** [comment]
At least provide screenshot...

**Comment by LordJoshie** [comment]
Why ? You dont know where the tps/load is located ?

You can type /status while the server is running.

**Comment by remotevase** [comment]
Confirmed

**Comment by LordJoshie** [comment]
Thank you. :)

I know I'm not crazy, just busy and dont always have the time while mobile
on my phone between home and work to compile versions and information about
my issues.

My descriptions are as informative as needed.

I appreciate the cooperation of the development team with my issues
submissions.

Where & When I can compile all acquired information, I will do so.

**Comment by remotevase** [comment]
Added to [projects, ](https://github.com/TesseractTeam/Tesseract/projects/2)hopefully we will add soon.

**Comment by LordJoshie** [comment]
What confuses me, is that PocketMine shows tps/load....

Isn't this based off it ? What did Tess do differently to break this
function ?

j.w

**Comment by remotevase** [comment]
@LordJoshie I am not sure. I'll look

**Comment by remotevase** [comment]
@LordJoshie Seems to just have been a problem fixed in PMMP here pmmp/PocketMine-MP#195

**Comment by LordJoshie** [comment]
thanks bro, I'll edit these changes when I get home.

**Comment by LordJoshie** [comment]
this works mint. can you do a PR on here if you haven't already ? 

Thanks a ton man ! 

Guess I should try searching harder next time. ;)

**Comment by remotevase** [comment]
I did already, it's in master branch!
