### ISSUE TITLE
Warning when player join

### ISSUE THREAD

**Issue by armagadon159753** [TesseractTeam/Tesseract#2]
![screenshot_2017-07-19-21-31-37](https://user-images.githubusercontent.com/25569806/28388855-609a6ec6-6cd4-11e7-824c-47629972adcd.png)

**Comment by AppleDevelops** [comment]
Forgot about adding that, thanks for reminding me.

**Comment by AppleDevelops** [comment]
Let’s keep that open so I don’t forget.

**Comment by armagadon159753** [comment]
Ok, other issu:
When player respawn after fall out of the map, chunck does not load correctly.

**Comment by AppleDevelops** [comment]
Should be fixed as of latest commit.
