### ISSUE TITLE
Various bugs

### ISSUE THREAD

**Issue by teram1001** [TesseractTeam/Tesseract#2]
chest bug, ladder bug, respawning bug...

**Comment by AppleDevelops** [comment]
You’ve given 0 information on how we can reproduce these bugs.

**Comment by teram1001** [comment]
The ladder won't work and put  item in the chest, it keeps coming out. Respawning bug: when i die and respawning i can't do anything.

**Comment by RateekMCPE** [comment]
Without knowing your Tesseract version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

**Comment by RateekMCPE** [comment]
@teram1001Version, OS, PHP, Client version, or plugins....

**Comment by jdongel2004** [comment]
@RateekMCPE make .github !! There is nobody.. in issue. (Sorry.. my english is poor..)
