### ISSUE TITLE
Inventory Glitch

### ISSUE THREAD

**Issue by daniktheboss** [TesseractTeam/Tesseract#200]
#### Problem description
Hello, some of my players have said that there inventory is cleared on re-log. This is not a plugin fault because i have checked and none of the plugins clear inventory. 

#### Steps to reproduce the issue
Fill inventory with stuff, re-log, maybe it will glitch? heh

#### OS and versions
* Tesseract: Commit [8883bb9](https://github.com/TesseractTeam/Tesseract/commit/8883bb9a899ec72b5378cfc3f171029efc472920)
* PHP: 7
* Server OS: Debian
* Game version: 1.0.3
* Server host: VPS

#### Crashdump, backtrace, memory dumps, plugins list or other files
None

**Comment by TDMidkwhatisxd** [comment]
Its becouse of floating inventory! Is a glich from long time ago!
Some cunning players, move/glich all items in floating inventory, then it drops! 
So, if a player enter in another player account and do that glich, he can drop items! Even if a auth plugin cancel drop event!

How to avoid this? Just do some auth plugin based on Device Id, or Xbox auth, this way, players can use other players name!

Hope it helps!

**Comment by Nought57** [comment]
Have you checked the items of "auto-clear-inventory" in Tesseract.yml?

**Comment by daniktheboss** [comment]
yes, i have

**Comment by remotevase** [comment]
Working on fixing this now. Pmmp fixed it.
