### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by Uniqulmuia** [TesseractTeam/Tesseract#202]
Firstly, when i start my server this happens:  Notice: Undefined property: pocketmine\Server::$maxTick in /home/sky/src/pocketmine/Server.php on line 666
[Tesseract] [05:05:45] INFO> [EssentialsPE] No new version found, you're using the latest version of EssentialsPE

Notice: Undefined property: pocketmine\Server::$maxUse in /home/sky/src/pocketmine/Server.php on line 684

Notice: Undefined property: pocketmine\Server::$maxTick in /home/sky/src/pocketmine/Server.php on line 666
transferserver
Also here is a bug.. Some people can be killed with a sword some no, its like a god.

Steps to reproduce the issue
I dont know.

OS and versions

Tesseract: newest
PHP: 7.0.15
Server OS: Ubuntu 14 x64
Game version: 1.0.3
Server host: ?

Crashdump, backtrace, memory dumps, plugins list or other files

**Comment by AnkitM252** [comment]
Try now!

**Comment by remotevase** [comment]
FYI if this is a MCR world, MCR support is deprecated.
