### ISSUE TITLE
CRITICAL Could not tick level

### ISSUE THREAD

**Issue by andris155** [TesseractTeam/Tesseract#206]
#### Problem description

CRITICAL Could not tick level 

#### Steps to reproduce the issue

I don't know.

#### OS and versions

* Tesseract: https://github.com/TesseractTeam/Tesseract/tree/997689823eaea7c84dc30c1974fe34f4ffd72b3b
* PHP: 7.0.15 genisys script
* Server OS: Ubuntu 16.04.1 LTS
* Game version: 1.0.3 Android
* Server host: Clans.hu VPS
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
10.02 23:22:29 [Server] INFO Notice: Undefined offset: 0 in phar:///Tesseract_1.1.0.phar/src/pocketmine/level/format/Chunk.php on line 389
10.02 23:22:29 [Server] CRITICAL Could not tick level "spawn": Return value of pocketmine\level\format\Chunk::getHeightMap() must be of the type integer, null returned
```

**Comment by AnkitM252** [comment]
Is that on server startup?

**Comment by andris155** [comment]
No

**Comment by AppleDevelops** [comment]
MCRegion or Anvil world?

**Comment by remotevase** [comment]
Tested with both. MCR worlds has this, Anvil does not.

**Comment by andris155** [comment]
MCRegion

**Comment by AppleDevelops** [comment]
MCRegion is deprecated, we don't support it anymore
