### ISSUE TITLE
World Generate Bugg

### ISSUE THREAD

**Issue by S3nS3IW00** [TesseractTeam/Tesseract#208]
#### Problem description

If I will generate a world, no bedrock at the bottom of the word, and if I fell out off the word, I will fall on something invisible and this "block" don't have hitbox, I can't break, and I can move on this block.
#### OS and versions

This server is running Tesseract-1.1.0 Ruby
API: 3.0.0
Target client: Minecraft PE v1.0.3.0
Protocol version: 101* Tesseract:
* PHP: 7.0.15 genisys script
* Server OS: Ubuntu 16.04.1 LTS
* Game version: 1.0.3 Android
* Server host: Clans.hu VPS
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by remotevase** [comment]
Hmm... Strange...

**Comment by S3nS3IW00** [comment]
Can you fix it? :D How many time?

**Comment by remotevase** [comment]
I'm not sure if I can, but I know that @AppleDevelops definitely can

**Comment by S3nS3IW00** [comment]
Ok thanks, I hope for this bugg not have too many time to fix
