### ISSUE TITLE
Add ban reason join banned players

### ISSUE THREAD

**Issue by andris155** [TesseractTeam/Tesseract#212]
Example: You are banned: reason

**Comment by Driesboy** [comment]
yeah that will be nice

**Comment by remotevase** [comment]
Don't we already have this? Its
/ban <player> <reason>

**Comment by Driesboy** [comment]
Yes but if the player join after ban it shows no reason

**Comment by remotevase** [comment]
Oh.

**Comment by LordJoshie** [comment]
I agree with this thread, and in fact, had this thought myself yesterday when I banned someone... wish when they joined back it would show them a reason why, opposed to saying "You are banned!" but then again, the message "You are banned" can easily be modified, so I'm sure you can add in code to call to the file and get the reason, and send that to the player... otherwise, if no reason given, just do the default "you are banned" 


good idea guys !

**Comment by RTGDaCoder** [comment]
So, who's working on this issue/enhancement? I'm really down to support Tesseract )

**Comment by remotevase** [comment]
Many of the devs are currently busy with school, we push major changes on weekends. Thanks for understanding!

**Comment by remotevase** [comment]
Added, I think. Test it?

**Comment by andris155** [comment]
A tested, and not work
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/23043607/2967eb72-f49d-11e6-9530-dcf567be53ca.PNG)

`andris155|2017-02-16 22:10:34 +0000|CONSOLE|Forever|test`

**Comment by AnkitM252** [comment]
Its not fully implemented yet!

**Comment by remotevase** [comment]
Oh... Lol

**Comment by AnkitM252** [comment]
Check this line! https://github.com/TesseractTeam/Tesseract/blob/master/src/pocketmine/Player.php#L1842

**Comment by remotevase** [comment]
Yeah. For that we have to edit the command, get args1 and make that $reason. then in player.php we gotta make $reason fetch $reason from the command

**Comment by RTGDaCoder** [comment]
Cool! That's how stuffs work :)

Sent by IG

**Comment by AnkitM252** [comment]
Try with the latest commit!

**Comment by andris155** [comment]
Latest commit write wrong reason
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/23102779/c797513e-f6af-11e6-9e0c-798f924903c4.PNG)

**Comment by AnkitM252** [comment]
What reason did you wrote when banning?

**Comment by LordJoshie** [comment]
if you add a space, it wont show the whole reason... I did /ban somerandom You suck !  ... 

and it showed up as "reason: You" .... LOL

**Comment by AnkitM252** [comment]
Its is fixed but you cannot do a time ban!

**Comment by RTGDaCoder** [comment]
https://github.com/TesseractTeam/Tesseract/blob/master/src/pocketmine/command/defaults/BanCommand.php#L61

@LordJoshie incorrect! You can add the whole string that you wanted to add as your ban reason..

Just use:

```
array_splice()

Example:

$reason = implode(" ", array_splice($args, 3));

sendMessage($reason);

```

**NOTE:** The array_splices' number isn't necessarily to be 3. It's depending on your args!

**Comment by EoflaOE** [comment]
This bug should be fixed immediately as it counts as banning for little-to-no reason

**Comment by LordJoshie** [comment]
What bug?
Either I havent noticed, or it doesnt effect me.

**Comment by EoflaOE** [comment]
This ban bug. I need it to be fixed. Some versions of Tesseract were experiencing this

**Comment by LordJoshie** [comment]
and what specifically is the issue  ?

You're unable to have the reason show when a player returns ?
