### ISSUE TITLE
Server now outdated and new upgraded to 1.0.3

### ISSUE THREAD

**Issue by KnightOfEnder** [TesseractTeam/Tesseract#214]
#### Problem description
Server now outdated when your update for 1.0.3
Write a short description about the issue -->

#### OS and versions

* Tesseract:
* PHP:
* Server OS:
* Game version: 
* Server host:
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Driesboy** [comment]
? The 1.0.3 update will only accept 1.0.3 clients

**Comment by KnightOfEnder** [comment]
I'm using Tesseract but server now outdated due to version being Version 1.0.0.16
But mojang updated game to 1.0.3

**Comment by remotevase** [comment]
Invalid. Server supports 1.0.3, and client is 1.0.3. Download the latest src build or phar from jenkins

**Comment by remotevase** [comment]
Download the phar from here if you need to. http://jenkins.tesseractteam.tk:8080/job/Tesseract/

**Comment by KnightOfEnder** [comment]
What I download ?

**Comment by remotevase** [comment]
If you do not know how to run the server from a phar file, please read this
https://github.com/TesseractTeam/Tesseract/wiki/Installation
