### ISSUE TITLE
[POLL] Protocol hack?

### ISSUE THREAD

**Issue by AppleDevelops** [TesseractTeam/Tesseract#215]
Should we add back the protocol hack?
Thumbs up = no
Thumbs down = no

**Comment by remotevase** [comment]
No :-1:

**Comment by remotevase** [comment]
There's a reason why it is called a "hack" XD

**Comment by remotevase** [comment]
So its a no either way? lol why i dont understand. Are we adding it?

**Comment by remotevase** [comment]
Seems to be in a PR by @xZeroMCPE. Now the final decision is if that is accepted or rejected.
