### ISSUE TITLE
Unable to open database

### ISSUE THREAD

**Issue by ISRAPIL** [TesseractTeam/Tesseract#216]
> Exception: "Unable to open database: unable to open database file" (EXCEPTION) in "/plugins/MyAPI/src/ISRAPIL/MainClass" at line 1097

```
        @mkdir($this->getDataFolder());
        $this->db = new \SQLite3($this->getDataFolder() . "regions.sqlite3");

```

It's a windows server.

**Comment by remotevase** [comment]
Plugin issue. Please check your plugin.

**Comment by ISRAPIL** [comment]
@remotevase 
Fack... On Android and Linux everything works !!!
