### ISSUE TITLE
Not Sure What this is yelling at me for ._.

### ISSUE THREAD

**Issue by jrodr10** [TesseractTeam/Tesseract#219]
#### Problem description

The server eventually crashes, not sure the cause only one error is being output
#### Steps to reproduce the issue

Not Sure
#### OS and versions

* Tesseract:
* PHP: 7.0.14
* Server OS: Ubuntu
* Game version: 1.0.3
* Server host: Dedicated Server
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```
11.02 21:59:14 [Server] INFO [Tesseract] [21:59:14] CRITICAL> Could not tick level "DRGold": Call to a member function spawnToAll() on null

**Comment by remotevase** [comment]
MCR world or anvil?

**Comment by Lazerplayz** [comment]
I think this is a corrupted world.

**Comment by remotevase** [comment]
@Lazerplayz Most likely.

**Comment by xZeroMCPE** [comment]
Unconfirmed, Not being able  to reproduce.

Maybe link us to your map?

**Comment by jrodr10** [comment]
Please reopen sorry for late response lots of college work! @xZeroMCPE
