### ISSUE TITLE
TransactionQueue translate to TransactionGroup 

### ISSUE THREAD

**Issue by Enes5519** [TesseractTeam/Tesseract#220]
#### OS and versions

* Tesseract: Ruby
* PHP: 7.0.1
* Server OS: Linux
* Game version: 1.0.3
* Server host: -
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

Fix please

**Comment by remotevase** [comment]
Will reopen once the main post is edited so that the required fields are filled.  "Fix please" is invalid.
