### ISSUE TITLE
Hopper DropItem Bug

### ISSUE THREAD

**Issue by Prisane** [TesseractTeam/Tesseract#222]
#### Problem description

I dig the hopper but the hopper item not drop

#### OS and versions

* Tesseract: Latest commit
* PHP: 7.0.15
* Server OS: Ubuntu
* Game version: 1.0.3
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by remotevase** [comment]
Redstone is not implemented.

**Comment by Prisane** [comment]
What? hopper is working but it does not break @remotevase

**Comment by Prisane** [comment]
@AppleDevelops please look for issues . there was no this problem in the past

**Comment by remotevase** [comment]
Read my previous post,
> Redstone is not implemented.

That means that you should not use it at all.

**Comment by AnkitM252** [comment]
I think we should remove the items from the inventory. So, that it will not be used!

**Comment by remotevase** [comment]
@AnkitM252 then we would get more complaints. Just rename each item to 
(TextFormat::RED."DO NOT USE!/nNOT IMPLEMENTED")

**Comment by AnkitM252** [comment]
Oh okay! We will send a tip/popup!

**Comment by remotevase** [comment]
Yup but gotta make sure that it only sends to the player not to the entire server

**Comment by AnkitM252** [comment]
yea!
