### ISSUE TITLE
bed translate not work force-language: true

### ISSUE THREAD

**Issue by andris155** [TesseractTeam/Tesseract#224]
#### Problem description

bed translate not work force-language: true

#### Steps to reproduce the issue

1. set force-language: true
2. right click bed

#### OS and versions

* Tesseract: https://github.com/TesseractTeam/Tesseract/tree/908e62aff7e02621f9376aca718211e5bf49146a
* PHP: 7.0.15
* Server OS: Uubuntu 14.04 lts
* Game version: 1.0.3 Windows 10
* Server host: InfinityHosting VPS
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/22883158/10bf72e4-f1ef-11e6-8bda-91d97d9f0bbb.PNG)

**Comment by remotevase** [comment]
Retest, make sure that the /src/pocketmine/lang/locale directory exists.

**Comment by ISRAPIL** [comment]
@remotevase These words in languages do not have ...

**Comment by andris155** [comment]
I tested, and not work.

**Comment by andris155** [comment]
```
 #Three-letter language code for server-side localization
 #Check your language code on https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes
 language: "eng"
 #Whether to send all strings translated to server locale or let the device handle them
 force-language: true
```
