### ISSUE TITLE
WHO DELETED THE PROJECTS?!

### ISSUE THREAD

**Issue by remotevase** [TesseractTeam/Tesseract#226]
I spent a long time on that. WHO DELETED IT?!

**Comment by LordJoshie** [comment]
sounds like you two have communication issues.... lol

**Comment by remotevase** [comment]
ikr we def do

**Comment by LordJoshie** [comment]
xD its funny.

like me and my co over my server...sorta. :P

**Comment by remotevase** [comment]
:P
