### ISSUE TITLE
WingProxy

### ISSUE THREAD

**Issue by MrReskill** [TesseractTeam/Tesseract#24]
Hello, wings proxy is actually good for install in my servers ?

And how to install this proxy ?

**Comment by IISweePII** [comment]
Currently I do not exactly how to work with wingproxy, I believe it was removed and currently in testing since it was having issues with platforms. I will notify @TheAppleGamer through this comment and through other means to see what can be a resolution for this.

**Comment by IISweePII** [comment]
WingProxy is a synapse like client which is for multiple servers I believe in 1 connection, I do not know much sadly about wingproxy since I do not work in that area of Tesseract

**Comment by xZeroMCPE** [comment]
@MrReskill It's a type of system like "BungeeCord". Which allows you to transfer players between players.

Here's a more detailed description:

WingProxy is a "proxy" server software that allows for multiple MCPE servers to be "connected" in such a way that it allows you to teleport between servers, but only use one IP to join the network of servers.

**Comment by MrReskill** [comment]
Others proxy is available and done for pm ? (Please dont speak Nemisys, its break in 0.16 ! )
