### ISSUE TITLE
[Network] Stopped interface

### ISSUE THREAD

**Issue by andris155** [TesseractTeam/Tesseract#241]
#### Problem description

[Network] Stopped interface

#### Steps to reproduce the issue

1. Start server.
2. Join 10-20 player
3. 
`[CRITICAL] [Network] Stopped interface pocketmine\network\RakLibInterface due to Tried to save closed player`

#### OS and versions

* Tesseract: https://github.com/TesseractTeam/Tesseract/tree/f9c6577aa6fb464093651ae8267f0e45e0cbc5dd
* PHP: 7.0.15 x64 Genisys
* Server OS: Ubuntu 14.04.1 lts
* Game version: 1.0.3
* Server host: InfinityHosting VPS, and home PC
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

![image](https://cloud.githubusercontent.com/assets/8324198/22981817/9c469e6e-f39d-11e6-8afd-d0f7b77cdf01.png)
```
[CRITICAL] [Network] Stopped interface pocketmine\network\RakLibInterface due to Tried to save closed player
```

**Comment by AppleDevelops** [comment]
Ya when @remotevase copied code 😜 He messed up some of it

**Comment by remotevase** [comment]
lol sorry

**Comment by remotevase** [comment]
well actually that part in that commit was not because of me. Its the other thing that was me. Signs and inventory

**Comment by andris155** [comment]
```
16.02 12:55:48 [Server] CRITICAL [Network] Stopped interface pocketmine\network\RakLibInterface due to Tried to save closed player
16.02 12:56:01 [Server] CRITICAL Could not execute task ServerAuth\Tasks\MessageTask: Tried to save closed player
16.02 12:56:01 [Server] CRITICAL InvalidStateException: "Tried to save closed player" (EXCEPTION) in "/src/pocketmine/Player" at line 3690
```

**Comment by ISRAPIL** [comment]
Close it. All nice!

**Comment by AppleDevelops** [comment]
@remotevase Stop adding the stupid "To Close?" label it makes no sense whatsoever

**Comment by xZeroMCPE** [comment]
loool
