### ISSUE TITLE
Violation of the PocketMine-MP license

### ISSUE THREAD

**Issue by dktapps** [TesseractTeam/Tesseract#244]
https://github.com/TesseractTeam/Tesseract/blob/master/LICENSE

This change is in violation of PocketMine-MP's LGPL license, which states that you must make your source code of any derived works available under the same license. By changing the license, you are violating several laws and can be subjected to a DMCA claim.

**Comment by remotevase** [comment]
Really? Where is that [here](https://github.com/PocketMine/PocketMine-MP/blob/master/LICENSE)?

**Comment by dktapps** [comment]
Fine, I'll submit a DMCA then. Since Genisys is licensed under GPL you're also violating its license.

**Comment by remotevase** [comment]
Provide proof that we are violating its license. Where does it say that we must keep the licence?

**Comment by remotevase** [comment]
If necessary, I will provide the counter argument to github support.

**Comment by dktapps** [comment]
The license itself states it. Read it.

I'm not here to argue with you. I'm here to inform you that you are in violation of copyright laws and are distributing GPL-licensed work illegally under a different license.

**Comment by remotevase** [comment]
> I am nice (unlike you)

FYI you cannot submit a DMCA just because someone is mean to you 😂

**Comment by remotevase** [comment]
Reverting that now

**Comment by remotevase** [comment]
I see it [here in conditions](https://choosealicense.com/licenses/gpl-3.0/)

**Comment by IISweePII** [comment]
@dktapps we will fix this as quickly as possible

**Comment by dktapps** [comment]
Just for the record, you were banned from the PocketMine-MP repository for advertisement. This does not follow our rules. Thank you for your time.

**Comment by IISweePII** [comment]
@dktapps I never used the PocketMine-MP repository to advertise Tesseract lol, if you are talking about me

**Comment by remotevase** [comment]
@dktapps Lastly, one question:
I was not trying to advertise, I was just trying to aid you in fixing an issue. Sorry if that is not allowed. I would really like to be unbanned from Genisys and PMMP repos.

**Comment by xZeroMCPE** [comment]
@remotevase 
@dktapps 

@dktapps is right...

Look here: https://github.com/PocketMine/PocketMine-MP/blob/master/LICENSE#L6

**Comment by remotevase** [comment]
@dktapps I already realized that he was right a long time ago, no need to clarify extra.

**Comment by remotevase** [comment]
EDIT: @xZeroMCPE that line refers to not allowed to change part of the licence like editing the actual licence file, not copy software on the condition of not changing entire licence
