### ISSUE TITLE
hey gents. little issue....raklib stopped on try to save closed player.

### ISSUE THREAD

**Issue by LordJoshie** [TesseractTeam/Tesseract#246]
#### Problem description

Someone leaves, server crashes.

#### Steps to reproduce the issue

mentioned above,.

#### OS and versions

* Tesseract: 66b92f0
* PHP: 7.0.3
* Server OS: Ubuntu 15.10
* Game version: 1.0.3
* Server host: OVH (not some lame leet server...)
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

![capture](https://cloud.githubusercontent.com/assets/17371144/23021622/e22f895e-f41a-11e6-8a0e-f92416662822.PNG)

**Comment by andris155** [comment]
https://github.com/TesseractTeam/Tesseract/issues/241

**Comment by xZeroMCPE** [comment]
Same as #241
