### ISSUE TITLE
Exception after transfer to my other server

### ISSUE THREAD

**Issue by Bluplayz** [TesseractTeam/Tesseract#247]
with newest version this exception comes if i transfer to another server using synapse\Player::transfer($hash);

#### OS and versions

* Tesseract:
* PHP:
* Server OS:
* Game version: 
* Server host:
<br>
CRITICAL> Could not execute task synapsepm\TickSynapseTask: Tried to save closed player
[Tesseract] [16:25:09] CRITICAL> InvalidStateException: "Tried to save closed player" (EXCEPTION) in "/src/pocketmine/Player" at line 3774
<br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by xZeroMCPE** [comment]
Same as #241

**Comment by remotevase** [comment]
Don't use synapse.

**Comment by Bluplayz** [comment]
what else then? i need it to transfer to other servers and manage them easily with Nemisys as Proxy

**Comment by remotevase** [comment]
Use the /transfer command built in.

/transfer <serverIP:Port>

EG: /transfer play.lbsg.net:19132

**Comment by AnkitM252** [comment]
You create plugins, right?
Then make one main server! make a plugin that transfer player to another server on join!

**Comment by remotevase** [comment]
yah i think he makes plugins

**Comment by AnkitM252** [comment]
Obviously he does! he told it on another issue!

**Comment by remotevase** [comment]
Oh lol

**Comment by Bluplayz** [comment]
okay :) then i use a normally server as proxy xD ty for your help guys
