### ISSUE TITLE
Player can't join in server

### ISSUE THREAD

**Issue by TheBaldCool** [TesseractTeam/Tesseract#248]
#### Problem description
When i join in server, in console are write nothing, and in minecraft write "Unable to connect to world."

#### Steps to reproduce the issue
Join in server.

#### OS and versions
* Tesseract: 1.1.0 Ruby
* PHP: 7.0.3
* Server OS: Ubuntu 14.04 x64
* Game version: 1.0.3.0
* Server host: ihor.ru
<br><br>
#### Crashdump, backtrace, memory dumps, 
Not crashdumps and other.
```
```

**Comment by AppleDevelops** [comment]
I've been able to join my server each and every update as well as others please gather more info and I will open

**Comment by remotevase** [comment]
works. If you are using an android, use the 1.0.4 branch.
