### ISSUE TITLE
Crafting Buggs, Glitches

### ISSUE THREAD

**Issue by S3nS3IW00** [TesseractTeam/Tesseract#249]
#### Problem description

If I craft anything sometimes it's dissapeare, and sometimes I got back a little piece of my items. And sometimes If I craft anything, I got a crafted item and I got back the ingredients.

#### OS and versions

This server is running Tesseract-1.1.0 Ruby
API: 3.0.0
Target client: Minecraft PE v1.0.3.0
Protocol version: 101* Tesseract:
* PHP: 7.0.15 genisys script
* Server OS: Ubuntu 16.04.1 LTS
* Game version: 1.0.3 Android
* Server host: Clans.hu VPS
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by ISRAPIL** [comment]
I do not have this bug.

**Comment by S3nS3IW00** [comment]
But this real bugg...not I have only this bugg..

**Comment by S3nS3IW00** [comment]
If I record a video and I send the link here are you watch?

**Comment by AppleDevelops** [comment]
Pocket GUI or Classic GUI?

**Comment by S3nS3IW00** [comment]
Classic

**Comment by S3nS3IW00** [comment]
Try this with pocket?

**Comment by S3nS3IW00** [comment]
Here the video: https://youtu.be/9CbXV_ttdaA
