### ISSUE TITLE
0.17 1.0 branch world do not load correct

### ISSUE THREAD

**Issue by caspervanneck** [TesseractTeam/Tesseract#25]
#### Problem description

Load a world from the  0.17.0. 1.0 branch and do not load correct
#### Steps to reproduce the issue

Load a world from the  0.17.0. 1.0 branch

#### OS and versions

* Tesseract:
* PHP: 7.0.13
* Server OS: Windows 10 and mcpe
* Game version:  0.17.0.2

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by TheAppleGamer** [comment]
We are working on it

**Comment by caspervanneck** [comment]
yes y know @TheAppleGamer
