### ISSUE TITLE
Nice. BUG.

### ISSUE THREAD

**Issue by ISRAPIL** [TesseractTeam/Tesseract#250]
[Tesseract] [22:42:01] CRITICAL> Ошибка прорисовки мира "world": Call to undefined method pocketmine\block\StonePressurePlate::checkActivation()
[Tesseract] [22:42:01] CRITICAL> Ошибка прорисовки мира "world": Call to undefined method pocketmine\block\StonePressurePlate::checkActivation()
[Tesseract] [22:42:02] CRITICAL> Ошибка прорисовки мира "world": Call to undefined method pocketmine\block\StonePressurePlate::checkActivation()

**Comment by ISRAPIL** [comment]
https://github.com/ISRAPIL/Tesseract/commit/38c78f17a870325c2f6d110aa209c2065108d7b7

**Comment by LordJoshie** [comment]
dude... not tryina be rude, but you are TERRIBLE at posting issues. 

Try being on the absolute latest version of Tess before posting your issue... and give a more descriptive title to the issue. 

"Nice.BUG"   is something I would just close immediately. 


also, this issue has been resolved already...

GET WITH THE TIMES MAN

**Comment by ISRAPIL** [comment]
@LordJoshie 
My English is bad
I always upgrade your kernel, immediately after the release. Since I know the kernel API I understand how to put the update and what is not ...

**Comment by remotevase** [comment]
Invalid issue, you may reopen this once it has a better title.

**Comment by LordJoshie** [comment]
x'D  Im dyin !
