### ISSUE TITLE
Serious bug!

### ISSUE THREAD

**Issue by Pizzahaet** [TesseractTeam/Tesseract#256]
#### Problem description
2017-02-16 [Tesseract] [18:53:24] CRITICAL> [Network] Stopped interface pocketmine\network\RakLibInterface due to Tried to save closed player 

#### Steps to reproduce the issue
Leave the game 

#### OS and versions

* Tesseract:1.0.0 (RUBY)
* PHP:7.0.3
* Server OS:Ubuntu:16.04
* Game version: 1.0.3
* Server host: Vps
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by AppleDevelops** [comment]
Use the latest commit, it is fixed in that.
