### ISSUE TITLE
Fix this for the love of god

### ISSUE THREAD

**Issue by YaBoiSavion** [TesseractTeam/Tesseract#257]
#### Problem description

Could not tick level "arena": Class pocketmine\block\Enchantment not found

#### OS and versions

* Tesseract: Latest
* PHP: 7.0.x
* Server OS: Latest
* Game version: Latest
* Server host: Own
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by YaBoiSavion** [comment]
For the love of fucking god fix your shit

**Comment by AppleDevelops** [comment]
Use the latest commit
