### ISSUE TITLE
Notice: Uninitialized string offset BinaryStream.php

### ISSUE THREAD

**Issue by andris155** [TesseractTeam/Tesseract#259]
#### Problem description

Notice: Uninitialized string offset BinaryStream.php

#### Steps to reproduce the issue

Join players (?)

#### OS and versions

* Tesseract: https://github.com/TesseractTeam/Tesseract/tree/c86fbf662c7c2df834b2e0dc763d53fdf4a7e7e9
* PHP: 7.0.15
* Server OS: Ubuntu 14.04 lts
* Game version: 1.0.3
* Server host: InfinityHosting VPS
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
17.02 12:59:32 [Server] INFO Notice: Uninitialized string offset: 7 in phar:///Tesseract_1.1.0.phar/src/pocketmine/utils/BinaryStream.php on line 154
```

**Comment by remotevase** [comment]
1. MCR is deprecated
2. Use the 1.0.4 branch if you are playing on MCPE Beta
3. Use the master branch if you are playing on official MCPE 1.0.3

**Comment by AppleDevelops** [comment]
@remotevase Please only respond if you know what the issue is or else I'm considering you span

**Comment by AppleDevelops** [comment]
This is not how to reproduce this anyways
