### ISSUE TITLE
Bug Tesseract #1

### ISSUE THREAD

**Issue by RateekMCPE** [TesseractTeam/Tesseract#26]
#### Problem Tesseract #1
1. Duplication when the armor is removed and returned
2. was a client side bug that is fixed in MCPE 1.0
3. When one and in the parameters and one looks the players it its in duplicate

#### OS and versions
Tesseract: Crystal
PHP: 7.0.2
Server OS: Debian GNU/Linux
Game version: 0.16.2

**Comment by IISweePII** [comment]
I see about the issue #1, I have not tried armor yet so I will look into that. What is the bug that occurs when you try to spawn a animal? Also can you clarify on what the parameters for issue #3 are? xD
