### ISSUE TITLE
Exception after leaving the server

### ISSUE THREAD

**Issue by Bluplayz** [TesseractTeam/Tesseract#260]
CRITICAL> InvalidStateException: "Tried to save closed player" (EXCEPTION) in "/src/pocketmine/Player" at line 3774

that comes after i transfer to another server using TransferPacket

#### OS and versions

* Tesseract: newest version(17.02.2017)
* PHP: 7
* Server OS: Debian
* Game version: 
* Server host:
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by AppleDevelops** [comment]
Outdated version, this has been fixed already.

**Comment by Bluplayz** [comment]
nope... i tested it with the latest version lol

**Comment by AppleDevelops** [comment]
No one else can reproduce it you have to be using an outdated version.

**Comment by AppleDevelops** [comment]
Are you using the phar?

**Comment by Bluplayz** [comment]
yes

**Comment by AppleDevelops** [comment]
That's why, a new build will be out in an hour

**Comment by Bluplayz** [comment]
ah ok, i try it again then, ty :)
