### ISSUE TITLE
Enchanting, Anvil and Cauldron don't work

### ISSUE THREAD

**Issue by NycuRO** [TesseractTeam/Tesseract#261]
#### OS and versions

* Tesseract: https://github.com/TesseractTeam/Tesseract/commit/e7ce036d2dca16054a6f291102b7c059649b0987
* PHP: 7.0.14
* Server OS: Ubuntuu 14.0.4.5 LTS 64bit 
* Game version: 1.0.3
* Server host: gazduirejocuri.ro
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by LagHD** [comment]
Same thing here, I'm not enabling cheats because then people can give themselves items and stuff

**Comment by xZeroMCPE** [comment]
Test on latest commit

**Comment by NycuRO** [comment]
@xZeroMCPE Not work.

**Comment by Iktaniyalol** [comment]
I agree. Not work

**Comment by JunkDaCoder** [comment]
Rip, same for me too

**Comment by JunkDaCoder** [comment]
Any news?

**Comment by SuperXingKong** [comment]
Already fix?
