### ISSUE TITLE
NOT A ISSUE | Please read

### ISSUE THREAD

**Issue by sero583** [TesseractTeam/Tesseract#262]
Why do you add a function called "getName()" to ever Event? Isn't it useless since you can't multitask event's?
I mean if you use that event in that way you would ofcourse know the name.
Also turning it to a public static function would be better than a public function since you can use the static function also in that way Class::staticfunction(); .

**Comment by Nought57** [comment]
EventDebug function was added when adding PacketDebug function. Originally it was not scheduled, but it was added as requested. PacketDebug was sought by plug-in developers,  Src developer asked for EventDebug function. These are functions created for those who learn the principle of src. The purpose of use is for each person, but if there is demand we will add it.
