### ISSUE TITLE
Your Mission, MrApple. 

### ISSUE THREAD

**Issue by LordJoshie** [TesseractTeam/Tesseract#264]
https://github.com/RevivalPMMP/PureEntitiesX

Please add support MrApple. You said if I create an issue here, you'll add support. 

Thanks !! :D

**Comment by remotevase** [comment]
@LordJoshie can we implement the entire plugin into tesseract?

**Comment by LordJoshie** [comment]
Im not sure, that would be between the devs of this server software, and
the devs of the plugin.

I just posted an issue a short bit ago on the plugin asking for support for
this server software, but Apple commented on my post saying I could make a
issue here and request compatibility support.

:)   I just want mobs cuz everyone is asking for horses and stuff. figure
rideable mobs would be an excellent addition to the server I host. :P
