### ISSUE TITLE
@AppleDevelops

### ISSUE THREAD

**Issue by remotevase** [TesseractTeam/Tesseract#265]
My official resignation from this team. I am not coding PHP any more after @AppleDevelops Said i can't code. Nice knowing y'all!

**Comment by remotevase** [comment]
Oh wait, @AppleDevelops Already kicked me from the org

**Comment by AppleDevelops** [comment]
And you're getting banned from the repo :)

**Comment by remotevase** [comment]
Okay!

**Comment by remotevase** [comment]
@xZeroMCPE farewell
