### ISSUE TITLE
About comments at top of each php file

### ISSUE THREAD

**Issue by Dog2puppy** [TesseractTeam/Tesseract#266]
Not exactly a issue, but I noticed that in one commit you removed all the comments that said PocketMine-MP. If you do want a easy way to add those back in, I use StyleCI.

**Comment by AppleDevelops** [comment]
If you could add them back that'd be nice! Remotevase ruined it.

**Comment by Dog2puppy** [comment]
I can't do it, but you can if you add the repo to StyleCI.
