### ISSUE TITLE
Timings v1 not work. :(

### ISSUE THREAD

**Issue by andris155** [TesseractTeam/Tesseract#268]
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/23084637/9c5863d4-f563-11e6-949c-8f68c3731511.PNG)

**Comment by xZeroMCPE** [comment]
Timings v1 was removed by it developer. 

We"ll have to to add Timings v2.  Which is what i'm doing

**Comment by LordJoshie** [comment]
Is this the only issue about timings ? 

can this remain open, until you're done with timings v2 ? 

I could REEEAAAALLLLYYYY use Timings right about now xD 

my usually stable, lagless server is sitting at 5-15tps @ 75-100% load, and /status gives POOP all for info XD 

just reply here with any answer, even so much as to what progress you've made on the adding of Timings v2 :)

**Comment by xZeroMCPE** [comment]
Added a fork of it, should be working now.
