### ISSUE TITLE
Not an issue, want suggestion

### ISSUE THREAD

**Issue by Assblocker** [TesseractTeam/Tesseract#269]
#### Problem description

Which world format should i use for creating a new world now? Anvil or mcregion? Which will be the fastest and not buggy and supported?
#### OS and versions

* Tesseract:
* PHP:
* Server OS:
* Game version: 
* Server host:
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by AnkitM252** [comment]
I think the MCregion is deprecated, you should use Anvil!

**Comment by Nought57** [comment]
Tesseract supports only the world type of Anvil or PMAnvil. MCRegion have many bugs. (MCRegion support is deprecated.)
