### ISSUE TITLE
[POLL] Come back developer soul?

### ISSUE THREAD

**Issue by Nought57** [TesseractTeam/Tesseract#270]
#266 About comments at top of each php file.
A number of doubts came after watching this.

I think that erasing these is not good from the surroundings.
As if to decide these, AppleDevelops has reverted remotevase commit and Reply from members to remotevase Commit.

remotevase said "This is a part of an ongoing process by numerous developers to remove unneccesary comments in the code"
AppleDevelopers said "If you could add them back that'd be nice! Remotevase ruined it."
There is a disagreement in opinion even if these are seen.

I have no idea what is true.
So i decided to ask the user who is using Tesseract.
I will act on this basis.

These are very important things.
I think developer team logo is the only intention that the developer left behind.

Do you need the developer team logo at the top of each PHP file?
Thumbs up = yes (need it)
Thumbs down = no (not need it)

Thank you for your cooperation in the questionnaire.

**Comment by AnkitM252** [comment]
Added it back!
