### ISSUE TITLE
Low TPS

### ISSUE THREAD

**Issue by LagHD** [TesseractTeam/Tesseract#272]
This has been happening for a while now, I'm quite annoyed with it and so are my server players. The TPS seems to be really low and I can't change it, it's lagging the server and sometimes it crashes it
* Tesseract: Tesseract-1.1.0 Ruby
* PHP: 7.0.3
* Server OS: Android
* Game version: 1.0.3
* Server host: Pocket Server

#### Crashdump, backtrace, memory dumps, plugins list or other files

**Comment by AnkitM252** [comment]
You are hosting in android? Thats the thing causing lag/low tps or a plugins you are using should cause a lag too!

**Comment by LordJoshie** [comment]
yeah..... buddy, don't write an issue here, when the ONLY issue you have to post is that YOU can't manage a server. 

Your players should be annoyed you can't manage your server very well. 


I have 70 plugins, average 20-50 players, and I average between 20-17.5 tps... 18 is where you'll begin to notice a bit of lag. 

If you have plugins calling to old functions, like popup/tip, then you will probably get lag... like I used to...


Tesseract IS NOT the cause of YOUR lag issue.
