### ISSUE TITLE
Critical crash

### ISSUE THREAD

**Issue by Iktaniyalol** [TesseractTeam/Tesseract#273]
I have crash.
2017-02-17 [Tesseract] [14:56:25] CRITICAL> [Network] Stopped interface pocketmine\network\RakLibInterface due to Tried to save closed player
In crashdumps crashes no. Only in console. 
Why this happens after a while the server? Previously there was no such. Yes, and a friend the same problem. After this error, the server can not go, but it works.
* Tesseract: Latest
* PHP: 7.0
* Server OS: Linux
* Game version: 1.0.4
* Server host: -

**Comment by RTGDaCoder** [comment]
This simply means that your PORT that the server use to run is used by another server. This will enable the server but you will not able to run it, i'll confirm this anyways.

**Comment by Iktaniyalol** [comment]
Thank you! I think this is the case

**Comment by RTGDaCoder** [comment]
![1](https://cloud.githubusercontent.com/assets/20971020/23092448/15d216ea-f606-11e6-8297-bba576dd2e04.PNG)
![2](https://cloud.githubusercontent.com/assets/20971020/23092449/19c83c0c-f606-11e6-8256-5795c7e4ab83.PNG)

**Comment by Iktaniyalol** [comment]
I realized) Thank you)

**Comment by RTGDaCoder** [comment]
👍
