### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by erkam2002** [TesseractTeam/Tesseract#274]
#### Problem description

Crash on start up look at Crashdumb
#### Steps to reproduce the issue

Start server
#### OS and versions

* Tesseract: Newest
* PHP: 7.0.15
* Server OS: Debian 8.7
* Game version: 1.0.3
* Server host: Dedicated Root Server
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
*** Error in `Tesseract 1.1.0': double free or corruption (fasttop): 0x0000000001ef05b0 ***
```

**Comment by RTGDaCoder** [comment]
Hi! Would you mind sharing me your .phar file for further testing and also proving?
Thanks

**Comment by erkam2002** [comment]
I use the source from github directly

**Comment by RTGDaCoder** [comment]
Ok, I'll pull it from there and let you know ASAP.
