### ISSUE TITLE
ItemFrame drop an item error.

### ISSUE THREAD

**Issue by KennFatt** [TesseractTeam/Tesseract#278]
#### Problem description

Just try to drop an item from Item Frame, but the item is not dropped out. and i saw this message on console (read on my log below).

#### Steps to reproduce the issue

I dont know, i'll look it.

#### OS and versions

* Tesseract: latest (1.0.3)
* PHP: 7
* Server OS: Ubuntu
* Game version: 1.0.3
* Server host: Localhost
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
Notice: Uninitialized string offset: 6 in /home/kennan/Desktop/Tesseract-master/src/pocketmine/utils/BinaryStream.php on line 154

Notice: Uninitialized string offset: 6 in /home/kennan/Desktop/Tesseract-master/src/pocketmine/utils/BinaryStream.php on line 154

Notice: Uninitialized string offset: 6 in /home/kennan/Desktop/Tesseract-master/src/pocketmine/utils/BinaryStream.php on line 154
```

**Comment by LordJoshie** [comment]
Please review open/closed issues before posting a new issue. 
This issue has already been posted and is known about.

You're creating spam on the issue tracker. 

Please don't. 

Thank you.
