### ISSUE TITLE
slapper not working

### ISSUE THREAD

**Issue by Alanf22** [TesseractTeam/Tesseract#28]
Crashdump
Tesseract Crash Dump Mon Jun 19 16:23:34 CDT 2017

Error: Class pocketmine\network\mcpe\protocol\AddPlayerPacket not found
File: /src/spl/BaseClassLoader
Line: 144
Type: notice

THIS CRASH WAS CAUSED BY A PLUGIN

Code:
[135] 
[136] 			if(method_exists($name, "onClassLoaded") and (new ReflectionClass($name))->getMethod("onClassLoaded")->isStatic()){
[137] 				$name::onClassLoaded();
[138] 			}
[139] 			
[140] 			$this->classes[] = $name;
[141] 
[142] 			return true;
[143] 		}elseif($this->getParent() === null){
[144] 			throw new ClassNotFoundException("Class $name not found");
[145] 		}
[146] 
[147] 		return false;
[148] 	}
[149] 
[150] 	/**
[151] 	 * Returns the path for the class, if any
[152] 	 *
[153] 	 * @param string $name
[154] 	 *

Backtrace:
#0 /plugins/Slapper_v1.3.5.phar/src/slapper/entities/SlapperHuman(65): spl_autoload_call(string pocketmine\network\mcpe\protocol\AddPlayerPacket)
#1 /src/pocketmine/entity/Entity(1885): slapper\entities\SlapperHuman->spawnTo(pocketmine\Player Player(1))
#2 /src/pocketmine/level/format/Chunk(697): pocketmine\entity\Entity->spawnToAll(boolean)
#3 /src/pocketmine/level/Level(2751): pocketmine\level\format\Chunk->initChunk(pocketmine\level\Level object)
#4 /src/pocketmine/level/Level(2315): pocketmine\level\Level->loadChunk(integer -159, integer 46, boolean 1)
#5 /src/pocketmine/level/Level(2996): pocketmine\level\Level->getChunk(integer -159, integer 46, boolean 1)
#6 /src/pocketmine/Player(811): pocketmine\level\Level->populateChunk(integer -159, integer 46)
#7 /src/pocketmine/Player(1762): pocketmine\Player->sendNextChunk(boolean)
#8 /src/pocketmine/Server(2672): pocketmine\Player->checkNetwork(boolean)
#9 /src/pocketmine/Server(2390): pocketmine\Server->tick(boolean)
#10 /src/pocketmine/Server(2300): pocketmine\Server->tickProcessor(boolean)
#11 /src/pocketmine/Server(1861): pocketmine\Server->start(boolean)
#12 /src/pocketmine/PocketMine(468): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string C:\Users\Lhuar06\Documents\genisys\, string C:\Users\Lhuar06\Documents\genisys\, string C:\Users\Lhuar06\Documents\genisys\plugins\, string unknown)

Tesseract version: 0000000000000000000000000000000000000000 [Protocol 113; API 3.0.1]
uname -a: Windows NT 6.1 build 7601 (Windows 7 Ultimate Edition Service Pack 1) AMD64
PHP version: 7.0.17
Zend version: 3.0.0
OS : WINNT, win

**Comment by xZeroMCPE** [comment]
Slapper does not support tesseract. Request support at slapper's GitHub.
