### ISSUE TITLE
drops/pickup item glitch for android users. [EDIT] Blocklauncher Only

### ISSUE THREAD

**Issue by LordJoshie** [TesseractTeam/Tesseract#282]
You guys should know my setup is legit, I'm on the last posted release from the master repo.

Noticing when I just made a new character, and I've gone to go mining, I can't pickup items or see them.... only on my Android. ( I usually play on Win10 )

when I pick stuff up, it doesn't show on my android in my inventory. and when I logout, it drops it... 

Whats going on ? No errors in console.

[EDIT]

Actually, I've noticed this is only happening to pickup items when using BlockLauncher on my android... 
I can open vanilla MC, pick my items up, and carry on playing just normal. 

I think this is good, that my modified client is having issues, and vanilla isn't... however, what would be causing this ?

**Comment by KennFatt** [comment]
i'll confirm it

**Comment by xZeroMCPE** [comment]
Maybe block launcher is broken.

**Comment by xZeroMCPE** [comment]
If it works well on vanilla then it's not our job to fix BlockLauncher... 

Which is good... I hate block launcher!
