### ISSUE TITLE
Beacon is not breakable on Survival

### ISSUE THREAD

**Issue by KennFatt** [TesseractTeam/Tesseract#283]
#### Problem description

Players can't break Beacon on Survival.

#### Steps to reproduce the issue

Working fine on Creative.

#### OS and versions

* Tesseract: Latest (1.0.3)
* PHP: 7
* Server OS: Ubuntu
* Game version: 1.0.3
* Server host: Localhost
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

there is no information on log (console) but i try to debug using blockbreakevent and canceled is return to false (so is not about event canceled).
```
```

**Comment by ISRAPIL** [comment]
I'm, no... All good
