### ISSUE TITLE
multicraft bug

### ISSUE THREAD

**Issue by bzdnd** [TesseractTeam/Tesseract#285]
If you are use it on multicraft,When you start server OK,Multicraft is still in restart.
On the game,when you are use bow and arrow，the arrow is have a emerald.If you join the game,you will see a emerald under your foot.
Version:It support Minecraft1.0.4,Trsseat1.1.0
I am use linux.
PHP:7.0.13
I am come from china,So I often speak English with some wrong....
Please help me to fix them(๑• . •๑)

**Comment by bzdnd** [comment]
and then,sometimes I can't start server,It is very slowly.If you start server ok,after that,you cannot join server,But the server is ok.

**Comment by andris155** [comment]
I use Multicraft and works perfectly. This is not Tesseract bug.
