### ISSUE TITLE
Nether does not generate

### ISSUE THREAD

**Issue by lowingly** [TesseractTeam/Tesseract#286]
Tesseract-1.1.0（代号为“Ruby”）
PHP：7.0.9
Minecraft PE v1.0.3.0
Protocol version: 101
Windows 8 and Window Server 2008

tesseract.yml:
level-name: "nether" 
allow-nether: true

but "Nether" does not generate.
There is no “Nether” in worlds.

**Comment by xZeroMCPE** [comment]
Test it on latest commit.

**Comment by lowingly** [comment]
Sorry, I tested the newest one, but it still did not work. (I did not install any plugins, so it was not affected by the plugin). No Nether..     (T-T)

**Comment by AppleDevelops** [comment]
I'll work on it tonight

**Comment by lowingly** [comment]
Why close the problem, “nether” still can not be generated. If I put the nether map（create by Elywing ） into Tesseract, nether's sky is not red.....

**Comment by AppleDevelops** [comment]
Elywing < Tesseract

**Comment by AppleDevelops** [comment]
The nether generates on tesseract now

**Comment by lowingly** [comment]
I really can not generate ....

[*] Tesseract set-up wizard
[*] Please select a language:
 English => eng
 简体中文 => chs
 繁體中文 => zho
 日本語 => jpn
 Русский => rus
 Italiano => ita
 한국어 => kor
 Deutsch => deu
[?] Language (eng): chs
[*] 您现在选择了简体中文.
欢迎来到Tesseract!
在开始使用您的新服务器之前，您需要接受以下协议
Tesseract使用了LGPL协议，
你可以在这个文件夹中找到LICENCE文件。

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Lesser General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

[?] 您接受协议内容吗？ (y/N): y
[?] 您想跳过安装向导吗? (y/N): y
[Tesseract] [19:25:59] INFO>
###################################################  -- Loaded: Properties and Configura
#                                                 #    Date: Fri, February 24, 2017, 19:
#   _______                                _      #    Version: 1.1.0 Codename: Ruby
#  |__   __|                              | |     #    MCPE: v1.0.3.0
#     | | ___  ___ ___  ___ _ __ __ _  ___| |_    #    Port: 19132
#     | |/ _ \/ __/ __|/ _ \ '__/ _` |/ __| __|   #    Protocol: 101
#     | |  __/\__ \__ \  __/ | | (_| | (__| |_    #    SSL Extension: false
#     |_|\___||___/___/\___|_|  \__,_|\___|\__|   #    Authentication: offline mode/inse
#                                                 #  -----------------------------------
#                                                 #    API Version: 3.0.0
#     www.github.com/TesseractTeam/Tesseract      #    Language: eng
#                                                 #    Package: phar
###################################################  -----------------------------------
[Tesseract] [19:25:59] INFO> Everything seems to be alright. Server started!
[Tesseract] [19:26:00] INFO> Loading recipes...
[Tesseract] [19:26:00] WARNING> McRegion is deprecated please refrain from using it!
[Tesseract] [19:26:00] NOTICE> 无法找到 "world" 地图
[Tesseract] [19:26:00] INFO> 准备地图中... "world"
[Tesseract] [19:26:00] NOTICE> 正在于背景生成世界 “world“ 的地形
[Tesseract] [19:26:00] INFO> 启动 GS4 状态监听器
[Tesseract] [19:26:00] INFO> Query 运作在 0.0.0.0:19132
[Tesseract] [19:26:00] INFO> 预设的游戏类型：生存模式
[Tesseract] [19:26:00] INFO> Done (9.895s)！如需帮助，请输入 "help" 或 "?"

**Comment by AppleDevelops** [comment]
Use latest version and enable nether in config

**Comment by lowingly** [comment]
This is the latest version, I downloaded a few minutes ago. nether is true in configis......T-T!!

**Comment by lowingly** [comment]
I know the reason. If you choose English language, it will generate nether. Choose Chinese, no nether. You can try....

**Comment by AppleDevelops** [comment]
Oops sorry
