### ISSUE TITLE
Why the player's Minecraft display "generic reason" when I stop the server. I hope it is server close...

### ISSUE THREAD

**Issue by lowingly** [TesseractTeam/Tesseract#287]
Tesseract-1.1.0（代号为“Ruby”）
PHP：7.0.9
Minecraft PE v1.0.3.0
Protocol version: 101
Windows 8 and Window Server 2008

pocketmine.yml:
 #When server shut down, the players will get kicked and this is what will show on there screen.
 shutdown-message: "Server Close"

No matter what I change it.  It only display "generic reason".
Pmmp wrong or Tesseract question？
Maybe this is not a big question, but my players always ask me: Is the server broken？ when they see "generic reason".   QvQ...

**Comment by Nought57** [comment]
Although the possibility that the server is broken is unknown, can you check the symptoms even if you use the latest version? Detailed information on procedures is required.

**Comment by LordJoshie** [comment]
use custom alerts... set it to w.e you want

**Comment by LordJoshie** [comment]
or is it restartme ?

**Comment by LordJoshie** [comment]
both have a thing to set a message... I use these... I find my server only says Generic Reason when I use /kickall of my Essentials command. :P

**Comment by lowingly** [comment]
All right. After I deleted all of my plugins, the server will display "server close" when I type "stop" in the console. Maybe is the  plugin affecting the server, but I can not give up any of my plugins. So I will try to use the "custom alerts" plugin. I think my problem has been solved. Thank you~~

**Comment by LordJoshie** [comment]
Hey man, no worries m'dude.

Share a list of the pluggie and I can help you sort out the one giving you
weird messages.
