### ISSUE TITLE
[SUGGESTION] Please view. 

### ISSUE THREAD

**Issue by LordJoshie** [TesseractTeam/Tesseract#288]
Perhaps add a way to prevent, and include in the config a way to enable/disable text from being seen through blocks. 

I think if you ran a realistic server, this would be something you would like to have control over..whether or not floating text/name tags can be seen through blocks. 

If this is possible, I think would be a neat addition to the features Tesseract offers.

**Comment by ajthemacboy** [comment]
This isn't something that can be effectively accomplished on the serverside... if it's possible at all.

**Comment by Nought57** [comment]
Although it is possible, an increase in load is expected. There are also bug fixes, so it is unknown whether to add.

**Comment by Nought57** [comment]
Added Project List.
