### ISSUE TITLE
What this mean? 

### ISSUE THREAD

**Issue by KnightOfEnder** [TesseractTeam/Tesseract#289]
#### Problem description
I'm getting this on my console everytime someone logs in why it doing that ?

#### Steps to reproduce the issue
Use new simpleAuth 

#### OS and versions
Use the 'version' command in Tesseract.
If the version is invalid, the issue will be CLOSED and marked as spam! 
NOTE: If you are using WINDOWS 10 Edition, please remember to let us know!
--
* Tesseract: Crystal
* PHP: ?
* Server OS: ?
* Game version: 1.0.3
* Server host: android 
![screenshot_2017-02-20-13-48-31](https://cloud.githubusercontent.com/assets/24853541/23127695/dc9cceaa-f773-11e6-8be3-b13aed8732be.png)

<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by AnkitM252** [comment]
This is a plugin issue! You know that it is the plugin issue and telling us to fix it for you. Make a issue on the SimpleAuth repo not here! This is a server software!

**Comment by KnightOfEnder** [comment]
Cause they never reply plus it say report bugs on github

**Comment by AnkitM252** [comment]
They say report bugs on github but on their repo not the server software!
