### ISSUE TITLE
Lag!

### ISSUE THREAD

**Issue by MrSmileCH** [TesseractTeam/Tesseract#29]
Issue description

There is a very noticeable small lag in version 1.1.0.55 when doing a versus in pvp with another player

Steps to reproduce the issue

I found in my server 10 gb of ram with 85 players and with 40 minutes of restart in 1.0.9 I did not have that problem, now at 5 minutes after the restart the server starts to have lag, it needs an optimization To the version, so that it goes well as 1.0.9

OS and versions

Tested in win10, server version 1.1.0.55

![sin titulo](https://user-images.githubusercontent.com/27845246/27313018-4e832986-5531-11e7-9ff9-d2c6edf6aa0a.png)

**Comment by xZeroMCPE** [comment]
Do a timings report. And send us the link.

**Comment by SuperKali** [comment]
use /status command and send screen

**Comment by SuperKali** [comment]
This problem clashes with my server

**Comment by MrSmileCH** [comment]
![sin titulo](https://user-images.githubusercontent.com/27845246/27341395-c7cfa488-55a2-11e7-9b41-738a9e1d9a42.png)
![sin titulo1](https://user-images.githubusercontent.com/27845246/27341405-ccc03eee-55a2-11e7-8d6e-140eca0ac9eb.png)

**Comment by xZeroMCPE** [comment]
Do /timings on  then wait like 5 minute then use /timings paste then screenshot the screen and upload it here

**Comment by MrSmileCH** [comment]
![sin titulo](https://user-images.githubusercontent.com/27845246/27346044-7ab83ebc-55b1-11e7-9e64-896e80a714ea.png)

**Comment by xZeroMCPE** [comment]
Seems like this plugin is causing major TPS drop:

- Skywars v5.0   / 23.57%

Likely to be wrongly coded. Contact the developer. If I were you, I'd try removing that plugin above and do another timing and compare the speed before and after.

**Comment by MrSmileCH** [comment]
This plugin used it in the previous version 1.0.9 and did not cause some type of problems

**Comment by MrSmileCH** [comment]
This plugin used it in the previous version 1.0.9 and did not cause some type of problems

**Comment by xZeroMCPE** [comment]
Your experiencing TPS lag.
