### ISSUE TITLE
Void generator not work

### ISSUE THREAD

**Issue by erkam2002** [TesseractTeam/Tesseract#290]

**Comment by LordJoshie** [comment]
my dude... to create an empty world.... if you use ManyWorlds, which I'm sure you do... 

/mw create (name) flat flat flat 

You're welcome... it generates void world.

**Comment by erkam2002** [comment]
ok..

In genisys need i to wirte /mw create (name) 0 void

**Comment by LordJoshie** [comment]
Nope, should be the same as I mentioned on all servers.... as far as Im
aware.
