### ISSUE TITLE
Beacon NOT DELETE ITEM IF YOU CHECK EFFECT AND SET OK!

### ISSUE THREAD

**Issue by NycuRO** [TesseractTeam/Tesseract#291]
#### Steps to reproduce the issue

If you put one item in beacon:
- select effect -> WORK
- add diamond/iron ingot/gold ingot -> WORK
- SET OK EFFECT. -> Work, and get effect.
- Close Inventory -> Effect's work, but diamond, or other IS DROPPED LIKE ENCHANTMENT. ( And effects works )
#### OS and versions

* Tesseract: https://github.com/TesseractTeam/Tesseract/commit/c516fbaf3251477d0cc10363933c9133bef01f0b
* PHP: 7.0.14
* Server OS: Ubuntuu 14.04.5 64BIT 
* Game version:  1.0.3
* Server host: gazduirejocuri.ro
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by LordJoshie** [comment]
Guy.... DONT TYPE YOUR HEADLINE OF THE ISSUE IN ALL CAPPS ITS TOTALLY ANNOYING.

**Comment by NycuRO** [comment]
@xZeroMCPE Why close?

**Comment by AnkitM252** [comment]
Cause you didn't explained the issue!

**Comment by NycuRO** [comment]
@AnkitM252 Open now.

**Comment by AppleDevelops** [comment]
We've removed beacon functionality until we're finished with some of the major issues.
