### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by NycuRO** [TesseractTeam/Tesseract#293]
#### Problem description

 ./start.sh
Failed loading /root/compile/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so:  /root/compile/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so: cannot open shared object file: No such file or directory
Warning: yaml_parse(): reading error encountered during parsing: invalid leading UTF-8 octet (line 1, column 1) in phar:///root/fac/Tesseract.phar/src/pocketmine/utils/Config.php on line 140

This bug created auto-save = off .
If is php problem ,anyone can give me one link with other?
#### Steps to reproduce the issue

Start server
#### OS and versions

* Tesseract: https://github.com/TesseractTeam/Tesseract/commit/bc6ef2a20ceb3db9cf18e5f70c8442041c83e29a
* PHP: 
https://dl.bintray.com/pocketmine/PocketMine/:PHP_7.0.6_x86-64_Linux.tar.gz
* Server OS: Ubuntuu 14.04.5 LTS 64bit
* Game version: 1.0.3
* Server host: gazduirejocuri.ro
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by xZeroMCPE** [comment]
Still happens on the latest commit?

**Comment by AppleDevelops** [comment]
@xZeroMCPE I got this

**Comment by AppleDevelops** [comment]
The first one is a problem with the php binaries, which we don't provide support for, and the second one is a plugin issue which we do not provide support for.

**Comment by NycuRO** [comment]
@AppleDevelops You can give me one link with php binaries?
