### ISSUE TITLE
addItem() dont work properly

### ISSUE THREAD

**Issue by Driesboy** [TesseractTeam/Tesseract#295]
#### Problem description

if you add 2 things with addItem() only the first or noting will display
if you tap with that index on the ground the item will display

#### Steps to reproduce the issue

^
#### OS and versions

* Tesseract: 1ebf2c6
* PHP: 7.0.13
* Server OS: Mac Osx
* Game version: 1.0.3
* Server host: Myself
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by EpicSteve33** [comment]
Send Inventory contents to the player

**Comment by Driesboy** [comment]
and than it works??

**Comment by Driesboy** [comment]
**$p->getInventory()->addItem(Item::get(261,0,1));
		   $p->getInventory()->addItem(Item::get(262,0,10));
		   $p->getInventory()->sendContents($p);`**

**Comment by EpicSteve33** [comment]
I have not tested it but I had this issue with `setItem()` so i added `sendContents()` after it and it worked after that

**Comment by xZeroMCPE** [comment]
Seems to be working for me....

**Comment by Driesboy** [comment]
Yes with sendcontent

Op 6-mrt.-2017 07:16 schreef "Andre | xZeroMCPE" <notifications@github.com>:
