### ISSUE TITLE
Close this as soon as it's answered please. :) <3

### ISSUE THREAD

**Issue by LordJoshie** [TesseractTeam/Tesseract#296]
....okay, I edit my original writing here... wasn't the world I was suspicious of. was actually the nether... 

I was flying in nether, then it didn't load, and it crashed... when I'd login, kept crashing. 

I disabled the nether, and deleted the world.

Tesseract Crash Dump Wed Feb 22 21:48:09 CST 2017

Error: Invalid subchunk index 8!
File: /src/pocketmine/level/format/Chunk
Line: 108
Type: notice

Code:
[99] 		$this->x = $chunkX;
[100] 		$this->z = $chunkZ;
[101] 
[102] 		$this->height = $provider !== null ? ($provider->getWorldHeight() >> 4) : 16;
[103] 
[104] 		$this->emptySubChunk = new EmptySubChunk();
[105] 
[106] 		foreach($subChunks as $y => $subChunk){
[107] 			if($y < 0 or $y >= $this->height){
[108] 				throw new ChunkException("Invalid subchunk index $y!");
[109] 			}
[110] 			if($subChunk->isEmpty()){
[111] 				$this->subChunks[$y] = $this->emptySubChunk;
[112] 			}else{
[113] 				$this->subChunks[$y] = $subChunk;
[114] 			}
[115] 		}
[116] 
[117] 		for($i = 0; $i < $this->height; ++$i){
[118] 			if(!isset($this->subChunks[$i])){

Backtrace:
#0 /src/pocketmine/level/generator/PopulationTask(169): pocketmine\level\format\Chunk::fastDeserialize(NULL , pocketmine\level\format\io\region\McRegion object)
#1 /src/pocketmine/scheduler/AsyncPool(151): pocketmine\level\generator\PopulationTask->onCompletion(pocketmine\Server object)
#2 /src/pocketmine/scheduler/ServerScheduler(252): pocketmine\scheduler\AsyncPool->collectTasks(boolean)
#3 /src/pocketmine/Server(2654): pocketmine\scheduler\ServerScheduler->mainThreadHeartbeat(integer 7048)
#4 /src/pocketmine/Server(2378): pocketmine\Server->tick(boolean)
#5 /src/pocketmine/Server(2288): pocketmine\Server->tickProcessor(boolean)
#6 /src/pocketmine/Server(1849): pocketmine\Server->start(boolean)
#7 /src/pocketmine/PocketMine(469): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string /home/console/Desktop/v2/, string /home/console/Desktop/v2/, string /home/console/Desktop/v2/plugins/, string unknown)

Tesseract version: 0000000000000000000000000000000000000000 [Protocol 101; API 3.0.0]
uname -a: Linux vpsgeneric #22-Ubuntu SMP Fri Nov 6 18:25:50 UTC 2015 x86_64
PHP version: 7.0.2
Zend version: 3.0.0
OS : Linux, linux

Server uptime: 5 minutes 57 seconds
Number of loaded worlds: 7
Players online: 22/75

**Comment by Nought57** [comment]
Are you using MCRegion's world type?

**Comment by LordJoshie** [comment]
Nought.... if you have some kind of special permission to manage issues here, then you should learn how to read. 


dunno how well this will work..but... look here ----------------------------------------------now down--v


Backtrace:
#0 /src/pocketmine/level/generator/PopulationTask(169): pocketmine\level\format\Chunk::fastDeserialize(NULL , pocketmine\level\format\io\region\McRegion object)

**Comment by Nought57** [comment]
I confirmed that and asked a question.
It is clearly stated that the world type of MCRegion is not supported.

**Comment by LordJoshie** [comment]
Cant you guys see the edits I make to my comments here ?

Thought you'd see my previous edit where I said I knew McRegion wasn't
supported... but I was just asking for help.

no worries. close the issue. u answ....well, actually you didn't, but
hey... least


actually nothing. nvm.

xD just close the issue.

I already disabled nether on my server for now, as that's what was causing
it. new terrain not generating in that level.

Thanks for your help!

**Comment by Nought57** [comment]
"new terrain not generating in that level"
This needs to be fixed. As it is valid information, please keep this issues open.

**Comment by LordJoshie** [comment]
This issue*  one, not plural.

And yeah, sure...that's your call. you control the opening and closing.

I just post my findings, since I'm an active owner with an active
server.... and prefer host off the best utencil of pmmp out there.

so yeh.

but, McRegion / the nether world on my server.

I'm too stupid to know the difference... I thought it was my spawn world (a
void world) at first... thankfully I flew around the nether, world wasn't
generating, then server crashed, and I'd rejoin just to keep causing the
crash... deleted nether, and disabled it in tesseract.yml and wallah...
servers fine again.

:)


LordJoshie, solvong issues by deleting them rather than fixing. xD
