### ISSUE TITLE
Minecarts/Rails are bugging at placing

### ISSUE THREAD

**Issue by sero583** [TesseractTeam/Tesseract#298]
#### Problem description
When placing a Minecart/Rail (I'm not sure which it was), those messages came (I did it more than once so don't wonder why the message's are soo much)

#### Steps to reproduce the issue
Use one of both (Minecart or Rail, not sure which..)

#### OS and versions
[Tesseract] [08:47:34] INFO> -----Server information-----
[Tesseract] [08:47:34] INFO> This server is running Tesseract-1.1.0 Ruby
[Tesseract] [08:47:34] INFO> PHP version: 7.0.3
[Tesseract] [08:47:34] INFO> API: 3.0.0
[Tesseract] [08:47:34] INFO> Target client: Minecraft PE v1.0.3.0
[Tesseract] [08:47:34] INFO> Protocol version: 101
* Server OS: Ubuntu 16.04.1
* Game version: /
* Server host: my own server
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
The messages:
"
[Tesseract] [08:44:35] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [08:44:35] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [08:44:35] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [08:44:35] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [08:44:35] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [08:44:35] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [08:44:36] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [08:44:36] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [08:44:36] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [08:44:36] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [08:44:58] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [08:44:58] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [08:44:58] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [08:44:59] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [08:44:59] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [08:44:59] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [08:44:59] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [08:44:59] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [08:44:59] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [08:44:59] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
"
```

**Comment by sero583** [comment]
By the way minecarts aren't anymore floating, but they arent proper on the rail + and when breaking the rail they go down into the ground

**Comment by sero583** [comment]
+ player cant move the minecart around

**Comment by Nought57** [comment]
Redstone relation is incomplete. I'm ongoing to fix those bugs.

**Comment by ISRAPIL** [comment]
https://github.com/ISRAPIL/FastCorePE/commit/02c0641992f7ffd2a2d0c434b06be0cb333fb765

Сheck it

**Comment by sero583** [comment]
Why is the constant value set to zero? @ISRAPIL

**Comment by ISRAPIL** [comment]
This direction, and it is implemented in the core in one direction @sero583

**Comment by sero583** [comment]
@ISRAPIL No no, you got me wrong. It could be also Integer 1, 2 or whatever; my question was, why it is Integer 0?

**Comment by ISRAPIL** [comment]
I have explained to you, but my bad english. @sero583

**Comment by ISRAPIL** [comment]
That's right. I sent all sides and looked @sero583

**Comment by DobberHockeyCom** [comment]
The minecart now rests on the rails (no longer floats), however players cannot ride in it. Also, the redstone does not activate the powered rails.

**Comment by sero583** [comment]
The minecarts should be atleast moveable

**Comment by AnkitM252** [comment]
Minecarts uses Redstone which is not implemented into Tesseract! The spawm bug has already been fixed! So closing this issue

**Comment by sero583** [comment]
@AnkitM252 Ehm not really, basic features like driving them isn't made with redstone. Do you use a lever to ride it? I guess not.

**Comment by AnkitM252** [comment]
You can't even ride?

**Comment by sero583** [comment]
@AnkitM252 Ofcourse you can ride the minecarts? Minecarts and normal rails are something else then detector rails fyi.

**Comment by AnkitM252** [comment]
Just tell the answer!

**Comment by sero583** [comment]
@AnkitM252 What I have been asked for? If thats the answer: The fact stays, the last time I used tesseract I were able to ride a minecart and I think thats still possible.

**Comment by AnkitM252** [comment]
Whats the main thing of this issue now?

**Comment by sero583** [comment]
@AnkitM252 the main thing isn't even solved the main thing is that when you place it they float very weird, thats first. 2nd adding a feature which makes pushing entitys around would be good though (also "frozen" [aka immobile] entitys)

**Comment by AnkitM252** [comment]
Gonna check them and try to fix it!

**Comment by sero583** [comment]
@AnkitM252 It's not a fix I think it was never implemented in any software (also meant it's forks like this one) of PocketMine. Well i've seen it sometimes I think you should add that on Entity collison.
