### ISSUE TITLE
Tesseract Raklib crash May or May not be Caused By WingProxy

### ISSUE THREAD

**Issue by Pogogo007** [TesseractTeam/Tesseract#30]
I tried running tesseract from source mulitple times all the times the raklib crashed.
Tried modifying ports nothing changed
This is most likely caused by WingProxy
Running Linux Debian 8
Tesseract Latest 0.16

**Comment by Pogogo007** [comment]
This may or may not happen when using a phar idk not tested

**Comment by IISweePII** [comment]
I'll remove wingproxy from my local servers src when I get back and see if a raklib error happens

**Comment by Pogogo007** [comment]
Mk

**Comment by IISweePII** [comment]
I'll also update my src as well since it could be a few days worth of commits behind, since then I never noticed a raklib error there

**Comment by Pogogo007** [comment]
Ok

**Comment by Pogogo007** [comment]
Found it fixing

**Comment by Pogogo007** [comment]
Fixed Closing.
