### ISSUE TITLE
"You need to authenticate to Xbox Live."

### ISSUE THREAD

**Issue by LeeTheENTP** [TesseractTeam/Tesseract#300]
#### Problem description
Tesseract running in online mode disallows connections from users signed in with Xbox Live. I've forwarded port 3074 for Xbox Live services and made an exception in the server's firewall.

#### Steps to reproduce the issue
Set up a Tesseract server with online mode enabled, and connect to it with an Xbox Live-authenticated account.

#### OS and versions

* Tesseract: 1.1.0
* PHP: 3.0.0
* Server OS: WS 2016
* Game version: 1.0.3
* Server host: Home computer
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files
N/A
```
```

**Comment by LeeTheENTP** [comment]
Is this being worked on?

**Comment by Atoman03** [comment]
I have the same problem where it says "You need to authenticate with Xbox Live."

**Comment by AppleDevelops** [comment]
I just logged in on my xbox account with online-mode set to on

**Comment by LeeTheENTP** [comment]
@AppleDevelops I would like to re-test on the latest build, but the link to download the PHAR is broken.

https://github.com/TesseractTeam/Tesseract/wiki/Installation-on-Windows

**Comment by AppleDevelops** [comment]
You can run it as src.

**Comment by LeeTheENTP** [comment]
@AppleDevelops How would I go about doing that? Bear in mind I know next to nothing about PHP.

**Comment by RocoWayne** [comment]
Change to false the online mode in server.propierties

**Comment by LeeTheENTP** [comment]
@RocoWayne If I was content in running without authentication, I would have not opened this issue.

**Comment by LeeTheENTP** [comment]
The problem persists in the latest version of Tesseract: http://i.imgur.com/Lry3bOS.jpg

**Comment by AnkitM252** [comment]
@LeeTheENTP Can't you see the `Authentication mode: Offline mode/insecure` line! Also can be the php binaries, You need a SSL Extension included binaries (Not sure of it! Gonna check and Edit)

**Comment by LeeTheENTP** [comment]
@AnkitM252 I assumed that it wasn't reading the server.properties file properly, because the online status I set in server.properties was what took effect.

Unfortunately, there is no documentation regarding authentication for Tesseract. In fact, this short list comprises the entire documentation for installation: https://i.gyazo.com/f8ae4a46575730239b359055c46d0ddf.png

There is no readme; there is merely a license file that is a copy of the GNU LGPL.

So, I want to thank you for directing me to the Genisys page, as updating the PHP binaries has solved the issue.

**Comment by AnkitM252** [comment]
We will add the Wiki page soon!
