### ISSUE TITLE
Class pocketmine\block\Enchantment not found

### ISSUE THREAD

**Issue by Driesboy** [TesseractTeam/Tesseract#302]
#### Problem description

Could not tick level "Paris": Class pocketmine\block\Enchantment not found

#### Steps to reproduce the issue

tap on a enchantment table

#### OS and versions

* Tesseract: a16c90f
* PHP: 7.0.15
* Server OS: Windows
* Game version: 1.0.3
* Server host: My Self
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
Could not tick level "Paris": Class pocketmine\block\Enchantment not found
```

**Comment by ISRAPIL** [comment]
https://github.com/ISRAPIL/FastCorePE/commit/323ec89c795d4c0b4c93630d7744b172872cd7ca

**Comment by Driesboy** [comment]
nice
