### ISSUE TITLE
Primitive world, no mineral, only stone.

### ISSUE THREAD

**Issue by lowingly** [TesseractTeam/Tesseract#306]
Create a new world, then mining, or use cheating props. You will find no minerals......only stone
The latest version.

**Comment by lowingly** [comment]
and when I start the server...
Everything is ok, but these tips are not the same as before ... a little strange?
Maybe this is not a problem. I just feel strange.
For example: no longer show the information generated by the new world

[Tesseract] [17:14:18] INFO> Everything seems to be alright. Server started!
[Tesseract] [17:14:19] INFO> Loading recipes...
[Tesseract] [17:14:19] WARNING> McRegion is deprecated please refrain from using it!
[Tesseract] [17:14:19] INFO> pocketmine.level.preparing
[Tesseract] [17:14:19] INFO> pocketmine.level.preparing
[Tesseract] [17:14:19] INFO> pocketmine.server.query.start
[Tesseract] [17:14:19] INFO> pocketmine.server.query.running
[Tesseract] [17:14:19] INFO> pocketmine.server.defaultGameMode
[Tesseract] [17:14:19] INFO> pocketmine.server.startFinished

**Comment by LordJoshie** [comment]
some language files are left out of the latest branch I guess ? 

you know how to check this on your own ? ... compare. 

Also, the latest commits have been by Apple adding the newest API from PocketMine....and PocketMine doesn't, by default, have these language files in their main src file... 

So chill out, learn something new, go explore the web a little, and close this issue at your own leisure when you've solved your own simple problem :) 


Or, go back to a previous version until this is resolved :)

**Comment by erkam2002** [comment]
Was me too 
````
[Tesseract] [11:30:57] INFO> pocketmine.server.query.start
[Tesseract] [11:30:57] INFO> pocketmine.server.query.running
[Tesseract] [11:30:57] INFO> pocketmine.server.defaultGameMode
[Tesseract] [11:30:57] INFO> pocketmine.server.startFinished
```

**Comment by LordJoshie** [comment]
click this

https://github.com/TesseractTeam/Tesseract/tree/master/src/pocketmine/lang

click the locale @ 0951719 , download the folder, and copy these files to their directory.
src/pocketmine/lang/

**Comment by LordJoshie** [comment]
Nice labels Nought ! 

Cool helpful response :)

**Comment by xZeroMCPE** [comment]
Follow issue template....
