### ISSUE TITLE
Synapse no longer work..

### ISSUE THREAD

**Issue by erkam2002** [TesseractTeam/Tesseract#308]
#### Problem description

SynapseTransfer cannot be enabled
#### Steps to reproduce the issue

Use SynapseTransfer plugin
#### OS and versions

* Tesseract: https://github.com/TesseractTeam/Tesseract/tree/01b3e8272e85ea3680e4066aacb65ab67b2016ba
* PHP: 7.0.15
* Server OS: Debian 8
* Game version: 1.0.3
* Server host: Root Server
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
INFO> Enabling SynapseTransfer v1.0.0
[Tesseract] [11:30:57] CRITICAL> Error: "Call to undefined method pocketmine\Server::isSynapseEnabled()" (EXCEPTION) in "/plugins/SynapseTransfer-master/src/synapsetransfer/SynapseTransfer" at line 39
[Tesseract] [11:30:57] INFO> Disabling SynapseTransfer v1.0.0
[Tesseract] [11:30:57] INFO> [SynapseTransfer] Synapse Transfer has been disabled.
```

**Comment by LordJoshie** [comment]
Synapse not needed. 

Software has /transfer (ip) (port)  built in

**Comment by erkam2002** [comment]
But i need a proxy
Proxy is better

**Comment by LordJoshie** [comment]
use something like taptodo, and use the %op variable in your command for players to teleport. 

or I believe doing having the command   'as {player} trasnfer (ip) (port)' works to.

**Comment by LordJoshie** [comment]
proxy isn't better. lol what makes you think that ?

**Comment by erkam2002** [comment]
And language files are broken if i write in chat chat.type. blabla

**Comment by erkam2002** [comment]
With proxy you can manage players

**Comment by erkam2002** [comment]
And with /transfer from mojang is your client freezing for 3-6 secounds

**Comment by LordJoshie** [comment]
I don't see how thats an issue... do you host on Windows, or did they ever fix the epic lag with Synapse on Linux ? 

Also... the language file thing is an easy fix, get the files and add them to your folder. 

I don't know what difference there is besides the proxy having the function to show players of another server, while on one.

**Comment by LordJoshie** [comment]
click this 

https://github.com/TesseractTeam/Tesseract/tree/master/src/pocketmine/lang

click the @locale , download the folder, and copy these files to their directory. 

novice :P

**Comment by AppleDevelops** [comment]
Synapse doesn't even support 1.0.3

**Comment by erkam2002** [comment]
I sued it... in 1.0.3 but the newest version is not compatiple with synapse

**Comment by SleepSpace9** [comment]
@erkam2002 You have to use the Synapse methods directly from SynapsePM plugin because they are no longer in the server core. SynapseTransfer plugin has to be updated.
