### ISSUE TITLE
FIX BUG PLEASE

### ISSUE THREAD

**Issue by SerezhaIvanov** [TesseractTeam/Tesseract#31]
#### Issue description

When i join in the server mcpe crashes.
#### Steps to reproduce the issue

Join the server
#### OS and versions

* Tesseract: 1.2.0 Ruby
* PHP: 7.0.3
* Server OS: Ubuntu
* Game version: 1.1.0

#### Crashdump, backtrace, memory dumps, plugins list or other files (or screenshot of console)

No errors

Tesseract > Player data not found for "serezhaivanov", creating new profile
Tesseract > SerezhaIvanov[/92.115.87.212:15853] [ClientID: -1654573155021342146] logged in with entity id 1 at (danya, -27, 68, -63)
Tesseract > SerezhaIvanov joined the game
Tesseract > SerezhaIvanov left the game
Tesseract > SerezhaIvanov[/92.115.87.212:15853] logged out due to timeout

**Comment by Alanf22** [comment]
What plugins are you using?

**Comment by SerezhaIvanov** [comment]
Tesseract > Plugins (6): EconomyAPI v2.0.9, Casino_by_SerezhaIvanov v1, WorldGuardian v2.0, PurePerms v1.4.0-INDEV, Clans v1.3.7, Ch
t v1

**Comment by Alanf22** [comment]
Disable the pureperms plugin and test

**Comment by SerezhaIvanov** [comment]
Hmmm, i disable PurePerms and i can join the server, what is problem?

**Comment by Alanf22** [comment]
Pureperms does not support tesseract only pocketmine, but previous versions of pureperms work perfectly in tesseract
