### ISSUE TITLE
RakLib error in Travis CI

### ISSUE THREAD

**Issue by IISweePII** [TesseractTeam/Tesseract#31]
#### Problem description
Looking at the job logs for each commit in Travis, I noticed there is a sudden raklib error that is present. It still does manage to load the world and build the phar, I wonder why the raklib thingy happened

#### Steps to reproduce the issue
Look at any recent commits (from 1-3 days ago)

**Comment by Pogogo007** [comment]
#30

**Comment by IISweePII** [comment]
@Pogogo007 hmm, this is now getting a little interesting, I think it could be WingProxy since that was implemented

**Comment by Pogogo007** [comment]
@IISweePII yes i think too

**Comment by Pogogo007** [comment]
@IISweePII maybe try removing WingProxy in a test branch

**Comment by IISweePII** [comment]
@Pogogo007 I guess WingProxy needs some work before being fully implemented, ill see if apple can make a separate wingproxy branch and remove it from the main and keep it in the new branch until it is fully working

**Comment by Pogogo007** [comment]
Closing this issue and moving to issue #30

**Comment by IISweePII** [comment]
@Pogogo007 alrighty
