### ISSUE TITLE
Translation issue

### ISSUE THREAD

**Issue by ScandiePlay** [TesseractTeam/Tesseract#310]
#### Problem description

Wanted to install Tesseract on Windows - got a problem.
![scr](https://cloud.githubusercontent.com/assets/17462298/23343006/d26d5faa-fc6c-11e6-952f-e0e2b3640153.png)

#### Steps to reproduce the issue

Just try to launch the server on Windows 10 and see the console.

#### OS and versions

* Tesseract: 43rd build from Jenkins
* PHP: 7
* Server OS: Windows 10
* Game version: 1.0.3
* Server host: my PC
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by erkam2002** [comment]
Put this in pocketmine\lang\locale
https://github.com/TesseractTeam/Tesseract-Lang/archive/master.zip

**Comment by ScandiePlay** [comment]
@erkam2002 , thanks, I'll try.
