### ISSUE TITLE
Error.

### ISSUE THREAD

**Issue by NycuRO** [TesseractTeam/Tesseract#311]
Warning: assert(): Unhandled player action 14 from xXGeorgeXDRo failed in phar:///root/fac/Tesseract_1.1.0_2017-02-24_06-15-02.phar/src/pocketmine/Player.php on line 2763

Sorry but i don't use versions and bla bla, but not need.

**Comment by Driesboy** [comment]
i have this already 20 days

**Comment by NycuRO** [comment]
lol xD.

I need PocketMine better :(

**Comment by AppleDevelops** [comment]
Are the players trying to do something that isn't implemented?

**Comment by AppleDevelops** [comment]
The version is 100% necessary because I have no idea which branch you are using.

**Comment by xZeroMCPE** [comment]
Follow issue template....
