### ISSUE TITLE
Plugin loader error. 

### ISSUE THREAD

**Issue by Tolo0** [TesseractTeam/Tesseract#313]
#### Problem description

No plugins load

#### Steps to reproduce the issue

start the server
#### OS and versions

* Tesseract: Version: 1.1.0 Codename: Ruby
* PHP:
* Server OS: Ubuntu 
* Game version: android 
* Server host: none
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
Tesseract] [15:33:51] ERROR> pocketmine.plugin.loadError
```

**Comment by AppleDevelops** [comment]
Plugin issue
