### ISSUE TITLE
Message issue

### ISSUE THREAD

**Issue by GlacierShard92** [TesseractTeam/Tesseract#315]
#### Problem description
Messages such as chat messages (enter anything) come out as "chat.type.text"

#### Steps to reproduce the issue
Type in chat

#### OS and versions
* Tesseract: Ruby 1.1.0
* PHP: 7
* Server OS: Windows 10
* Game version: 1.0.3
* Server host: Home PC
* Game OS: PE/WIN10
#### Crashdump, backtrace, memory dumps, plugins list or other files
- No plugins
Some chat examples (from console):
[Tesseract] [21:39:29] INFO> pocketmine.level.preparing
[Tesseract] [21:39:29] INFO> pocketmine.level.preparing
[Tesseract] [21:39:29] INFO> pocketmine.server.query.start
[Tesseract] [21:39:29] INFO> pocketmine.server.query.running
[Tesseract] [21:39:29] INFO> pocketmine.server.defaultGameMode
[Tesseract] [21:39:29] INFO> pocketmine.server.startFinished

**Comment by GlacierShard92** [comment]
Found the issue - It's in API 3.0.1, I got a API 3.0.0 build from jenkins to fix it.

**Comment by Nought57** [comment]
I confirm it, currently conducting inspections. I will correct it as soon as confirmation is over. Please wait until the correction.

**Comment by xZeroMCPE** [comment]
@Nought57 Add back the languages files to /lang

it's the main cause of this error, I've told apple this but he has not done it.

**Comment by Nought57** [comment]
@xZeroMCPE I know. but, Items not used were included. I created a corresponding lang file there.
