### ISSUE TITLE
When players with donate joining server freezing

### ISSUE THREAD

**Issue by ivan691** [TesseractTeam/Tesseract#316]
Chto za huynya blyat??
I'm tryed all PurePerms versions.. this bug appeared when i make wipe on server
But i and simple players can play
I know this can be not tess bug but can you help me? I haven't bad plugins, i'm check all.

**Comment by ISRAPIL** [comment]
Был такой же баг... Недавно... @ivan691

**Comment by Bruno99** [comment]
Рок, еее!
