### ISSUE TITLE
Error on Ban

### ISSUE THREAD

**Issue by NycuRO** [TesseractTeam/Tesseract#318]
#### Steps to reproduce the issue

[Tesseract] [19:43:59] INFO> An unknown error occurred while attempting to perform this command
[Tesseract] [19:43:59] CRITICAL> Unhandled exception executing command 'ban KingPvP5' in ban: Call to a member function kick() on string
[Tesseract] [19:43:59] CRITICAL> Error: "Call to a member function kick() on string" (EXCEPTION) in "/src/pocketmine/permission/BanList" at line 108
#### OS and versions

* Tesseract: https://github.com/TesseractTeam/Tesseract/commit/acd0f720a07e265b5c05b1df6fe6178fbb15194a
* PHP: 7.0.14
* Server OS: Ubuntuu 14.04.5 LTS 64bit
* Game version:  1.0.3
* Server host: gazduirejocuri.ro
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by AnkitM252** [comment]
You banned the player when he was offline?

**Comment by NycuRO** [comment]
No. Online.
