### ISSUE TITLE
erors from a minecart

### ISSUE THREAD

**Issue by caspervanneck** [TesseractTeam/Tesseract#320]
#### Problem description

if i go in of minecart than i get spam erors

#### Steps to reproduce the issue

go in a mi4ecar and get spam
#### OS and versions

* Tesseract:
* PHP:7.0.15
* Server OS: windows 10
* Game version: 1.0.3 (pe and windows 10)
* Server host:
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files
[Tesseract] [12:06:58] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [12:06:59] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [12:06:59] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [12:06:59] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [12:06:59] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [12:06:59] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [12:06:59] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [12:06:59] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [12:06:59] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [12:06:59] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [12:06:59] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [12:07:00] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [12:07:00] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [12:07:00] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [12:07:00] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [12:07:00] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [12:07:00] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [12:07:00] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [12:07:00] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [12:07:00] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [12:07:00] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [12:07:01] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [12:07:01] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [12:07:01] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [12:07:01] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [12:07:01] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [12:07:01] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [12:07:01] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [12:07:01] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [12:07:01] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'
[Tesseract] [12:07:01] CRITICAL> Could not tick level "world": Undefined class constant 'STRAIGHT_NORTH_SOUTH'

```
```

**Comment by MalakasPlayzMC** [comment]
The word error has double r

**Comment by Nought57** [comment]
#298 Please check this issues. These are similar contents.
