### ISSUE TITLE
Missing noteblock sound

### ISSUE THREAD

**Issue by MalakasPlayzMC** [TesseractTeam/Tesseract#321]
**Problem description:**

When I tap a noteblock I don't get the noteblock sound. I have double-checked that my sound was on (in-game and in my tablet)

**Steps to reproduce the issue:**

Tap a noteblock

**OS and versions:**

Tesseract: Tesseract-1.1.0 Ruby
PHP: 7.0.9
Server OS: I tried from my Toshiba PC and my Lenovo Tablet and from server.pro (same result)
Game version: Minecraft PE 1.0.3 on a Lenovo Tablet
Server host: server.pro

**Crashdump, backtrace, memory dumps, plugins list or other files:**

Plugins (51): ParticlesPlus v0.0.2, BloodFX v1.1.0, PocketVote v1.2.0, MSpawns v1.4, MegaBan v1.2.2, Translator v1, ColorfulArmor v1, aParticles v1.1.0, ServerAuth v2.13, GunShop v0.1, ZipPluginLoader v1.1.3, ServerKits v1.3, MoreCommands v1.1.4, VipParticle v1.0.1, PurePerms v1.3.7, CoolDeath v0.0.1, SkinChanger v1.3.12, VIPSlots v0.0.2, DrawMyThing v1.0.0, ManyWorlds v2.0.3, BlockParticle v1, EconomyAPI v2.0.9, EconomySell v2.0.7, EconomyShop v2.0.7, PureChat v1.4.0, WalkingParticles v2.2.4, SignWarp v1.5.1, MyPlot v1.1.3, BarTip v1.2, Slapper v1.3.3, WorldProtect v2.2.0, SizePlayer v1, TapToDo v2.2.1, QueryFacade v1.1.0, Fly v1, BossBarAPI v2.2.2, FactionsPro v1.4, CrateKeys v1, AlwaysSpawn v2.2.2, ZMusicBox v1.2.0, NetherChests v1.1.1, LBParticles v0.0.1, iControlU v1.3, MagicWE v0.2.7, BanClient v1.1, Broadcaster v1.16, Pets by FreeGamingHere v1.5.0, MagicTelePortal v1.3.2, JoinCommands v1.3, DevTools v1.11.2, BossAnnouncement v1.0.2

**Comment by AnkitM252** [comment]
I don't think it is implemented on the core!

**Comment by MalakasPlayzMC** [comment]
What do you mean? How could I fix it?

**Comment by AnkitM252** [comment]
There is no option to fix it until it is implemented on the core!

**Comment by MalakasPlayzMC** [comment]
OK, thanks
When will it be implemented on the core?
Sorry if you can't answer my questions

**Comment by AnkitM252** [comment]
I can't specify the date but soon!

**Comment by MalakasPlayzMC** [comment]
Ok. Thanks for giving me a reply to my question
