### ISSUE TITLE
My World Save Pct Tick is wayyyy higher than normal :S

### ISSUE THREAD

**Issue by LordJoshie** [TesseractTeam/Tesseract#322]
:S

My world save was NEVER this high ! 

Can you help solve the issue, squad ? 

       0.06%	2,018.64%	  1.01 s	 1,009.32 ms	 0.0	       0.0k	    World Save

Tesseract version : 4b067da
OS : Linux 15.10
Server Host : OVH VPS
MCPE Game Version : 1.0.3 

My worlds somehow just recently got realllllly high pct tick, which is causing lag. 
Hasn't been like this before, and I've only added two-three plugins, which I've since removed.
Still, seems my worlds are killing my server :S

**Comment by LordJoshie** [comment]
this might be an issue cuz I'm on an older branch xD but, it's before all the language and whatchamahcallsits happened... so ya, maybe I'll try making other changes to me serva :P

**Comment by xZeroMCPE** [comment]
Provide us a 10 min timings report.

**Comment by LordJoshie** [comment]
owa' bout a "Sample Time: 7797.409s" timings report mate ?!

**Comment by LordJoshie** [comment]
Total: 21039.638s (Ticks: 185104) - Sample Time: 9971.072s  - Spigot Version: v1.0.3.0
 - Average Entities: 48.27 - Average Players: 30.28 - Average TPS: 18.56 - Server Load:   98.76%
Minecraft Total: 17475.192 s	Pct: 175.26%
   Pct Total	Pct Tick	   Total	      Avg	 PerTick	     Count		Event
      91.67%	  98.76%	9,140.63 s	    49.38 ms	 1.0	     185.1k	    Full Server Tick
      23.95%	  25.81%	2,388.56 s	    12.90 ms	 1.0	     185.1k	    Plugin Scheduler
Learn More

      16.55%	  17.83%	1,650.00 s	     8.91 ms	 1.0	     185.1k	    PlotWorld - doTick
      13.64%	  14.70%	1,360.16 s	     7.35 ms	 1.0	     185.1k	    Spawn - doTick
      10.96%	  11.81%	1,092.90 s	     5.90 ms	  46	   8,552.8k	    Player Network Receive
       5.40%	   5.78%	537.97 s	     2.89 ms	 1.6	     298.1k	    Player Send Chunks
       3.90%	   4.20%	389.12 s	     2.10 ms	 1.0	     185.1k	    ClanWorld - doTick
       3.54%	   3.82%	353.17 s	     1.91 ms	 1.0	     185.1k	    AngelTazon - doTick
       2.86%	   3.08%	285.09 s	     1.54 ms	  55	  10,143.2k	    Player Network Send
       2.01%	   2.17%	200.61 s	     1.08 ms	 1.0	     185.1k	    LoneWolfWorld - doTick
       0.28%	   0.30%	 27.87 s	     0.15 ms	 1.0	     185.1k	    VIP - doTick
       0.21%	  12.57%	 21.22 s	     6.29 ms	 0.0	       3.4k	    Permissible Calculation
       0.13%	   0.19%	 13.34 s	     0.09 ms	 0.8	     141.1k	    Player Order Chunks
       0.04%	   0.04%	  3.55 s	     0.02 ms	 1.0	     185.1k	    Server Command
       0.03%	1,338.45%	  3.35 s	   669.23 ms	 0.0	       0.0k	    World Save
       0.03%	   0.04%	  3.03 s	     0.02 ms	 0.9	     168.8k	    pvp1 - doTick
Show rest...

**Comment by LordJoshie** [comment]
![capture](https://cloud.githubusercontent.com/assets/17371144/23537875/08663824-ff9d-11e6-8a76-71878f9eaf60.PNG)

**Comment by LordJoshie** [comment]
dat ram usage doe o.O LOL

**Comment by LordJoshie** [comment]
ish-lika-saw :)

**Comment by xZeroMCPE** [comment]
MCPETimings !

**Comment by LordJoshie** [comment]
.....thats what that is.

**Comment by Nought57** [comment]
MCPE Timings (/timings command)

**Comment by LordJoshie** [comment]
bro.. you dont get it.

I'm not stupid.

I did that.

/timings on
/timings paste
then went to the link....

holy. you really think I'm dumb, or you are to not understand that I
copy/pasted text from the MCPE timings page...


sorry, but server setups are private ...I'm not about to share all my
plugins and everything with you.

you see enough info there.


I'm still purplexed that you didn't see that was timings...

like... holy.

**Comment by Nought57** [comment]
@LordJoshie 
That's very strange.
The contents of the screen are different.
Please show me the generated file.

**Comment by LordJoshie** [comment]
Nought... what do you even do, besides close issues ? 

j.w. 

I'm not showing you anything, besides what I've shown here. 

Total: 21039.638s (Ticks: 185104) - Sample Time: 9971.072s - Spigot Version: v1.0.3.0

Average Entities: 48.27 - Average Players: 30.28 - Average TPS: 18.56 - Server Load: 98.76%
Minecraft Total: 17475.192 s	Pct: 175.26%
Pct Total	Pct Tick	Total	Avg	PerTick	Count	Event
91.67%	98.76%	9,140.63 s	49.38 ms	1.0	185.1k	Full Server Tick
23.95%	25.81%	2,388.56 s	12.90 ms	1.0	185.1k	Plugin Scheduler

16.55%	17.83%	1,650.00 s	8.91 ms	1.0	185.1k	PlotWorld - doTick
13.64%	14.70%	1,360.16 s	7.35 ms	1.0	185.1k	Spawn - doTick
10.96%	11.81%	1,092.90 s	5.90 ms	46	8,552.8k	Player Network Receive
5.40%	5.78%	537.97 s	2.89 ms	1.6	298.1k	Player Send Chunks
3.90%	4.20%	389.12 s	2.10 ms	1.0	185.1k	ClanWorld - doTick
3.54%	3.82%	353.17 s	1.91 ms	1.0	185.1k	AngelTazon - doTick
2.86%	3.08%	285.09 s	1.54 ms	55	10,143.2k	Player Network Send
2.01%	2.17%	200.61 s	1.08 ms	1.0	185.1k	LoneWolfWorld - doTick
0.28%	0.30%	27.87 s	0.15 ms	1.0	185.1k	VIP - doTick
0.21%	12.57%	21.22 s	6.29 ms	0.0	3.4k	Permissible Calculation
0.13%	0.19%	13.34 s	0.09 ms	0.8	141.1k	Player Order Chunks
0.04%	0.04%	3.55 s	0.02 ms	1.0	185.1k	Server Command
0.03%	1,338.45%	3.35 s	669.23 ms	0.0	0.0k	World Save <-- wowza
0.03%	0.04%	3.03 s	0.02 ms	0.9	168.8k	pvp1 - doTick




This is a copy from the webpage, if you want to see a screen shot of the text I copied and pasted above, I'll show you that, so you can see it in an easier to read format... 

but still, so shocking you couldn't identify that this IS a timings report.

**Comment by Nought57** [comment]
@LordJoshie 
I understand that. What he is looking for is another more detailed Timings report.
Surely unfamiliar format and title could have made him mistake.

**Comment by LordJoshie** [comment]
oh jheez... my bad, next time I'll copy this text too... ya kno... for simple people. 


© Aikar of Empire Minecraft
[source] [donate] 
This is a fork of (Aikar timings) aikar.

**Comment by LordJoshie** [comment]
© Aikar of Empire Minecraft
[source] [donate] 
This is a fork of (Aikar timings) aikar.

Total: 1741.407s (Ticks: 13442) - Sample Time: 779.724s  - Spigot Version: v1.0.3.0
 - Average Entities: 44.68 - Average Players: 34.67 - Average TPS: 17.24 - Server Load:  113.36%
Minecraft Total: 1446.806 s	Pct: 185.55%
   Pct Total	Pct Tick	   Total	      Avg	 PerTick	     Count		Event
      97.71%	 113.37%	761.88 s	    56.68 ms	 1.0	      13.4k	    Full Server Tick
      24.36%	  28.26%	189.95 s	    14.13 ms	 1.0	      13.4k	    Plugin Scheduler
Learn More

      13.95%	  16.18%	108.73 s	     8.09 ms	 1.0	      13.4k	    PlotWorld - doTick
      11.96%	  13.87%	 93.24 s	     6.94 ms	 1.0	      13.4k	    Spawn - doTick
      10.13%	  11.74%	 78.95 s	     5.87 ms	  54	     722.3k	    Player Network Receive
       5.00%	   5.92%	 38.99 s	     2.96 ms	 2.4	      31.6k	    Player Send Chunks
       4.99%	   5.79%	 38.92 s	     2.90 ms	 1.0	      13.4k	    AngelTazon - doTick
       4.69%	   5.44%	 36.59 s	     2.72 ms	 1.0	      13.4k	    Mines - doTick
       3.64%	   4.23%	 28.39 s	     2.11 ms	  75	   1,008.9k	    Player Network Send
       3.21%	   3.73%	 25.05 s	     1.86 ms	 1.0	      13.4k	    ClanWorld - doTick
       2.90%	   3.36%	 22.62 s	     1.68 ms	 1.0	      13.4k	    LoneWolfWorld - doTick
       1.86%	   2.16%	 14.53 s	     1.08 ms	 1.0	      13.4k	    pvp2 - doTick
       0.46%	  14.34%	  3.62 s	     7.17 ms	 0.0	       0.5k	    Permissible Calculation
       0.26%	   0.30%	  2.04 s	     0.15 ms	 1.0	      13.4k	    VIP - doTick
       0.14%	   0.17%	  1.11 s	     0.08 ms	 1.0	      13.3k	    Player Order Chunks
       0.13%	1,978.17%	  0.99 s	   989.08 ms	 0.0	       0.0k	    World Save
       0.07%	   0.08%	  0.55 s	     0.04 ms	 1.0	      13.4k	    Server Command
       0.03%	   0.03%	  0.23 s	     0.02 ms	 1.0	      13.4k	    nether - doTick
Show rest...

**Comment by LordJoshie** [comment]
![capture](https://cloud.githubusercontent.com/assets/17371144/23576911/5525752a-007f-11e7-8f8d-dec1843a9ede.PNG)

**Comment by LordJoshie** [comment]
![capture](https://cloud.githubusercontent.com/assets/17371144/23576916/67b82afc-007f-11e7-899a-48baf47efcd2.PNG)

**Comment by LordJoshie** [comment]
👍

**Comment by LordJoshie** [comment]
Keep in mind, I have 74 plugins... none of which I think are causing this, due to the fact this is a recent issue. 

This server is on Tess from a few commits ago.   Tesseract version : 4b067da

**Comment by LordJoshie** [comment]
I'm going to disable world saving, except for when my server reboots, and see if this solves anything.

**Comment by LordJoshie** [comment]
didn't do anything... besides not save my worlds at all. xD

**Comment by xZeroMCPE** [comment]
Try reducing chunks sending
