### ISSUE TITLE
There is no mineral in the ground

### ISSUE THREAD

**Issue by lowingly** [TesseractTeam/Tesseract#323]
Generate a new map and then dig mine. Under the ground, there is no mineral (carbon, gold, iron, diamonds), all are stones.

I did not install any plugins and did not change any configuration.

Tesseract:  f4e4c69  
PHP: 7.0.9
Server OS: Windows 7
Game version: 1.0.3
Server host: macbookpro

**Comment by Bruno99** [comment]
Its first start server?

**Comment by lowingly** [comment]
Yes, this is the first start.
Actually, start at  last week, my players told me that they did not see any minerals even though they were constantly digging  2 hours（only stone）. 
This time I used the latest version to create a new world, then I can not find any minerals too...
This phenomenon occurs shortly after Tesseract supports 1.0.3. The previous version have minerals.

**Comment by xZeroMCPE** [comment]
@lowingly Try with a fresh copy.

**Comment by lowingly** [comment]
Sorry for my english ... what is fresh copy? =. =
I have used the latest version, created a lot of new worlds.
I even changed a computer to test, but I still can not find any minerals.
I also used a plugin that could look for minerals,  and the plugin told me that there was no mineral...
Please try to fix it,  in addition to this problem, Tesseract is still the best server software.    QAQ

**Comment by AydarTop** [comment]
@xZeroMCPE I have this bug too. Minerals no generate in the world

**Comment by xZeroMCPE** [comment]
@lowingly Like delete everything, settings,worlds etc. And try again

@AydarTop With a fresh copy?

**Comment by AydarTop** [comment]
@xZeroMCPE  Yes

**Comment by lowingly** [comment]
@xZeroMCPE Yes. I deleted everything many times…

**Comment by lowingly** [comment]
I'm sorry, I know I should not urge, but I hope to fix this bug as soon as possible. I think this is a serious problem with map generator. For all surviving servers, this is a tragedy. I can only stay in the early 1.0.3 version and wait...
