### ISSUE TITLE
People can break protected blocks

### ISSUE THREAD

**Issue by NiclasQueen** [TesseractTeam/Tesseract#325]
My Lobby got griefed... thanks

Please fix NOW!!!!

**Comment by LordJoshie** [comment]
Make backups, you're welcome !
Also, take note... ALL MCPE SERVER SOFTWARE IS STILL BEING DEVELOPED. 

When YOU choose to update, YOU are taking the risk of unknown changes. 

YOU are held ENTIRELY responsible for what YOU do to YOUR server. 

Perhaps check and make sure your protection plugins still work on a testing base server, before applying changes to your public server.

**Comment by Nought57** [comment]
@NiclasQueen 
Information is necessary.
Server spawn point protection is successfully working now.
What function are you using?

**Comment by LordJoshie** [comment]
Regardless of built in spawn protection, it's always suggested to use 3rd party plugins for advanced functions. 

I use iProtector & added some forked extras to enable/disable per area hunger. 

Perhaps.... step up ya game a bit, and try something like this ?

**Comment by Nought57** [comment]
My server also uses its own protection plugin, but it works normally.

**Comment by LordJoshie** [comment]
I know, so does mine... which is why this kids issue is stupid, he probably doesn't know what he's doing, and just comes here to whine about his problems.

**Comment by ISRAPIL** [comment]
`
public function onBreak(BlockBreakEvent $event){
  $player = $event->getPlayer();
  $level = $this->getServer()->getLevelByName("LOBBY");
  if($player->getLevel()->getName() == $level->getName()){
    $event->setCancelled(true);
  }
}
`

use this code, LOL.

**Comment by erkam2002** [comment]
level getName?

**Comment by erkam2002** [comment]
```
 public function onBreak(BlockBreakEvent $event){
    $player = $event->getPlayer();
    $lobby = $this->getServer()->getLevelByName("Lobby");
       if($player->getLevel()->getName() == $lobby){
          $event->setCancelled(true);
       }
   }

**Comment by Driesboy** [comment]
`   public function onBreak(BlockBreakEvent $ev){
        if ($ev->getPlayer()->getLevel()->getFolderName() === "Lobby"){
            $ev->setCancelled();
        }`

**Comment by erkam2002** [comment]
Look my code its the same

**Comment by Driesboy** [comment]
no i use getFolderName()!

**Comment by Driesboy** [comment]
so it dont need to be the official name for downloaded or imported maps

**Comment by erkam2002** [comment]
Ok :/

**Comment by erkam2002** [comment]
But my code works too xD

**Comment by NiclasQueen** [comment]
My English is kinda bad sorry

I`ve used MyPlot for all the time after 1.0.3 - NOW (since yesterday) people can break blocks in their Plots and hold the screen, walk to other BPlots (while holding the screen) and break Blocks there (even at Spawn).

PLUS my Shop got griefed (idk how)

**Comment by Driesboy** [comment]
i think you have force op hackers

Op 4-mrt.-2017 11:43 schreef "Niclas Queen" <notifications@github.com>:

**Comment by Nought57** [comment]
@NiclasQueen 
You will be able to use it. but, That Plugin developers are leaving support.
It is not recommended to use that plugin. 
The version is updated and a deprecated function also appears.
You need to find a corresponding plugin or fix it yourself.

**Comment by NiclasQueen** [comment]
I apologize, i fixed it

**Comment by lowingly** [comment]
@NiclasQueen 
https://github.com/jasonwynn10/MyPlot
You can try this and download the Branch: API3
I am using it.

**Comment by LordJoshie** [comment]
to disable force op, i just made my ops.txt file read only... lol.

throws an error on console that the file write task didnt work...cuz yah...
restricted file to read only.

dunno if it works...but no ops are added to my ops.txt file anymore.

**Comment by xZeroMCPE** [comment]
@LordJoshie Yep...

**Comment by shdudwns** [comment]
Item frames in item frame are checked by item frames.
