### ISSUE TITLE
Why is this warning?

### ISSUE THREAD

**Issue by bulutsun** [TesseractTeam/Tesseract#328]
CRITICAL> Could not tick level "world": Call to a member function getItemInHand() on null

Why is this warning?

* Tesseract:
* PHP: 7
* Server OS: Windows
* Game version: 1.0.3
* Server host:
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by bulutsun** [comment]
Please help.

**Comment by bulutsun** [comment]
Nice help...

**Comment by AnkitM252** [comment]
If there are crashdumps so us and also show us your plugins!

**Comment by AppleDevelops** [comment]
@bulutsun Some of us have lives, we like to enjoy our weekends not spend it, listening to people complain.

**Comment by bulutsun** [comment]
Okey sorry. You can help?

**Comment by bulutsun** [comment]
@AnkitM252 No crashdumps. Plugins: aCases v1.1, AdvancedKits v5.1, AlwaysSpawn v2.2.2, AntiSpam v1.3, BanItem v2.3, BanSystem v1.0.3, Broadcaster v1.16, ChatClear v1.0.0, CombatLogger v1.2.0, CommandBlocker v1.5.5, CustomAlerts v1.6, DevTools v1, EconomyAPI v2.0.9, EconomyCShop v0.5.4, EconomyJob v2.0.4, EconomyShop v2.0.7, EssentialsPE v2.0.0, FactionsPro v1.3.7, Help v1.0.0, iFriend v1.0.0, iProtector v3.1b, ItemCasePE v1.0.8, LiveTexts v1.4pre, LoadAllWorlds v2.0.1, MineReset v2.2, NoAdvertisingPE v1.0.1, PEXProtection v0.1.0, PureEntitiesX v0.1.2_dev, PurePerms v1.3.7, PvPWorlds v1, RestartMe v1.2.0, Sell v2, ServerAuth v2.13, ServerBackup v1.0.0, ServerRules v1.0.0, Slapper v1.3.1, Staff v1.0.0, superBAR v1.6.2, TimeCommander v2.1, TopVoter v2.0.5, VIP1b v2.0.0, VIPSlots v0.0.4, VoteReward v3.0.2, WorldEditPotato v1.5, WorldFixer v1, MyPlot v1.1.3, PureChat v1.4.0

**Comment by AnkitM252** [comment]
Try without plugins. The plugins may cause the errors.

**Comment by xZeroMCPE** [comment]
How did you get that error? and provide plugin list, crash dumps, etc

**Comment by bulutsun** [comment]
I do not know. No crashdump. Plugin List:  aCases v1.1, AdvancedKits v5.1, AlwaysSpawn v2.2.2, AntiSpam v1.3, BanItem v2.3, BanSystem v1.0.3, Broadcaster v1.16, ChatClear v1.0.0, CombatLogger v1.2.0, CommandBlocker v1.5.5, CustomAlerts v1.6, DevTools v1, EconomyAPI v2.0.9, EconomyCShop v0.5.4, EconomyJob v2.0.4, EconomyShop v2.0.7, EssentialsPE v2.0.0, FactionsPro v1.3.7, Help v1.0.0, iFriend v1.0.0, iProtector v3.1b, ItemCasePE v1.0.8, LiveTexts v1.4pre, LoadAllWorlds v2.0.1, MineReset v2.2, NoAdvertisingPE v1.0.1, PEXProtection v0.1.0, PureEntitiesX v0.1.2_dev, PurePerms v1.3.7, PvPWorlds v1, RestartMe v1.2.0, Sell v2, ServerAuth v2.13, ServerBackup v1.0.0, ServerRules v1.0.0, Slapper v1.3.1, Staff v1.0.0, superBAR v1.6.2, TimeCommander v2.1, TopVoter v2.0.5, VIP1b v2.0.0, VIPSlots v0.0.4, VoteReward v3.0.2, WorldEditPotato v1.5, WorldFixer v1, MyPlot v1.1.3, PureChat v1.4.0

**Comment by bulutsun** [comment]
This error is constantly being spammed on the console.
