### ISSUE TITLE
Inventory Issue #1

### ISSUE THREAD

**Issue by JunkDaCoder** [TesseractTeam/Tesseract#329]
Issue description

1.Items with custom inttags drops out of ur inventory
Steps to reproduce the issue
1. Get an item with an int tag.
2.Open your inventory.
3.Move it somewhere in your inventory.
4.It drops.
OS and versions

Genisys: 715b6a8
PHP: 7.0.14
Server OS: CentOS7
Game version: 1.0.2
Crashdump, backtrace, memory dumps, plugins list or other files

**Comment by JunkDaCoder** [comment]
Note:readding enchantments and setting a custom name does the same exact thing

**Comment by JunkDaCoder** [comment]
@AppleDevelops

**Comment by JunkDaCoder** [comment]
Heres code from @Muqsit that reproduces it$item = Item::get(Item::DIAMOND_SWORD, 0, 10);
$item->setCustomName(TextFormat::RESET.TextFormat::AQUA.'A Custom Named TNT');
$nbt = $item->getNamedTag();
$nbt->tag1 = new StringTag('tag1', 'A custom tag');
$nbt->tag2 = new StringTag('tag2', 'Another custom tag');
$item->setNamedTag($nbt);
//Player::getInventory()->addItem($item);

**Comment by JunkDaCoder** [comment]
bump

**Comment by jrodr10** [comment]
Was this fixed? @TesseractTeam/software

**Comment by AppleDevelops** [comment]
You'd have to know

**Comment by TDMidkwhatisxd** [comment]
What happened? Apple is trying to steal the project?

**Comment by jrodr10** [comment]
@TDMidkwhatisxd quite litterally and i no idea why.. he will only seek to delete it

**Comment by TDMidkwhatisxd** [comment]
https://github.com/TesseractTeam/Tesseract/commit/3acb9b71b25a2e71afec86787b8616e53879e460

check if my commit fix this issue

**Comment by AppleDevelops** [comment]
@TDMidkwhatisxd I wouldn't consider it stealing if Linux kicked me and removed my ownership.

**Comment by TDMidkwhatisxd** [comment]
I'm so confused ^^

**Comment by AppleDevelops** [comment]
Pretty much, I promoted Linux to owner, because I trusted him, and he demoted everyone else, and so I left, and created the official Tesseract, as this one is now unofficial. https://github.com/ServerSoftwareArchive/Tesseract
