### ISSUE TITLE
Verbose-Notifications

### ISSUE THREAD

**Issue by Akuroma** [TesseractTeam/Tesseract#334]
#### Problem description
Removing Verbose-Notifications via a permission or something like that.

#### Steps to reproduce the issue
Feature-Request:
Maybe you could add a toggle function which is able to turn those annoying verbose notifications off. Otherwise a setting in tesseract.yml could be also an option to resolve this.

#### OS and versions

* Tesseract:  Tesseract-1.1.0 (Codename "Ruby")
* PHP: 7.0.3
* Server OS: Linux (Ubuntu 14.04)
* Game version: 1.0.3 Windows 10 and PE
* Server host: Virtual-Server
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by NFGamerMC** [comment]
Please report this or request it [here](bit.ly/TesseractRequests)
