### ISSUE TITLE
Getting clipped !

### ISSUE THREAD

**Issue by LordJoshie** [TesseractTeam/Tesseract#336]
#### Problem description
Aye.. so, cocoa blocks/ carpets on fence posts, stuff like that... you get clipping killed... like... if you're in the block space of that object, you take damage. 

#### Steps to reproduce the issue
Place a cocoa bean on a jungle tree, and walk close to it, should take damage from it.

#### OS and versions

* Tesseract:  1.1.0 ruby
* PHP: 7.0.2
* Server OS: Ubuntu 15.10 Server
* Game version: 1.0.3
* Server host: A sexy Host
A rented VPS from OVH
<br><br>

**Comment by AppleDevelops** [comment]
Bounding box issues :/

**Comment by AppleDevelops** [comment]
No longer able to reproduce anymore, lemme know if you are.

**Comment by LordJoshie** [comment]
Nope, this ones solved for me now also


as for the world height issue, try generating a world with manyworld plugin
on tesseract, it wouldn't let me build past 128 height.
