### ISSUE TITLE
Bug Reports - List (MCPE Creative)

### ISSUE THREAD

**Issue by DobberHockeyCom** [TesseractTeam/Tesseract#337]
* Game version: MCPE 1.0.3
* Server host: gameservers.com

**EDITED**

1. Minecarts can only be ridden underneath the Mine Cart (because the Mine Cart hovers above the rail), and there is no ride button to get on the Cart, you have to just get lucky to get on the Cart.
2. Power Rails do not light up or give power when next to the red block. ETA?

**Comment by lowingly** [comment]
I'm not a developer, but I can answer some questions as a server player...My English is not good, sorry.
1-3. I think the Redstone system and rails system is not perfect (many bugs/problems) in the any PM server .. This is a long lasting issue...
4. I think animals can not move in any PM server, you can try to find some Animal AI plugins.
5. When you are creative mode, the chests can not open. You can open it in Survival mode.
6. I think most servers are using plugin to ban water flow, so many people don't care about this problem....
7. You can turn off the weather at 'tesseract.yml'.     Use /time stop
8. You can use the trough to color the armor.

If you just play with your family and you don't want to use the server plugin, I recommend you using the Realms....It will give you the original and complete MC functionality. Server dependent plugins. This is my personal opinion...

**Comment by Lazerplayz** [comment]
All these issues besides the mob API can be fixed if you are using MyPlot it bans water flow you can disable in their config. Water flows for me in my server so it should in yours :)

**Comment by DobberHockeyCom** [comment]
I'm fine with any issue - can live with them and not quit the server - EXCEPT the rails. The whole point of this was to build a fantastic huge minecart rail system with my two daughters.

The last build, I could curve the tracks and point them in different directions. But the minecart floated in the air. This build the minecart is on the tracks properly - but now I can't curve the rails or even point them in another direction.

I won't use a Realm at 10 bucks a month, that's just crazy. Even Warcraft was too much, and that was a better game at $8 a month. No game is worth that much. So I really hope the rail issues get fixed so I can keep playing this game on this server with my daughters.

**Comment by lowingly** [comment]
I do not think rails can be resolved immediately. This problem is difficult to solve......
You can try to turn on “multiplayer game”and “Broadcast to LAN” in MC , then you can play with your daughter when you are in the same Wi-Fi. It is a direct online way that does not require a server and a fee.

**Comment by DobberHockeyCom** [comment]
Even if the rails issue reverted back to when the cart was in the air - that would be fine as a temporary solution. Because then I could go back to being able to curve the rails and put them in a north/south direction instead of just east/west. I can worry about putting the minecart on the rails later.

As for playing with my girls - you have to trust me on this. I've tried everything. My trials and tribulations could take hours to type here. I did play with them on our Wi-Fi. Then their worlds froze and we had to lose the game. They had to host on their tablet. So then I tried everything to host on my PC, but something to do with Blue Stacks won't allow others onto my world. Even after buying XBox gold (and I don't even own an XBox). Then I tried putting a server on my PC. Couldn't get it to work. 

Finally, using gameservers I have a world that we can all join - it's it's bugged. But if the rails can go back to curving and going in different directions within a few days, and the rest of the rail issues fix within a month - I don't need the other things on my list.

Sigh. I surrender. I just...give up. I've spent hours and money on making this happen and it's just no longer worth it :(

**Comment by lowingly** [comment]
Ok. You can try to create a new Issue. Describe the most important about rails features you need (the most urgent). I think the developer will try to solve.  But it takes time. =。=

**Comment by TDMidkwhatisxd** [comment]
Weird! I was playing long ago with my sis, and my world didnt freeze! 
If you wanna a High Quality Server, with all Vanilla features and no gliches, buy Realms! ;)
From what i hear, even Realms got some dupe gliches!

Servers should provide basic functions! Like: Generating World, Crafting, etc....  . Then you customize game via plugins! I think that rails+minecart should be added via plugins!

If you wanna Play for Free, from what i see in your comments you got a $ problem, just join a Plots server, or even Better , a creative one(you can get a free plot, and dont need to do jobs for in game money)!

https://minecraftpocket-servers.com

**Comment by DobberHockeyCom** [comment]
Updated the OP to reduce the clutter and get to the meat of the problem, as well as to reflect what's been fixed already.

**Comment by JunkDaCoder** [comment]
I see what your saying here but for what your trying to do realms is probably the best option till Tesseract has all the proper functions Vanilla does.

**Comment by NFGamerMC** [comment]
Please submit one issue per bug, that will help us solve them faster
