### ISSUE TITLE
Ban command bug.

### ISSUE THREAD

**Issue by NycuRO** [TesseractTeam/Tesseract#338]
#### Steps to reproduce the issue

Notice: Undefined variable: player in phar:///root/fac/Tesseract_1.1.0_2017-03-04_06-15-05.phar/src/pocketmine/command/defaults/BanCommand.php on line 66

#### OS and versions

* Tesseract: https://github.com/TesseractTeam/Tesseract/commit/c090b0ec3be314a056d0d406598218816738f8b6
* PHP: 7.0.15
* Server OS: Ubuntuu 14.04.5 LTS 64bit 
* Game version: 1.0.3
* Server host: gazduirejocuri.ro
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by NycuRO** [comment]
I don't know why you modify ban command. You broked all. -_-

**Comment by AppleDevelops** [comment]
Fixed
