### ISSUE TITLE
Movement bug

### ISSUE THREAD

**Issue by Driesboy** [TesseractTeam/Tesseract#339]
#### Problem description

players are bugging in movement

#### Steps to reproduce the issue

join your server

#### OS and versions

* Tesseract: latest after 1.0.4 update
* PHP: 7.0.13
* Server OS: Windows
* Game version: 1.0.4
* Server host: Myself
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Lazerplayz** [comment]
Hmmm, I'll try test the latest version with my server host to see if these issues happen.

**Comment by AppleDevelops** [comment]
Fixed
