### ISSUE TITLE
The server stops

### ISSUE THREAD

**Issue by MrSmileCH** [TesseractTeam/Tesseract#34]
Issue description

The server stops

Steps to reproduce the issue

The server stops when a player enters the server

OS and versions

Tested in win10, server version 1.1.0.55

Crashdump:

Tesseract Crash Dump Tue Jun 20 10:36:56 CDT 2017

Error: Argument 3 passed to pocketmine\Server::broadcastPacketsCallback() must be of the type boolean, none given, called in C:\Users\Smile\Desktop\server pocketmine\src\pocketmine\network\CompressBatchedTask.php on line 51
File: /src/pocketmine/Server
Line: 2071
Type: notice

Code:
[2062] 			$task = new CompressBatchedTask($str, $targets, $this->networkCompressionLevel, $immediate);
[2063] 			$this->getScheduler()->scheduleAsyncTask($task);
[2064] 		}else{
[2065] 			$this->broadcastPacketsCallback(zlib_encode($str, ZLIB_ENCODING_DEFLATE, $this->networkCompressionLevel), $targets, $immediate);
[2066] 		}
[2067] 
[2068] 		Timings::$playerNetworkTimer->stopTiming();
[2069] 	}
[2070] 
[2071] 	public function broadcastPacketsCallback($data, array $identifiers, bool $immediate){
[2072] 		$pk = new BatchPacket();
[2073] 		$pk->payload = $data;
[2074] 		$pk->encode();
[2075] 		$pk->isEncoded = true;
[2076] 
[2077] 		if($immediate){
[2078] 			foreach($identifiers as $i){
[2079] 				if(isset($this->players[$i])){
[2080] 					$this->players[$i]->directDataPacket($pk);
[2081] 				}

Backtrace:
#0 /src/pocketmine/scheduler/AsyncPool(151): pocketmine\network\CompressBatchedTask->onCompletion(pocketmine\Server object)
#1 /src/pocketmine/scheduler/ServerScheduler(252): pocketmine\scheduler\AsyncPool->collectTasks(boolean)
#2 /src/pocketmine/Server(2686): pocketmine\scheduler\ServerScheduler->mainThreadHeartbeat(integer 941)
#3 /src/pocketmine/Server(2410): pocketmine\Server->tick(boolean)
#4 /src/pocketmine/Server(2320): pocketmine\Server->tickProcessor(boolean)
#5 /src/pocketmine/Server(1872): pocketmine\Server->start(boolean)
#6 /src/pocketmine/PocketMine(468): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string C:\Users\Smile\Desktop\server pocketmine\, string C:\Users\Smile\Desktop\server pocketmine\, string C:\Users\Smile\Desktop\server pocketmine\plugins\, string unknown)

Tesseract version: 0000000000000000000000000000000000000000 [Protocol 113; API 3.0.1]
uname -a: Windows NT DESKTOP-RKO50LP 10.0 build 14393 (Windows 10) AMD64
PHP version: 7.0.3
Zend version: 3.0.0
OS : WINNT, win

Server uptime: 49 seconds
Number of loaded worlds: 2
Players online: 1/20

Loaded plugins:

**Comment by AppleDevelops** [comment]
Enable debugging and try again

**Comment by MrSmileCH** [comment]
Where is that located?

**Comment by AppleDevelops** [comment]
pocketmine.yml

**Comment by MrSmileCH** [comment]
It is activated, but the same thing happens, the server stops when a player enters
![sin titulo1](https://user-images.githubusercontent.com/27845246/27346298-58833aee-55b2-11e7-8603-06033c965095.png)

**Comment by AppleDevelops** [comment]
Set debug level to 2 so I can see the issue

**Comment by MrSmileCH** [comment]
![sin titulo](https://user-images.githubusercontent.com/27845246/27346888-3c98589e-55b4-11e7-99f3-5a2f7a2875cf.png)
![sin tituloq](https://user-images.githubusercontent.com/27845246/27346892-4394a4a4-55b4-11e7-9044-47fb4630b42f.png)
![sin titulo1](https://user-images.githubusercontent.com/27845246/27346945-73e2a64c-55b4-11e7-9e80-00d42091d22e.png)

I still do the same thing, in an earlier version, where the hotbar bug was if I let it enter the server
