### ISSUE TITLE
[Suggestion] ResourcePacks

### ISSUE THREAD

**Issue by Bruno99** [TesseractTeam/Tesseract#344]
TODO?

**Comment by ImagicalGamer** [comment]
That doesn't look like an issue, there are more important things to work on than Resource Packs.

**Comment by Driesboy** [comment]
https://github.com/pmmp/PocketMine-MP/commit/d41bdfc31c4875dccec0d572d747acde8bc232de#commitcomment-21266346

**Comment by NFGamerMC** [comment]
Please report this or request it [here](http://bit.ly/TesseractRequests)

Message: Please request this, also use our issue template if it is an issue!
