### ISSUE TITLE
Item Frame protection not work some plugins

### ISSUE THREAD

**Issue by andris155** [TesseractTeam/Tesseract#346]
#### Problem description

Item Frame protection not work some plugins. Example: Iprotector

#### Steps to reproduce the issue

1. Break item frame
2. Item frame drop item

#### OS and versions

* Tesseract: https://github.com/TesseractTeam/Tesseract/tree/9e8171321fa78fe05c903b01603c1aa6b195a3e6
* PHP: 7.0.15
* Server OS: Ubuntu 14.0.4.2 lts
* Game version: 1.0.4 Windows 10
* Server host: InfinityHosting
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Bruno99** [comment]
In FastCorePE fixed

**Comment by AppleDevelops** [comment]
@Bruno99 Do not mention other softwares here.

**Comment by Bruno99** [comment]
@AppleDevelops Sorry me! Okey!

**Comment by ImagicalGamer** [comment]
Fixing this now!

**Comment by Bruno99** [comment]
@ImagicalGamer Okey! Help you?

**Comment by intagaming** [comment]
Just asking: Why don't we put a event in `case ProtocolInfo::ITEM_FRAME_DROP_ITEM_PACKET:` in Player.php ?
