### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by Akuroma** [TesseractTeam/Tesseract#347]
#### Problem description
Plugin does not work, after I updated the server with Tesseract to 1.0.4. Hope you can read the error-message below. Because I'm german.

#### OS and versions

* Tesseract: Tesseract-1.1.0 (Codename "Ruby")
* PHP: 7.0.3
* Server OS: Linux (Ubuntu 14.04)
* Game version: Exception in 1.0.4; plugin works with 1.0.3
* Server host: Virtual-Server
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files
CRITICAL> Unbehandelte Ausnahme bei Ausführung des Befehls 'pets spawn Hund' in pets: Argument 2 passed to pocketmine\entity\Entity::createEntity() must be an instance of pocketmine\level\Level, instance of pocketmine\level\format\Chunk given, called in /home/MagicCraftPE/plugins/Pets-master/src/pets/main.php on line 171

```
```

**Comment by AppleDevelops** [comment]
Plugin issue
