### ISSUE TITLE
Hopper Bug

### ISSUE THREAD

**Issue by ISRAPIL** [TesseractTeam/Tesseract#349]
[VIDEO](https://www.youtube.com/watch?v=zkdHCxMNHn0)

**Comment by Bruno99** [comment]
Not bad bug!

**Comment by LordJoshie** [comment]
Bruno... lol.
Yes a bad bug. 
You can't remove hoppers ? 
Dang :/

**Comment by ISRAPIL** [comment]
I already forbade putting them. I just warned about the bug. @LordJoshie
