### ISSUE TITLE
Travis CI Corrupt Error (it happened again Apple)

### ISSUE THREAD

**Issue by IISweePII** [TesseractTeam/Tesseract#35]
#### Problem description
Travis CI acted up very badly after running the mcregion commit, it was not like that before, but the build passed

#### Steps to reproduce the issue
Look at the Travis CI log (Idk how it happened):
 
![screenshot-travis-ci org-2016-12-05-13-23-21](https://cloud.githubusercontent.com/assets/22999497/20896995/38884234-baee-11e6-8f99-cd6c50c9633c.png)

**Comment by AppleDevelops** [comment]
It's fine now

**Comment by IISweePII** [comment]
I explained in the title why I had to temporarily re-open it, it confuses me why it happens

**Comment by AppleDevelops** [comment]
I wouldn't fret about it, we are fine.

**Comment by IISweePII** [comment]
Alrighty
