### ISSUE TITLE
Doesnt show multisever player count.

### ISSUE THREAD

**Issue by alexbgameson** [TesseractTeam/Tesseract#352]
Doesnt show multisever player count when linked with dserver. Only shows the amount of players on the main server.

**Comment by NiclasQueen** [comment]
-> PlayerList

**Comment by alexbgameson** [comment]
Issue hasn't been fixed!

**Comment by alexbgameson** [comment]
@AppleDevelops 

Tesseract no longer shows the multisever player count when linked with dserver. Only shows the amount of players on the main server.

**Comment by Driesboy** [comment]
i know

**Comment by KennFatt** [comment]
Can we close it now?
