### ISSUE TITLE
Skulls

### ISSUE THREAD

**Issue by Enrick3344** [TesseractTeam/Tesseract#353]
#### Problem description
All the skulls are invisible when placed.

#### Steps to reproduce the issue
Place any kind of skulls

#### OS and versions

* Tesseract: 419eccb
* PHP: 7.0.3
* Server OS: Windows 10
* Game version: 1.0.4
* Server host: VPS
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Lazerplayz** [comment]
This happened before on pmmp I think they just updated the skulls how they where placed.
