### ISSUE TITLE
Enchantments

### ISSUE THREAD

**Issue by Enrick3344** [TesseractTeam/Tesseract#354]
#### Problem description
I don't know if it meant this way but You cannot use enchantments if you have not enabled Allow-Cheat in tesseract.yml. which is kind of dangerous for some servers. players who use mods can get Creative Mode Inventory if enabled.

#### Steps to reproduce the issue
Make sure Allow-Cheat is false and try to enchants

#### OS and versions

* Tesseract: 419eccb
* PHP: 7.0.3
* Server OS: Windows 10
* Game version: 1.0.4
* Server host: VPS
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by daniktheboss** [comment]
Known problem

**Comment by bulutsun** [comment]
It needs to be resolved urgently.

**Comment by JunkDaCoder** [comment]
close this, it is a known/open issue

**Comment by Heroata** [comment]
absolutely need a fast fix

**Comment by SuperXingKong** [comment]
Has it fixed?

**Comment by SuperXingKong** [comment]
Any news?

**Comment by NFGamerMC** [comment]
Not to my knowledge, I will put this on the list though
