### ISSUE TITLE
Server lags when player chats

### ISSUE THREAD

**Issue by daniktheboss** [TesseractTeam/Tesseract#355]
Hey, ones the update the chat lags the server like shit.... when people chat this happens. People reported pmmp this don't happen.

**Comment by NiclasQueen** [comment]
Uninstall your plugins and check then

**Comment by TDMidkwhatisxd** [comment]
Confirmed! If u spam someone with /tell , or just spam chat, players crash!
There should be a default countdown on chat and commands!
Any spam mod can crash all players from server!

**Comment by daniktheboss** [comment]
no, the whole server lags! not a plugin issue!

**Comment by NiclasQueen** [comment]
Get some more RAM i think xD

**Comment by daniktheboss** [comment]
dude... it worked fine last update

**Comment by NiclasQueen** [comment]
Xd how much memory ?
Is your disc full
Try to uninstall all Plugins (backup!)

**Comment by daniktheboss** [comment]
DUDE! it worked before 1.0.4! its not my plugin for server fault! its the tesseract fault PMMP doesnt have this shit

**Comment by xZeroMCPE** [comment]
@daniktheboss Provide us a timings report. 

Use ( /timings on )

Try chatting, doing normal things. Then after 5 min or above, use ( /timings paste )

provide us the link, it gives in chat.

**Comment by daniktheboss** [comment]
Timings is shut down remeber?

**Comment by xZeroMCPE** [comment]
It works, now... Try it..

**Comment by daniktheboss** [comment]
Aericio:
https://paste.ubuntu.com/24174623/

**Comment by SuperMaXAleX** [comment]
You have got many plugins, wow

**Comment by daniktheboss** [comment]
Thx... but it's not because of that... it worked fine last update

**Comment by Aericio** [comment]
When a player chats in the server, it takes ~3 seconds to send and everything freezes until the message is sent. I've found out that commands get sent instantly though.

**Comment by Aericio** [comment]
@daniktheboss close please, i found the cause

**Comment by Aericio** [comment]
Probably TesserREKT has something different than PMMP.

**Comment by AppleDevelops** [comment]
@Aericio Keep sucking Dylan's dick and maybe you'll actually get a friend.

**Comment by daniktheboss** [comment]
Lolololol

**Comment by Aericio** [comment]
thanks for editing my message, love you shits.

**Comment by Aericio** [comment]
@AppleDevelops i love you too

**Comment by Aericio** [comment]
close issue please.
