### ISSUE TITLE
1.0.5.0 update

### ISSUE THREAD

**Issue by SergeyIvanov14** [TesseractTeam/Tesseract#357]
#### OS and versions

* Tesseract:
* PHP:
* Server OS:
* Game version: 
* Server host:
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by AppleDevelops** [comment]
Don't worry we're working on it. :)

**Comment by Driesboy** [comment]
is it out??

**Comment by daniktheboss** [comment]
Beta
