### ISSUE TITLE
no sound

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [TesseractTeam/Tesseract#358]
There is no sound :D. !

**Comment by kaitododoyt** [comment]
the same here

**Comment by Lazerplayz** [comment]
I only noticed this when the chests didn't make any sounds :O

**Comment by IISweePII** [comment]
I will try to implement sounds back at least into the game, when I worked on the project before 1.0.0 anvils and doors were working fine

**Comment by AppleDevelops** [comment]
We need to implement resource packs for it to work now

**Comment by IISweePII** [comment]
but then the resource pack would have to replace the existing sound for the sound code somehow, shouldn't it work normally and play the sound through the clients pack since it is still under the same name?

**Comment by DelxHQ** [comment]
Its a client bug, not a server bug

**Comment by AydarTop** [comment]
@AppleDevelops Can you implement resource packs on this weekend?

**Comment by xZeroMCPE** [comment]
Check new commit
