### ISSUE TITLE
Remove anti-cheat

### ISSUE THREAD

**Issue by AppleDevelops** [TesseractTeam/Tesseract#36]
#### Problem description

The AntiCheat should be handled by plugins not the server, the current anticeaht is extremely buggy
#### OS and versions

* Tesseract:
* PHP:
* Server OS:
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by xZeroMCPE** [comment]
Yeah, argree!

**Comment by AppleDevelops** [comment]
Removed Anti-Fly and Check Movement.... Sound alright @xZeroMCPE?

**Comment by xZeroMCPE** [comment]
@AppleDevelops  Yeah.
