### ISSUE TITLE
Player join crash

### ISSUE THREAD

**Issue by SerezhaIvanov** [TesseractTeam/Tesseract#36]
#### Issue description

Server crashes when i join the server
#### OS and versions

* Tesseract: 1.2.0
* PHP: 7.0.3
* Server OS: Ubuntu
* Game version: 1.1.0

#### Crashdump, backtrace, memory dumps, plugins list or other files (or screenshot of console)

`Tesseract > TypeError: "Argument 3 passed to pocketmine\Server::broadcastPacketsCallback() must be of the type boolean, none given,
alled in /home/srv1/src/pocketmine/network/CompressBatchedTask.php on line 51" (EXCEPTION) in "/src/pocketmine/Server" at line 2071
Tesseract > Произошла фатальная ошибка и сервер вышел из строя. Создание аварийного дампа
Tesseract > Пожалуйста, загрузите файл"/home/srv1/crashdumps/CrashDump_Tue_Jun_20-22.26.17-MSK_2017.log" в краш-архив и отправьте сс
лку на страницу исправления ошибок. Дайте как можно больше информации.`

**Comment by andris155** [comment]
same problem

**Comment by MrSmileCH** [comment]
The same happens to me

**Comment by xZeroMCPE** [comment]
Try with the latest build!

**Comment by MrSmileCH** [comment]
thing still happens

**Comment by xZeroMCPE** [comment]
Should be fixed.

**Comment by AppleDevelops** [comment]
Try on the latest commit now

**Comment by MrSmileCH** [comment]
Resolved, if we find more bugs we will report them
