### ISSUE TITLE
BeaconDelayedCheckTask lag

### ISSUE THREAD

**Issue by andris155** [TesseractTeam/Tesseract#360]
#### Problem description

BeaconDelayedCheckTask lag

#### Steps to reproduce the issue

Place beacons

#### OS and versions

* Tesseract: https://github.com/TesseractTeam/Tesseract/tree/9e8171321fa78fe05c903b01603c1aa6b195a3e6
* PHP: 7.0.15
* Server OS: Ubuntu 14.0.4.2 lts
* Game version: 1.0.4 Windows 10
* Server host: InfinityHosting
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

http://mcpetimings.com/?url=24158099

**Comment by mote166** [comment]
confirmed . just placed beacon and got the same error + server lagged

**Comment by AppleDevelops** [comment]
We're removing these features until we are finished with API 4
