### ISSUE TITLE
sendTitle ERROR

### ISSUE THREAD

**Issue by SergeyIvanov14** [TesseractTeam/Tesseract#361]
#### Problem description
When I send title in console appear ;

[Tesseract] [20:49:23] INFO> SerezhaIvanov[/92.115.87.19:10170] вошел с id сущности -6013041642068504841 на (1, world, 1706, 13)
[Tesseract] [20:49:25] CRITICAL> "Невозможно обработать событие 'pocketmine\event\player\PlayerJoinEvent' в 'API v1': Undefined clas
 constant 'TYPE_TITLE' в SIvanov\API\JoinMessages"
[Tesseract] [20:49:25] CRITICAL> Error: "Undefined class constant 'TYPE_TITLE'" (EXCEPTION) in "/src/pocketmine/Player" at line 3574

#### Steps to reproduce the issue
sendTitle("title", "subtitle"); or sendTitle("title");

#### OS and versions

* Tesseract:
* PHP:
* Server OS:
* Game version: 
* Server host:
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by badp1g** [comment]
я самалыга! у меня в руках панцирь

**Comment by SuperMaXAleX** [comment]
I reproduced what you did, but I don't have any error.
