### ISSUE TITLE
Item frames in item frame are checked by item frames.

### ISSUE THREAD

**Issue by shdudwns** [TesseractTeam/Tesseract#364]
#### Problem description

* Tesseract:1.1.0
* PHP:7.0.2
* Server OS:Linux
* Game version: 1.0.4~1.0.4.11
* Server host:root
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Driesboy** [comment]
wow its like
my computer is controlling my computer checked by my computer

RIP THE WORLD
