### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by NiclasQueen** [TesseractTeam/Tesseract#367]
I can't find a Tesseract .phar to download.
your jenkins is down

**Comment by erkam2002** [comment]
Download src

**Comment by NiclasQueen** [comment]
is there no way to download phar ?
and is it on 1.0.4 already?

**Comment by Driesboy** [comment]
yes

**Comment by ZaneWalter** [comment]
Okay so where from and how to implement .phar file in the server.??

**Comment by Ishannaik** [comment]
first download the src then put it in ur server use devtools type /makeserver go to devtools folder rename the .phar to PocketMine-MP.phar and put it in your server and dlete the src :D

**Comment by ZaneWalter** [comment]
Where do I get devtools? And this is for MCPE?

**Comment by ZaneWalter** [comment]
Also can you plz just provide the download link for phar. It will make all of it so easier. Please I am struggling...

**Comment by keithkfng** [comment]
Unofficial: https://jenkins.imgcl.co/job/Tesseract/

**Comment by xZeroMCPE** [comment]
Thank you @keithkfng 

Anyhow, @NiclasQueen use https://jenkins.imgcl.co/job/Tesseract/ for as of now. Seems good enough :)

**Comment by keithkfng** [comment]
@xZeroMCPE if you wanted auto-build on commit, add a webhook to https://jenkins.imgcl.co/github-webhook/ and make it active :)

**Comment by xZeroMCPE** [comment]
@keithkfng Will do.

**Comment by xZeroMCPE** [comment]
@keithkfng 

I took a look at the jenkins (yesterday) and it seems like it's creating builds every week? Last builds was (	5 days 13 hr ). Why not make it like every day? or maybe 6 hours.

**Comment by keithkfng** [comment]
@xZeroMCPE will do.

**Comment by xZeroMCPE** [comment]
@keithkfng Great!

Eh, they're failing now... on jenkins
