### ISSUE TITLE
ItemFrameDropItemEvent doesn't work

### ISSUE THREAD

**Issue by badp1g** [TesseractTeam/Tesseract#368]
#### Problem description

ItemFrameDropItemEvent doesn't work. Players can take items from item frame.
#### OS and versions

* Tesseract: Tesseract-1.1.0 Ruby (Protocol: 102), latest 
* PHP: 7.0.2
* Server OS: ubuntu 14.04
* Game version: 1.0.4.1 
* Server host: VPS, ihor.ru
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

There are no messages in console
#### Code
```
//Events are registered, Listener imported
public function check3(ItemFrameDropItemEvent $e){
		$e->setCancelled(true);
		$e->getPlayer()->sendMessage("test");
	}
```

**Comment by eddir** [comment]
You can use DataPacketReceiveEvent to fix this with a plugin. For example:
>public function fixFrame(DataPacketReceiveEvent $event)
>{
>	if($event->getPacket()::NETWORK_ID == Info::ITEM_FRAME_DROP_ITEM_PACKET)
>	{
>		$event->setCancelled();
>		//Your code here (callEvent( new ItemFrameDropItemEvent ) etc.)
>	}
>}

(Киберправославия вам)

**Comment by Bruno99** [comment]
@eddir И вам киберпроваславия

**Comment by badp1g** [comment]
@eddir thanks
Теперь мои картинки будут жить.
(Киберправославия и Вам)

**Comment by ISRAPIL** [comment]
Russian hackers top!

**Comment by ISRAPIL** [comment]
228 AYE

**Comment by AppleDevelops** [comment]
I'll do this. Just need to find the time.
