### ISSUE TITLE
Can't Join server with arc for 1.0.4

### ISSUE THREAD

**Issue by omgA4L** [TesseractTeam/Tesseract#369]
#### Problem description
Can't join the server using the latest src

#### Steps to reproduce the issue
install the src on the server then start the server

#### OS and versions

* Tesseract: Tesseract-1.1.0 Ruby
* PHP: 7.0.3
* Server OS: Ubuntu Linux
* Game version: 1.0.4
* Server host: Dedicated Server from Nocix
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
None
```

**Comment by omgA4L** [comment]
Meant to say src not arc** sorry

**Comment by intagaming** [comment]
You were probably forgot to install PHP binary. Follow the install instruction here:
[http://pocketmine-mp.readthedocs.io/en/latest/installation.html](http://pocketmine-mp.readthedocs.io/en/latest/installation.html)

**Comment by omgA4L** [comment]
Nope the php is updated

**Comment by xZeroMCPE** [comment]
arc lol

**Comment by intagaming** [comment]
Sorry. Are you sure that other version of Tesseract is working fine on your configurations?

**Comment by MCPEGamerJPatGitHub** [comment]
This version is confirmed broken. 

Tested on newest Build

**Comment by AppleDevelops** [comment]
Ive been able to join with no issues
