### ISSUE TITLE
NPC_HELP !

### ISSUE THREAD

**Issue by huybinh2009** [TesseractTeam/Tesseract#370]
CRITICAL> Unhandled exception executing command 'fnpc add teleport 1 survival' in fnpc: Undefined class constant 'DATA_LEAD'
[Tesseract] [11:21:06] CRITICAL> Error: "Undefined class constant 'DATA_LEAD'" (EXCEPTION) in "/plugins/zip_FNPC_v1.1.8_ihWmGXpQIa2t2TT/src/FNPC/npc/NPC" at line 504

**Comment by Driesboy** [comment]
your plugin is outdate

**Comment by huybinh2009** [comment]
But why it works on Elywing

**Comment by intagaming** [comment]
It is not outdated. Every PocketMine forks is different in constants or functions in some point.
Please use IDE with the fork's source as library to seek the unknown field, as this is a plugin's fault.

**Comment by Whatevr** [comment]
elywing plugins are not compatible with tesseract's.. you can't expect plugins to work cross-platform

**Comment by AppleDevelops** [comment]
Elywing plugins aren't compatible

**Comment by huybinh2009** [comment]
Hoang ơi người vn hả


2017-03-13 17:38 GMT+07:00 An Xuan Hoang <notifications@github.com>:
