### ISSUE TITLE
Block IDs Needed Some Fixes

### ISSUE THREAD

**Issue by Qimie** [TesseractTeam/Tesseract#371]
Read First Before You Close This. Also If You Guys Are Too Busy, I Can Try Update The Block IDs & Make A Pull Request.

Steps To Reproduce This Issue:-

1. Get On The Server And Do /give {USERNAME} 322:1 {AMOUNT}
2. If You Check Your Inv Back, It Gives You Regular Golden Apple Not The Enchanted One.
3. This Is Cause Because Of Some Items Doesn't Have Their Own IDs.

* Tesseract: Latest(Just Tested 2 Hours Ago)
* PHP: 7.0.9
* Server OS: IDK What This Means But I'm Using Android Jelly Bean To Make The Server.(Lenovo A850)
* Game version: 1.0.4.1
* Server host: My Phone(Lenovo A850)

**Comment by AppleDevelops** [comment]
It's purposely has it's own id https://github.com/TesseractTeam/Tesseract/blob/master/src/pocketmine/item/ItemIds.php#L221

**Comment by Qimie** [comment]
Update it. Enchanted gapple is appleenchanted now. Not enchanted_golden_apple
