### ISSUE TITLE
cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by Driesboy** [TesseractTeam/Tesseract#372]
#### Problem description

./start.sh: line 73: /root/bin/php7/bin/php: cannot execute binary file: Exec format error
./start.sh: line 73: /root/bin/php7/bin/php: Success
#### Steps to reproduce the issue

idk i have this only on debian 8
#### OS and versions

* Tesseract: latest start.sh
* PHP: 7.0.2
* Server OS: Debian 8
* Game version: /
* Server host: myself
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by AppleDevelops** [comment]
Php binary issue

**Comment by Driesboy** [comment]
ok

**Comment by Driesboy** [comment]
fixed thx i reinstalled it but plz make a wiki for it
