### ISSUE TITLE
Jenkins website for Tesseract Offline

### ISSUE THREAD

**Issue by willamsphp** [TesseractTeam/Tesseract#373]
The download Tesseract´s phar file off line

http://jenkins.tesseractteam.tk:8080/job/Tesseract/lastStableBuild/

off line****

**Comment by IISweePII** [comment]
I just realized about that, I will contact Apple or Zero to see if this can be fixed (i think it has been like that for a while)

**Comment by xZeroMCPE** [comment]
Use this: https://jenkins.imgcl.co/job/Tesseract/

Special thanks to @keithkfng for providing it.
