### ISSUE TITLE
Download .phar

### ISSUE THREAD

**Issue by thekillerby** [TesseractTeam/Tesseract#374]
Where the phar?

**Comment by ZaneWalter** [comment]
Yea same here. Where can I get the .phar file from???

**Comment by intagaming** [comment]
Compile it yourself using DevTools, since travis-ci are not implemented the build release in Tesseract (I guess, because I couldn't find the artifact anywhere) and the jenkins is down. You can run the /src on any OS without popping any problem (at all).

**Comment by xZeroMCPE** [comment]
Use this: https://jenkins.imgcl.co/job/Tesseract/
