### ISSUE TITLE
[ENHANCEMENT][SUGGESTION] Please Implement the full DevTools plugin...

### ISSUE THREAD

**Issue by CortexPE** [TesseractTeam/Tesseract#375]
I know Tesseract has a FolderPluginLoader built onto it...
(That's why I cannot compile a plugin with DevTools or ImagicalDevTools)

But Implementing the full DevTools plugin will help A LOT...
Regarding Building a Server Phar and Developing Plugins Out-Of-The-Box...

~ CortexPE

**Comment by Whatevr** [comment]
https://github.com/TesseractTeam/DevTools
is this what you want?

**Comment by CortexPE** [comment]
I mean, An In-Built DevTools...

**Comment by Driesboy** [comment]
Why

**Comment by CortexPE** [comment]
A FolderPluginLoader is already added but you cannot compile plugins on DevTools because Tesseract already loaded it as a source plugin...

So why not implement the whole DevTools plugin so you can make a server phar and compile plugins on the go....

Without having to either go to pmt.mcpe.me or going to another fork without a folder plugin loader and compiling it there instead.

**Comment by AppleDevelops** [comment]
There's an option to disable folder plugin loader now

**Comment by AnkitM252** [comment]
He mean the devtools command! /makeserver , /makeplugin , /extractplugin ects

**Comment by CortexPE** [comment]
Ok...

But I'd like it if that feature would be added in the future... :)
