### ISSUE TITLE
Join and Respawn glitch

### ISSUE THREAD

**Issue by FunnyBuddys** [TesseractTeam/Tesseract#379]
#### Problem description

When i Join or Respawn, sometimes i bug/glitch in the ground

#### Steps to reproduce the issue

Try to Join and Respawn

#### OS and versions

* Tesseract: https://github.com/TesseractTeam/Tesseract/commit/9b00fcb6cf5781869dde78ecbacec6dc5d2f76e3
* PHP: 7.0.2
* Server OS: Ubuntu 14.10
* Game version: v1.0.4.1
* Server host: I don't know what this mean xD IP? ( Antoxia.net )
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by xZeroMCPE** [comment]
This issue is caused because of this commit [here](7f2e464b158201cdd08477a14cb3ec8a42d668dc)

**Comment by AppleDevelops** [comment]
I think I fixed the issue

**Comment by NFGamerMC** [comment]
Looks fixed to me!
