### ISSUE TITLE
Rails don't work [Tesseract 1.0.5]

### ISSUE THREAD

**Issue by SergeyIvanov14** [TesseractTeam/Tesseract#381]
#### Problem description
Rail don't connect if rail is a above 1 block.

#### Steps to reproduce the issue
Place rails.

#### OS and versions

* Tesseract:
* PHP:
* Server OS:
* Game version: 
* Server host:
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by caspervanneck** [comment]
this is knowen issue @SergeyIvanov14

**Comment by ISRAPIL** [comment]
О, Сережа
