### ISSUE TITLE
Entity despawn bug

### ISSUE THREAD

**Issue by LucGamesDE** [TesseractTeam/Tesseract#382]
If I despawn entities, they don't despawn correctly.
They only despawn for the player who joined first. All other players see them.

This happens if I use $entity->kill() or $entity->close();

 OS and versions

Tesseract: 1.1.0 Ruby (Protocol: 102)
PHP: 7.0.9
Server OS: Windows 10
Game version: MCPE 1.0.4
Server host: My windows computer

*Edit:
$entity->despawnFromAll() also isn't working

**Comment by AppleDevelops** [comment]
Fixed in latest version
