### ISSUE TITLE
Tesserekt 1.0.5 SetTitle

### ISSUE THREAD

**Issue by thebigsmileXD** [TesseractTeam/Tesseract#383]
IDGAF about templates.

https://github.com/TesseractTeam/Tesseract/blob/1.0.5/src/pocketmine/network/protocol/SetTitlePacket.php#L31
It "despawns" the title from a player

https://github.com/TesseractTeam/Tesseract/blob/1.0.5/src/pocketmine/network/protocol/SetTitlePacket.php#L32
This one is to remove a line. You can spawn a title, and a subtitle, and you can for example clear the subtitle with this.

https://github.com/TesseractTeam/Tesseract/blob/1.0.5/src/pocketmine/network/protocol/SetTitlePacket.php#L39
Speed

**Comment by AppleDevelops** [comment]
Follow the template, they'll close it otherwise. You like making issues on "Tesserekt"? Instead of making issues here, go make issues on ClearShit.

**Comment by xinghao2003** [comment]
@AppleDevelops ClearSky -.- ,not ClearShit

**Comment by thebigsmileXD** [comment]
If, then its MessySky

Apple, did you notice many people have issues with you?

@xZeroMCPE Sorry for trying to help this fork. Sure plenty people use it, but hey.. Helping is useless on a (readme: ) spoon, because everything is handeled like on ImagicalCorp

**Comment by AppleDevelops** [comment]
@thebigsmileXD Plenty of people have issues with me, just as people have issues with you.

**Comment by thebigsmileXD** [comment]
Thats true, we should create a gang 'the super pm villians'.
But i help ~ 50 people in our group every day ;) https://t.me/joinchat/AAAAAD88JwKTn1d9XrS1xA
