### ISSUE TITLE
Please Add Command Blocks!

### ISSUE THREAD

**Issue by caspervanneck** [TesseractTeam/Tesseract#384]
shuld be great for any server so plz add it for mcpe 1.0.5 beta branch and it shuld be cool if its fully working

**Comment by Qimie** [comment]
Needs a long time to add it bc com. block is hard to code. I think at
least.. xd

**Comment by caspervanneck** [comment]
@Qimie i know its hard ):

**Comment by LagHD** [comment]
I want this feature too, it'll be great!

**Comment by AnkitM252** [comment]
We need Redstone at first for the Command Blocks!

**Comment by NFGamerMC** [comment]
I am going to change the title so this is not spam!

**Comment by NFGamerMC** [comment]
Please report this or request it [here](http://bit.ly/TesseractRequests)
