### ISSUE TITLE
Signs and Endrods and more items get flipped

### ISSUE THREAD

**Issue by Ishannaik** [TesseractTeam/Tesseract#385]
Tesseract: b8a4c17
PHP: 7.0.9
Server OS: Windows 10
Game version: MCPE 1.0.4
Server host: VPS
Signs endrods and some items get fliped when i type a sign it gets flipped from front to backside...

**Comment by AnkitM252** [comment]
Close?

**Comment by AydarTop** [comment]
@AnkitM252 Yes, I don't have this bug. Tested this latest Tesseract version
