### ISSUE TITLE
Glowstone doesn't light completely

### ISSUE THREAD

**Issue by poustmal** [TesseractTeam/Tesseract#386]
* Tesseract: latest(commit b8a4c17b)
* PHP:7.0.3
* Server OS: android
* Game version: 1.0.4
* Server host:(my tablet)

You can see in this picture:

**Comment by poustmal** [comment]
![screenshot_2017-03-16-14-44-19](https://cloud.githubusercontent.com/assets/22281205/24021572/5013dd44-0aaa-11e7-8545-5e8fb83c8112.png)

**Comment by ImagicalGamer** [comment]
Try tapping the glowstone.

**Comment by poustmal** [comment]
I have already done this and works temporary,but when time goes again to night,again glowstone doesn't lights.
