### ISSUE TITLE
Image map

### ISSUE THREAD

**Issue by SergeyIvanov14** [TesseractTeam/Tesseract#387]
#### Problem description
ClientboundMapItemDataPacket don't work, image is null.

#### OS and versions

* Tesseract:
* PHP:
* Server OS:
* Game version: 
* Server host:
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```
1[. ](`

> url

`)

**Comment by eddir** [comment]
I have some problem with 1.0.5 . What version of MCPE are you using?
