### ISSUE TITLE
warning + the game has no sounds

### ISSUE THREAD

**Issue by mote166** [TesseractTeam/Tesseract#388]
#### Steps to reproduce the issue

idk
#### OS and versions

* Tesseract: Tesseract-1.1.0 Ruby
* PHP: 7.0.13
* Server OS: linux 
* Game version: 1.0.4.1
* Server host: blockshost.com
<br><br>
im using this hosting site : https://blockshost.com
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
Warning: assert(): Movement distance is excessive: dx=0, dy=-30.3788, dz=0 failed in phar:///jar/versions/Tesseract/tesseract104.phar/src/pocketmine/entity/Entity.php on line 1478
```

**Comment by mote166** [comment]
i just had this message right before the server freezed :


18.03 01:11:12 [Server] INFO Warning: assert(): Movement distance is excessive: dx=1520.3741, dy=-56, dz=-1022.3582 failed in phar:///jar/versions/Tesseract/tesseract104.phar/src/pocketmine/entity/Entity.php on line 1478

**Comment by Driesboy** [comment]
is this error back???

**Comment by mote166** [comment]
@Driesboy  what?

**Comment by mote166** [comment]
are you guys willing to fix this issue or ur going to ignore it and act like u saw nothing?! my server keeps on freezing right after i get this error in the console .

**Comment by ImagicalGamer** [comment]
We are looking into this issue! @AppleDevelops I thought you fixed that.
