### ISSUE TITLE
World/level issue

### ISSUE THREAD

**Issue by SirOptic** [TesseractTeam/Tesseract#39]
Hey, I've updated to latest tesseract there seem to be a bug where it spams console saying "Could not tick level "world": call to a member function getValue() on null"

**Comment by AppleDevelops** [comment]
Enable debugging

**Comment by Shadow166050** [comment]
I have this same issue

**Comment by xZeroMCPE** [comment]
Which branch? and follow the issue template!

**Comment by SirOptic** [comment]
I'm sorry I will follow it next time and, on the main branch.

**Comment by ivan691** [comment]
It appears when you have mobs at map
It needs to be fixed

**Comment by andris155** [comment]
https://github.com/TesseractTeam/Tesseract/issues/48

**Comment by Dhrhciebcy** [comment]
I have the same problem and I haven't mobs in my world

**Comment by Rateek** [comment]
fix https://github.com/TesseractTeam/Tesseract/commit/e895c7403faa8fe0ecbb235ed6c0c17504f3410f
