### ISSUE TITLE
cant join my server it saying unable to connect to the world!

### ISSUE THREAD

**Issue by AmrSlayer** [TesseractTeam/Tesseract#396]
> 

> [`<!---`](url)

 BEFORE CREATING THIS ISSUE, CHECK OUR PROJECTS TO SEE IF IT IS ALREADY ADDED to ToDo! -->

#### OS and versions

* Tesseract:
* PHP:
* Server OS:
* Game version: 
* Server host:
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by AmrSlayer** [comment]
it wont work my server is port-forward and it still dont work what do i do? someone please help i been looking for 3 weeks how to fix it?

**Comment by AmrSlayer** [comment]
its on and running but it wont let me join but i could join it form my phone??

**Comment by Whatevr** [comment]
is both the host and ur device both connected to the internet?

**Comment by ISRAPIL** [comment]
unlink tesseract.yml

**Comment by AmrSlayer** [comment]
Whatevr yes and when my server is run i cant join it or any other servers and also ISRAPIL i tried no luck

**Comment by AppleDevelops** [comment]
It's hard for me to explain but portforwarded servers aren't the good way to go

**Comment by AmrSlayer** [comment]
@AppleDevelops i could join from my phone but not my w10 why? im port fowrd and the server is runing good

**Comment by AppleDevelops** [comment]
https://github.com/iTXTech/Genisys/wiki/FAQs
