### ISSUE TITLE
Blocks are not broken with EFFICIENCY Enchantment

### ISSUE THREAD

**Issue by Prisane** [TesseractTeam/Tesseract#401]
#### Problem description
I showed the problem with the video
https://www.youtube.com/watch?v=Jru4svI2zoo&feature=youtu.be
Please offer me a temporary solution

#### OS and versions

* Tesseract: Latest commit [323500b](https://github.com/TesseractTeam/Tesseract/tree/323500b0b931f26c948ffe8ee2a7bea4851f022e)
* PHP: 7 
* Server OS: linux
* Game version: PE/Win10

```

**Comment by AydarTop** [comment]
In tesseract.yml:
allow-instabreak: true

**Comment by Prisane** [comment]
Thanks solved
