### ISSUE TITLE
Iron Trapdoor can be opened by hand

### ISSUE THREAD

**Issue by intagaming** [TesseractTeam/Tesseract#402]
#### Problem description

By the title
#### Steps to reproduce the issue

What do you expecting?

#### OS and versions

* Tesseract: 323500b
* PHP: 7.0.3
* Server OS: Windows
* Game version: 1.0.4
* Server host: Server
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by AppleDevelops** [comment]
No redstone system so that's why.

**Comment by sero583** [comment]
@AppleDevelops Vanilla MC:PE also didnt allowed to use them at no-redstone times, so tesseract should too atm
