### ISSUE TITLE
Critical Error when Run

### ISSUE THREAD

**Issue by NFGamerMC** [TesseractTeam/Tesseract#404]
#### Problem description
When I start Tesseract using ./start.sh it will run but there is an error that says that there was an error? Click [here](https://s16.postimg.org/sawvue9p1/BUG.png) for a example

#### Steps to reproduce the issue
Run Tesseract using the Latest Phar from the repo

#### OS and versions
* Tesseract: Latest from GitHub
* PHP: 7.0
* Server OS: Ubnutu 16.0
* Game version: 1.0.4.11
* Server host: DigitalOcean

#### Crashdump, backtrace, memory dumps, plugins list or other files
No Crashsdumps

**Comment by ImagicalGamer** [comment]
Please remove all plugins and try booting up the server again, it is mostlikely a Plugin issue/

**Comment by AppleDevelops** [comment]
Plugin issue

**Comment by NFGamerMC** [comment]
Okay, I willl make another request if that doesn't work.
