### ISSUE TITLE
server freeze

### ISSUE THREAD

**Issue by mote166** [TesseractTeam/Tesseract#408]
#### Problem description

I don't know how this is happening but this error shows on the console before the server freezes and theres lag when that error show in the console
#### Steps to reproduce the issue

no idea it just happens
#### OS and versions

* Tesseract: Tesseract-1.1.0 Ruby
* PHP: 7.0.13
* Server OS: linux
* Game version: 1.0.4.1
* Server host: blockshost.com
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
Warning: assert(): Movement distance is excessive: dx=622.8956, dy=-56, dz=-512.3959 failed in phar:///jar/versions/Tesseract/tesseract104.phar/src/pocketmine/entity/Entity.php on line 1478
```
are u guys going to fix this or not? im really sick of people calling me and saying that my server has freezed again , DUDE IM LOSING MY PLAYERS :(  . if this is duplicated as u might say . give me the link to the other issue .

**Comment by caspervanneck** [comment]
it can be a plugin @mote166

**Comment by mote166** [comment]
@caspervanneck no i don't think so .

**Comment by Driesboy** [comment]
remove that line
i did it to

**Comment by mote166** [comment]
@Driesboy  @caspervanneck can u guys do it on the 1.0.5 branch ? cuz im updating to that branch now.

**Comment by mote166** [comment]
nvm imma do it myself

**Comment by mote166** [comment]
@driesboy are you sure this won't cause any error?

**Comment by RTGDaCoder** [comment]
Let me know if any error comes up

**Comment by mote166** [comment]
this issue has been fixed . just remove the line and this error will disappear.  thanks @Driesboy
