### ISSUE TITLE
Timings report

### ISSUE THREAD

**Issue by Infernus102** [TesseractTeam/Tesseract#409]
#### Problem description

New Timings domain is not working. Can you guys just roll it back to Aikar?
#### Steps to reproduce the issue

Go to the /timings paste website
#### OS and versions

* Tesseract: 1.1.0 [#28c996 2017-03-23] Ruby
* PHP: 7.0.10
* Server OS: Linux
* Game version: 1.0.4
* Server host: VG
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
None
```

**Comment by Driesboy** [comment]
aikar v1 is not working!

**Comment by Infernus102** [comment]
well mcpetimings isn't working either

**Comment by keithkfng** [comment]
Try timings.imgcl.co

**Comment by xZeroMCPE** [comment]
Will be fixed tomorrow.

**Comment by AnkitM252** [comment]
Should we add the pmmp new timings host?

**Comment by Driesboy** [comment]
yes
