### ISSUE TITLE
Client crash at player join

### ISSUE THREAD

**Issue by AndreySK4** [TesseractTeam/Tesseract#41]
When I join my server,the client crashes
#### OS and versions

* Tesseract: 1.2.0 Ruby
* PHP: 7.0.17
* Server OS: Ubuntu 14.04 LTS
* Game version: MCPE 1.1.0.55

**Comment by AndreySK4** [comment]
I don't have any error in the console

**Comment by Prisane** [comment]
Update your pureperms.

**Comment by AndreySK4** [comment]
Thanks
