### ISSUE TITLE
LoginPacket

### ISSUE THREAD

**Issue by Infernus102** [TesseractTeam/Tesseract#410]
#### Problem description

Don't know what caused this, this errors poped up on console
24.03 08:53:15 [Server] CRITICAL InvalidArgumentException: "Must have exactly 16 bytes" (EXCEPTION) in "/src/pocketmine/utils/UUID" at line 66
24.03 08:53:15 [Server] INFO Notice: Uninitialized string offset: 48 in phar:///home/multicraft/jar/pocketmine/tesseract/1.0.4/Tesseract.phar/src/pocketmine/network/protocol/LoginPacket.php on line 162
24.03 08:53:15 [Server] INFO Notice: Uninitialized string offset: 48 in phar:///home/multicraft/jar/pocketmine/tesseract/1.0.4/Tesseract.phar/src/pocketmine/network/protocol/LoginPacket.php on line 161
24.03 08:53:15 [Server] INFO Notice: Uninitialized string offset: 0 in phar:///home/multicraft/jar/pocketmine/tesseract/1.0.4/Tesseract.phar/src/pocketmine/network/protocol/LoginPacket.php on line 160
24.03 08:53:15 [Server] INFO Notice: Uninitialized string offset: 0 in phar:///home/multicraft/jar/pocketmine/tesseract/1.0.4/Tesseract.phar/src/pocketmine/network/protocol/LoginPacket.php on line 159
24.03 08:53:15 [Server] INFO Notice: Undefined offset: 2 in phar:///home/multicraft/jar/pocketmine/tesseract/1.0.4/Tesseract.phar/src/pocketmine/network/protocol/LoginPacket.php on line 154
24.03 08:53:15 [Server] INFO Notice: Undefined offset: 1 in phar:///home/multicraft/jar/pocketmine/tesseract/1.0.4/Tesseract.phar/src/pocketmine/network/protocol/LoginPacket.php on line 154
24.03 08:53:15 [Server] INFO Warning: unpack(): Type V: not enough input, need 4, have 0 in phar:///home/multicraft/jar/pocketmine/tesseract/1.0.4/Tesseract.phar/src/pocketmine/utils/Binary.php on line 235
24.03 08:53:15 [Server] INFO Notice: Trying to get property of non-object in phar:///home/multicraft/jar/pocketmine/tesseract/1.0.4/Tesseract.phar/src/pocketmine/network/protocol/LoginPacket.php on line 71
24.03 08:53:15 [Server] INFO Warning: unpack(): Type V: not enough input, need 4, have 0 in phar:///home/multicraft/jar/pocketmine/tesseract/1.0.4/Tesseract.phar/src/pocketmine/utils/Binary.php on line 235
24.03 08:53:15 [Server] INFO Warning: zlib_decode(): data error in phar:///home/multicraft/jar/pocketmine/tesseract/1.0.4/Tesseract.phar/src/pocketmine/network/protocol/LoginPacket.php on line 65
#### Steps to reproduce the issue

idk
#### OS and versions

* Tesseract: 1.1.0 [#28c996 2017-03-23] Ruby
* PHP: 7.0.10
* Server OS: Linux
* Game version: 1.0.4
* Server host: VG
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by mote166** [comment]
i have the same issue .

**Comment by RateekMCPE** [comment]
Use last version Tesseract .
