### ISSUE TITLE
Snow stays and without snowing

### ISSUE THREAD

**Issue by poustmal** [TesseractTeam/Tesseract#411]
-->
* Tesseract: 128c9960
* PHP: 7.0.3
* Server OS: Android
* Game version: 1.0.4
* Server host:my tablet

I think that doesn't happens this in mcpe vanilla.

**Comment by poustmal** [comment]
![screenshot_2017-03-24-19-23-34](https://cloud.githubusercontent.com/assets/22281205/24306180/52f041b4-10c8-11e7-92f3-a6b1fde90d08.png)

**Comment by poustmal** [comment]
When world reloads,snow is appearing again in biome,I think you understand,and I was trying to remove it with water,lagg..

**Comment by mote166** [comment]
did u install any snow plugin? cuz i did it once and i had this issue

**Comment by poustmal** [comment]
No,Server has support of raining/snowing,so no.

**Comment by AppleDevelops** [comment]
Snow is handled by the client #BlameShoghicp
