### ISSUE TITLE
Pearls used to work on my server but not anymore ;(

### ISSUE THREAD

**Issue by XDqrkneZ** [TesseractTeam/Tesseract#413]
#### Problem description
 Pearls used to work on my server but not anymore ;(

#### OS and versions

* Tesseract: 1.1.0 
* PHP: PHP version; 7.0.3
* Server OS: Debian 8 64 bits
* Game version: 1.0.4
* Server host: OVH
its being hosted on a VPS from OVH
#### Crashdump, backtrace, memory dumps, plugins list or other files

``` here are my plugins, sorry if this don't help but i tried http://paste.ubuntu.com/24242331/
```

**Comment by AppleDevelops** [comment]
Stop spamming issues

**Comment by XDqrkneZ** [comment]
apple this is not a spam -_- i reposted it because the other one didn have
template or any information about my server
