### ISSUE TITLE
[REPOST] since the my other issue post did not have any info

### ISSUE THREAD

**Issue by XDqrkneZ** [TesseractTeam/Tesseract#414]
Problem description

Pearls used to work on my server but not anymore ;(
Steps to reproduce the issue

OS and versions

Tesseract: 1.1.0
PHP: PHP version; 7.0.3
Server OS: Debian 8 64 bits
Game version: 1.0.4
Server host: OVH
its being hosted on a VPS from OVH

**Comment by MCPEGamerJPatGitHub** [comment]
You're doing something wrong
