### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by huybinh2009** [TesseractTeam/Tesseract#415]
CRITICAL> "Could not pass event 'pocketmine\event\entity\EntityTeleportEvent' to 'NPC v1.4': Call to a member function getFolderName() on null on onebone\npc\Main
[Tesseract] [14:50:35] CRITICAL> Error: "Call to a member function getFolderName() on null" (EXCEPTION) in "/NPC/src/onebone/npc/Main" at line 115

**Comment by Driesboy** [comment]
Plugin bug

**Comment by huybinh2009** [comment]
thank :)) do you have link stable NPC no
and plz give me SkyBlock :)))
thank again <3

**Comment by Driesboy** [comment]
slapper

**Comment by erkam2002** [comment]
https://github.com/fengberd/FNPC
