### ISSUE TITLE
Loading multiple worlds at startup

### ISSUE THREAD

**Issue by MCPEGamerJPatGitHub** [TesseractTeam/Tesseract#420]
#### Problem description
Cannot load multiple worlds at startup

#### Steps to reproduce the issue
1. Use the latest Tesseract phar to start server.
2. Edit pocketmine.yml under the worlds section for worlds you want to load at the same time.
3. Restart your server, and you will see that it isn't loaded.

#### OS and versions
* Tesseract: 1.1.0
* PHP: 7.0.3
* Server OS: Unknown
* Game version: 1.0.4
* Server host: MinersPlanet, using custom phar from Jenkins
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files
None
```
```

**Comment by MCPEGamerJPatGitHub** [comment]
I see that there are plans to delete pocketmine.yml, although I do not know any other way of making this work.

**Comment by ISRAPIL** [comment]
```
public function loadAllLevel(){
   $dir = $this->getServer()->getDataPath()."worlds";
   $files = scandir($dir);
   foreach($files as $file){
      $this->getServer()->loadLevel($file);
   }
}
```

**Comment by AppleDevelops** [comment]
It's working on my end

**Comment by MCPEGamerJPatGitHub** [comment]
@AppleDevelops weird.

**Comment by MCPEGamerJPatGitHub** [comment]
@ISRAPIL that is useless

**Comment by MCPEGamerJPatGitHub** [comment]
update: solved by changing some files.
