### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by NycuRO** [TesseractTeam/Tesseract#421]
#### Problem description

Warning: yaml_parse(): reading error encountered during parsing: invalid leading UTF-8 octet (line 1, column 1) in /root/hub/src/pocketmine/utils/Config.php on line 142

#### Steps to reproduce the issue

1) Start server
2) Get error
#### OS and versions

* Tesseract: https://github.com/TesseractTeam/Tesseract/commit/128c9960eaf2b78fb80f5cf69f3f5405daa352e4
* PHP: 7.0.17
* Server OS: Linux
* Game version: 1.0.4
* Server host: gazduirejocuri.ro
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by AppleDevelops** [comment]
plugin issue

**Comment by NycuRO** [comment]
@AppleDevelops Can you help me what plugin?
