### ISSUE TITLE
/op and /deop bug

### ISSUE THREAD

**Issue by AndreySK4** [TesseractTeam/Tesseract#428]
[Tesseract] [03:44:38] INFO> [Comenzi] <CONSOLE> /d
eop cartof                                         
[Tesseract] [03:44:38] INFO> An unknown error occur
red while attempting to perform this command       
[Tesseract] [03:44:38] CRITICAL> Unhandled exceptio
n executing command 'deop cartof' in deop: Return v
alue of pocketmine\Server::getOfflinePlayer() must 
be an instance of pocketmine\nbt\tag\CompoundTag, i
nstance of pocketmine\OfflinePlayer returned       
[Tesseract] [03:44:38] CRITICAL> TypeError: "Return
 value of pocketmine\Server::getOfflinePlayer() mus
t be an instance of pocketmine\nbt\tag\CompoundTag,
 instance of pocketmine\OfflinePlayer returned" (EX
CEPTION) in "/src/pocketmine/Server" at line 748

* Tesseract: e7a626e
* PHP: 7.0.16
* Server OS: Ubuntu 14.04 LTS
* Game version: Android 1.0.4
* Server host: VPS

**Comment by shdudwns** [comment]
meㅠㅠ
