### ISSUE TITLE
Titles dont work in 1.0.5

### ISSUE THREAD

**Issue by DelxHQ** [TesseractTeam/Tesseract#434]
#### Problem description

  $event->getPlayer()->sendTitle("Welcome to", "DelxCraft!");
This does not work on the latest update.

#### OS and versions

* Tesseract: 1.1.0
* PHP: PHP7
* Server OS: Windows 10
* Game version: 1.0.5
* Server host: N/A
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by AnkitM252** [comment]
Did you send on join?

**Comment by DelxHQ** [comment]
Yes

**Comment by SuperMaXAleX** [comment]
Okay, something changed, it will be fixed soon

**Comment by ImagicalGamer** [comment]
Some functions cannot be used when a player joins the server! Try using a DelayedTask 10 ticks after they join and send it.

**Comment by SinlesFlyer376** [comment]
Is this updated to 1.0.5?

**Comment by AppleDevelops** [comment]
Yes

**Comment by NycuRO** [comment]
@AppleDevelops Code of Packet is incorrect :P

**Comment by RateekMCPE** [comment]
@NycuRO THE TEXTURE PACK 1.0.4 = TITLE NOT WORK (GO WITH NO TEXTURE PACK) :)

**Comment by RateekMCPE** [comment]
https://github.com/TesseractTeam/Tesseract/commit/6e65c2da8d6a54d17c0ecb8cc13bbfc72f485589
Fix ! :) Title is work on Tesseract now.

**Comment by AnkitM252** [comment]
@RateekMCPE It would be an issue but you can do it by adding scheduleDelayedTask which runs after 3-5 secs of player join!

Example:
```php
public function onJoin(PlayerJoinEvent $event){
 $this->getServer()->getPluginManager()->getScheduler()->scheduleDelayedTask(new ShowTask($this, $event->getPlayer()), 60); //60 or 80!
}
//Use sendTitle on ShowTask class!
`

**Comment by RateekMCPE** [comment]
@AnkitM252 I wanted to say that if you have a pack in 1.0.4 you do not see the Titles, if you do sendTitle () it works after may be with the Task it's bug ..

**Comment by AnkitM252** [comment]
Oh, Got it! BTW There is a bug with sendTitle it doesn't shows up until you set delayed task!

**Comment by RateekMCPE** [comment]
@AnkitM252 Oh ok fix soon :/

**Comment by AnkitM252** [comment]
I think its a bug with mojang! Cause Max told that after 1.0.4 update, The loading screen stays for a little long time!
