### ISSUE TITLE
How can I make a Tesseract.phar?

### ISSUE THREAD

**Issue by PluginBOXone** [TesseractTeam/Tesseract#437]
How can I make a Tesseract.phar from all these Datas? LG!

**Comment by AydarTop** [comment]
@PluginBOXone Use DevTools plugin.

**Comment by DelxHQ** [comment]
run /makeserver from console or ingame

**Comment by PluginBOXone** [comment]
And where do i have to input the files? (In plugin folder or i dont know)

**Comment by ImagicalGamer** [comment]
Jenkins is currently not working, download the .zip of Tesseract and import the /src into your server folder, delete your old .phar and startup the server and run the src. You can also run /makeserver while running the src and DevTools will generate a .phar of Tesseract.
