### ISSUE TITLE
Generator Error

### ISSUE THREAD

**Issue by KennFatt** [TesseractTeam/Tesseract#441]
#### Problem description

Generator with name "Normal2" (i've just tested only normal2) and then this error happen. Please to someone who was working on this project, please to test your code first then create a pull request :(

#### OS and versions

* Tesseract: [e3208c14c5dbe4ed75023d9f484a9449596ff4da](https://github.com/TesseractTeam/Tesseract/commit/e3208c14c5dbe4ed75023d9f484a9449596ff4da)
* PHP: 7.0
* Server OS: Ubuntu 16
* Game version: 1.0.5
* Server host: localhost
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
> Error: "Call to a member function getBiomeId() on null" (EXCEPTION) in "/src/pocketmine/level/generator/normal/populator/GroundCover" at line 41
> Could not execute asynchronous task PopulationTask: Task crashed
```

**Comment by caspervanneck** [comment]
@KennFatt  yes i wasent done whit it so

**Comment by KennFatt** [comment]
of course it was since #292

**Comment by KennFatt** [comment]
![default-generator](https://cloud.githubusercontent.com/assets/10755895/24454430/0bcf3726-14b6-11e7-9683-954152e1a6bd.png)
_a mesa biome on default generator..._
