### ISSUE TITLE
Lava on join! 1.0.5 bug

### ISSUE THREAD

**Issue by intagaming** [TesseractTeam/Tesseract#442]
#### Problem description

Players start clicking their hand while holding lava, which was automatically given to the player onJoin.

#### Steps to reproduce the issue

1.0.5 version of Tesseract. (e3208c1)

#### OS and versions

* Tesseract: e3208c1
* PHP: 7.1
* Server OS: Windows
* Game version: 1.0.5 official
* Server host: Server
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by AnkitM252** [comment]
This might be a plugin issue!

**Comment by intagaming** [comment]
Oh okay! Disabled all the plugins and that works.
On hold..

**Comment by intagaming** [comment]
Even if i re-enabled it, it disappears! What bizzare..
