### ISSUE TITLE
Arm hits every 10 seconds automatically!

### ISSUE THREAD

**Issue by PluginBOXone** [TesseractTeam/Tesseract#443]
Hey! Every 10 Seconds the player hits and gets a sandblock while hiting! (It hits automatically but doesnt brake blocks!) --> Sorry for bad english! I am german xD ! <--

* Tesseract: Newest version!
* PHP: 7
* Server OS: Codename "Ruby"
* Game version: 1.0.5
* Server host: ---

**Comment by XDqrkneZ** [comment]
ikr

**Comment by McGrimmi** [comment]
Same problem. And still no sounds :/

**Comment by PluginBOXone** [comment]
Solved! You have to delete the Plugin : BossBarAnnouncement and BossBarAPI !
