### ISSUE TITLE
Server fails load - 1.0.5

### ISSUE THREAD

**Issue by MCPEGamerJPatGitHub** [TesseractTeam/Tesseract#448]
#### Problem description
phar created by dev tools crash
#### Steps to reproduce the issue
1. convert source file into phar using devtools
2. run server, but crashes with error below
#### OS and versions

* Tesseract: 1.2.0
* PHP: 7.0.3
* Server OS: linux
* Game version: 1.0.5
* Server host: custom phar hosted
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

 Fatal error: require_once(): Failed opening required 'phar:///custom-phar.phar/src/pocketmine/PocketMine.php' (include_path='.:/jar/php-build-scripts-master/lib/php') in /custom-phar.phar on line 1
29.03 21:13:31 [Server] INFO Warning: require_once(phar:///custom-phar.phar/src/pocketmine/PocketMine.php): failed to open stream: in phar "/custom-phar.phar", manifest claims to have zero entries.  Phars must have at least 1 entry in /custom-phar.phar on line 1
```
```

**Comment by AnkitM252** [comment]
Use this DevTools: https://github.com/TesseractTeam/DevTools
