### ISSUE TITLE
BanCommand Problems

### ISSUE THREAD

**Issue by Prisane** [TesseractTeam/Tesseract#450]
#### Problem description

1. When player is banned, it won't kick game if it is online (Fixed)

2. When player is join the game, the ban reason not shown correctly

#### Steps to reproduce the issue

_1. Issues:_ (Fixed)
Join the game, use "/ban yourname test test" command

_2. Issues:_
prisane|2017-03-30 14:16:04 +0400|CONSOLE|Forever|test test
This prisane is reason "test test" but on join kick message "Banned by an operator." this is not true

#### OS and versions

* Tesseract: This commit [885e790](https://github.com/TesseractTeam/Tesseract/commit/885e7904c4b91aeab663beafc8296b6cb3789492)
* PHP: 7 
* Server OS: linux
* Game version: PE/Win10
<br><br>
```

**Comment by LordJoshie** [comment]
the ban command no longer handles kicks... I recall reading that somewhere in older commits. 

and yeah, I've also noticed it doesn't show the reason given, just "Banned by an operator" or something....

**Comment by Prisane** [comment]
Problem 1 fixed. @AppleDevelops

**Comment by RateekMCPE** [comment]
Is fixed. !
