### ISSUE TITLE
Console notice?

### ISSUE THREAD

**Issue by bulutsun** [TesseractTeam/Tesseract#451]
* Tesseract: Lastest
* PHP: 7
* Server OS: Windows
* Game version: 1.0.4
* Server host:

on console Notice: A non well formed numeric value encountered in C:\Users\Administrator\Desktop\TurkMCPE Network Factions Sunucusu\src\pocketmine\item\Item.php on line 330

How to fix?

**Comment by AnkitM252** [comment]
Plugin issue

**Comment by bulutsun** [comment]
How can i hide this notice?

**Comment by bulutsun** [comment]
I cant find error. How find?

**Comment by AnkitM252** [comment]
We don't know what are the plugin you are using!!
We help peoples with our software only not any other plugins!
