### ISSUE TITLE
1.0.5 World Height = 128 ?

### ISSUE THREAD

**Issue by LordJoshie** [TesseractTeam/Tesseract#452]
since 1.0.5, any world I generate has a 128 build height cap. 

just notifying.
in case I'm not the only one with this issue.

**Comment by Driesboy** [comment]
in mc or in your server?

**Comment by LordJoshie** [comment]
any worlds generated by tesseract, on my server.

**Comment by AppleDevelops** [comment]
Cannot reproduce
