### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Driesboy** [TesseractTeam/Tesseract#453]
#### Problem description

After a few a random time the server give a segmentatoin fault

Since 1.0.5 update i do not use setTittle btw

#### Steps to reproduce the issue

Idk

#### OS and versions

* Tesseract: https://github.com/TesseractTeam/Tesseract/commit/bc6c95123a845c1bfcd02f2bd7202f9dec11f7b4
* PHP: 7.0.17 and 7.0.6
* Server OS: Windows
* Game version: 1.0.5
* Server host: Myself
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by AnkitM252** [comment]
Give us the whole error!

**Comment by Driesboy** [comment]
only 
```
[Tesseract] [21:30:55] INFO> JuanPablo608[/186.158.137.0:63366] [ClientID: -1.7725149736252E+18] logged in with entity id 1870 at (Lobby, -1, 77, 9)
[Tesseract] [21:31:00] INFO> KillerStones_6[/200.77.131.128:0] [ClientID: 6.5133930456881E+18] logged in with entity id 1874 at (Lobby, -1, 77, 9)
[Tesseract] [21:31:00] INFO> Preparing level "ice"
bin\php\php.exe: Exit 127
```

**Comment by Driesboy** [comment]
its not a specefic world that world has been restarted

**Comment by AnkitM252** [comment]
I think it is php! If your on windows try this: https://github.com/TesseractTeam/Installation-Binariesx86

**Comment by Driesboy** [comment]
already used

**Comment by RateekMCPE** [comment]
What.. It's not Tesseract. I have test and is no problem

**Comment by Driesboy** [comment]
and i have it without plugins and the official bin!
