### ISSUE TITLE
Minecarts don't appear

### ISSUE THREAD

**Issue by DobberHockeyCom** [TesseractTeam/Tesseract#455]
This worked prior to the latest update I just put in, though the Minecarts hovered above the tracks. Now, after the mod update, they don't appear at all.

Minecraft PE 1.0.5, latest Tesseract update

Also - tracks no longer point north/south. They only point east/west and will not curve and point the other way.

**Comment by JunkDaCoder** [comment]
doesnt this have something to do with redstone?

**Comment by DobberHockeyCom** [comment]
That's another issue. Redstone doesn't power the rails, The cart just goes full speed automatically (back when the cart actually appeared). Low priority. The key here is for the minecart to actually appear, and for the rails to be able to face the other way. I've held off building my tracks for now. I love building tracks around the world, through tunnels, etc for my daughters to get a kick out of when they play

**Comment by DobberHockeyCom** [comment]
PS - Nought57: this is not a duplicate issue. The rails worked fine last update, and the cart appeared (they just hovered). This update, they no longer work.

**Comment by RateekMCPE** [comment]
Fix soon
