### ISSUE TITLE
Server is lagging since 1.0.5

### ISSUE THREAD

**Issue by Driesboy** [TesseractTeam/Tesseract#457]
#### Problem description

https://timings.pmmp.io/?url=24286633

#### Steps to reproduce the issue

https://timings.pmmp.io/?url=24286633

#### OS and versions

* Tesseract: 885e790 
* PHP: 7.0.9
* Server OS: Windows
* Game version: 1.0.5
* Server host: myself
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by MateiGamingYTB** [comment]
Yeah i remarked this

**Comment by NycuRO** [comment]
Jail plugin issue.

And use other config for no lag ;)

**Comment by AppleDevelops** [comment]
This is a plugin issue, you have multiple repeating tasks that lag the server.

**Comment by Driesboy** [comment]
but its only since 1.0.5
