### ISSUE TITLE
Titles dont work

### ISSUE THREAD

**Issue by ISRAPIL** [TesseractTeam/Tesseract#458]
`$event->getPlayer()->sendTitle("CloudMine", "Обновления почти каждый день!");`

**Comment by AnkitM252** [comment]
Schedule a delayed task on join!

**Comment by GamakCZ** [comment]
I have the same problem.

console:
`[Tesseract] [19:18:48] CRITICAL> Error: "Call to undefined method pocketmine\Player::sendTitle()" (EXCEPTION) in "/SwagCore.phar/src/SwagCore/Main" at line 1011`

code:
`class TitleTask extends PluginTask {
    /** @var Main  */
    public $plugin;
    public function __construct($plugin) {
        parent::__construct($plugin);
        $this->plugin = $plugin;
    }
    public function onRun($currentTick) {
        foreach($this->plugin->getServer()->getLevelByName("Lobby")->getPlayers() as $p) {
            //bossbar
            $p->sendTitle("§6Lobby §8| §eOnline §b".count($this->plugin->getServer()->getOnlinePlayers())."§7/§b100",$this->plugin->prefix, 20,20,20);
        }
    }
}`

**Comment by ISRAPIL** [comment]
@AnkitM252 What? This causes a load.

**Comment by RateekMCPE** [comment]
Is work with no task, delete your texture pack 1.0.4.. (Texture 1.0.4 no implemented title)

**Comment by ISRAPIL** [comment]
I'm dont use textures @RateekMCPE

**Comment by Nought57** [comment]
A bug that did not work properly for some events(JoinEvent etc) was confirmed.

**Comment by ISRAPIL** [comment]
How to fix?
@Nought57

**Comment by Nought57** [comment]
@ISRAPIL 
I tried PacketDebug but it was normal.
Information sent to the client terminal overwrites Title Packet.
It is difficult to change according to server specifications.
It seems best to send by using Scheduler.

**Comment by ISRAPIL** [comment]
Ok... I'm close this issue
