### ISSUE TITLE
Bug report.

### ISSUE THREAD

**Issue by iPeedroPvP** [TesseractTeam/Tesseract#459]
#### Steps to reproduce the issue
 antifly dont works. on remove allowflight of player, he continue on sky.

#### OS and versions

* Tesseract: Actually​.
* PHP:
* Server OS:
* Game version: 1.0.5
* Server host:
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by bulutsun** [comment]
Please use anticheat plugin.

**Comment by JunkDaCoder** [comment]
anticheat plugins handle this, dont depend on just the server
