### ISSUE TITLE
Title Command

### ISSUE THREAD

**Issue by SuperDude36** [TesseractTeam/Tesseract#462]
#### Problem description
it says unknown command when /title is run
#### Steps to reproduce the issue
do /title
#### OS and versions
* Tesseract: Tesseract-1.1.0 Ruby
* PHP: 7.0.3
* Server OS: Mac
* Game version: 1.0.5
* Server host: Home server

**Comment by NFGamerMC** [comment]
That is not yet implemented fully in PocketMine/Tesseract. Please search GitHub or Poggit for plugins with similar functions.

**Comment by SuperDude36** [comment]
oh, thanks 👍

**Comment by NFGamerMC** [comment]
Try this, it will display things in the actionbar. You are unable to use title and subtitle though, for instructions on using the plugin just ask.
