### ISSUE TITLE
Spawntoall to null

### ISSUE THREAD

**Issue by daniktheboss** [TesseractTeam/Tesseract#464]
![capture](https://cloud.githubusercontent.com/assets/19934671/24583746/e2fc3f32-1709-11e7-879a-3f2d35224035.PNG)
um... ^^^^

**Comment by AppleDevelops** [comment]
Enable debug and report what it says.

**Comment by daniktheboss** [comment]
I'll do it tmr, it stopped for a while now.

**Comment by KennFatt** [comment]
explain the problem when happening or debug message. i'll test and confirm it on my server

**Comment by daniktheboss** [comment]
idk, i have mobs in my server and it randomly started doing this.. never had the error again tho... wierd

**Comment by daniktheboss** [comment]
where do i enable it

**Comment by daniktheboss** [comment]
nvm it shows nothing
