### ISSUE TITLE
Please help me...

### ISSUE THREAD

**Issue by NemanjaMAX** [TesseractTeam/Tesseract#465]
Please give me link to Factions plugin...
FactionsPro and PocketFactions isn't working...

[Tesseract] [14:55:31] CRITICAL> Unhandled exception executing command 'f create test' in f: Call to undefined function FactionsPro\ctype_alnum()
[Tesseract] [14:55:31] CRITICAL> Error: "Call to undefined function FactionsPro\ctype_alnum()" (EXCEPTION) in "/plugins/FactionsPro-master/src/FactionsPro/FactionCommands" at line 129

.
[Tesseract] [15:21:36] CRITICAL> Unhandled exception executing command 'f create Test' in factions: Call to a member function setLeader() on null
[Tesseract] [15:21:36] CRITICAL> Error: "Call to a member function setLeader() on null" (EXCEPTION) in "/plugins/PocketFactions-master/src/TheDiamondYT/PocketFactions/FPlayer" at line 92

**Comment by Akuroma** [comment]
Questions about plugins are not allowed here. Please contact the Plugin-Developer. This is a thread about Tesseract.

**Comment by NemanjaMAX** [comment]
I know, but i rly need factions plugin :)

**Comment by Akuroma** [comment]
I'm sry I can't help you here. Also I don't know any other factions plugin.

**Comment by Driesboy** [comment]
its not a forum!

**Comment by GamakCZ** [comment]
Contact the developer of the plugin, or on the forums forums.pmmp.io

**Comment by RateekMCPE** [comment]
Contact the developer of FactionPRO lel 👎  Close the issues
