### ISSUE TITLE
SendTitle error

### ISSUE THREAD

**Issue by LCraftPE** [TesseractTeam/Tesseract#467]
Hey ! I noticed that when I use the function sendTitle several times, the title sent is wrong. 
For example, I use a first time the function sendTitle with the title "Hello" then I reuse the sendTitle function with as title "Test", the player will then receive the title "Hello"... This bug also applies for the subtitle and can be for the action bar.
My server is hosted at HostMyServers.

Thank you :)

I take 2 following pictures to show you 👍 

![image1](https://cloud.githubusercontent.com/assets/20226143/24589121/57025f4e-17d5-11e7-93fe-7449d016a400.PNG)
![image2](https://cloud.githubusercontent.com/assets/20226143/24589124/5a3ce832-17d5-11e7-9edc-b48b5983ebd8.PNG)

And here are the codes that are used for :

First image : (the message "Aucun adversaire n'a été trouvé..." corresponds to the previous subtitle) `$sender->sendTitle("§lCréer un clan ?", "§7Veux-tu vraiment créer un clan ?\n       §a[§f§lOK §r§a/create {clan}]");`

Second image : `$sender->sendTitle("", "§lTon clan a été créé !");`

**Comment by ISRAPIL** [comment]
The title takes time to appear and disappear

**Comment by LCraftPE** [comment]
@ISRAPIL I know... The titles that I display can be separated from 10 minutes, the bug still happens ...

**Comment by RateekMCPE** [comment]
@LCraftPE Je vais essayer de corriger sa ^^ vien mp si tu peut

**Comment by SuperMaXAleX** [comment]
@LCraftPE SPOIL ??? NOUVEAU JEU HPE ????
