### ISSUE TITLE
Inventory bug

### ISSUE THREAD

**Issue by Akuroma** [TesseractTeam/Tesseract#468]
#### Problem description
Items are dropping out of the inventory or out of chests, when placing them into them.

#### Steps to reproduce the issue
Place a chest and put an item into it. Try as OP and non-OP.

#### OS and versions

* Tesseract:  Tesseract-1.2.0 (Codename "Ruby")
* PHP: 7.0.3
* Server OS: Linux (Ubuntu 14.04)
* Game version: 1.0.5 (Android, IOS and Windows 10)
* Server host: V-Server (Linux/Ubuntu 14.04)
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by AydarTop** [comment]
Same bug

**Comment by Akuroma** [comment]
What do you mean by "Same bug"?

**Comment by AydarTop** [comment]
@Akuroma  I have this bug on my server

**Comment by Prisane** [comment]
try this #461

**Comment by AydarTop** [comment]
@Prisane Thanks, I fix this
