### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by CrazyCraft22** [TesseractTeam/Tesseract#469]
#### Problem description
Hello, I have an error on my server, when starting the server, tesseract normally starts, but this happens: many windows start to open the software and do not stop and when I enter the game tells me Server is Full.

#### 
Starts Server, but it starts to open many windows of tesseract and not stops, when you enter the Server says Server is Full.

#### OS and versions
OS: Windows 10 Home Version: 1.0.5
Use the 'version' command in Tesseract.
If the version is invalid, the issue will be CLOSED and marked as spam! 
NOTE: If you are using WINDOWS 10 Edition, please remember to let us know!
-->
* Tesseract: 1.2.0
* PHP: 7.0.4
* Server OS: Windows
* Game version: 1.0.5
* Server host: No Host, my PC
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by xZeroMCPE** [comment]
You might have another instance of your server running in the background, this happened to me..

You can fix it by launching CMD and use those commands:

netstat -o -n -a | findstr 19132

Then after it should give you a PID id. Use this command

taskkill /F /PID PID-HERE

Then start your server and try joining!
