### ISSUE TITLE
Bug generation and msg join / leave

### ISSUE THREAD

**Issue by Barlaf** [TesseractTeam/Tesseract#470]
#### Problem description
Hello, I have a migration from Genisys to Tesseract and the new chunk generated does not contain any minerals, even when generating a new map the minerals do not build. In addition, the input / output messages of players on 0 does not change in game and on 1 the input message changes but not the output message.

#### OS and versions

* Tesseract: Tesseract-1.2.0
* PHP: 7.0.10
* Server OS:
* Game version: 1.0.5
* Server host: HostMyServer

**Comment by AppleDevelops** [comment]
For the first issue, that once has been fixed, HostMyServer is slow at updating, and two please elaborate.

**Comment by Barlaf** [comment]
In this part of Tesseract.yml:

#This setting chooses how to remind players when someone joins the game
 #0 = Message, 1 = Tip, 2 = Popup
 player-msg-type: 1
 login-msg: "§6@player a rejoint le royaume"
 logout-msg: "§6@player a quitté le royaume"

If I select 0 whatever I put, it puts me the basic messages and if I select on 1 the welcome message is displayed correctly but the starting message remains the same as if it were selected on 0

(Sorry but I use Google Translation for speak ^^')

**Comment by RateekMCPE** [comment]
@Barlaf  Je suis français et actuellement HostMyServers mais longtemps a mettre à jours mais la il on une version de pas longtemps, dans "player-msg-type: 1" mais 2 à la place :) ! Tiens moi au courent.

**Comment by Barlaf** [comment]
Ho Rateek MDR ouais je test dessuite :)
Et non ça fais toujours la même chose :/

**Comment by MCPEGamerJPatGitHub** [comment]
@Barlaf That bug has been there for a very long time, I know what you are talking about.

**Comment by Barlaf** [comment]
@MCPEGamerJPatGitHub Hum okey... There is a plugin that patches this ?

**Comment by MCPEGamerJPatGitHub** [comment]
@Barlaf It's possible. But that's something that shouldn't be discussed here.

**Comment by Barlaf** [comment]
Ha okey @MCPEGamerJPatGitHub no problem ^^

**Comment by MCPEGamerJPatGitHub** [comment]
@Barlaf Removed in fa3950d

**Comment by Barlaf** [comment]
Thx @MCPEGamerJPatGitHub I wait for my host to update the last version of Tesseract :)
