### ISSUE TITLE
1.0.5 is not compatible with FractionPro. May not be a plugin problem

### ISSUE THREAD

**Issue by lowingly** [TesseractTeam/Tesseract#471]
---Problem Description---
When I open the server, FractionsPro will be reported.
I guess this may not be a plugin problem, because FractionPro in Tesseract1.0.3-1.0.4 can be used normally.

[Tesseract] [05:45:51] Developer> Enable FactionsPro v1.4.1
[Tesseract] [05:45:51] CRITICAL> Exception: "Can not open database: Can not open database file" (EXCEPTION) In "/plugins/FactionsPro_1.4-FactionsPro1.4/src/FactionsPro/FactionMain" 70
[Tesseract] [05:45:51] DEVELOPER> Disable FactionsPro v1.4.1
[Tesseract] [05:45:51] CRITICAL> Error: Calling a member function in "/plugins/FactionsPro_1.4-FactionsPro1.4/src/FactionsPro/FactionMain" close () on null "(EXCEPTION) 257

FactionsPro / FactionMain line 70:
$This->db= new \SQLite3 ($this->getDataFolder (). "FactionsPro.db");

This server is running Tesseract-1.2.0 Ruby
PHP Version: 7.0.8
API: 3.0.1
Target customers: Minecraft PE v1.0.5
Protocol version: 105
Window 8

**Comment by AppleDevelops** [comment]
Plugin issue

**Comment by lowingly** [comment]
I regret that the author told me that Tesseract is not supported by normal supported..... T_T
