### ISSUE TITLE
Server force stop/crash

### ISSUE THREAD

**Issue by XDqrkneZ** [TesseractTeam/Tesseract#472]
#### OS and versions

* Tesseract: Tesseract 1.2.0 Ruby 
* PHP: 3.0.1
* Server OS: 
* Game version: 1.0.5
* Server host: OVH
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

Server force stop/crash, the console said look for the crashdump so this is what i found, here is the crashdump
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

Tesseract Crash Dump Sun Apr 2 16:55:50 EDT 2017

Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 53248 bytes)
File: /src/pocketmine/level/Level
Line: 3079
Type: E_ERROR

Code:
[3070] 	 */
[3071] 	public static function getChunkCacheFromData($chunkX, $chunkZ, $payload){
[3072] 		$pk = new FullChunkDataPacket();
[3073] 		$pk->chunkX = $chunkX;
[3074] 		$pk->chunkZ = $chunkZ;
[3075] 		$pk->data = $payload;
[3076] 		$pk->encode();
[3077] 
[3078] 		$batch = new BatchPacket();
[3079] 		$batch->payload = zlib_encode(Binary::writeUnsignedVarInt(strlen($pk->getBuffer())) . $pk->getBuffer(), ZLIB_ENCODING_DEFLATE, Server::getInstance()->networkCompressionLevel);
[3080] 		$batch->encode();
[3081] 		$batch->isEncoded = true;
[3082] 		return $batch;
[3083] 	}
[3084] 
[3085] 	public function setMetadata($metadataKey, MetadataValue $metadataValue){
[3086] 		$this->server->getLevelMetadata()->setMetadata($this, $metadataKey, $metadataValue);
[3087] 	}
[3088] 
[3089] 	public function getMetadata($metadataKey){

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Tesseract version: 0000000000000000000000000000000000000000 [Protocol 105; API 3.0.1]
uname -a: Linux ns533049.ip-149-56-242.net 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

Server uptime: 38 minutes 2 seconds
Number of loaded worlds: 3
Players online: 79/80

Loaded plugins:
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
VoteReward 3.0.2 by LDX for API(s) 1.12.0, 2.0.0
Sell 2 by Muqsit, KairusDarkSeeker for API(s) 2.0.0
BanWord 1.0.0 by laurobeleche for API(s) 1.0.0, 2.0.0
Wild 1 by iPedroo for API(s) 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3
MagicWE 0.3.0 by XenialDan for API(s) 2.0.0, 3.0.0
EasierTP 0.6.6 by Ad5001 for API(s) 2.0.0, 1.14.0
Lobby 1 by UltimateDevs for API(s) 2.0.0
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
AutoInv 0.0.2 by JackNoordhuis for API(s) 1.0.0, 2.0.0
AdvertisingKick 1.0.0 by  for API(s) 1.0.0
RealMute 3.4.1 by Leo3418 for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.12.0, 1.13.0, 1.13.1, 2.0.0, 2.1.0, 3.0.0-ALPHA4
FactionsPro 1.8.0 by X for API(s) 1.12.0, 2.0.0
WorldGuard 1 by Muqsit for API(s) 2.0.0, 3.0.0-ALPHA3, 3.0.0-ALPHA4
TeleportPlus 1.0.0 by  for API(s) 1.0.0
CombatLogger 1.2.0 by Lambo for API(s) 1.12.0
ToolsPE 1 by paetti for API(s) 1.0.0
BuyCraft 1.2.2 by Falkirks for API(s) 1.0.0
AntiServerStop 1.1 by paetti for API(s) 1.0.0, 2.0.0, 3.0.0, 3.0.1, 3.1.0, 3.0.0-ALPHA1, 4.0.0, 5.0.0
OreInstantDrop 1.0 by ScandiePlay for API(s) 1.12.0
StackMobs 1.0.0 by sero583 for API(s) 2.0.0
AntiAbusiveEnchants 1 by SavionLegendZzz for API(s) 1.12.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
Alias 1.2.0 by ZacHack for API(s) 1.12.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
Fly 2 by iPedroo for API(s) 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
iProtector 3.1b by LDX for API(s) 1.9.0, 2.0.0
OpLogin 1 by  for API(s) 2.0.0
Fix 1 by iPedroo for API(s) 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3
MCMMO-PE 2.0.0_ALPHA by Angelo Vidrio for API(s) 2.0.0
CommandBlocker 1.5.5 by Thunder33345 for API(s) 2.0.0
AntiVoid 1.0.0 by KairusDarkSeeker for API(s) 2.0.0
VirtualChest 1 by RedstoneAlmeida for API(s) 2.0.0
VIPSlots 0.0.2 by iJoshuaHD for API(s) 1.8.0
UltimateNameTag 1.0.0 by MichaelM04 for API(s) 1.0.0, 2.0.0
InvSee 0.0.1 by tschrock (tschrock123@gmail.com) for API(s) 1.0.0
AdvancedKits 5.1 by luca28pet for API(s) 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3
ASR 2.0.2 by iJoshuaHD for API(s) 1.12.0
PortalsPE 1 by luca28pet for API(s) 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3
PurePerms 1.4.0-INDEV by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0
essentialsTP 1 by xd for API(s) 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3
BlockBreaker 0.0.1 by Jack Noordhuis for API(s) 2.0.0
BanItem 2.2 by LDX for API(s) 1.0.0, 2.0.0
AccidentCaps 0.0.1 by thebigsmileXD for API(s) 1.0.0
CheckID 1.0-Alpha by XxD7omGamer for API(s) 2.0.0
EntitiesCleaner 0.2-Alpha by ifteam for API(s) 1.12.0, 1.13.0, 2.0.0
TitleJoin 1 by Husk for API(s) 3.0.0
EconomySell 2.0.7 by onebone for API(s) 1.12.0
PrivateVault 1.0.0 by ImagicalGamer for API(s) 2.0.0
Json 1 by RedstoneAlmeida for API(s) 2.0.0
Envoy 0.0.2 by ImagicalGamer for API(s) 1.0.0, 2.0.0, 3.0.0
ReportHacker 1.0.0 by LCraftPE for API(s) 1.0.0
WorldProtect 2.2.0 by aliuly for API(s) 1.10.0, 1.12.0
HealthBar 1.0.0 by TheBisonXD for API(s) 1.0.0
AntiSpam 1.3 by xBeastMode for API(s) 2.0.0
Spawner 2 by zMarcos360 for API(s) 2.0.0
EnderPearl 1.0.0 by FRISCOWZ for API(s) 2.1.0, 3.0.0-ALPHA3, 1.12.0
EconomyShop 2.0.7 by onebone for API(s) 1.12.0
PureChat 1.3.4-BETA-01 by 64FF00 for API(s) 1.13.0, 2.0.0
SimpleAuthHelper 2.0.4 by aliuly for API(s) 1.12.0

```
```

**Comment by Driesboy** [comment]
@AppleDevelops A Chunk bug AGIAN

**Comment by AppleDevelops** [comment]
It seems like a memory leak, but with the lack of information, I cannot help

**Comment by XDqrkneZ** [comment]
By memory leak.. do you mean I didn't have enough memory so it crashed? I'm using a 32gb ram btw

**Comment by MCPEGamerJPatGitHub** [comment]
@XDqrkneZ not like that

**Comment by Nought57** [comment]
Try raising the memory usage limit.
You can change from a settings file.

**Comment by XDqrkneZ** [comment]
@Nought57 where is it? can you tell me please, I just knew that you can increase ram

**Comment by Nought57** [comment]
@XDqrkneZ 
Please see this.
PocketMine.yml >> Memory >> main-hard-limit.

**Comment by TDMidkwhatisxd** [comment]
Just set memory limit to 10gb or just set memory limit to 0 in pocketmine.yml

**Comment by TDMidkwhatisxd** [comment]
Main hard limit, set to 0 , in pocketmine.yml

**Comment by xZeroMCPE** [comment]
@XDqrkneZ Use /dumpmemory then after, upload the .txt here Or paste so I can take a look
