### ISSUE TITLE
[POLL] Remove limited creative?

### ISSUE THREAD

**Issue by AppleDevelops** [TesseractTeam/Tesseract#473]
Thumbs up = yes
Thumbs down = no

**Comment by JunkDaCoder** [comment]
**REMOVE IT**, plugins should honestly handle this

**Comment by KennFatt** [comment]
Wait, think twice with other server owners. I also used a plugin to handle all of that.

if we remove the feature, will it affected to software performance? if no, keep it there.

**Comment by AppleDevelops** [comment]
It won't affect performance, it'll just help it stay cleaner, plus we like to be close to vanilla.

**Comment by caspervanneck** [comment]
remove it

**Comment by AppleDevelops** [comment]
Already did it in API 4.0.0, we're working on cleaning up the core, plugins can handle most of the stuff I've gotten rid of.
