### ISSUE TITLE
I can't use Redstone

### ISSUE THREAD

**Issue by jdongel2004** [TesseractTeam/Tesseract#478]
#### Problem description

I can't use redstone
#### OS and versions

* Tesseract: 1.2.0 .phar
* PHP: 7.0.3
* Server OS: Ubuntu 16.10
* Game version:  1.0.5
* Server host: Vultr
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

I know Tesseract can use redstone, but I can't. How can I use?

**Comment by poustmal** [comment]
Tesseract removed redstone

**Comment by AnkitM252** [comment]
We removed the redstone.
