### ISSUE TITLE
You can't go on nether

### ISSUE THREAD

**Issue by poustmal** [TesseractTeam/Tesseract#480]
Tesseract: 53b7b8a(I updated tesseract today)
Php: 7.0.3
Game version: 1.0.5(no beta,official) android

This happens when I'm trying to go to nether and my screen stucks on building terrain(bad english idk)

Warning: assert(): Unhandled player action 14 from Saxavlax001 failed in /storage/sdcard0/PocketMine/src/pocketmine/Player.php on line 2590

**Comment by poustmal** [comment]
This was happening also here in older versions,1.0.4 etc

**Comment by LordJoshie** [comment]
if you logout/login, you'll relog in the nether.

**Comment by NemanjaMAX** [comment]
@AppleDevelops Close this..
All works fine. Maybe Plugin bug :)

**Comment by LordJoshie** [comment]
only plugin id use that might have anything to do with this is manyworlds.

**Comment by poustmal** [comment]
I'm using essentialspe,but on other software and version,nether was working,I think that sth is missing on tesseract

**Comment by AppleDevelops** [comment]
I'll work on it in API 4

**Comment by NFGamerMC** [comment]
This is something that is most likely happening in pocketmine.yml or tesseract.yml

**Comment by NFGamerMC** [comment]
I am going to close this and mark it as invalid!

**Comment by poustmal** [comment]
Yes,but I can't join!I can only try without plugins,but I don't think that this is the problem

**Comment by NFGamerMC** [comment]
How about re-download Tesseract!

**Comment by NFGamerMC** [comment]
Here is the link for the lates phar (1.0.5)

https://circleci-tkn.rhcloud.com/api/v1/project/TesseractTeam/Tesseract/tree/master/latest/artifacts/Tesseract_1.2.0.phar

**Comment by poustmal** [comment]
Well,wait

**Comment by NFGamerMC** [comment]
What?

**Comment by NFGamerMC** [comment]
Try that and then see if you can join the nether also when the server is stopped just delete Pocketmine.yml

**Comment by poustmal** [comment]
Again the same error and with deleted pocketmine.yml

**Comment by NFGamerMC** [comment]
Are you useing a VPS or are you hosting it at home

**Comment by poustmal** [comment]
Warning: assert(): Unhandled player action 14 from Saxavlax001 failed in phar:///storage/sdcard0/PocketMine/PocketMine-MP.phar/src/pocketmine/Player.php on line 2590

**Comment by poustmal** [comment]
Im hosting it at home

**Comment by poustmal** [comment]
But when I was using genisys,(older mcpe versions) mether was working idk

**Comment by NFGamerMC** [comment]
My PHP is a bit rusty so I will look for errors but someone else may fix it

**Comment by NFGamerMC** [comment]
So, you are on Genisys now?

**Comment by poustmal** [comment]
No,im usong tesseract,i mean when i was using genisys 0.14-0.15 nether was working

**Comment by NFGamerMC** [comment]
Just looked on the line and i see nothing related to nether portals just elytra!, the line seems to be intentionally saying that

**Comment by IrishPacks** [comment]
Reopen this. The issue is that when changing dimensions, a PlayStatusPacket must be sent, otherwise the player will never be spawned in and will be stuck on the building terrain screen.
