### ISSUE TITLE
Add beacons back

### ISSUE THREAD

**Issue by TheAz928** [TesseractTeam/Tesseract#486]
Hi, working beacons was really good. So add them back. Thank you...

**Comment by NFGamerMC** [comment]
Please use the issue template, currently we don't have a sudgestion box but we will close this when it is available!

**Comment by Qimie** [comment]
How about making a Google docs?
On Apr 7, 2017 8:11 PM, "Nathaniel" <notifications@github.com> wrote:
>
> Please use the issue template, currently we don't have a sudgestion box
but we will close this when it is available!

**Comment by NFGamerMC** [comment]
My plans are to start a website for Tesseract with the form but temp. I may make one!

**Comment by NFGamerMC** [comment]
You can make a pull request and invite me to the form though

**Comment by NFGamerMC** [comment]
Please report this or request it [here](http://bit.ly/TesseractRequests)
