### ISSUE TITLE
The "Unknown dependency" is useless

### ISSUE THREAD

**Issue by intagaming** [TesseractTeam/Tesseract#489]
#### Problem description

So imagine someone released a plugin, and the docs/wiki page has been deleted for 2 years. Now what?
Unphar website. Then if you don't have the internet, for example on the vacation, what do you do?

#### Steps to reproduce the issue

Add bunch of dependency in plugin.yml, and enjoy the "Unknown dependency"

#### OS and versions

* Tesseract: d7d9c84
* PHP: 7.1
* Server OS: Windows
* Game version: 1.0.5
* Server host: Home
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
Couldn't load plugin: Unknown dependency
```

**Comment by xZeroMCPE** [comment]
@NFGamerMC Do you have twitter? or discord?

**Comment by NFGamerMC** [comment]
Yes, I have discord, gitter and google+

**Comment by xZeroMCPE** [comment]
Add me on discord: xZeroMCPE

**Comment by NFGamerMC** [comment]
Kk

**Comment by NFGamerMC** [comment]
What are your four digits? Example: xZeroMCPE#0000

**Comment by xZeroMCPE** [comment]
#6811

**Comment by NFGamerMC** [comment]
@xZeroMCPE Request Sent!

**Comment by MCPEGamerJPatGitHub** [comment]
@intagaming It maybe useless for you, but might not be the same for others.

**Comment by intagaming** [comment]
I'm not meaning that it's useless, but the information provided is useless. What's the poibt of not providing the list of dependencies needed for the plug?

**Comment by intagaming** [comment]
Okay, that's fine. What a contribution 👍
