### ISSUE TITLE
1.0 chunk issue

### ISSUE THREAD

**Issue by KillerXtream** [TesseractTeam/Tesseract#49]
#### Problem description

User crashes at join on 1.0

#### Steps to reproduce the issue

Join on 1.0

#### OS and versions

* Tesseract: Crystal
* PHP: 7
* Server OS: RHEL 7
* Game version: MC Win10

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
Error while unloading a chunk: Call to undefined method pocketmine\nbt\NBT::putItemHelper()
[Tesseract] [14:09:23] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\nbt\NBT::putItemHelper()" (EXCEPTION) in "/src/pocketmine/tile/Dispenser" at line 141

```

**Comment by AppleDevelops** [comment]
Chunks aren't finished yet

**Comment by Skull3x** [comment]
It works fine for me
