### ISSUE TITLE
Problem with the join/leave message

### ISSUE THREAD

**Issue by Barlaf** [TesseractTeam/Tesseract#490]
#### Problem description
Hello,
I have a probleme with the join / leave message.

 #This setting chooses how to remind players when someone joins the game
 #0 = Message, 1 = Tip, 2 = Popup
 player-msg-type: 1
 login-msg: "§6@player a rejoint le royaume"
 logout-msg: "§6@player a quitté le royaume"

Tesseract config V:29

With this setting i have always the basic message
My heberger has been upload the recent update of Tesseract.phar

#### OS and versions

* Tesseract: Tesseract-1.2.0 Ruby protocole 105
* PHP: 7.0.10
* Server OS:
* Game version: Minecraft PE 1.0.5
* Server host: HostMyServer

**Comment by AppleDevelops** [comment]
If you didn't notice, we removed that as it did not work.

**Comment by Qimie** [comment]
@Apple It actually works.... Just some problems with deprecated-verbose
setting.

**Comment by Barlaf** [comment]
Okey is not an urgent probleme

**Comment by NFGamerMC** [comment]
It would be great if you could use proper English

**Comment by NFGamerMC** [comment]
I am going to re-open this but add a few labels as it is not urgent

**Comment by NFGamerMC** [comment]
Please report this or request it [here](http://bit.ly/TesseractRequests)
