### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by Ihor01** [TesseractTeam/Tesseract#491]
A link to download windows installet is not found (404)

**Comment by NFGamerMC** [comment]
My error, please allow up to 30 minutes for me to fix it!

**Comment by NFGamerMC** [comment]
Sorry, this error is being worked on. Sometime in the next week I will have it fixed! Please just install PocketMine and drop in a Tesseract phar for now!

**Comment by NFGamerMC** [comment]
This is now fixed and simpler to use!
