### ISSUE TITLE
server freeze

### ISSUE THREAD

**Issue by mote166** [TesseractTeam/Tesseract#492]
#### Problem description

the server freeze from time to time for 30~60 seconds then goes back normal
#### Steps to reproduce the issue

i really dunno how this is happening and in the console theres no errors. (it didn't happen on genisys or elywing or any other software)
#### OS and versions

* Tesseract: Tesseract-1.2.0 Ruby
* PHP: 7.0.11
* Server OS: linux
* Game version: Minecraft PE v1.0.5
* Server host: blockshost.com
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by NFGamerMC** [comment]
Please put any crashdumps that you find and the steps to re-produce

**Comment by mote166** [comment]
theres no crashdumbs cuz theres no crash just a freeze . it just happens

**Comment by mote166** [comment]
do u want my plugins list ? maybe it will help somehow

**Comment by NFGamerMC** [comment]
Yes Please. That should help!

**Comment by mote166** [comment]
Plugins (51): KillMoney v1.5, Broadcaster v1.16, 1vs1 v0.0.5, morph v0.1beta, PurePerms v1.3.5, ServerAuth v2.13, CommandTracker v1.1, ClearLagg v1.1.0, PassHack v1.2, TimeCommander v2.1, PvPWorlds v1, SlapperRotation v1.0.1, DevTools v1.11.0, BanWarn v1.2.1, MSpawns v1.4, Rotater v1.1.0, NoExplode v1, ColorMatch v1.1.2, PotPvp v0.0.5, SplatCraft v1.1.1, CoreProtect v0.1.5, AntiSpam v1.3, BuildUHC v2.3, WorldEdit+ v0.01, WorldFixer v1, EconomyAPI v2.0.9, NoAdvertisingPE v1.0.1, Whois v3, WorldProtect v2.2.0, SignChanger v1, TapToDo v2.2.1, EconomyShop v2.0.7, GrabBag v2.3.0, PureChat v1.4.0, FlyCommand v1.0.0, iProtector v3.1b, BBDoDo vNetherBox , SAC v3.2.1, LBParticles-Tim_15 v0.0.1, AdvancedKits v5.0b1, ManyWorlds v2.0.3, Slapper v1.3.3, EssentialsPE v2.0.0, BlockCmdPE v1.0.0, PmChair v1.3, NobadWordsKHAV v1.0.3, EnderParkour v1.0.0, LiveTexts v1.4pre, SW_svile v0.6dev, EDB-Pro v, MyPlot v1.1.3

**Comment by NFGamerMC** [comment]
Okay, are you able to upload these to Dropbox or Drive and share them with nfgamermc@outlook.com? If not that is okay and I will test Ina different way...

**Comment by mote166** [comment]
k ill upload them but u gotta promise me that u won't use them in any server or share them .

**Comment by NFGamerMC** [comment]
They are not safe then because they are public to the open. I will try the other way and you will just need to wait...

**Comment by mote166** [comment]
k whatever . i sent u the link. check ur email

**Comment by NFGamerMC** [comment]
Okay, I will remove the public link from the repo when I am done testing

**Comment by mote166** [comment]
btw since u got the plugins . theres an error i believe is caused by a plugin but i don't know which plugin it is so heres the error hoping that u find the plugin that is causing it: (i didn't find it as it occurs from time to time but i remember it says do not attempt to change .... in hotbar ... something like that)

**Comment by NFGamerMC** [comment]
Does the freeze happen in game or on the command line

**Comment by mote166** [comment]
in game

**Comment by NFGamerMC** [comment]
Okay, when did this first occur

**Comment by mote166** [comment]
umm i don't really remember but i started using tesseract since 1.0.0 came out umm i think it started with 1.0.5 yes 1.0.5

**Comment by NFGamerMC** [comment]
Just looked on the line and i see nothing related to nether portals just elytra!

**Comment by mote166** [comment]
yea i commented out the line that has elytra cuz i don't want my creative players be wearing it cuz they can use it to cheat (glitch)

**Comment by mote166** [comment]
so.. found anything ?

**Comment by NFGamerMC** [comment]
I have lots to do, please allow time for us to fix your issue. 

Estimate: 1-5hrs

**Comment by mote166** [comment]
k sorry .

**Comment by NFGamerMC** [comment]
You don't need to be sorry, I am just stating that I have other things to deal with in life.

**Comment by MCPEGamerJPatGitHub** [comment]
server freeze occurs by cpu outage so restart your server often not reload them

**Comment by mote166** [comment]
i never reload my server. with time commander plugin i made it restart every 6 hours . and btw it never happened with elywing or genisys , just tesseract

**Comment by LamKietCrack** [comment]
It Continues Happens

**Comment by NFGamerMC** [comment]
Your server seems fine, please just upgrade tesseract.

**Comment by NFGamerMC** [comment]
I tested it with all of your plugins and I don't see an issue at all, you probably are just lagging out
