### ISSUE TITLE
Phar

### ISSUE THREAD

**Issue by LolNova** [TesseractTeam/Tesseract#5]
Not a issue but can I have link. to the .phar of it?

**Comment by XDqrkneZ** [comment]
Just use the src,

**Comment by nikoskon2003** [comment]
If you use a pc to run the server download the zip file and place the 'src' folder to the location that you usually place your .phar 
Then install devtools plugin 
Last start the server and type 'makeserver'
  ---YOU WILL HAVE TO WAIT---
the .phar file is located at '/---/plugins/Tesseract/Tesseract(version).phar
rename it to 'PocketMine-MP.phar' and place it on the correct location!!!
//make sure to delete the src folder//

If you use android .... UR DOOMED (unless you do it first on pc and then send the .phar file to android!!!)
