### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by XDqrkneZ** [TesseractTeam/Tesseract#5]
The crashdump said that the crash was caused by a plugin when I don't have any plugins on. See https://pastebin.com/wY1A8pVB for crashdump

and https://pastebin.com/4jW9dav4 for crash on startup.

i could not do /ver so i dont know the version but im using the updated one on github

**Comment by xZeroMCPE** [comment]
Try now.

**Comment by XDqrkneZ** [comment]
Legend! @xZeroMCPE
