### ISSUE TITLE
Jenkins

### ISSUE THREAD

**Issue by Enrick3344** [TesseractTeam/Tesseract#5]
#### Problem description
I know you guys are doing your best but i wanted to put the new version on. on jenkins but i saw that it has been loading for 8h and 47 min. try to upload it again please
If you guys want i can make a list of some bug that we are having.

#### OS and versions

* Tesseract: 1a90bd1
* PHP: 7
* Server OS: WINDOWS 10
* Game version: 1.0
* Server host: Cubedhost
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Enrick3344** [comment]
wait hmm i mean jenkins link is dead

**Comment by xZeroMCPE** [comment]
I'm working on fixing it as of now.

**Comment by xZeroMCPE** [comment]
Should be fixed.
