### ISSUE TITLE
Call to a member function spawnToAll() on null

### ISSUE THREAD

**Issue by ivan691** [TesseractTeam/Tesseract#503]
Call to a member function spawnToAll() on null

This error appears very often and very much spam in the console.
It was after I updated core to the 1.0.5-1.0.6

* Tesseract: 1.2.0 Ruby
* PHP: 7.0.15
* Game version: Minecraft PE v1.0.5

**Comment by NFGamerMC** [comment]
More Details Please!

**Comment by MCPEGamerJPatGitHub** [comment]
@ivan691 Look at issue #464

**Comment by AnkitM252** [comment]
Its the problem with mobs spawning in the world!

**Comment by ivan691** [comment]
@AnkitM252 So, how disable it?

**Comment by AnkitM252** [comment]
Despawn all the Entities/Mobs! I removed my world and recreated it and it worked!

**Comment by NFGamerMC** [comment]
Are you using PMAnvil or Anvil because there are lots of bugs with Anvil
