### ISSUE TITLE
Crash upon Joining Server :/

### ISSUE THREAD

**Issue by LagHD** [TesseractTeam/Tesseract#504]
Crash Dump:
Tesseract Crash Dump Fri Apr 7 21:21:19 UTC 2017

Error: mkdir(): File exists
File: /plugins/450_essentialstp_v1.phar/src/essentialsTP/essentialsTP
Line: 1344
Type: E_WARNING

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN : essentialsTP v1.0.9

Code:
[1335]             $this->config->set("wild-MaxY", "300");
[1336]             $this->config->save();
[1337]         }
[1338] 
[1339] 
[1340]     }
[1341] 
[1342]     public function onEnable(){
[1343]         $this->getLogger()->info(TextFormat::GREEN."essentialsTP+ loading...");
[1344]         @mkdir($this->getDataFolder());
[1345]         $this->check_config();
[1346]         try{
[1347]             if(!file_exists($this->getDataFolder().$this->config->get("sqlite-dbname").'.db')){
[1348]                 $this->db2 = new \SQLite3($this->getDataFolder().$this->config->get("sqlite-dbname").'.db', SQLITE3_OPEN_READWRITE | SQLITE3_OPEN_CREATE);
[1349]             }else{
[1350]                 $this->db2 = new \SQLite3($this->getDataFolder().$this->config->get("sqlite-dbname").'.db', SQLITE3_OPEN_READWRITE);
[1351]             }
[1352]         }
[1353]         catch (Exception $e)
[1354]         {

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Tesseract version: 0000000000000000000000000000000000000000 [Protocol 110; API 3.0.1]
uname -a: Linux localhost 3.4.39-4779190 #1 SMP PREEMPT Fri Apr 24 19:39:10 KST 2015 armv7l
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, android

Server uptime: 2 minutes 40 seconds
Number of loaded worlds: 2
Players online: 0/12

Loaded plugins:
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
VIPSlots 0.0.2 by iJoshuaHD for API(s) 1.8.0
EssentialsPE 2.0.0 by LegendsOfMCPE Team for API(s) 2.1.0, 2.0.0
PurePerms 1.3.7 by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0
Alias 2 by ZacHack for API(s) 2.0.0
iProtector 3.1b by LDX for API(s) 1.9.0, 2.0.0
Popper 1.0.0 by Hoyinm14mc,PatchesMCPE for API(s) 1.12.0
AdminFun 1.0.0 by hoyinm14mc for API(s) 1.12.0, 1.13.0, 2.0.0
Cameraman 1.1 by ChalkPE for API(s) 1.12.0, 1.13.0, 2.0.0
ServerAuth 2.13 by EvolSoft for API(s) 1.11.0
DevTools 1.2 by PocketMine Team & TesseractTeam for API(s) 3.0.0
essentialsTP 1.0.9 by  for API(s) 1.0.0
MostrarVida 1.0.0 by  for API(s) 2.0.0
ExplodeYourFriends 1.1.0 by Calrizer for API(s) 2.0.0
iControlU 1.3 by Falkirks for API(s) 1.6.0
BuyCraft 1.2.2 by Falkirks for API(s) 1.0.0
CommandTracker 1.1 by Scott Handley for API(s) 1.10.0
ZMusicBox 2.5.0 by Zzm for API(s) 1.0.0
morph 0.1beta by PmHard for API(s) 2.0.0, 3.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3
CommandSigns 2 by Samueljh1 for API(s) 1.0.0
MagicWE 0.2.7 by thebigsmileXD for API(s) 1.13.0, 2.0.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
BuycraftPM 0.1 by Tebex Limited for API(s) 2.0.0, 3.0.0, 3.0.0-ALPHA4
PureChat 1.4.0 by 64FF00 for API(s) 1.13.0, 2.0.0

**Comment by NFGamerMC** [comment]
Please remove the plugin EssentialsTP then restart your server!

**Comment by mote166** [comment]
u should just close this issue . its a plugin issue the crashdumb itself is telling u that its a plugin issue ,it should be considered as spam .

**Comment by mote166** [comment]
[off topic] btw is the morph plugin working good for u with tesseract?

**Comment by MCPEGamerJPatGitHub** [comment]
@nfgamermc plugin issue, close this ...

**Comment by AnkitM252** [comment]
Plugin Issue!

**Comment by LagHD** [comment]
@mote166 yes the morph plugin is working smooth!

**Comment by LagHD** [comment]
@NFGamerMC Thanks!

**Comment by LagHD** [comment]
I still seem to crash! :( I removed essentialsTP and still crash upon joining this time no error on console

**Comment by LagHD** [comment]
@NFGamerMC I removed essentialsTP but I still seem to crash, this time no error on console

**Comment by LagHD** [comment]
The first time it happened it referred me to an error in src/network/protocol/can't remember something like SetContainer on line 50

**Comment by NFGamerMC** [comment]
Re-Install Tesseract!

**Comment by LagHD** [comment]
Ok

**Comment by NFGamerMC** [comment]
Also the link is broken so use this, https://15-73522113-gh.circle-artifacts.com/0/tmp/circle-artifacts.Vd4PFl8/Tesseract_1.2.0.phar

**Comment by LagHD** [comment]
Alright, I'll download that and put it in pocketmine folder, if any errors pop up on console I'll send u crashdump

**Comment by LagHD** [comment]
@NFGamerMC same thing happened I crashed upon joining
Here's my crashdump:


Tesseract Crash Dump Sat Apr 8 10:48:34 UTC 2017

Error: Call to undefined method pocketmine\network\protocol\ContainerSetContentPacket::putEntityUniqueId()
File: /src/pocketmine/network/protocol/ContainerSetContentPacket
Line: 66
Type: notice

Code:
[57] 			for($s = 0; $s < $count and !$this->feof(); ++$s){
[58] 				$this->hotbar[$s] = $this->getVarInt();
[59] 			}
[60] 		}
[61] 	}
[62] 
[63] 	public function encode(){
[64] 		$this->reset();
[65] 		$this->putUnsignedVarInt($this->windowid);
[66] 		$this->putEntityUniqueId($this->targetEid);
[67] 		$this->putUnsignedVarInt(count($this->slots));
[68] 		foreach($this->slots as $slot){
[69] 			$this->putSlot($slot);
[70] 		}
[71] 		if($this->windowid === self::SPECIAL_INVENTORY and count($this->hotbar) > 0){
[72] 			$this->putUnsignedVarInt(count($this->hotbar));
[73] 			foreach($this->hotbar as $slot){
[74] 				$this->putVarInt($slot);
[75] 			}
[76] 		}else{

Backtrace:
#0 /src/pocketmine/Player(1077): pocketmine\network\RakLibInterface->putPacket(pocketmine\Player Player(1), pocketmine\network\protocol\ContainerSetContentPacket object, boolean , boolean )
#1 /src/pocketmine/inventory/PlayerInventory(528): pocketmine\Player->dataPacket(pocketmine\network\protocol\ContainerSetContentPacket object)
#2 /src/pocketmine/Player(948): pocketmine\inventory\PlayerInventory->sendContents(array Array())
#3 /src/pocketmine/Player(868): pocketmine\Player->doFirstSpawn(boolean)
#4 /src/pocketmine/Player(1768): pocketmine\Player->sendNextChunk(boolean)
#5 /src/pocketmine/Server(2671): pocketmine\Player->checkNetwork(boolean)
#6 /src/pocketmine/Server(2389): pocketmine\Server->tick(boolean)
#7 /src/pocketmine/Server(2299): pocketmine\Server->tickProcessor(boolean)
#8 /src/pocketmine/Server(1860): pocketmine\Server->start(boolean)
#9 /src/pocketmine/PocketMine(468): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /storage/emulated/0/PocketMine/, string /storage/emulated/0/PocketMine/, string /storage/emulated/0/PocketMine/plugins/, string unknown)

Tesseract version: 0000000000000000000000000000000000000000 [Protocol 110; API 3.0.1]
uname -a: Linux localhost 3.4.39-4779190 #1 SMP PREEMPT Fri Apr 24 19:39:10 KST 2015 armv7l
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, android

Server uptime: 1 minutes 42 seconds
Number of loaded worlds: 2
Players online: 1/12

Loaded plugins:
VIPSlots 0.0.2 by iJoshuaHD for API(s) 1.8.0
EssentialsPE 2.0.0 by LegendsOfMCPE Team for API(s) 2.1.0, 2.0.0
PurePerms 1.3.7 by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0
Alias 2 by ZacHack for API(s) 2.0.0
iProtector 3.1b by LDX for API(s) 1.9.0, 2.0.0
Popper 1.0.0 by Hoyinm14mc,PatchesMCPE for API(s) 1.12.0
AdminFun 1.0.0 by hoyinm14mc for API(s) 1.12.0, 1.13.0, 2.0.0
Cameraman 1.1 by ChalkPE for API(s) 1.12.0, 1.13.0, 2.0.0
ServerAuth 2.13 by EvolSoft for API(s) 1.11.0
DevTools 1.2 by PocketMine Team & TesseractTeam for API(s) 3.0.0
MostrarVida 1.0.0 by  for API(s) 2.0.0
ExplodeYourFriends 1.1.0 by Calrizer for API(s) 2.0.0
iControlU 1.3 by Falkirks for API(s) 1.6.0
BuyCraft 1.2.2 by Falkirks for API(s) 1.0.0
CommandTracker 1.1 by Scott Handley for API(s) 1.10.0
ZMusicBox 2.5.0 by Zzm for API(s) 1.0.0
morph 0.1beta by PmHard for API(s) 2.0.0, 3.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3
CommandSigns 2 by Samueljh1 for API(s) 1.0.0
MagicWE 0.2.7 by thebigsmileXD for API(s) 1.13.0, 2.0.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
BuycraftPM 0.1 by Tebex Limited for API(s) 2.0.0, 3.0.0, 3.0.0-ALPHA4
PureChat 1.4.0 by 64FF00 for API(s) 1.13.0, 2.0.0

**Comment by LagHD** [comment]
As u can see in crashdump above it says something about src/pocketmine/network/protocol/ContainerSetContentPacket on line 66
[66] $this->putEntityUniqueId($this->targetEid);

**Comment by mote166** [comment]
can u give me the link for the morph plugin?

**Comment by NFGamerMC** [comment]
@mote166 https://github.com/Falkirks/DisguiseMe

**Comment by AnkitM252** [comment]
@LagHD That line even doesn't exists on latest commits! https://github.com/TesseractTeam/Tesseract/blob/master/src/pocketmine/network/protocol/ContainerSetContentPacket.php

**Comment by AnkitM252** [comment]
This is the error of MCPE-1.1 branch which is in beta stage!

**Comment by LagHD** [comment]
Ok
