### ISSUE TITLE
MineReset error

### ISSUE THREAD

**Issue by XDqrkneZ** [TesseractTeam/Tesseract#505]
#### OS and versions

* Tesseract:  Tesseract-1.2.0 Ruby
* PHP: PHP 7.0.3
* Server OS: API 3.0.1
* Game version: 1.0.5
* Server host: OVH
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

ERROR when running /mine reset

:::::::::::::::::::::::::::::::::::::::

An unknown error occurred while attempting to perform this command
[Tesseract] [17:51:10] CRITICAL> Unhandled exception executing command 'mate reset a' in mate: Cannot call constructor
[Tesseract] [17:51:10] CRITICAL> Error: "Cannot call constructor" (EXCEPTION) in "/MineReset-master/src/minereset/MineResetTask" at line 33

```
```

**Comment by XDqrkneZ** [comment]
LOL FALKIRKS JUST FIXED IT! ILY ALL

**Comment by NFGamerMC** [comment]
This is not related to tesseract, you will get a repo ban if there is 3 offences
