### ISSUE TITLE
[Branch] 1.1 File:ContainerSetContentPacket

### ISSUE THREAD

**Issue by ZloyNick** [TesseractTeam/Tesseract#506]
Tesseract Crash Dump Sat Apr 8 14:06:06 MSK 2017

Error: Call to undefined method pocketmine\network\protocol\ContainerSetContentPacket::putEntityUniqueId()
File: /src/pocketmine/network/protocol/ContainerSetContentPacket
Line: 66
Type: notice

Code:
[57] 			for($s = 0; $s < $count and !$this->feof(); ++$s){
[58] 				$this->hotbar[$s] = $this->getVarInt();
[59] 			}
[60] 		}
[61] 	}
[62] 
[63] 	public function encode(){
[64] 		$this->reset();
[65] 		$this->putUnsignedVarInt($this->windowid);
[66] 		$this->putEntityUniqueId($this->targetEid);
[67] 		$this->putUnsignedVarInt(count($this->slots));
[68] 		foreach($this->slots as $slot){
[69] 			$this->putSlot($slot);
[70] 		}
[71] 		if($this->windowid === self::SPECIAL_INVENTORY and count($this->hotbar) > 0){
[72] 			$this->putUnsignedVarInt(count($this->hotbar));
[73] 			foreach($this->hotbar as $slot){
[74] 				$this->putVarInt($slot);
[75] 			}
[76] 		}else{

Backtrace:
#0 /src/pocketmine/Player(1077): pocketmine\network\RakLibInterface->putPacket(pocketmine\Player Player(1), pocketmine\network\protocol\ContainerSetContentPacket object, boolean , boolean )
#1 /src/pocketmine/inventory/PlayerInventory(528): pocketmine\Player->dataPacket(pocketmine\network\protocol\ContainerSetContentPacket object)
#2 /src/pocketmine/Player(948): pocketmine\inventory\PlayerInventory->sendContents(array Array())
#3 /src/pocketmine/Player(868): pocketmine\Player->doFirstSpawn(boolean)
#4 /src/pocketmine/Player(1768): pocketmine\Player->sendNextChunk(boolean)
#5 /src/pocketmine/Server(2671): pocketmine\Player->checkNetwork(boolean)
#6 /src/pocketmine/Server(2389): pocketmine\Server->tick(boolean)
#7 /src/pocketmine/Server(2299): pocketmine\Server->tickProcessor(boolean)
#8 /src/pocketmine/Server(1860): pocketmine\Server->start(boolean)
#9 /src/pocketmine/PocketMine(468): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /root/, string /root/, string /root/plugins/, string unknown)

Tesseract version: 0000000000000000000000000000000000000000 [Protocol 110; API 3.0.1]
uname -a: Linux s1.dtx.su 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64
PHP version: 7.0.17
Zend version: 3.0.0
OS : Linux, linux

Server uptime: 38 сек
Number of loaded worlds: 2
Players online: 1/300

Loaded plugins:

**Comment by LagHD** [comment]
Exactly! This is what happened to me and they think it was a plugin but I removed the plugin and I still crash upon joining

**Comment by McGrimmi** [comment]
@LagHD It's not plugin issue.

**Comment by LagHD** [comment]
@McGrimmi I know it's not I said that they said it was but it isn't

**Comment by LagHD** [comment]
Hope it gets fixed today
