### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by FireSprout** [TesseractTeam/Tesseract#51]
How to analyze 1.0's packets?
I want to develop a plugin using packets.

**Comment by AppleDevelops** [comment]
Analyze them? Be a little more specific.

**Comment by xZeroMCPE** [comment]
You can use this tool to log packets

( https://github.com/PocketMine/PacketLogger )

Didn't really understand what you meant, like @AppleDevelops  stays'  you should "Be a little more specific." next time. The more  specific it is, the more things we"ll be able to understand and help you!

**Comment by FireSprout** [comment]
Thank you, sorry for making confusing.
I want to ask how to set the value of the packet.
