### ISSUE TITLE
World Generator bug

### ISSUE THREAD

**Issue by Crypthu** [TesseractTeam/Tesseract#510]
#### Problem description
World not generated!

#### Steps to reproduce the issue
1. Download MyPlot plugin for GitHub
2. type command: /p generate alma(or other name)
3. watch Tesseract panel window

#### OS and versions

* Tesseract:
* PHP:
* Server OS:
* Game version: 
* Server host:

[Tesseract] [11:28 pm] INFO> Preparing level "alma"
[Tesseract] [11:28 pm] NOTICE> Spawn terrain for level "alma" is being generated in the background
[Tesseract] [11:28 pm] CRITICAL> Error: "Call to undefined method pocketmine\level\generator\normal\biome\PlainBiome::getColor()" (EXCEPTION) in "/plugins/MyPlot.phar/src/MyPlot/MyPlotGenerator" at line 104
[Tesseract] [11:28 pm] CRITICAL> Error: "Call to undefined method pocketmine\level\generator\normal\biome\PlainBiome::getColor()" (EXCEPTION) in "/plugins/MyPlot.phar/src/MyPlot/MyPlotGenerator" at line 104
[Tesseract] [11:28 pm] CRITICAL> Error: "Call to undefined method pocketmine\level\generator\normal\biome\PlainBiome::getColor()" (EXCEPTION) in "/plugins/MyPlot.phar/src/MyPlot/MyPlotGenerator" at line 104
[Tesseract] [11:28 pm] CRITICAL> Error: "Call to undefined method pocketmine\level\generator\normal\biome\PlainBiome::getColor()" (EXCEPTION) in "/plugins/MyPlot.phar/src/MyPlot/MyPlotGenerator" at line 104
[Tesseract] [11:28 pm] CRITICAL> Error: "Call to undefined method pocketmine\level\generator\normal\biome\PlainBiome::getColor()" (EXCEPTION) in "/plugins/MyPlot.phar/src/MyPlot/MyPlotGenerator" at line 104
[Tesseract] [11:28 pm] CRITICAL> Could not execute asynchronous task PopulationTask: Task crashed
[Tesseract] [11:28 pm] CRITICAL> Could not execute asynchronous task PopulationTask: Task crashed
[Tesseract] [11:28 pm] CRITICAL> Error: "Call to undefined method pocketmine\level\generator\normal\biome\PlainBiome::getColor()" (EXCEPTION) in "/plugins/MyPlot.phar/src/MyPlot/MyPlotGenerator" at line 104
[Tesseract] [11:28 pm] CRITICAL> Could not execute asynchronous task PopulationTask: Task crashed
[Tesseract] [11:28 pm] CRITICAL> Error: "Call to undefined method pocketmine\level\generator\normal\biome\PlainBiome::getColor()" (EXCEPTION) in "/plugins/MyPlot.phar/src/MyPlot/MyPlotGenerator" at line 104
[Tesseract] [11:28 pm] CRITICAL> Error: "Call to undefined method pocketmine\level\generator\normal\biome\PlainBiome::getColor()" (EXCEPTION) in "/plugins/MyPlot.phar/src/MyPlot/MyPlotGenerator" at line 104
[Tesseract] [11:28 pm] CRITICAL> Could not execute asynchronous task PopulationTask: Task crashed
[Tesseract] [11:28 pm] CRITICAL> Error: "Call to undefined method pocketmine\level\generator\normal\biome\PlainBiome::getColor()" (EXCEPTION) in "/plugins/MyPlot.phar/src/MyPlot/MyPlotGenerator" at line 104
[Tesseract] [11:28 pm] CRITICAL> Could not execute asynchronous task PopulationTask: Task crashed
[Tesseract] [11:28 pm] CRITICAL> Could not execute asynchronous task PopulationTask: Task crashed
[Tesseract] [11:28 pm] CRITICAL> Could not execute asynchronous task PopulationTask: Task crashed
[Tesseract] [11:28 pm] CRITICAL> Could not execute asynchronous task PopulationTask: Task crashed
[Tesseract] [11:28 pm] CRITICAL> Could not execute asynchronous task PopulationTask: Task crashed

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by NFGamerMC** [comment]
We don't deal with plugins, please contact the plugin owner. This is not our problem!
