### ISSUE TITLE
Crashed Server

### ISSUE THREAD

**Issue by AffanStarPure** [TesseractTeam/Tesseract#512]
Anyone Know What Problem Keep Crashed Server 

Tesseract Crash Dump Sun Apr 9 00:31:59 CEST 2017

Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 131072 bytes)
File: /src/pocketmine/nbt/NBT
Line: 473
Type: E_ERROR

Code:
[464] 			}
[465] 			return $this->buffer;
[466] 		}
[467] 
[468] 		return false;
[469] 	}
[470] 
[471] 	public function writeCompressed($compression = ZLIB_ENCODING_GZIP, $level = 7){
[472] 		if(($write = $this->write()) !== false){
[473] 			return zlib_encode($write, $compression, $level);
[474] 		}
[475] 
[476] 		return false;
[477] 	}
[478] 
[479] 	public function writeNetworkCompressed($compression = ZLIB_ENCODING_GZIP, $level = 7){
[480] 		if(($write = $this->write(true)) !== false){
[481] 			return zlib_encode($write, $compression, $level);
[482] 		}
[483] 

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Tesseract version: 0000000000000000000000000000000000000000 [Protocol 105; API 3.0.0]
uname -a: Linux fr35.server.pro 3.14.32-xxxx-grs-ipv6-64 #7 SMP Wed Jan 27 18:05:09 CET 2016 x86_64
PHP version: 7.0.9
Zend version: 3.0.0
OS : Linux, linux

Server uptime: 2 hours 17 minutes 39 seconds
Number of loaded worlds: 4
Players online: 3/20

Loaded plugins:
FactionsPro 1.4.1 by Tethered_, HostingItAll.com for API(s) 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4
PlanB 1.3.0 by Gamecrafter for API(s) 1.10.0
CombatLogger 0.0.2 by Jack Noordhuis for API(s) 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4
SkinChanger 1.3.12 by SalmonDE, Aericio, KairusDarkSeeker for API(s) 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3
TimeCommander 2.2 by LDX for API(s) 1.0.0, 2.0.0, 2.1.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5
VoteReward 3.0.2 by LDX for API(s) 1.12.0, 2.0.0
FoodEffect 1.0.0 by MUedsa for API(s) 1.12.0
1vs1 0.0.5 by  for API(s) 1.0.0, 1.1.0
ChatFilter 1.0.0 by IG for API(s) 2.1.0
NoTell 1.1b by awzaw for API(s) 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3
MegaBan 1.2.2 by awzaw for API(s) 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3
AdminFun 1.0.0 by hoyinm14mc for API(s) 1.12.0, 1.13.0, 2.0.0
ServerInfo 1.0_birdkkk by birdkkk for API(s) 1.0.0, 2.0.0, 2.1.0, 3.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3
CommandTracker 1.1 by Scott Handley for API(s) 1.10.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
ItemEffects 2.5.0 by XFuryMCPE for API(s) 1.12.0
ServerMail 0.0.2 by tschrock (tschrock123@gmail.com) for API(s) 1.0.0
TreasureChest 1.1 by Awzaw for API(s) 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3
Alias 1.2.0 by ZacHack for API(s) 1.12.0
PocketGuard 2.1.1 by MinecrafterJPN for API(s) 1.10.0
LagFixer 1 by PEMapModder for API(s) 2.0.0
EconomyPShop 2.0.2 by onebone for API(s) 1.12.0
NoTP 1.0.5 by awzaw for API(s) 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4
WorldProtect 2.3.5 by aliuly for API(s) 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5
IPLogger 1.3 by PEMapModder for API(s) 1.0.0
NoAdvertisingPE 1.0.1 by Vaivez66 for API(s) 1.12.0
TapToDo 2.1.2 by Falk for API(s) 1.0.0
ManyWorlds 2.1.0 by aliuly for API(s) 2.0.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
Parkour 1.5.1 by jdcraft for API(s) 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5
PurePerms 1.4 by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3
ServerAuth 2.13 by EvolSoft for API(s) 1.11.0
ServerLoveMCPE 3.2.1 by TheDeibo, ratchetgame98, and, The Plugin Community! for API(s) 2.0.0
KillMoney 1.1.0 by Topic for API(s) 1.9.0
RealTime 2.1.1 by Guillaume351 for API(s) 1.0.0
iProtector 3.1b by LDX for API(s) 1.9.0, 2.0.0
CustomAreas 1.1 by luca28pet for API(s) 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3
Broadcaster 1.16 by EvolSoft for API(s) 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4
Slapper 1.3.3 by jojoe77777 for API(s) 3.0.0-ALPHA4
noVoid 0.0.1 BETA by ImagicalGamer for API(s) 1.0.0, 2.0.0, 3.0.0
KillCash 1.0.1 by Fix kittisak for API(s) 2.0.0
AdvancedKits 5.1 by luca28pet for API(s) 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3
StatsPE 2.4.11 by SalmonDE, Aericio, robske_110, XenialDan for API(s) 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3
Sell 2 by Muqsit, KairusDarkSeeker for API(s) 2.0.0
ItemCloud 1.3 by onebone for API(s) 1.13.0, 2.0.0
ItemCasePE 1.0.8 by aliuly for API(s) 2.0.0, 2.1.0
EssentialsPE 2.0.0 by LegendsOfMCPE Team for API(s) 2.1.0, 2.0.0
ChatLogin 1.4 by EvolSoft for API(s) 1.11.0
BuyCraft 1.2.2 by Falkirks for API(s) 1.0.0
ExplosiveBottle 1.0 by XShockinFireX for API(s) 2.0.0
EconomyAPI 2.0.9 by onebone for API(s) 3.0.0, 2.0.0, 2.1.0
AntiSpam 1.3 by xBeastMode for API(s) 2.0.0
superBAR 1.6.2 by FaigerSYS for API(s) 2.0.0
AntiCheat 2.6.3 by DarkWav for API(s) 5.0.0, 4.0.0, 3.0.0, 2.0.0, 1.0.0
MineReset 2.2 by Falk for API(s) 1.0.0, 2.0.0
MagicWE 0.3.0 by XenialDan for API(s) 2.0.0, 3.0.0
EconomySell 2.0.7 by onebone for API(s) 1.12.0
EconomyShop 2.0.7 by onebone for API(s) 1.12.0
EconomyLand 2.0.9 by onebone for API(s) 3.0.0, 2.0.0, 2.1.0
EconomyAirport 2.0.4 by onebone for API(s) 3.0.0, 2.0.0, 2.1.0
RankUp 0.3.1 by Falkirks for API(s) 1.4.0
PureChat 1.4.0 by 64FF00 for API(s) 1.13.0, 2.0.0
MyPlot 1.1.3 by Wiez, Exxarion, jasonwynn10 for API(s) 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3

**Comment by SuperMaXAleX** [comment]
Oh my gash, all this plugins .-.

**Comment by xZeroMCPE** [comment]
Not enough memory!

Please open another issue if this issue happens again, follow the template, and provide details such as how much memory do you have allocated to Tesseract, and total of memory your system has!

**Comment by AnkitM252** [comment]
This is same as #472!

**Comment by AffanStarPure** [comment]
I use server pro hosting that don't show memory RAM

**Comment by AnkitM252** [comment]
Contact them!
