### ISSUE TITLE
player::transfer missing

### ISSUE THREAD

**Issue by thebigsmileXD** [TesseractTeam/Tesseract#514]
Because this spoon didn't stay up to date with PMMP, the Player -> transfer() function is fully missing.

**Comment by NFGamerMC** [comment]
Please don't request things as an issue

**Comment by thebigsmileXD** [comment]
Its not a "request".. or lets say its an request to fucking update tesserekt from pmmp. too hard?

**Comment by NFGamerMC** [comment]
Okay, I will open this issue

**Comment by NFGamerMC** [comment]
You can fix it in a PR but this is a low priority fix

**Comment by NFGamerMC** [comment]
@thebigsmileXD You can fix it in a PR but this is a low priority fix

**Comment by thebigsmileXD** [comment]
diy

**Comment by NFGamerMC** [comment]
We will get to it, thanks for your report. *[not sarcasm]*

**Comment by thebigsmileXD** [comment]
*We are going to do this

**Comment by NFGamerMC** [comment]
Yes, the TesseractTeam

**Comment by thebigsmileXD** [comment]
Good.
would be time as of it been added in 1.0

**Comment by NFGamerMC** [comment]
I don't have a timeline for bug fixes or enhancements, I will add this to the list

**Comment by thebigsmileXD** [comment]
Thats what i call a great team <3

**Comment by NFGamerMC** [comment]
<3 + ;)

**Comment by xZeroMCPE** [comment]
@thebigsmileXD Really? "tesserekt".

**Comment by thebigsmileXD** [comment]
yes why. i mean, tesserektMe

**Comment by NFGamerMC** [comment]
?

**Comment by AnkitM252** [comment]
Isn't this completed? I added it!

**Comment by Driesboy** [comment]
https://github.com/TesseractTeam/Tesseract/projects/1

**Comment by Driesboy** [comment]
please close this in the projects
