### ISSUE TITLE
Ban Reason Problem

### ISSUE THREAD

**Issue by Prisane** [TesseractTeam/Tesseract#515]
#### Problem description
When player is join the game, the ban reason not shown correctly

#### Steps to reproduce the issue

_Issues:_
prisane|2017-03-30 14:16:04 +0400|CONSOLE|Forever|test test
This prisane is reason "test test" but on join kick message "Banned by an operator." this is not true

#### OS and versions
* Tesseract: [3a6a5b0](https://github.com/TesseractTeam/Tesseract/commit/3a6a5b083607188683b641382f8f65ff432cbf69)
* PHP: 7 
* Server OS: linux
* Game version: PE/Win10
```

**Comment by NFGamerMC** [comment]
Use the correct template and possibly an attached image
