### ISSUE TITLE
Tiles

### ISSUE THREAD

**Issue by AppleDevelops** [TesseractTeam/Tesseract#52]
#### Problem description

Tiles are unable to be opened if they contain an inventory. For instance chests do not open anymore. I'd like to get some more people to confirm this issue.
#### OS and versions

* Tesseract: https://github.com/TesseractTeam/Tesseract/commit/5544a894c9aa4d83ca331c59245eb01d31cf3ebb
* PHP: 7.0.12
* Server OS: Windows 10
* Game version: PE/W10

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by KillerXtream** [comment]
Reproduced.

**Comment by SuperDude36** [comment]
Yeah, for factions this needs to be fixed ASAP. Would help, but I have no idea.

**Comment by SuperDude36** [comment]
EconomyShops have the same issue, plugin has no error but I can't buy anything via signs.

**Comment by AppleDevelops** [comment]
@SuperDude36 @KillerXtream Can you reproduce the issue anymore?

**Comment by KillerXtream** [comment]
EconomyShops have the same issue, plugin has no error but I can't buy anything via signs.

There's a problem wth PlayerInteractEvent.  Something's messed up

**Comment by KillerXtream** [comment]
issue not fixed.
![image](https://cloud.githubusercontent.com/assets/16330761/21361344/9b7aa48a-c6b1-11e6-8852-b9ade6dc8768.png)
