### ISSUE TITLE
Is there any synapse-related function?

### ISSUE THREAD

**Issue by remotevase** [TesseractTeam/Tesseract#54]
#### OS and versions

* Tesseract:
* PHP:
* Server OS:
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by remotevase** [comment]
Ah I see WinProxy! Awesomeness!

**Comment by remotevase** [comment]
Nope... WingProxy isnt even ready for 0.16 let alone 1.0

**Comment by remotevase** [comment]
@AppleDevelops

**Comment by xZeroMCPE** [comment]
I"ll start updating WingProxy into 1.0 soon...

**Comment by remotevase** [comment]
YAY!

**Comment by remotevase** [comment]
BUMP @xZeroMCPE @AppleDevelops
