### ISSUE TITLE
Server freezes after 10 minutes of usage approx

### ISSUE THREAD

**Issue by KillerXtream** [TesseractTeam/Tesseract#55]
#### Problem description

Title says all
#### Steps to reproduce the issue

Wait with a player inside
#### OS and versions

* Tesseract: for 1.0
* PHP: 7.0
* Server OS: RHEL 7
* Game version: W10

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by omgA4L** [comment]
Hey, how did u fix this issue? I have the same issue rn and it only happens when I switch from 0.16.2 to 1.0 tesseract

**Comment by Infernus102** [comment]
#86
