### ISSUE TITLE
Duplication with Thorns

### ISSUE THREAD

**Issue by Shadow166050** [TesseractTeam/Tesseract#554]
#### Problem description

Duplication with Thorns

#### Steps to reproduce the issue
One player must wear thorns armor of any kind.

2nd player must be holding any sword or tool they want to dupe.

The 2nd player must be down to half or 1 heart of health then you use the tool you want to dupe and you hit the player who hs the thorns armor and the 2nd player dies from thorns.

Then the tool the 2nd player had drops and when 2nd player respawns they still have the tool in there inv like of they never died so there you have 2 of the same tools

#### OS and versions
* Tesseract: Tesseract-1.2.0 Ruby
* PHP: 7.0.7
* Server OS: Dont understant this question
* Game version: 1.0.5
* Server host: MinersPlanet

#### Crashdump, backtrace, memory dumps, plugins list or other files
Check Steps to reproduce

**Comment by Driesboy** [comment]
Server OS: is bv. Windows 10, Debian 8, Mac OSX
