### ISSUE TITLE
resources packs

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [TesseractTeam/Tesseract#555]
Sorry for being annoying, resources pack works? If so, please, can you tell me how to use?

**Comment by MCPEGamerJPatGitHub** [comment]
@tdmidkwhatisxd Resource packs are not implemented yet.

**Comment by TDMidkwhatisxd** [comment]
It is, check my server, buildmcpe.eu

**Comment by TDMidkwhatisxd** [comment]
:3 , teseract is the best :)

**Comment by NFGamerMC** [comment]
You will be repo banned for spam if you do this again!

**Comment by TDMidkwhatisxd** [comment]
Ok , sorry!
There is a problem with resource pack! Sometimes u get timed out! Weird xd!

**Comment by NFGamerMC** [comment]
We have found this bug and are working on it!

**Comment by NFGamerMC** [comment]
👍

**Comment by TDMidkwhatisxd** [comment]
I removed resource pack until is fixed! It seems that it cause game crash ! Tested on Windows10
:)

**Comment by AnkitM252** [comment]
@SuperMaXAleX is working on Resource packs!
