### ISSUE TITLE
Bug with nether

### ISSUE THREAD

**Issue by Frago9876543210** [TesseractTeam/Tesseract#556]
#### Problem description

I think ChangeDimensionPacket not work or wrong. In the game, loading nether goes until timeout. The generation of the landscape goes on forever.
#### Steps to reproduce the issue

* start server on windows 10
* launch WINDOWS 10 Edition
* create nether portal and go to it
#### OS and versions

* Tesseract: Tesseract-1.2.0 Ruby (for mcpe 1.0.5)
* PHP: 7.0.13
* Server OS: Windows 10
* Game version:  minecraft windows 10 edition
* Server host: localhost on my PC

**Comment by MCPEGamerJPatGitHub** [comment]
@Frago9876543210 I cannot reproduce your bug.
