### ISSUE TITLE
Add command block

### ISSUE THREAD

**Issue by BeerMC** [TesseractTeam/Tesseract#557]

**Comment by AnkitM252** [comment]
Since there is no redstone implemented on Tesseract, The command blocks also cannot be used!

**Comment by LagHD** [comment]
Just make levers work and that'll do with command blocks

**Comment by AnkitM252** [comment]
For now command blocks are placeable!

**Comment by LagHD** [comment]
Really?

**Comment by LagHD** [comment]
Cool!

**Comment by IISweePII** [comment]
@AnkitM252 @LagHD at least they are placeable, soon enough once support comes out it will be much better

**Comment by AnkitM252** [comment]
Yea!

**Comment by MalakasPlayzMC** [comment]
You can place levers next to the command blocks and by adding commands to levers with TapToDo, everyone will think that there are working command blocks!

**Comment by xinghao2003** [comment]
Good Idea 😂😂
