### ISSUE TITLE
MOTD

### ISSUE THREAD

**Issue by LagHD** [TesseractTeam/Tesseract#558]
MOTD Doesn't show the players online, there was 7 people online when I joined but when I checked MOTD it showed as 0/190

**Comment by NFGamerMC** [comment]
That is a client-sid bug, MCPE has trouble with real-time updating players!

**Comment by IISweePII** [comment]
It will soon be fixed, ever since 1.0, the way code has been made a lot of the formatting different. Such thing with the MOTD can be a result from this

**Comment by ISRAPIL** [comment]
it's dont client side error...

**Comment by MCPEGamerJPatGitHub** [comment]
@israpil It seems like a client side bug. I cannot confirm, but the MCPE code format may have issues

**Comment by Driesboy** [comment]
i dont have this bug screen shot coming

**Comment by AnkitM252** [comment]
Check the fake queries plugin if you use it! Mostly caused by it!
