### ISSUE TITLE
Loading a world takes a lot of time at 1.0

### ISSUE THREAD

**Issue by KillerXtream** [TesseractTeam/Tesseract#56]
#### Problem description

Title is descriptive
#### Steps to reproduce the issue

Load a world that's not the default  world
#### OS and versions

* Tesseract: for 1.0
* PHP: 7.0
* Server OS: RedHat 7
* Game version: MCWIN10

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by KillerXtream** [comment]
**Update:** Not only loading a world freezes the server for some minutes, teleporting to it also does.

**Comment by KillerXtream** [comment]
Update 2:

Stuck at this when you teleport to the level

![image](https://cloud.githubusercontent.com/assets/16330761/21359676/f956edfe-c6aa-11e6-9254-acb906579e49.png)

**Comment by SuperMaXAleX** [comment]
Your world is dead by 1.0 update.
You need to convert your mcRegion's world to Anvil's world.

**Comment by KillerXtream** [comment]
It's on Anvil format.
It loads correctly after some minutes

**Comment by KillerXtream** [comment]
Region> MCA (Anvil) level

**Comment by KillerXtream** [comment]
**Update:** If I am on the world Test (not default) and I'm at x 0 y 50 and z 0 and I teleport to a far coordinate. Same problem happens.

**Comment by expexes** [comment]
a similar problem

**Comment by AppleDevelops** [comment]
Can this be reproduced anymore?

**Comment by KillerXtream** [comment]
Yes. Still can

**Comment by SuperMaXAleX** [comment]
Strange. This world has got many generated chunks or not ?

**Comment by remotevase** [comment]
Apple

**Comment by remotevase** [comment]
WHY THE F DID YOU CHANGE FROM MCR TO ANVIL?

**Comment by AppleDevelops** [comment]
@remotevase It shouldn't cause server lag anymore. It is now handled by the client.

**Comment by AppleDevelops** [comment]
@SuperMaXAleX I can easily reproduce the issue as well. It's on both pregenerated worlds and brand new worlds.

**Comment by remotevase** [comment]
What do you mean? Client is still LDB, and all other softwares are MCR. Why is tesseract Anvil not MCR?

**Comment by AppleDevelops** [comment]
@remotevase MCR is a dying thing. The biome colors are no longer handled by the server, it's by the client.

**Comment by KillerXtream** [comment]
#MCR is died.

**Comment by remotevase** [comment]
Ugh now I have to convert 50 worlds...

**Comment by omgA4L** [comment]
So if I convert my worlds to mcr my server will stop freezing after about 10 minutes of it being on?

**Comment by omgA4L** [comment]
*to mca* not mcr, sorry

**Comment by Infernus102** [comment]
CAN SOMEONE TELL ME HOW TO CONVERT YOUR WORLD TO ANVIL!!!!!!

**Comment by Enrick3344** [comment]
https://github.com/H4PM/Elywing/wiki/How-to-convert-a-MCRegion-world-to-an-Anvil-world-%3F

**Comment by Infernus102** [comment]
Unfortunately that dont work

**Comment by Enrick3344** [comment]
If you already have tesseract then your world should convert themself  automaticly

**Comment by Infernus102** [comment]
Can you pass on .phar please

**Comment by Enrick3344** [comment]
here bud: http://jenkins.tesseractteam.tk:8080/job/Tesseract/262/

**Comment by Infernus102** [comment]
same error - getBiomeColor()

**Comment by Enrick3344** [comment]
same error as me huh?
use this one http://jenkins.tesseractteam.tk:8080/job/Tesseract/257/

**Comment by Infernus102** [comment]
TypeError: "Argument 1 passed to pocketmine\tile\Skull::__construct() must implement interface pocketmine\level\format\Chunk, instance of pocketmine\level\format\mcregion\Chunk given, called in phar://E:/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/tile/Tile.php on line 89" (EXCEPTION) in "/src/pocketmine/tile/Skull" at line 32

**Comment by Enrick3344** [comment]
go in your Pocketmine.yml  and find default-format depend on what you have if it set to avil change it to mcregion and vice versa

**Comment by Infernus102** [comment]
same error on both

**Comment by Enrick3344** [comment]
hmmm

**Comment by Infernus102** [comment]
Fix this issue, chunk doesn't load up fast.

**Comment by AppleDevelops** [comment]
Fixed
