### ISSUE TITLE
Rails Still Won't Curve

### ISSUE THREAD

**Issue by DobberHockeyCom** [TesseractTeam/Tesseract#560]
The latest mod (v0.16.0.5), for Minecraft PE 1.0.5. "This server is running PocketMine-MP version 1.6.2dev "Unleashed" (API 3.0.0-ALPHA5)"

Wish I could upload a screen shot
Rails placed side by side won't curve. Rails won't move in north/south direction, only east/west. This wasn't an issue with earlier versions, so this should be an easy fix, no? Tracks won't go uphill either.

Please and thank you.

**Comment by NFGamerMC** [comment]
We are not pmmp, please note that we are Tesseract!

**Comment by DobberHockeyCom** [comment]
WTF is pmmp?
My server host at Game Servers gave me the link to this thread as the one they are using.

**Comment by NFGamerMC** [comment]
They are wrong, pmmp is other Server Software! You have PocketMine not Tesseract! Do not argue with us!

**Comment by NFGamerMC** [comment]
Please Note: This issue is only open temp. so I can deal with the issue

**Comment by MCPEGamerJPatGitHub** [comment]
@DobberHockeyCom to clarify
This is Tesseract, mainly for everyone to use .
pmmp is the next generation of PocketMine, which is used generally by developers .

there is a difference there .
hope you understand .

**Comment by AnkitM252** [comment]
This is not a bug as it was removed with redstone from the core
