### ISSUE TITLE
Items are always falling out

### ISSUE THREAD

**Issue by lowingly** [TesseractTeam/Tesseract#561]
Many players told me:
When they enter the server, the things in the backpack have chance to fall to the ground. 
Or within 1 minute after they entered the service, the items (in the bag) will fell to the ground.

Sometimes they pick up items, may also fall out.

After they put something into / out of the chest, it may fall to the ground.

This is a random occurrence.
This problem occurs at least on five different servers (I asked the other server hosts)
This problem may be difficult to reproduce, but I hope you do not easily turn it off. He is really present in many servers.

There is no specific version.
1.0.4-1.0.5 have occurred.
No error report.
Window 7
PHP7

**Comment by NFGamerMC** [comment]
Please tell me what a backpack is, that is not implemented in Tesseract or MCPE?

**Comment by lowingly** [comment]
![img_6534](https://cloud.githubusercontent.com/assets/18659344/24923612/0f932ed0-1ec0-11e7-88f5-9c6e9cb100d7.PNG)
Sorry...My English is not good.  This is backpack? Item bar？？ = =！

**Comment by NFGamerMC** [comment]
Ohh, that is a bug in the game. Technically this means that Mojang made this bug and that we are unable to fix it. Please consider making a bug report [here](http://bugs.mojang.com)

**Comment by TDMidkwhatisxd** [comment]
Ohh! This is simple -_- ! Imma do a fix right now! I didnt know that this will be so trouboesome!
Is just the problem with floating inventory!

**Comment by TDMidkwhatisxd** [comment]
Sorry for grammar, but i cant edit comment! Browser not compatible (touch problem)

**Comment by NFGamerMC** [comment]
Umm, this is client side as that happens to me locally all the time
