### ISSUE TITLE
console warnings

### ISSUE THREAD

**Issue by mote166** [TesseractTeam/Tesseract#562]
#### Problem description

i just downloaded the .phar from the readme.md and after like half an hour these error started showing up in the console
#### Steps to reproduce the issue

no idea
#### OS and versions

* Tesseract: Tesseract-1.2.0 Ruby
* PHP: 7.0.11
* Server OS: linux
* Game version: 1.0.5
* Server host: blockshost.com
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
Warning: assert(): Movement distance is excessive: dx=-3.5659, dy=-73.8697, dz=14.2878 failed in phar:///jar/versions/Tesseract/Tesseract105fdfdsf.phar/src/pocketmine/entity/Entity.php on line 1478
```

```
Warning: assert(): Unhandled player action 17 from zyad132 failed in phar:///jar/versions/Tesseract/Tesseract105fdfdsf.phar/src/pocketmine/Player.php on line 2743
```

```
Could not execute task pocketmine\tile\BeaconDelayedCheckTask: Call to a member function getName() on null 11.04 22:36:57 [Server] INFO Error: "Call to a member function getName() on null" (EXCEPTION) in "/src/pocketmine/tile/BeaconDelayedCheckTask" at line 42
```

**Comment by NFGamerMC** [comment]
Find out how to reproduce and stop making issues frequently that are invalid!

I said that in the nicest way possible!

**Comment by mote166** [comment]
how could i reproduce them if i don't even know how they happened ? my server is always 100/50 how could i know how those errors happened?
