### ISSUE TITLE
Protocol version of Tesseract is stated as 1.0.6 but says "Outdated Server"

### ISSUE THREAD

**Issue by alexbgameson** [TesseractTeam/Tesseract#563]
Protocol version of Tesseract is stated as 1.0.6 but when I try to join its says "Outdated Server"

I am running version 1.0.6 on my phone.
-->
* Tesseract: 1.2.0 
* PHP: 7
* Server OS: Windows R2 2012
* Game version: 1.0.6
* Server host: ForceCraft Server Hosting

**Comment by NFGamerMC** [comment]
Working on it now, asap

**Comment by NFGamerMC** [comment]
Fixed
