### ISSUE TITLE
Unable join server "Unable to join world"

### ISSUE THREAD

**Issue by alexbgameson** [TesseractTeam/Tesseract#564]
#### Problem description
When I go to login to the server it says "unable to connect to world" then a few seconds later it says that I logged out without ever saying I logged in.

[Tesseract] [15:34:52] INFO> Starting GS4 status listener
[Tesseract] [15:34:52] INFO> Query running on 0.0.0.0:10005
[Tesseract] [15:34:52] INFO> Default game type: Survival Mode
[Tesseract] [15:34:52] INFO> Done (10.721s)! For help, type "help" or "?"
[Tesseract] [15:34:52] INFO> Lobby will restart in 0 hr 40 min 0 sec.
[Tesseract] [15:35:27] INFO> AlexBGamesON[/192.168.1.6:19132] logged out due to timeout
[Tesseract] [15:35:44] INFO> AlexBGamesON[/192.168.1.6:19132] logged out due to timeout

#### Steps to reproduce the issue
Try to login with latest version.

-->
* Tesseract: 1.2.0
* PHP: 7
* Server OS: Windows Server Software R2 2012
* Game version: 1.0.6
* Server host: ForceCraft Hosting

**Comment by NFGamerMC** [comment]
Disable all resource packs and try again, resource packs are in Tesseract.YML

**Comment by alexbgameson** [comment]
They are disabled.

packs:
  force-resources: false
  resource-stack: []

**Comment by NFGamerMC** [comment]
Try this phar, https://46-73522113-gh.circle-artifacts.com/0/tmp/circle-artifacts.NQNw6Pw/Tesseract_1.2.0.phar
