### ISSUE TITLE
Unable to connect to world..

### ISSUE THREAD

**Issue by XDqrkneZ** [TesseractTeam/Tesseract#566]
#### OS and versions

* Tesseract:
* PHP: 7.0.3
* Server OS: API 3.0.1
* Game version: 1.0.6
* Server host: OVH
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

title says everything.. I saw a closed issue about this but that didn't work so I want an answer that will actually help me. thanks
```
```

**Comment by XDqrkneZ** [comment]
Tesseract: 1.2.0 Ruby^^

**Comment by alexbgameson** [comment]
Make sure that PurePerms and PureChat are updated for API 3.0.0. 

It caused my server to do the same thing.

**Comment by XDqrkneZ** [comment]
oh

**Comment by XDqrkneZ** [comment]
;-;

**Comment by XDqrkneZ** [comment]
can you send me links for PureChat and pPerms api 3.0.0 please?

**Comment by NFGamerMC** [comment]
Stop making false issues, follow the template and give details if you want help. :)

**Comment by alexbgameson** [comment]
http://www.mediafire.com/file/6oe4kqwu89nhoz7/Pure.zip
