### ISSUE TITLE
Cannot join (.6)?

### ISSUE THREAD

**Issue by ZaydPE** [TesseractTeam/Tesseract#567]
You cannot join. Either 'disconnected from server' or 'timeout'
This happens only with the .6 branch

**Comment by ZaydPE** [comment]
Closed for no reason?

**Comment by lowingly** [comment]
Follow the template and give details if you want help.....Otherwise your question will be close....

**Comment by NFGamerMC** [comment]
Nope, will explain

**Comment by ZaydPE** [comment]
I didn't really need to follow, it's a simple issue
