### ISSUE TITLE
Logged out due to timeout

### ISSUE THREAD

**Issue by TheAz928** [TesseractTeam/Tesseract#569]
###Problem description
Players log out due to mine out

###Steps to reproduce
Generate the lastest Tesseract.phar, try joining server and boom! Console log: @player logged out due to timeout
Player: disconnected from server

**Comment by Driesboy** [comment]
i think its @NFGamerMC after 42f691b9f3e1b515d9823f40344b93fe5f27a7f3

**Comment by Driesboy** [comment]
oops sorry

**Comment by TheAz928** [comment]
@Drieaboy I think ResourcePacks is messed up and it's causing it...

**Comment by Driesboy** [comment]
its posible

**Comment by Driesboy** [comment]
Nope i have tested the latest 1.0.5 version and i have not this issue

**Comment by Driesboy** [comment]
but i will remove resource packs for testing

**Comment by Driesboy** [comment]
Just remove the resource packs and it is fixed

**Comment by TheAz928** [comment]
@Diresboy Told you lol, now fix ResourcePacks

**Comment by Driesboy** [comment]
its fixed :)

**Comment by Driesboy** [comment]
for now use this one https://github.com/TesseractTeam/Tesseract/tree/3d91d1f541720bab91c4a1aa9120903178f084b5

**Comment by NFGamerMC** [comment]
@Driesboy That was not my fault and I fixed it, it was @SuperMaXAleX fault for merging it into the master branch!

**Comment by Driesboy** [comment]
Ok sorry

**Comment by NFGamerMC** [comment]
Can you revert @SuperMaXAleX's commit, so people can join again. There is a resource packs branch if people want to test it

**Comment by Driesboy** [comment]
if i am back home

Op 12-apr.-2017 16:39 schreef "Nathaniel" <notifications@github.com>:

**Comment by Driesboy** [comment]
its already done i think
