### ISSUE TITLE
I think touch event messed up

### ISSUE THREAD

**Issue by SuperDude36** [TesseractTeam/Tesseract#57]
#### Problem description
I have next to zero experience coding but tap to do doesn't work. It only works when I try to break the block (holding down).

#### Steps to reproduce the issue
Download tap to do, assign a cmd to a block (hold down not tap) tap the block, doesn't work, hold down on block, works
#### OS and versions

* Tesseract: Crystal
* PHP: 7.0.3
* Server OS: Protocol version: 100
* Game version: 0.17.0/1.0

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by KillerXtream** [comment]
I have my server with my own minigames. Something with PlayerInteractEvent is going wrong. Issue reproduced.

**Comment by AppleDevelops** [comment]
@KillerXtream @SuperDude36 Try again with the new update

**Comment by SuperDude36** [comment]
Sorry, I haven't done it, sports and Rouge 1 to watch XD. Maybe tomorrow...

**Comment by SuperDude36** [comment]
Screw homework, I'm on IOS and chests, EcoShop, and TapToDo all work! The people here are all better then Elywing or Genisys, should've switched earlier...
