### ISSUE TITLE
Bucket should not be overlapping

### ISSUE THREAD

**Issue by lowingly** [TesseractTeam/Tesseract#570]
survival mode：
Give about 3 buckets.
Throw all of them on ground.
Pick all bucket.Get the water. 
you will get 3 barrels of water in the bucket..
(Players can use the overlapping bucket to get a lot of water / magma bucket at once)
The correct way should be: Get two empty buckets, and a bucket with water.

![image](https://cloud.githubusercontent.com/assets/18659344/24946164/f95004de-1f2f-11e7-9e01-4fb07e4cfe98.png)

This server is running Tesseract-1.2.0 Ruby
PHP version: 7.0.8
API: 3.0.1
Target client: Minecraft PE v1.0.5
Protocol version: 105

**Comment by NFGamerMC** [comment]
Client-Issue, Minecraft des the Models not us!

**Comment by lowingly** [comment]
That is not the same. Local games can not cheat. 
Local game：If you use the overlapping bucket to click on the water (for example: 3), you will get a bucket of water bucket. 
In the server: If you use the overlapping bucket to click on the water (for example: 3), you will get 3 barrels of water in the bucket.....

**Comment by AnkitM252** [comment]
Confirmed!
Go in survival
Give about 5 buckets
Throw all of them on ground
Pick all bucket
Get the water and confirmed

**Comment by ISRAPIL** [comment]
It's not client bug, stupid @NFGamerMC

**Comment by ISRAPIL** [comment]
You call all mistakes the client's mistakes ...  @NFGamerMC

**Comment by ISRAPIL** [comment]
What is your role here? You can only change redmi @NFGamerMC

**Comment by lowingly** [comment]
@ISRAPIL Excuse me, can you look at #561  #565?
I do not think #565 and #561 is a client issue, because my players never encounter this problem in local game. 
I just want someone to be sure that this is not a server error....

**Comment by ISRAPIL** [comment]
#561 and #565 is kernel error... Perhaps Mojang changed packages of some kind or simply in the kernel something hurt!

@NFGamerMC thinks that all errors are client errors...

I do not see its role in this kernel, it only edits ReadMe.


@lowingly @NFGamerMC @AnkitM252 @hmy2001 @Enes5519

**Comment by AnkitM252** [comment]
We will take a look at those issues. Also @NFGamerMC has been kicked out by one of the members!

**Comment by NFGamerMC** [comment]
No, I fixed that. I saw the error and I fixed it!

**Comment by NFGamerMC** [comment]
Why did you kick ME!

**Comment by NFGamerMC** [comment]
Also some of them are, because they have been occurring locally on my device!

**Comment by NFGamerMC** [comment]
Also @ISRAPIL I can do more than change the readme, my role is to manage the Jenkins, CI, and Web Pages. I have been mostly working on the Tesseract webpage on my computer with another dev

**Comment by NFGamerMC** [comment]
![Proof](http://preview.ibb.co/iMfvt5/IMG_1439.jpg)

**Comment by ISRAPIL** [comment]
It can each from us, it's not difficult ... I do not see the point of keeping you here ... You always say that it's a client's mistake, although it's not so. You're just a little boy who wanted something more. This is evident from your behavior! @NFGamerMC

**Comment by NFGamerMC** [comment]
@ISRAPIL The reason that you see that is because I am new to GitHub and know Web Design not too skilled in PHP but knows some.

**Comment by ISRAPIL** [comment]
Then why are you here? @NFGamerMC 

To tell everyone that everything is customer's fault? To spoil the reputation that is already falling? @NFGamerMC

**Comment by NFGamerMC** [comment]
Okay, then I will stop managing the issues. What I was added for is services such as Jenkins, CircleCI, Web Development, and Issue Managing?

**Comment by ISRAPIL** [comment]
It can each from us, it's not difficult ...

**Comment by ISRAPIL** [comment]
It can each from us, it's not difficult ... @NFGamerMC

**Comment by NFGamerMC** [comment]
Yes, I was made to replace @TheRoyalBlock, that was his job before he got banned!

**Comment by ISRAPIL** [comment]
Why is it complicated? Poggit created a Poggit bot, on CircleCI and Travis-CI documentation ... @NFGamerMC 

It can each from us, it's not difficult ..

**Comment by NFGamerMC** [comment]
@ISRAPIL That is correct, anyone can do it. But I manage it, there's an error, I fix it... and so on.

**Comment by jrodr10** [comment]
@NFGamerMC calm down on my repo

**Comment by NFGamerMC** [comment]
This is @xZeroMCPE Repo. Did he give it to you? Also I am calm irl but online it is hard to tell

**Comment by TheRoyalBlock** [comment]
@jrodr10 this is not your repo.
@ISRAPIL when there is plenty of evidence that is not in your favor, stop the argument immediately.
Everybody else, this is definitely a client issue. Also, @xZeroMCPE is the true owner. 
If anyone wishes to argue, please present proper evidence.

**Comment by AppleDevelops** [comment]
@TheRoyalBlock Zero is the true owner? Weird I thought @ImagicalGamer and I founded the repo....

**Comment by AnkitM252** [comment]
@TheRoyalBlock thinks @xZeroMCPE is the true owner cause you tweeted out the post saying that!

**Comment by ISRAPIL** [comment]
@TheRoyalBlock Don't clien bug, in local game all good

**Comment by TheRoyalBlock** [comment]
Hey, quick question: Why is @NFGamerMC blocked? He is a part of the team, is he not? The audit logs for the team state that @AppleDevelops blocked him.

**Comment by NFGamerMC** [comment]
@TheRoyalBlock I was a part of the team!
![Proof](https://preview.ibb.co/mv6YD5/IMG_1448.png)

**Comment by TheRoyalBlock** [comment]
The audit logs for the organization show that AppleDevelops removed @NFGamerMC from the team. He used to be a part of the team, so why was he removed without proper reasoning?

**Comment by ImagicalGamer** [comment]
Zero Meh, I founded the repo. It's owned by the org, no single entity owns Tesseract.

**Comment by IrishPacks** [comment]
Before stupidity strikes again, this is NOT a client issue. Buckets should not be stackable whatsoever. If you don't know anything about the software and/or how it works, do not say anything.
