### ISSUE TITLE
Disconnected from Server

### ISSUE THREAD

**Issue by LagHD** [TesseractTeam/Tesseract#571]
Tesseract version: Latest
When I try joining server it says disconnected from server
I'm on 1.0.6 and server is too.

**Comment by BexiPE** [comment]
I have the same problem :/
Pls Fix that!

**Comment by Zuruki** [comment]
This is happening to me aswell! Confirmed

**Comment by alexbgameson** [comment]
You guys need to make sure your pureperms and purechat plugins are updated to API 3.0.0.

Download thwm here http://www.mediafire.com/file/6oe4kqwu89nhoz7/Pure.zip

Having them outdated caused me that same issue.

**Comment by Driesboy** [comment]
https://github.com/TesseractTeam/Tesseract/tree/3d91d1f541720bab91c4a1aa9120903178f084b5

**Comment by Driesboy** [comment]
@SuperMaXAleX is fixing the resource pack bug and he said i need to remove that commit so

**Comment by Driesboy** [comment]
Just revert the revert :) 
now you can use the master agian

**Comment by ZaydPE** [comment]
So it's caused by PurePerms + Purechat or the resourcepack commit?

**Comment by LagHD** [comment]
Got a link for latest phar?

**Comment by Driesboy** [comment]
Jenkins server

Op 12-apr.-2017 13:23 schreef "LagHD ✔" <notifications@github.com>:

**Comment by NFGamerMC** [comment]
Our Jenkins is under Construction, you can help with it here tesseractmc.herokuapp.com

The custom domain for it is coming soon

**Comment by NFGamerMC** [comment]
For the latest phar use CircleCI
