### ISSUE TITLE
Tesseract is supported to 1.1.0 beta ??

### ISSUE THREAD

**Issue by RocoWayne** [TesseractTeam/Tesseract#573]
Hi! 

Your github says that Tesseract is supported to 1.1.0 beta, but it does not work, login timeout (the client dont crash) 

Can you help us?

**Comment by NFGamerMC** [comment]
That is being worked on, please don't make anymore issues about this topic.

**Comment by RocoWayne** [comment]
oh, ok, maybe you need to remove that message from the github description then.

**Comment by NFGamerMC** [comment]
We do support the beta but there is an error with all that say Timeout
