### ISSUE TITLE
Player accounts stay logged in!

### ISSUE THREAD

**Issue by FienixEC** [TesseractTeam/Tesseract#574]
#### Problem description

Not sure what is happening but, since the latest 1.0.6 update, some players are reporting not being able to log into their main account, they get kicked with "already logged in" reason. Didnt happen on 1.0.5
has happened to several players and the only way to fix is by restarting the server.

#### Steps to reproduce the issue

Not sure how to reproduce

#### OS and versions

* Tesseract: latest version
* PHP: php7
* Server OS:
* Game version: 1.0.6
* Server host:
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by xZeroMCPE** [comment]
It's needs to be reproduced!

**Comment by FienixEC** [comment]
idk how to reproduce the issue or what is causing it. The only thing that ive changed on my server recently is added the latest src file from here to update to 1.0.6 and then this morning ive had several players complain that they cant log in because it says they are already logged in.

**Comment by xZeroMCPE** [comment]
any logs?

**Comment by KairusDarkSeeker** [comment]
@FienixEC What plugins are you using?

**Comment by LagHD** [comment]
I'm not experiencing this issue on 1.0.6 but I experienced it on 1.0.5, strange

**Comment by KairusDarkSeeker** [comment]
@LagHD okay?

**Comment by KairusDarkSeeker** [comment]
Maybe its your auth plugin getting outdated

**Comment by TDMidkwhatisxd** [comment]
Reproduced

**Comment by LordJoshie** [comment]
Oddly.... this only happens to my players when they go on my Nukkit server. lol.

**Comment by MCPEGamerJPatGitHub** [comment]
Depends on which auth plugin you are using, but the bug on SimpleAuth was fixed and updated for API3.0. You can download from the poggit page for pmmp.

**Comment by KairusDarkSeeker** [comment]
@MCPEGamerJPatGitHub or use [this](https://github.com/KairusDarkSeeker/KaiAuth)

**Comment by ManiakMCPE** [comment]
It's a kicking issue, the server isn't disconnecting the player when they leave the server or get kicked so they can't join back because they are technically still on the server.
