### ISSUE TITLE
Chests Dont Work In New Phar

### ISSUE THREAD

**Issue by MagicStarzHD** [TesseractTeam/Tesseract#578]
Chests Are not working in the lastest phar for tesseract.(1.0.6)Also Chests cannot be removed or break once place.I have tryed to open the chest in survival and it is not opening.Please Fix this bug asap.

**Comment by MCPEGamerJPatGitHub** [comment]
@MagicStarzHD use the issue template. Thanks

**Comment by NFGamerMC** [comment]
Turn off limited creative!
