### ISSUE TITLE
Dupe Glitch

### ISSUE THREAD

**Issue by ObeyBeastJj23** [TesseractTeam/Tesseract#579]
Hello there,

I use tesseract on my 3 servers and on my Prison server (the most active server) my users have found a duplication glitch, working with other plugins like Withdraw which allows the player to withdraw notes of money and give them to other players and with any other item in the game players can break any block on the map but it wont get destroyed because of the WorldProtect plugin so it will get replaced but as the player breaks the block with any item in their hand they can drop it and if they open their inventory before picking it up, another of the same item will appear in their inventory. I tried blocking drops with InventoryExchanger and they can still do it because they are still trying to drop that item, this means players can duplicate any item even money notes and break the whole of the server as they have infinate items, we also have crate keys which are Emeralds for 3 of the 4 tiers and Nether Stars for the 4th tier and players have been duplicating them, i have already had to reset all of the Balances of the server and the ranks because of this issue.

I hope this can be fixed very shortly as i will have to turn off my server or try find an alternative version to run the server on.

Server Version: Tesseract-1.2.0 Ruby
PHP version: 7.0.3
API: 3.0.1
Target client: Minecraft PE v1.0.6
Protocol version: 106

Yours Sincerely,
    - Obey

**Comment by ObeyBeastJj23** [comment]
Hello there, this is now not needed. I found out that i must have enabled "Allow-Cheats" in the bottom of the tesseract.yml file. I have now fixed this, sorry for the waste..

**Comment by TDMidkwhatisxd** [comment]
Suicide! Now all ppl can give them items with toolbox!
Tested! ;-;
