### ISSUE TITLE
Enderchests

### ISSUE THREAD

**Issue by ManiakMCPE** [TesseractTeam/Tesseract#58]
Enderchests can be placed but can't be opened?
Only creating this because Apple said they are implemented.
![k](https://user-images.githubusercontent.com/14960438/27465331-b12e29c0-5787-11e7-9940-c42f3bb33273.PNG)

**Comment by kenygamer** [comment]
@ManiakMCPE In-dev feature.
> ☆∂єvєlσρєя☆
кєνιи αи∂яєωѕ

**Comment by ManiakMCPE** [comment]
Does that mean it's coming soon, and how soon?

**Comment by kenygamer** [comment]
@ManiakMCPE I don't know. You would have to ask a contributor.
> ☆∂єvєlσρєя☆
кєνιи αи∂яєωѕ

**Comment by Shadow166050** [comment]
EnderChest work fine, Please make sure your using the lastest tesseract and it might be a plugin issue. - Close
