### ISSUE TITLE
Player logs on but the console says disconnected from server

### ISSUE THREAD

**Issue by Ishannaik** [TesseractTeam/Tesseract#581]
This server is running Tesseract-1.2.0 Ruby
PHP version: 7.0.8
API: 3.0.1
Target client: Minecraft PE v1.0.6
Protocol version: 106
When i try to join the server it says you have been disconnected from the server but on console it says player joined the game and then it says player has left the game after some time

**Comment by AnkitM252** [comment]
Please edit the issue for a correct template!

**Comment by GamakCZ** [comment]
issue exists https://github.com/TesseractTeam/Tesseract/issues/564

**Comment by AnkitM252** [comment]
That issue not the same and This has happened to me too!

**Comment by Ishannaik** [comment]
Template? and fix this bug asap its game breaking no one can log on

**Comment by MCPEGamerJPatGitHub** [comment]
I don't get this bug, lol.

**Comment by Ishannaik** [comment]
no one can log on the server thats it the bug

**Comment by Ishannaik** [comment]
PLeasee fix this no one can join

**Comment by Akuroma** [comment]
Which Account-System do you use. SimpleAuth could cause this issue.

**Comment by Ishannaik** [comment]
i use here auth when i used the phar from 1.0.6 it started that glitch it was working fine on 1.0.5 or are my worlds currupt because i tried tping my self to other worlds but did not work
