### ISSUE TITLE
Noteblock don't work

### ISSUE THREAD

**Issue by SuperXingKong** [TesseractTeam/Tesseract#584]
#### Problem description

When I click a noteblock, it doesn't make any sounds.

#### OS and versions

* Tesseract:
* PHP:
* Server OS:
* Game version: 
* Server host:
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by NFGamerMC** [comment]
Can someone please add me to the org.

**Comment by jdongel2004** [comment]
Noteblock doesn't work.  You can listen Noteblock's sound with plugin.

**Comment by SuperXingKong** [comment]
@jdongel2004 Can you give me an example :?

**Comment by GamakCZ** [comment]
https://forums.pmmp.io/threads/how-to-add-piano-sound.1827/#post-19544
