### ISSUE TITLE
How can I import a singleplayer MC:PE world to a server?

### ISSUE THREAD

**Issue by KensonN** [TesseractTeam/Tesseract#585]

**Comment by AnkitM252** [comment]
You have to convert them into Anvil world!

**Comment by KensonN** [comment]
How would one do this? I'm completely knew to the whole MCPE server thing

**Comment by AnkitM252** [comment]
Google it! Level DB to Anvil!

**Comment by KensonN** [comment]
Got it. Thank you very much!

**Comment by KensonN** [comment]
Hey, I Googled around and found that none of the converters work due to the 1.0.0 world format being different. Do you happen to have a solution?
