### ISSUE TITLE
Item frame error

### ISSUE THREAD

**Issue by PEszem** [TesseractTeam/Tesseract#586]
The first item in the frames of the item to be taken in the field Protect
so:
1. Put an item off FRAM
2. Take off the field
3. Usd players a smooth take off of the Perm territorial

**Comment by Crypthu97** [comment]
The main problem in the area of ​​Product Escapes Being a framework that can modify the elements in it can be removed

**Comment by ISRAPIL** [comment]
Use ItemFrameDropItemEvent

**Comment by ISRAPIL** [comment]
WTF? Contributor?

**Comment by TheRoyalBlock** [comment]
@ISRAPIL before someone answers your question, please consider reading the github documentation to figure out how someone earns the "contributor" tag.
