### ISSUE TITLE
Items won't drop when I kill someone

### ISSUE THREAD

**Issue by Itemple** [TesseractTeam/Tesseract#587]
Why if I kill my playmates the items wont drop 
It's hosted by virtual gladiator
And here's the plugins I'm using
Clearyourinv,clearlagg,simple messages , anti spam , always spawn , advanced kits , more commands , economy , iprotector , world protect , many world's , Slapper

**Comment by MCPEGamerJPatGitHub** [comment]
@ITemple open this issue again using the template. Also, try testing it with all plugins removed. If it still doesn't work and you have the latest Tesseract version, you may get support.

**Comment by ISRAPIL** [comment]
check Tesseract.yml, keepinvenory
