### ISSUE TITLE
Can't connect to serveur ...

### ISSUE THREAD

**Issue by diygun** [TesseractTeam/Tesseract#588]
I can't connect to my server . I try to reboot the server but it not work...

* Tesseract: 1.1 BETA
* PHP: 7
* Server OS: Debian 8 ( vps )
* Game version: 1.1.0.1
* Server host: XeyHost.ml
[Tesseract] [19:06:08] INFO> DiyGunFr[/PLEASE REMOVE THE IP NEXT TIME!:58765] [ClientID: -2044773837247212939] logged in with entity id 1 at (lobby, 256, 4, 256)
[Tesseract] [19:06:10] INFO> DiyGunFr joined the game
[Tesseract] [19:06:18] INFO> DiyGunFr left the game
[Tesseract] [19:06:18] INFO> DiyGunFr[/62.235.15.108:58765] logged out due to timeout

**Comment by TheRoyalBlock** [comment]
Outdated packets on the server side, please wait for the team to update the 1.1 beta.

**Comment by ManiakMCPE** [comment]
Use this  https://github.com/TesseractTeam/Tesseract/tree/2e4fb2767d7971330c563275cfe265fa3e6f1e3e

**Comment by Ishannaik** [comment]
hide the ip pls ;D

**Comment by erkam2002** [comment]
xD

**Comment by Ishannaik** [comment]
do u know u can just google the ip  Scarlet-TIS and located in Belgium

**Comment by Driesboy** [comment]
http://whatismyipaddress.com/ip/62.235.15.108

**Comment by ImagicalGamer** [comment]
Please remove the IP when creating issues next time :)

**Comment by jrodr10** [comment]
Is this caused by the texture pack shitty code that was added? @ImagicalGamer @AppleDevelops

**Comment by diygun** [comment]
Oh Yes sorry ... But I think my ip change evry day (dynamic ip )
Thanks for link
