### ISSUE TITLE
Logo 

### ISSUE THREAD

**Issue by expexes** [TesseractTeam/Tesseract#59]
Make with love :)

![tssrct](https://cloud.githubusercontent.com/assets/21020331/21361434/ad81bb10-c6ec-11e6-96c5-d9ecc8c636b9.jpg)

or

![tssrc2](https://cloud.githubusercontent.com/assets/21020331/21361519/0d749038-c6ed-11e6-9c1f-39feced8b278.jpg)

**Comment by AppleDevelops** [comment]
We'll make sure to use this! Could you by any chance shrink the 2nd photo so we can fit it in our readme file?

**Comment by expexes** [comment]
![0d749038-c6ed-11e6-9c1f-39feced8b278 2](https://cloud.githubusercontent.com/assets/21020331/21381624/08bb9eba-c765-11e6-98bc-a689d1538ba2.jpg)

**Comment by AppleDevelops** [comment]
Thanks a ton! I'll add this when I'm home from school!
