### ISSUE TITLE
Running with PHP7 on Windows gives an odd message from PocketMine

### ISSUE THREAD

**Issue by ALinuxLover** [TesseractTeam/Tesseract#6]
The very first thing printed in the terminal (or whatever Microsoft calls it :P) is this:
```
[CRITICAL] Unable to find the pthreads extension.
[CRITICAL] Please use the installer provided on the homepage.
```
I'm sure I'm missing something obvious.

**Comment by AppleDevelops** [comment]
You don’t have the proper PHP binaries, which is why it doesn’t work.
