### ISSUE TITLE
mob bug

### ISSUE THREAD

**Issue by daniktheboss** [TesseractTeam/Tesseract#60]
please fix the mobs

**Comment by kenygamer** [comment]
@daniktheboss Not a bug, just not implemented.
> ☆∂єvєlσρєя☆
кєνιи αи∂яєωѕ

**Comment by daniktheboss** [comment]
no shit Sherlock. Thats why i made this issue

**Comment by kenygamer** [comment]
@daniktheboss Mob AI isn't implemented.. it's not a lie,
There are alternative plugins such as **PureEntitiesX** that recovers mob AI but doesn't work on *Teserract*.
> ☆∂єvєlσρєя☆
кєνιи αи∂яєωѕ

**Comment by Shadow166050** [comment]
#26

**Comment by kenygamer** [comment]
Duplicate.

**Comment by daniktheboss** [comment]
are you a member of the repo? no sir

**Comment by kenygamer** [comment]
@daniktheboss I am not a member of the repository, but I like saying 'Thank you', etc. I do help other repositories althought I'm not member or contributor of them

**Comment by AnkitM252** [comment]
@kenygamer I know that Mob AI is not implemented but its not related with this!! You should be able to punch mobs without AI!!

**Comment by kenygamer** [comment]
@AnkitM252 I know
> ☆∂єvєlσρєя☆
кєνιи αи∂яєωѕ

**Comment by Rateek** [comment]
duplicate https://github.com/TesseractTeam/Tesseract/issues/26
