### ISSUE TITLE
How to disable Xbox Live authentication?

### ISSUE THREAD

**Issue by MechRalph04** [TesseractTeam/Tesseract#61]
So hello, I wanted to disable Xbox Live authentication because I have a friend that can't connect to Xbox Live so she can't join my server, and I know, too, other players can't, too. And so I am wanting to disable Xbox Live authentication on my server, and Idk how.

**Comment by XDqrkneZ** [comment]
Stop the server
Go to "server.properties"
At the very bottom you should see "online-mode="
Make it "online-mode=off" to disable xbox auth

**Comment by MechRalph04** [comment]
Ok, thanks @XDqrkneZ
