### ISSUE TITLE
How can I remove it?

### ISSUE THREAD

**Issue by ProCOmpTEAM** [TesseractTeam/Tesseract#63]
help me please
![servmcpe](https://user-images.githubusercontent.com/24737193/27509720-b9d17034-590b-11e7-9751-40410fb1696c.PNG)

**Comment by andris155** [comment]
This is a Tesseract bug. Use clearlagg plugin and use /lagg killmobs to fix.

**Comment by andris155** [comment]
https://github.com/TesseractTeam/Tesseract/issues/48

**Comment by andris155** [comment]
This is a Beacon error.
https://github.com/TesseractTeam/Tesseract/issues/49

**Comment by Dhrhciebcy** [comment]
"This is a Tesseract bug. Use clearlagg plugin and use /lagg killmobs to fix"




It doesn't work for me

**Comment by Dhrhciebcy** [comment]
"This is a Tesseract bug. Use clearlagg plugin and use /lagg killmobs to fix"



Not always

**Comment by ProCOmpTEAM** [comment]
@andris155 did'nt worked

**Comment by andris155** [comment]
I changed to GenisysPro and fix all bug.

**Comment by Dhrhciebcy** [comment]
"I changed to GenisysPro and fix all bug"


And is it fast like Tesseract? And where have you downloaded it?

**Comment by Rateek** [comment]
it's fix ! e895c74
