### ISSUE TITLE
Decay Potions Don't Work

### ISSUE THREAD

**Issue by SuperDude36** [TesseractTeam/Tesseract#63]
#### Problem description
If you do /give NAME potion:36 it will give you a decay potion (wither), it does nothing when you drink ir
#### Steps to reproduce the issue
/give NAME potion:36, drink, nothing  happens...
#### OS and versions

* Tesseract: Crystal
* PHP: 7.0.3
* Server OS: Protocol Version 100
* Game version: 1.0/0.17.0

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by AppleDevelops** [comment]
We're still adding those along with a bunch of other things

**Comment by AppleDevelops** [comment]
Soon, a few people on my Twitter are tweeting out teasers about Tesseract, and they aren't part of the repo. I'm waiting on them.

**Comment by SuperDude36** [comment]
I'll just use the one with the most features :)

**Comment by Nought57** [comment]
@SuperDude36 Add Decay Potion. Please use latest version.
