### ISSUE TITLE
What Happend ?

### ISSUE THREAD

**Issue by RottenBread** [TesseractTeam/Tesseract#64]
#### OS and versions

* Tesseract: Crystal
* PHP: 7.0.9
* Server OS: Tesseract ( Protocol 100 )
* Game version: 1.0.0 ( PE )

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```
[Tesseract] [08:34:13] [RakLibServer thread/DEBUG]: #0 /src/raklib/server/SessionManager(157): raklib\server\UDPServerSocket->readPacket(NULL , NULL , NULL )
[Tesseract] [08:34:13] [RakLibServer thread/DEBUG]: #1 /src/raklib/server/SessionManager(105): raklib\server\SessionManager->receivePacket()
[Tesseract] [08:34:13] [RakLibServer thread/DEBUG]: #2 /src/raklib/server/SessionManager(96): raklib\server\SessionManager->tickProcessor()
[Tesseract] [08:34:13] [RakLibServer thread/DEBUG]: #3 /src/raklib/server/SessionManager(84): raklib\server\SessionManager->run()
[Tesseract] [08:34:13] [RakLibServer thread/DEBUG]: #4 /src/raklib/server/RakLibServer(234): raklib\server\SessionManager->__construct(raklib\server\RakLibServer object, raklib\server\UDPServerSocket object)
[Tesseract] [08:34:13] [RakLibServer thread/DEBUG]: #5 (): raklib\server\RakLibServer->run()

I CANNOT Connect to the server.

**Comment by AppleDevelops** [comment]
Who is your host?
