### ISSUE TITLE
DEFAULT world is abnormal

### ISSUE THREAD

**Issue by gigantessbeta** [TesseractTeam/Tesseract#65]
Fatal error: Out of memory (allocated 807403520) (tried to allocate 4096 bytes) in D:\PocketMine\src\pocketmine\level\Level.php on line 1379

**Comment by AppleDevelops** [comment]
Please explain how you encountered this issue

**Comment by gigantessbeta** [comment]
It occurred when the world type entered the world of DEFAULT.
(use SimplePortal)

**Comment by xZeroMCPE** [comment]
@gigantessbeta It might be memory LEAK... Maybe  from SimplePortal itself?

**Comment by NycuRO** [comment]
Fix: https://github.com/Hydreon/Steadfast2/commit/e153acded0294a6469b25a2be61417011266afb7

**Comment by Nought57** [comment]
It is not the problem the Memory Leak.
This problem is caused by the Entity World Teleport bugs.

**Comment by AppleDevelops** [comment]
Cannot reproduce anymore

**Comment by remotevase** [comment]
Can reproduce

**Comment by remotevase** [comment]
Fixing now
