### ISSUE TITLE
Broken lights in the flat world

### ISSUE THREAD

**Issue by ProCOmpTEAM** [TesseractTeam/Tesseract#66]
# Broken lights in the flat world

* Tesseract: 0.0dev
* PHP: 7
* Server OS: Windows 8
* Game version: 1.0.16

**Hi! Help me please! Day and night light everywhere, light stone and lights do not work. Sometimes there are dark spots on the blocks.**
What about it?
![5ef9tl_stcu](https://cloud.githubusercontent.com/assets/24737193/21471764/38743722-cace-11e6-9cf7-a15c1d676bae.jpg)
![k0q1ohurbh4](https://cloud.githubusercontent.com/assets/24737193/21471765/3d915ff0-cace-11e6-96dd-b36eb90718b8.jpg)

**Comment by Nought57** [comment]
This issue ("Sometimes there are dark spots on the blocks") is caused by Chunk Load Bug.
About this issue ("Day and night light everywhere, light stone and lights do not work"), You are using the MCRegion type world?? MCRegion type world has a lot of bugs.

**Comment by ProCOmpTEAM** [comment]
@Nought57 
What can you advise? **Is it possible to save the world and its buildings?**

**Comment by Nought57** [comment]
@ProCOmpTEAM MCRegion is not available.
You need to convert by using the data of the old world.
Please Convert your world to Anvil (mcapm)

**Comment by remotevase** [comment]
Why is this closed? Is it fixed? On other server providers this happens too... To fix place a block in the darkness...
