### ISSUE TITLE
Game Crash/Close When Join

### ISSUE THREAD

**Issue by TheNoobster14** [TesseractTeam/Tesseract#66]
So I just updated my server using the latest SRC from the master code. Now when I join using Win10 and also my tablet it crashes/closes the game! I am not receiving any sort of message in console either. I dont know what is needed to help solve this, I will say that I'm running the server on a VPS running Ubuntu 16.04 and currently have 46 plugins that have never caused a problem before. If you need anything else to help solve I will gladly provide the information. Please dont bash me for not providing enough info just please ask for it instead 😓😖

**Comment by andris155** [comment]
Plugin list?

**Comment by TheNoobster14** [comment]
[Plugin List](http://imgur.com/y4M1ulB)

**Comment by andris155** [comment]
Pureperms is a latest version?

**Comment by TheNoobster14** [comment]
Yes

**Comment by andris155** [comment]
Ok. This is other plugin issue. And not Tesseract.

**Comment by Dearkungchannel** [comment]
i know it is a essential plugin because i found this on console not Tesseract(i am thai people)

**Comment by TheNoobster14** [comment]
Issue has been resolved! It was PurePerms I got another version and it worked fine! Sorry for thinking it was Tesseract but I did update PurePerms to the latest and didnt work had to get another version.

**Comment by Shadow166050** [comment]
Not a tesseract issue - Close

**Comment by iZeaoGamer** [comment]
What version did you update Pureperms to? Because purePerms doesn't work for me. I've tried updating it to 1.4.0-INDEV, 1.3.7, 1.4.1, etc.

**Comment by alexbgameson** [comment]
Slapper plugin doesn't work with any tesseract based server software. Please inform slapper dev about this issue.

**Comment by Rateek** [comment]
It's not tesseract.
