### ISSUE TITLE
Anvil can't change name of item

### ISSUE THREAD

**Issue by Dearkungchannel** [TesseractTeam/Tesseract#67]
#### OS and versions

* Tesseract:
* PHP:
* Server OS:
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files (or screenshot of console)

```
```

**Comment by Dearkungchannel** [comment]
if change will get double item

**Comment by Shadow166050** [comment]
Anvils are broken -  Close Issue

**Comment by kenygamer** [comment]
@Shadow166050  anvils work for me.
They arent broken.
Try turning

**Comment by Dearkungchannel** [comment]
thx it work

**Comment by Dearkungchannel** [comment]
thx it work

**Comment by kenygamer** [comment]
@Dearkungchannel no problem
