### ISSUE TITLE
I cant kill players using sword and tools

### ISSUE THREAD

**Issue by arsenicblast** [TesseractTeam/Tesseract#69]
20:24:18 [CRITICAL] Error: "Undefined class constant 'SHARPNESS'" (EXCEPTION) in "/src/pocketmine/item/Tool" at line 56
20:24:18 [CRITICAL] Error: "Undefined class constant 'SHARPNESS'" (EXCEPTION) in "/src/pocketmine/item/Tool" at line 56
20:24:18 [CRITICAL] Error: "Undefined class constant 'SHARPNESS'" (EXCEPTION) in "/src/pocketmine/item/Tool" at line 56
20:24:18 [NOTICE] Blocked 192.168.0.10 for 5 seconds
20:24:18 [NOTICE] Blocked 192.168.0.11 for 5 seconds
20:24:23 [CRITICAL] Error: "Undefined class constant 'SHARPNESS'" (EXCEPTION) in "/src/pocketmine/item/Tool" at line 56
20:24:23 [CRITICAL] Error: "Undefined class constant 'SHARPNESS'" (EXCEPTION) in "/src/pocketmine/item/Tool" at line 56
20:24:23 [CRITICAL] Error: "Undefined class constant 'SHARPNESS'" (EXCEPTION) in "/src/pocketmine/item/Tool" at line 56
20:24:23 [CRITICAL] Error: "Undefined class constant 'SHARPNESS'" (EXCEPTION) in "/src/pocketmine/item/Tool" at line 56
20:24:23 [CRITICAL] Error: "Undefined class constant 'SHARPNESS'" (EXCEPTION) in "/src/pocketmine/item/Tool" at line 56
20:24:23 [CRITICAL] Error: "Undefined class constant 'SHARPNESS'" (EXCEPTION) in "/src/pocketmine/item/Tool" at line 56
20:24:23 [CRITICAL] Error: "Undefined class constant 'SHARPNESS'" (EXCEPTION) in "/src/pocketmine/item/Tool" at line 56
20:24:24 [CRITICAL] Error: "Undefined class constant 'SHARPNESS'" (EXCEPTION) in "/src/pocketmine/item/Tool" at line 56
20:24:24 [CRITICAL] Error: "Undefined class constant 'SHARPNESS'" (EXCEPTION) in "/src/pocketmine/item/Tool" at line 56
20:24:24 [CRITICAL] Error: "Undefined class constant 'SHARPNESS'" (EXCEPTION) in "/src/pocketmine/item/Tool" at line 56
20:24:24 [NOTICE] Blocked 192.168.0.10 for 5 seconds
20:24:43 [CRITICAL] Error: "Undefined class constant 'SHARPNESS'" (EXCEPTION) in "/src/pocketmine/item/Tool" at line 56
20:24:43 [NOTICE] Blocked 192.168.0.10 for 5 seconds

**Comment by ZaydPE** [comment]
When does this occur? We need more information.

**Comment by Shadow166050** [comment]
Can not reproduce, Close

**Comment by arsenicblast** [comment]
How can it happen : Go get your sword,Try to hit someone and then that will popup on your console

**Comment by kenygamer** [comment]
@arsenicblast there's constant undefined
You are using a sword with sharpness.
> ☆∂єvєlσρєя☆
кєνιи αи∂яєωѕ

**Comment by Rateek** [comment]
need more information and reopen issues
