### ISSUE TITLE
any error

### ISSUE THREAD

**Issue by armagadon159753** [TesseractTeam/Tesseract#7]
# when player open inventory MCPE client crash 
**CONSOLE**
![screenshot_2017-06-17-20-21-40](https://user-images.githubusercontent.com/25569806/27255258-e680f508-539a-11e7-9182-6537292c05ee.png)

# missing src/pocketmine/level/generator
**CONSOLE**
![screenshot_2017-06-17-20-15-54](https://user-images.githubusercontent.com/25569806/27255265-16ae708e-539b-11e7-9e04-30e9884a06bb.png)

I can help you for finished src/pocketmine/level

**Comment by RateekMCPE** [comment]
@armagadon159753 Tu peut créer ta propre Task (Custom).
