### ISSUE TITLE
Problem when hitting.

### ISSUE THREAD

**Issue by Enrick3344** [TesseractTeam/Tesseract#7]
#### Problem description
After a while, when i break a block my friend arms move without her touching her screen.

#### Steps to reproduce the issue
Hit the floor close to someone.

#### OS and versions

* Tesseract: 1a90bd1
* PHP: 7 
* Server OS: Windows 10
* Game version: 1.0
* Server host: Cubedhost
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by YaBoiSavion** [comment]
This is a mcpe issue not this server software

**Comment by Enrick3344** [comment]
Okay thanks! was wondering cuz it wasnt doing that before

**Comment by remotevase** [comment]
Haha this has something to do with real life+gravity
