### ISSUE TITLE
Block break bug

### ISSUE THREAD

**Issue by Crypt97** [TesseractTeam/Tesseract#70]
#### Issue description
watch video: https://www.youtube.com/watch?v=NRBzhbuJ3U4&feature=youtu.be

#### Steps to reproduce the issue
i dont know

#### OS and versions

* Tesseract: 1.2.0
* PHP: 7.0
* Server OS: Ubuntu
* Game version:  1.1.0.55

#### Crashdump, backtrace, memory dumps, plugins list or other files (or screenshot of console)

```
```

**Comment by HipsterAF** [comment]
tesseract is discontinued sorry

**Comment by Crypt97** [comment]
:(
