### ISSUE TITLE
Teleport issue

### ISSUE THREAD

**Issue by NycuRO** [TesseractTeam/Tesseract#71]
#### Steps to reproduce the issue

If you die, you teleport back where you die...

*In not all cause*
#### OS and versions

* Tesseract: https://github.com/TesseractTeam/Tesseract/commit/4b9baed99b0ef2eb66dec2548b03f2b9aeed78d5
* PHP: 7.0.14
* Server OS: Ubuntuu 16.04.1 LTS 64bit
* Game version: 1.0.0
* Server host: gazduirejocuri.ro
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Nought57** [comment]
The same phenomenon has occurred.
The console of the server freezes with /TP command.
This issue is caused by the Chunk Bug.
There are chunks related bugs.

**Comment by Nought57** [comment]
The same phenomenon has occurred.
The console of the server freezes with /tp command.
This issue is caused by the Chunk Bug.
There are chunks related bugs.

**Comment by AppleDevelops** [comment]
Fixed
