### ISSUE TITLE
Need to add elytra?

### ISSUE THREAD

**Issue by remotevase** [TesseractTeam/Tesseract#73]
If you would like, I can add the elytra features from here using Ad5001/Elytra#1
Note: Not the PR, but the actual code

**Comment by xZeroMCPE** [comment]
And maybe Enderchest

**Comment by remotevase** [comment]
So I take it thats a yes? Also plz work on WingProxy plz plz plz

**Comment by Nought57** [comment]
Problem occurs with the Anti-Cheat.
Future, Add elytra and Delete Anti-Cheat System??

**Comment by AppleDevelops** [comment]
We no longer have that anti cheat

**Comment by remotevase** [comment]
Unfortunately I am unable to add elytra copying ad5001s code but I will add it anyways using my own code

**Comment by remotevase** [comment]
see #80
