### ISSUE TITLE
Long loading.

### ISSUE THREAD

**Issue by ZloyNick** [TesseractTeam/Tesseract#75]
#### Issue description

When im connecting to server (mcpe 1.1.3), client genarates map for a long times.

#### OS and versions

* Tesseract: 1.2.0 Ruby
* PHP: 7.0.20
* Server OS: Debian 7 86x_64
* Game version: Minecraft:PE 1.1.3

#### Crashdump, backtrace, memory dumps, plugins list or other files (or screenshot of console)

```
```

**Comment by ZloyNick** [comment]
Tesseract > Steve[/212.26.236.93:2597] вошел с id сущности -6083172325362448100 на (38, world, -153.7784, 79)
Tesseract > Error: "Call to a member function getBiomeId() on null" (EXCEPTION) in "/src/pocketmine/level/generator/normal/populator/GroundCover" at line 41

**Comment by ProCOmpTEAM** [comment]
I have problem as your
![console](https://user-images.githubusercontent.com/24737193/27985438-ad59798a-63f3-11e7-8c00-a6a700fc876f.PNG)

**Comment by Rateek** [comment]
fix https://github.com/TesseractTeam/Tesseract/commit/e895c7403faa8fe0ecbb235ed6c0c17504f3410f
