### ISSUE TITLE
Problem When Joining My Server. (still not fixed)(Login Timeout)

### ISSUE THREAD

**Issue by Enrick3344** [TesseractTeam/Tesseract#79]
#### Problem description
I download the Tesseract latest version on Jenkins and each time i try to get in, There is errors in console and it kick me for login timeout. And it say server is not running on Multicraft but it is.

#### Steps to reproduce the issue
Trying to enter the server.

#### OS and versions

* Tesseract: 4b9baed  #260 (jenkins)
* PHP: 7.0.14
* Server OS: 
* Game version: WIN10/ 1.0.0
* Server host: CubedHost
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files
I get those 2 errors (in order):

27.12 15:19:43 [Server] INFO [Tesseract] [17:19:43] CRITICAL> Error: "Call to undefined method pocketmine\level\format\generic\GenericChunk::getBiomeColor()" (EXCEPTION) in "/src/pocketmine/level/Level" at line 2732

27.12 15:19:53 [Server] INFO Notice: Undefined property: pocketmine\Server::$redstoneEnabled in phar:///phar/custom.phar/src/pocketmine/entity/Entity.php on line 1753

**Comment by xZeroMCPE** [comment]
Test it on the current branch / update,

**Comment by Enrick3344** [comment]
But on my host only the .phar files work and i tried to compile it but its not working.

**Comment by xZeroMCPE** [comment]
Check our jenkins :)

**Comment by Enrick3344** [comment]
Thanks!:)

**Comment by Enrick3344** [comment]
The last one i see i tried it and its the one that made those error.

**Comment by remotevase** [comment]
Confirmed for me as well
And I update my server to the latest src from github every 12 hours (last update 7 hours ago)

**Comment by Enrick3344** [comment]
It does the same error for you?

**Comment by remotevase** [comment]
Yes, I get the login timeout.

**Comment by Enrick3344** [comment]
Because there is another one out on Jenkins but build failed.

**Comment by remotevase** [comment]
yes I thought so.. The latest commit has some problems

**Comment by remotevase** [comment]
Okay. We need to revert the latest commit, as the job was not done fully. There are other instances that fetch the protocol from info.php other than the 1 instance that was replaced in the commit. Either finish the job (update ALL instances to INFO::CurrentProtocol) or revert the commit. The current stages are causing the server to have a login timeout

**Comment by Enrick3344** [comment]
Probably! you seem to know what you're talking about. Not me! lol but when the job would be finish we would have to put it in jenkins

**Comment by remotevase** [comment]
Yes, I know what I am talking about. I used to run ImagicalMine (you may have heard of that before) and I am also a plugin dev

**Comment by Enrick3344** [comment]
Nice!!! Need a plugin dev but meh! and yea I've heard about Imagicalmine

**Comment by AppleDevelops** [comment]
Try latest build now

**Comment by remotevase** [comment]
Apple you didnt fix anything... there are no commits, please reopen

**Comment by Enrick3344** [comment]
Still having the GetBiome Problem and multicraft still saying server is closed. nothing changed

**Comment by AppleDevelops** [comment]
getBiome for MCRegion worlds?

**Comment by Enrick3344** [comment]
yes my default world type is mcregion

**Comment by AppleDevelops** [comment]
That's why for one

**Comment by Enrick3344** [comment]
have to put my default format into Anvil?

**Comment by remotevase** [comment]
Oh yes @AppleDevelops mine are also mcr

**Comment by Enrick3344** [comment]
but what about the Multicraft? will it fix it

**Comment by AppleDevelops** [comment]
MultiCraft issue is a little difficult for me to figure out since I'm waiting on EnderCrate to give me a free server

**Comment by Enrick3344** [comment]
Okay Thanks Apple ill test it
! @remotevase i sent you an email!

**Comment by Enrick3344** [comment]
Still Did Not Work...

**Comment by Enrick3344** [comment]
What can I do To make it work! i put my default-format to anvil and nothing changed

**Comment by Enrick3344** [comment]
Please fix it...

**Comment by Infernus102** [comment]
Getting same error, undefined method getBiomeColor()

**Comment by Nought57** [comment]
To resolve this issue (Undefined property: RedstoneEnabled), update to the latest version.
This issue (Error: Call to undefined method GenericChunk::getBiomeColor()
) is due to a MCRegion bug. Am trying to fix.

**Comment by Infernus102** [comment]
Are you gonna fix getBiomeColor() or no? @AppleDevelops @Nought57

**Comment by Nought57** [comment]
@Infernus102 I fixed that. successfully working now.

**Comment by Nought57** [comment]
A temporary error avoidance. (Until the corresponding)

**Comment by Infernus102** [comment]
Check the issue i created @Nought57

**Comment by Nought57** [comment]
@Infernus102 OK

**Comment by Enrick3344** [comment]
@Nought57 No more error in console thats great but getting the login timeout and it doesnt say that i tried to join in my console.

**Comment by Infernus102** [comment]
Damn

**Comment by Enrick3344** [comment]
there is an update that was letting me on was the #257 on jenkins. thats what I'm using while it's getting fixed. idk if that could help you @Nought57

**Comment by Infernus102** [comment]
Yes but that error is giving me the skull error

**Comment by Infernus102** [comment]
The login timeout seems to be the latest commits problem as said by @remotevase

**Comment by remotevase** [comment]
Restatement
>Okay. We need to revert the latest commit, as the job was not done fully. There are other instances that fetch the protocol from info.php other than the 1 instance that was replaced in the commit. Either finish the job (update ALL instances to INFO::CurrentProtocol) or revert the commit. The current stages are causing the server to have a login timeout
PS: this would be a lot easier if I was a colaborator...

**Comment by Enrick3344** [comment]
yes! Guys do that please!

**Comment by remotevase** [comment]
Ah, I didn't see my invitation to the organization... I'll try to fix it soon

**Comment by Infernus102** [comment]
fixed

**Comment by Infernus102** [comment]
[Tesseract] [00:07:15] INFO> An unknown error occurred while attempting to perform this command
[Tesseract] [00:07:15] CRITICAL> Unhandled exception executing command 'makeserver' in makeserver: Call to undefined method pocketmine\Server::getGeniApiVersion()
[Tesseract] [00:07:15] CRITICAL> Error: "Call to undefined method pocketmine\Server::getGeniApiVersion()" (EXCEPTION) in "/plugins/DevTools_v1.1.1-iTX.phar/src/DevTools/commands/MakeServerCommand" at line 43
makeserver wont work

**Comment by remotevase** [comment]
:+1:

**Comment by Enrick3344** [comment]
how did you got it to work @Infernus102

**Comment by Infernus102** [comment]
This seems to be working for me but freezes up the server - https://www.dropbox.com/s/tzl39u850s1bh11/Tesseract__2016-12-29_01-25-33.phar?dl=0

**Comment by Enrick3344** [comment]
Thanks @Infernus102 It Work!!:D and yea its kinda laggy! Lets just wait for the other update! and can you explain how you find the phar?

**Comment by Infernus102** [comment]
https://github.com/TesseractTeam/DevTools Downloaded this and started the server with src and did /makeserver in console

**Comment by Enrick3344** [comment]
oh but on my server i can't start server with src thats what is annoying...

**Comment by Infernus102** [comment]
I don't know about that

**Comment by Nought57** [comment]
@remotevase Could you invite to the Tesseract Team??
If it is possible, please invitation to the Tesseract organization.
I tried to fix some errors. but, Take time to fix in pull request.

**Comment by Infernus102** [comment]
@nought57 can you fix the #86 issue?

**Comment by Nought57** [comment]
@Infernus102 I'll try to fix it. However, difficult to verify it.

**Comment by Infernus102** [comment]
Ik since no error and crashdump

**Comment by Nought57** [comment]
@Infernus102 I know.

**Comment by Enrick3344** [comment]
i have another issues

**Comment by Enrick3344** [comment]
with the one you sent me @Infernus102 . What was the last commit updated when you made your phar to send it to me?

**Comment by Infernus102** [comment]
It was the latest

**Comment by Enrick3344** [comment]
so the one right now?

**Comment by Infernus102** [comment]
Yes

**Comment by Nought57** [comment]
@AppleDevelops I have sent an Commit. However, an "No Permission" error appears.
I use desktop Repository. I can only sent pull request. I feel like this situation hasn't changed...
Contributor not have Share Repository. but, I need Share Repository. Please invitation to the organization...
If it is possible, I can help for team...

**Comment by Infernus102** [comment]
Why not just create pull request?

**Comment by Nought57** [comment]
@Infernus102 I tried to fix some errors. but, Take time to fix in pull request.

**Comment by Infernus102** [comment]
Did you fix the freezing error?

**Comment by Enrick3344** [comment]
what you want to do is to fix everything/bug we are having?

**Comment by Nought57** [comment]
@Infernus102 In this case, with no errors. if to cause New bug. need As soon as possible, revert.

**Comment by Enrick3344** [comment]
There is alot of Bug i could make a whole list

**Comment by Infernus102** [comment]
Can you just create a pull req for now so i can check

**Comment by Infernus102** [comment]
Do it @enrick3344

**Comment by Enrick3344** [comment]
okay:
-The block issues i put,
-Multicraft Not saying server is on.
-Freeze alot and have a memory bug.
-when someone hit the floor (my friend) my arm move too.
-Sometime other world chunk get over your world.
-really slow to load world.

**Comment by Enrick3344** [comment]
when you place block in the block issues you can just right click and blocks come back

**Comment by Enrick3344** [comment]
There we Go thats what i see that need to be fixed @Infernus102 @Nought57

**Comment by Infernus102** [comment]
multicraft bug is because your host hasn't put tessaract in there mods, just let them know you want tessaract just like i did, and it will work

**Comment by Enrick3344** [comment]
ok thanks
