### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by DonkihotD** [TesseractTeam/Tesseract#79]
I use latest version of Tesseract

#### Issue description
In my plugin I create 2 configs JSON. Why with configs JSON creates config YAML?

#### OS and versions

* Tesseract: latest
* PHP: 7.1
* Server OS: Debian 8
* Game version: 1.1.2 and 1.1.3

Crashdumps nope
```
```

**Comment by Rateek** [comment]
I not tesseract.
