### ISSUE TITLE
Real or old ?

### ISSUE THREAD

**Issue by erkam2002** [TesseractTeam/Tesseract#790]
Is this now the real tesseract or the other https://github.com/ServerSoftwareArchive/Tesseract ?
Need an answer pls!

**Comment by TDMidkwhatisxd** [comment]
Im confused too . :s

**Comment by erkam2002** [comment]
xD

**Comment by NFGamerMC** [comment]
Eveeybody, the link is the new one

**Comment by AppleDevelops** [comment]
This one that you've reported the issue to, is outdated and is maintained by Linux who copied everything I committed on the new repo

**Comment by NFGamerMC** [comment]
Apple can you disable this org and make it go to the new one?

**Comment by AppleDevelops** [comment]
Can't, Linux removed all the owners and removed me from the repo.

**Comment by NFGamerMC** [comment]
I did you want this repo to go down, I can ask him

**Comment by NFGamerMC** [comment]
Okay, reported him!

**Comment by TheRoyalBlock** [comment]
so did I

**Comment by NFGamerMC** [comment]
Thanks, you have access to imagicalmine inside the new org ServerSoftwareArchive

**Comment by TheRoyalBlock** [comment]
ik

**Comment by NFGamerMC** [comment]
Chat with me on Discord

**Comment by TheRoyalBlock** [comment]
kk
