### ISSUE TITLE
Tesseract has Moved

### ISSUE THREAD

**Issue by NFGamerMC** [TesseractTeam/Tesseract#791]
Tesseract has moved to https://github.com/ServerSoftwareArchive/Tesseract. Ask @AppleDevelops the founder

**Comment by erkam2002** [comment]
Why its moved -,-

**Comment by NFGamerMC** [comment]
Apple wanted to revive all server software in on org. Go there for the new ImagicalMine, Genesis, PocketMine, and Cenisys

**Comment by MechRalph04** [comment]
Elywing moved to Tesseract, Tesseract moved to a new reprository.

**Comment by MechRalph04** [comment]
And cool! :D
