### ISSUE TITLE
Why do you steal it

### ISSUE THREAD

**Issue by caspervanneck** [TesseractTeam/Tesseract#793]
Why its not dead so

**Comment by jrodr10** [comment]
its dead now and apple will prob delete his version buh ill close this one till he does

**Comment by TheRoyalBlock** [comment]
Its not dead, apple is not gonna delete it...

**Comment by NFGamerMC** [comment]
I am owner so anyway I can rever the delete!

**Comment by TheRoyalBlock** [comment]
Delete this repository please.

**Comment by NFGamerMC** [comment]
Only he can, he devoted everyone else

**Comment by TheRoyalBlock** [comment]
You literally just said
> I am owner so anyway I can rever the delete!
