### ISSUE TITLE
Moved!

### ISSUE THREAD

**Issue by AppleDevelops** [TesseractTeam/Tesseract#794]
https://github.com/ServerSoftwareArchive/Tesseract

**Comment by MCPEGamerJPatGitHub** [comment]
@AppleDevelops I hope he doesn't take this down again... that little dick

**Comment by AppleDevelops** [comment]
He will, all he's done is steal the code from the new repo

**Comment by NFGamerMC** [comment]
Everyone report him!!

**Comment by MCPEGamerJPatGitHub** [comment]
@AppleDevelops I'll report him and make sure he will never be noticed in a good way 👍🏻

**Comment by NFGamerMC** [comment]
@AppleDevelops Do you know of any GitHub issue spam Bots?

**Comment by AppleDevelops** [comment]
@xZeroMCPE has one

**Comment by NFGamerMC** [comment]
Okay, in his profile?

**Comment by AppleDevelops** [comment]
no

**Comment by NFGamerMC** [comment]
Ohh, I I make a lot. People will get email notifications of they are watching the repo
