### ISSUE TITLE
WTF

### ISSUE THREAD

**Issue by ImagicalGamer** [TesseractTeam/Tesseract#8]
1. Why is my email on Travis-CI? I got 67 emails last night from Travis-CI and this repo.
2. Why is there another PHP software? Theres like 40 this is utterly ridiculous contribute to the main repo skrubs

**Comment by TheAppleGamer** [comment]
Travis should have been set up with my email lmfao but it didn't, I started this because I don't do Python alone and I've got nothing better to do
