### ISSUE TITLE
Pls Disable The Rain

### ISSUE THREAD

**Issue by ExplodingCraftPE** [TesseractTeam/Tesseract#80]
#### Issue description

The Rain Is Pretty Annoying Because Of My Server Had Players And The Rain Will Start And My Players Will Say "WTF Rain" They Get Perm Ban For The Badwords Pls Fix

#### Steps to reproduce the issue

Just Disable The Rain

#### OS and versions

* Tesseract: Latest 1.1.X
* PHP: 7.0
* Server OS: Windows 2015
* Game version: 1.1.0.55

#### Crashdump, backtrace, memory dumps, plugins list or other files (or screenshot of console)

```
```

**Comment by xZeroMCPE** [comment]
Use /weather clear
