### ISSUE TITLE
Chat spam

### ISSUE THREAD

**Issue by Infernus102** [TesseractTeam/Tesseract#85]
#### Problem description

Commands running several times or has to do something with chat.
![untitles](https://cloud.githubusercontent.com/assets/22660649/21530145/a16c8db8-cd64-11e6-89dd-83c03c0cf206.png)
#### OS and versions

* Tesseract: Tesseract Crystal
* PHP: 7.0.10
* Server OS: Linux
* Game version: MCPE v1.0
* Server host: VG
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
None
```

**Comment by xZeroMCPE** [comment]
It's not a command spam, it's message spam..

Somehow messages are sent to the player multiple times..

I confirmed, this happens. Try running any commands and messages will get sent to you multiple times or triple.

**Comment by AppleDevelops** [comment]
Client side issue
