### ISSUE TITLE
Can't get response for commands via RCON

### ISSUE THREAD

**Issue by ariefbayu** [TesseractTeam/Tesseract#85]
Previously, I was testing PMMP and use this [RCON tools](https://github.com/ekaomk/Minecraft-RCON-Console/) to issue command from web without issue.

However, I can't seems to send command to Tesseract via RCON.
#### Steps to reproduce the issue

1. Install latest version from RCON tools repo.
2. Install latest version from Tesseract repo.
3. Issue command from RCON tools website.
4. Command not delivered / recognized. (No response from RCON server)

#### OS and versions

* Tesseract: Latest
* PHP: 7.0
* Server OS: Ubuntu
* Game version: Version: 1.3.0 Codename: Diamond

#### Crashdump, backtrace, memory dumps, plugins list or other files (or screenshot of console)

```
```

**Comment by Rateek** [comment]
Enable rcon xddd

**Comment by ariefbayu** [comment]
sorry, apparently I copied the config from another server, hence rcon password difference. It's all running well now.
