### ISSUE TITLE
PurePerms always kills the server

### ISSUE THREAD

**Issue by NickTehUnicorn** [TesseractTeam/Tesseract#86]
#### Issue description
So without PurePerms, my server is nothing. Just a map. all my permissions and stuff are in it and Teserract somehow doesn't work with it. It doesn't et me join and crashes MCPE.

#### Steps to reproduce the issue
Got the latest PurePerms
Got the latest Teserract

#### OS and versions

* Tesseract: 1.3.0
* PHP: 7.0.3
* Server OS: Windows 10
* Game version: Windows 10 Edition v1.1.3

#### Crashdump, backtrace, memory dumps, plugins list or other files (or screenshot of console)

![2017-07-11_li](https://user-images.githubusercontent.com/29836508/28060874-3ceb88b0-6631-11e7-8a0f-f0ae2afc5860.jpg)
Plugins: PurePerms & PureChat

**Comment by Crypt97** [comment]
Use old PurePerms !
