### ISSUE TITLE
Freezes up

### ISSUE THREAD

**Issue by Infernus102** [TesseractTeam/Tesseract#86]
#### Problem description

Server freezes up when more than 5 players join sometimes 10, load goes to 100%
#### OS and versions

* Tesseract: Tesseract Crystal
* PHP: 7.0.10
* Server OS: Linux
* Game version: MCPE v1.0
* Server host: VG
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
None
```

**Comment by Infernus102** [comment]
Apple can you fix? Virtual gladiators are now using tesserract because of my ticket

**Comment by Infernus102** [comment]
#55

**Comment by SuperMaXAleX** [comment]
Strange. I don't' have this on my server with Elywing .-. (It's not advertising, just compared)

**Comment by Infernus102** [comment]
dude, atleast this loads up a mcr world perfectly

**Comment by Nought57** [comment]
#56 #65 #66 Associated with MCRegion Bug, Chunk Bug.

**Comment by Infernus102** [comment]
you sure?

**Comment by Nought57** [comment]
@Infernus102 Overload is chunk loading

**Comment by Infernus102** [comment]
how does load increase then?

**Comment by Infernus102** [comment]
ahhh

**Comment by Nought57** [comment]
@Infernus102 Do you know about the Teleport Bug Issues??

**Comment by Infernus102** [comment]
if you mean the lag/freeze when you teleport then yes

**Comment by Nought57** [comment]
@Infernus102 in the same way.

**Comment by Infernus102** [comment]
what?

**Comment by Nought57** [comment]
@Infernus102 chunk overload bug.

**Comment by Infernus102** [comment]
yea

**Comment by Infernus102** [comment]
can you fix #85?

**Comment by xZeroMCPE** [comment]
@Infernus102 I think it has to do with somekind of packets, somehow same thing happens on Nukkit..

But will be taking a look at  it...

**Comment by Infernus102** [comment]
@xZeroMCPE You should add @Nought57 in the org. He seems active.

**Comment by Infernus102** [comment]
@Nought57 i don't think your pr fixed because the load just went to 31% when i teleported and i was the only player online

**Comment by Nought57** [comment]
@Infernus102 Chunk Bug is not related to Number of Online Player.

**Comment by Nought57** [comment]
@Infernus102 Occurs regardless of the number of Online Player.
Trying to fix the bug. Please wait until correspondence.

**Comment by Nought57** [comment]
@xZeroMCPE I know. About the chunk packets is a validating.

**Comment by xZeroMCPE** [comment]
@Nought57 Yeah, I'm also trying to fix this issue trying to debug and look at some timings.

**Comment by remotevase** [comment]
CONFIRMED!!!!! THIS IS CRAZY...

**Comment by remotevase** [comment]
Console says logged out timeout, client shows a frozen game

**Comment by xZeroMCPE** [comment]
I think this happened because of  @AppleDevelops commit about the chunks thing..

**Comment by remotevase** [comment]
Yes, the single chunks commit caused 7 new issues that were not there before

**Comment by xZeroMCPE** [comment]
@remotevase I have an idea, revert it and COMMIT it again... I think he did something wrong..

**Comment by AppleDevelops** [comment]
Fixed

**Comment by remotevase** [comment]
Not fixed...
