### ISSUE TITLE
Blocks Problem

### ISSUE THREAD

**Issue by Enrick3344** [TesseractTeam/Tesseract#88]
#### Problem description
when i try to put another block where an old block was, it change it back to the old one each time! and it doesnt go away for other players. and we just have to right click and the block come back!!!
#### Steps to reproduce the issue
Place a block on the floor, break it, take another block in your inventory and try to place it where the other one was. Voila!

#### OS and versions

* Tesseract: 07570a1 (Latest)
* PHP: 7.0.10
* Server OS: Windows 10 Edition
* Game version: MCPE 1.0
* Server host: Cubedhost
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Infernus102** [comment]
Weird problem

**Comment by Nought57** [comment]
This world bug isuues means, no edit no save??

**Comment by Nought57** [comment]
No drop item bug.

**Comment by Nought57** [comment]
No drop item bug.

**Comment by Nought57** [comment]
No drop item bug.

**Comment by Nought57** [comment]
item and block

**Comment by Enrick3344** [comment]
not a drop. placing blocks!

**Comment by Enrick3344** [comment]
when placing one then removeing and putting another block on it it doesnt work

**Comment by Infernus102** [comment]
that might be lag or freezing

**Comment by Enrick3344** [comment]
probably

**Comment by Nought57** [comment]
Bug did not occur until yesterday.

**Comment by Nought57** [comment]
Trying to fix the bug. Please wait until correspondence.

**Comment by Enrick3344** [comment]
The new tesseract on Jenkins is having problem.. been working on for 6 hours is that normal? @Nought57

**Comment by Enrick3344** [comment]
on the bottom of console output there is this:
Failed loading /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so:  /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so: cannot open shared object file: No such file or directory

**Comment by AppleDevelops** [comment]
Fixed
