### ISSUE TITLE
Crazy ? (╬☉д⊙)

### ISSUE THREAD

**Issue by lowingly** [TesseractTeam/Tesseract#948]
You only need to update the ReadMe and tell everyone Tesseract  move.
Why did you submit so much spam (ﾒ ﾟ皿ﾟ)ﾒ

**Comment by NFGamerMC** [comment]
He removed our access, that was the only way to alert people!

**Comment by lowingly** [comment]
Who is the main developer of Tesseract? 
Who is officially recognized by the developer?
I think you guys are robbing Tesseract's official renewal right?
Can someone concentrate on updating Tesseract?
Constantly quarreling, snatching, moving, is very boring.

**Comment by NFGamerMC** [comment]
1. AppleDevelops
2. AppleDeblops
3. No, read the licence
4. Yes, on the new repo
5. I agree but this will be over soon!

**Comment by TDMidkwhatisxd** [comment]
You banned me here noob. Wen i proposed a fix! Why would i belive a stupid kid?

**Comment by jrodr10** [comment]
🤔
