### ISSUE TITLE
Again and again and again........

### ISSUE THREAD

**Issue by poustmal** [TesseractTeam/Tesseract#951]
This starts to be boring.tesseract discontinued,tesseract moved to nfcgamer and others,then again here,stolen   respitory,appledevelops made an organisation to save tesseract etc. and now that organization removed.If you don't want all to continue,just tell it.I believed this software was stable.I don't want to use pocketmine or another software that is unfunctionable or with more problems.

**Comment by TheRoyalBlock** [comment]
I do believe that Tesseract is discontinued. I recommend switching to https://github.com/BlueLightJapan/BlueLight instead of using this.

**Comment by NFGamerMC** [comment]
Yeah, it is more stable (srry grammar)
