### ISSUE TITLE
Information

### ISSUE THREAD

**Issue by jrodr10** [TesseractTeam/Tesseract#954]
Hey guys.. so things are semi back to normal and hopefully people will continue to contribute to tesseract as like i said.. apple deleted his version.. again.... Make issue reports if you need help <3 much love bai

**Comment by Nought57** [comment]
The lost credit can't be revived.

**Comment by Nought57** [comment]
The lost credit can't be revived.

**Comment by AppleDevelops** [comment]
I didn't delete my version, Jake deleted it

**Comment by TDMidkwhatisxd** [comment]
I was sure! Maybe I continue tesseract locally.

**Comment by Nought57** [comment]
@jrodr10 Why did you change the permission?
The fact that you can not edit Repo means the end of Tesseract.
Everything is ambiguous, no one knows the future.
User is waiting for official announcement.

**Comment by jrodr10** [comment]
I would allow pushing commits but it would prob end up like it did before I fixed it

**Comment by jrodr10** [comment]
@Nought57

**Comment by ImagicalGamer** [comment]
@jrodr10 I would like to be owner of my organization again -.-

**Comment by erkam2002** [comment]
1.0.7 is out

**Comment by jrodr10** [comment]
Updated already @erkam2002

**Comment by erkam2002** [comment]
ok

**Comment by AppleDevelops** [comment]
@ImagicalGamer Linux is too high strung, he isn't giving up the repo even tho he can't code
