### ISSUE TITLE
InventoryTransactionEvent

### ISSUE THREAD

**Issue by SergeyIvanov14** [TesseractTeam/Tesseract#955]
#### Problem description
When i use InventoryTransactionEvent in plugin, when i checking if player click item in chest he should to send message to him. But when player use item in PlayerInventory, working function when player use in chest.
#### Steps to reproduce the issue
Use this code:

public function transactionEvent(\pocketmine\event\inventory\InventoryTransactionEvent $e){
foreach($e->getTransaction()->getTransactions() as $transaction){
foreach($e->getTransaction()->getInventories() as $inv){
if($inv->getHolder() instanceof \pocketmine\Player) $p = $inv->getHolder();
elseif($inv->getHolder() instanceof \pocketmine\tile\Chest) $chest = $inv->getHolder();
if($transaction->getTargetItem()->getId() == 0 and $transaction->getTargetItem()->getDamage() == 0){
$p->sendMessage("Working");
}}}}

When I removed the check for the player's inventory code don't send message.

#### OS and versions
* Tesseract: 1.1.0 Ruby
* PHP: 7.3
* Server OS: Ubuntu
* Game version: 1.0.5.0
* Server host: ihor.ru

#### Crashdump, backtrace, memory dumps, plugins list or other files
No crashes
```
```

**Comment by jrodr10** [comment]
Update to the latest version

**Comment by ImagicalGamer** [comment]
This isn't a Tesseract issue, this is a plugin issue.
