### ISSUE TITLE
Lies?

### ISSUE THREAD

**Issue by NFGamerMC** [TesseractTeam/Tesseract#956]
ImahicalGamer deleted the org. That is what the logs say!

**Comment by MCPEGamerJPatGitHub** [comment]
@NFGamerMC He accidentally deleted it but didn't care to restore it

**Comment by NFGamerMC** [comment]
No, he is working for jrodr. That is why he was not kicked from the org!

**Comment by erkam2002** [comment]
Bruh

**Comment by AnkitM252** [comment]
BTW I was not kicked from the org! I left it cause its no longer official! And the official one is [here](https://github.com/ServerSoftwareArchive/Tesseract)

**Comment by ImagicalGamer** [comment]
I deleted it because it was never supposed to happen, we do not own any of those repos that were there and therefore it was not ours to manage so I deleted it.

**Comment by NFGamerMC** [comment]
Ohh, can I be added back to this?

**Comment by erkam2002** [comment]
I too xD

**Comment by archie426** [comment]
Funny how spooners have all these problems. Shows true character in all the developers....
