### ISSUE TITLE
Can I be added!

### ISSUE THREAD

**Issue by NFGamerMC** [TesseractTeam/Tesseract#957]
Hey, jrodr10.
I a, sorry for spamming you and others and now I understand as the repo did get deleted. Could you please add me back to Tesseract. My role was the guy who manages the Web, and all of the CI. Plus a surprise (XenForo)

**Comment by SuperMaXAleX** [comment]
Linux will never give us back the possibility to be on Tesseract lmao
He will just fuck this out

**Comment by PluginBOXone** [comment]
I thinkI think he won't add you again! Because you are a bad person... deleting tesseract and saying this is repo here is illegal... spamming issues... I think you know what I mean!

**Comment by NFGamerMC** [comment]
This is illegal, this violates the licence and a bunch of other stuff. I can get this toook down if I report this!

**Comment by ImagicalGamer** [comment]
This doesn't violate the license, Tesseract was created here and never officially moved by the org owner (me).

**Comment by NFGamerMC** [comment]
Yes it does, read the licence twice!
