### ISSUE TITLE
This ends here.

### ISSUE THREAD

**Issue by NFGamerMC** [TesseractTeam/Tesseract#960]
https://github.com/TesseractSoftware/Tesseract

**Comment by TDMidkwhatisxd** [comment]
no life kid

**Comment by ImagicalGamer** [comment]
Get a life kid, this is the official repo

**Comment by TDMidkwhatisxd** [comment]
why no ban and block spammers? I made a repo with last stable tesseract, in case it will die,
I didn't see a usefull commit in days.

**Comment by Borduni** [comment]
NFGamerMC, pls stop that

**Comment by TDMidkwhatisxd** [comment]
NFGamerMC is just a kid! He banned me wen I wanted to propose a fix, then deleted my comment,so nobody can see why I was banned. This is so wrong.

**Comment by Borduni** [comment]
dafuq

**Comment by NFGamerMC** [comment]
1: Not a kid
2. I didn't ban you

**Comment by Borduni** [comment]
I reported him on Github. Hope, there are banning him xD

**Comment by Borduni** [comment]
@NFGamerMC Why you are faking Tesseract?

**Comment by NFGamerMC** [comment]
This one is broke! He broke it!

**Comment by TDMidkwhatisxd** [comment]
https://github.com/TesseractTeam/Tesseract/issues/565
Don't lie kid, you are the one with c: Banned , I was banned until u got kicked

**Comment by NFGamerMC** [comment]
Sorry Then, if there is swearing in an issue I must remove the the issue, also I didn't ban you. I just put in the label

**Comment by TDMidkwhatisxd** [comment]
I was banned, and I was not swearing, I didn't even talked bad

**Comment by NFGamerMC** [comment]
Okay, I am very sorry then. Can you tell me what the issue was about

**Comment by TDMidkwhatisxd** [comment]
I told u that I fixed items drops, items should not be droped, instead get it back in inventory.
I already made a pr and got merged, after apple left.

**Comment by NFGamerMC** [comment]
Ohh. Sorry about that. Also Apple did not leave someone kicked him from his own org. His name is jrodr10 (LinuxLogo)

**Comment by TDMidkwhatisxd** [comment]
Apple is trying to take all forks in a org and terminate all

**Comment by NFGamerMC** [comment]
Okay, I didn't know that!

**Comment by NFGamerMC** [comment]
I want to make a new Tesseract, this one is broken as jrodr10 is not an actual dev.

**Comment by TDMidkwhatisxd** [comment]
same to you too ^^

**Comment by jrodr10** [comment]
Okay @NFGamerMC stop fucking making stupid issues that aren't even issues. How is making it harder for me to see real issues good for the software. You can grow with us and help maintain it or get the Fuck out of here already for fuck sake it's fking pointless nothing you do will change it. So just fking stop ur annoying asf

**Comment by NFGamerMC** [comment]
Okay, I will grow up and maintain!

**Comment by NFGamerMC** [comment]
Now please add me back!

**Comment by lowingly** [comment]
Since you came later, you did something bad, such as: wrong to add a label to the problem, send spam, move tesseract. At least I think so.
I do not deny your ability, but I think you are not suitable for managing tesseract.
As a tesseract user, I only need a team dedicated to updating tesseract.
Not to see you constantly quarreling.
I think this is the official tesseract, do not move it.
If you like tesseract, you can pull a request.
 @NFGamerMC

**Comment by NFGamerMC** [comment]
1. That was for good reason, I didn't want to tell him the actual reason
2. That was because no one would listen 
3. That was because no one could acces this one at the time
4. Why gout gotta be so rude?

**Comment by jrodr10** [comment]
I added you back to the repo as a member, contribute as much as you can and never... I mean never ask for ownership of this repo in ur life. Only person deserving of such a title would be @imagicalgamer if he were a bit more active. No one else comes close.
