### ISSUE TITLE
who is the owner?

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [TesseractTeam/Tesseract#962]
I just wanna to know, what is the future of tesseract?

**Comment by Borduni** [comment]
I hope, that Tesseract will not be discontinued like Elywing. I don't wanna use PocketMine-MP. Their Code is not optimized and works really slow

**Comment by TDMidkwhatisxd** [comment]
From what I know, is that apple got into a organization that "worship" pmmp, and he wanna terminate all forks!
Add me on kik or, what app you have, so if I use a new fork I can share with you!

**Comment by Nought57** [comment]
There are others who hate meaningless src.
He will not crush trustworthy forks.

**Comment by Nought57** [comment]
There are others who hate meaningless src.
He will not crush trustworthy forks.

**Comment by TDMidkwhatisxd** [comment]
nope, he try to crush all forks, he is on revivalpmmp , a group that worship pmmp, and spam on forks

**Comment by NFGamerMC** [comment]
What is your Discord?

**Comment by TDMidkwhatisxd** [comment]
TeamSpeak/KIK

**Comment by Nought57** [comment]
There are others who hate meaningless src.
He will not crush trustworthy forks.
Tesseract also went well along the way...

**Comment by NFGamerMC** [comment]
I only do Discord!

**Comment by TDMidkwhatisxd** [comment]
good for u ;)

**Comment by NFGamerMC** [comment]
-_-

**Comment by NFGamerMC** [comment]
Can someone add me so I can fix this mess.

**Comment by TDMidkwhatisxd** [comment]
imma make acc now xd

**Comment by NFGamerMC** [comment]
Kk

**Comment by Nought57** [comment]
He forgot what mattered. User has changed him.
Users do not value src. This is all the culprit.

**Comment by TDMidkwhatisxd** [comment]
I don't care! He should make his own repo and done!

username asterW10

**Comment by Nought57** [comment]
I have been developing src for nearly 3-4 years and I know his feelings

**Comment by TDMidkwhatisxd** [comment]
how come, you all developed for years, and still unexperienced. -.-'

**Comment by Nought57** [comment]
Siy, I do not understand what you are talking about.

**Comment by Nought57** [comment]
I said I understood his feelings. but, I do not say he is right.

**Comment by NFGamerMC** [comment]
Okay, can I be added back. I am the manager of continuous integration, forums (coming soon), and web development!

**Comment by TDMidkwhatisxd** [comment]
I really, don't care why he do that ^^ . All I care is about what he try to do.

**Comment by Nought57** [comment]
We can not stop him... They change their names and resurrect...

**Comment by TDMidkwhatisxd** [comment]
We can, Tesseract is a spoon, anyone can copy/paste, all we need is a reliable dev

**Comment by NFGamerMC** [comment]
What I mean is how I was the manager of everything related to the Tesseract Community

**Comment by TDMidkwhatisxd** [comment]
Until you banned me :/

**Comment by Nought57** [comment]
Since he pressed the commit to the member, there are no excellent developers anymore.
Tesseract developer got tired and disappeared...

**Comment by NFGamerMC** [comment]
For the last time, all I did was put the label "c: banned" I didn't actually ban you!

**Comment by Nought57** [comment]
Tesseract is dead soon. but, The origin of Tesseract is alive.

**Comment by Nought57** [comment]
keep a secret

**Comment by NFGamerMC** [comment]
Okay, I can

**Comment by TDMidkwhatisxd** [comment]
asterW10#8080
