### ISSUE TITLE
Won't run on Windows 10 (Creator's Update)

### ISSUE THREAD

**Issue by TheModdersDen** [TesseractTeam/Tesseract#964]
#### Problem description
When I run the 'start.cmd' script, nothing happens.

#### Steps to reproduce the issue
Use the windows installer, then run the 'start.cmd' script and nothing should happen.

#### OS and versions
Windows 10 Creators Update (desktop computer)

#### Crashdump, backtrace, memory dumps, plugins list or other files
None to post, as literally nothing happens in the command window. I've tried running it as Admin, in a PowerShell window, etc. and nothing is displayed. I've deduced the line in question to this one:
"%PHP_BINARY% -c bin\php %POCKETMINE_FILE% %*"

Any ideas? I'm going to try to run this with Windows 10's built in bash (that's hidden and only available to develoers)...
EDIT: As there is an apparent lack of documentation on how to start this in Linux (or Ubuntu), I can't attempt to start it.

**Comment by TDMidkwhatisxd** [comment]
for Linux, you need php bin file, src , start.sh , and done, you can set it up.
src, bin, start.sh need to be in same folder.

**Comment by PluginBOXone** [comment]
Download my data! I have made it ready to start for Windows 10 (just click the start.cmd) --> https://github.com/PluginBOXone/Tesseract-MCPE-Windows

**Comment by TheModdersDen** [comment]
Alrighty! PluginBOXone, your fix worked. I'm running MCPE v1.0.7, so I can't connect and test it, but it at least runs on Windows 10.
Also, are there any working plugins for the Tesseract project?

**Comment by PluginBOXone** [comment]
I am going to update it yet :) Maybe there is coming a message in your console like this "RakLib crashed..." if this is coming please write me here ... :) I am german xD

**Comment by TheModdersDen** [comment]
Don't see anything about RakLib crashing, so we're good there... I'll wait for the update I guess... :)

**Comment by PluginBOXone** [comment]
Update is online :) If you like to see my server ... message me on my GitHub uploaded files!

**Comment by TheModdersDen** [comment]
OK. I'm trying to connect to my server locally, and it says: "Unable to connect to world." Any idea why?

**Comment by PluginBOXone** [comment]
Wait

**Comment by TheModdersDen** [comment]
Also, it can't seem to retrieve the server... It just stays there and says: "Locating server" on the main menu. It's the same for Nukkit too,.. I have no clue how to fix this. Any ideas?

**Comment by PluginBOXone** [comment]
#Properties Config file
#Fri Apr 21 20:03:01 BST 2017
motd=PluginBOXone Minecraft: PE
server-ip=Go into your CMD, make ipconfig, paste the IPv4 adress here!
server-port=19132
white-list=off
announce-player-achievements=on
spawn-protection=16
max-players=20
allow-flight=off
spawn-animals=on
spawn-mobs=on
gamemode=0
force-gamemode=off
hardcore=off
pvp=on
difficulty=1
generator-settings=
level-name=world
level-seed=
level-type=DEFAULT
enable-query=on
enable-rcon=off
rcon.password=ytOzsCA89R
auto-save=on
online-mode=off

**Comment by PluginBOXone** [comment]
#Properties Config file
#Fri Apr 21 20:03:01 BST 2017
motd=PluginBOXone Minecraft: PE
server-ip=localhost
server-port=19132
white-list=off
announce-player-achievements=on
spawn-protection=16
max-players=20
allow-flight=off
spawn-animals=on
spawn-mobs=on
gamemode=0
force-gamemode=off
hardcore=off
pvp=on
difficulty=1
generator-settings=
level-name=world
level-seed=
level-type=DEFAULT
enable-query=on
enable-rcon=off
rcon.password=MyPasswordHerexD
auto-save=on
online-mode=off

**Comment by PluginBOXone** [comment]
Now go into your mcpe or w10 and type in at the IP: localhost and port: 19132

**Comment by PluginBOXone** [comment]
1. Go in your browser and type in 192.168.0.1 then go into settings and make "port-forwarding" and then type in 19132 and your IP (you can get the ip by going into cmd: ipconfig ) Its the IPv4 adress!

**Comment by TheModdersDen** [comment]
I've had the port forwarding part done, so that's not the issue. I just tried the config that you provided, and it still doesn't work. Any other ideas? Is there any known incompatibility with these kinds of Minecraft servers and antiviruses (Avast, in my case)?

**Comment by TheModdersDen** [comment]
Nevermind... Got it to work. Turns out I had to connect using my outside IP. :)

**Comment by TheModdersDen** [comment]
Closing this...
