### ISSUE TITLE
People are Demanding!

### ISSUE THREAD

**Issue by NFGamerMC** [TesseractTeam/Tesseract#967]
Hey @jrodr10,
People are demanding phars. They have been asking me like crazy if I have one for 1.0.7. Can I be owner just for a minute so I can setup the phar building system. I **PROMISE** not to kick you as I think you are a better person to manage Tesseract! #RottenApple

**Comment by MCPEGamerJPatGitHub** [comment]
@NFGamerMC You can build phars using DevTools. If they can't do that, they shouldn't have it.

**Comment by NFGamerMC** [comment]
IK, most people are dumb and can't

**Comment by MCPEGamerJPatGitHub** [comment]
@NFGamerMC That's what you think. That's fine. But as far as I am concerned you just want Owner rights to the repo to kick Linux out. The way you ask for it tells the answer.

**Comment by NFGamerMC** [comment]
i keep my word, take a screenshot. If I kick him you all can report me and I will close my GitHub account (after backup)

**Comment by NFGamerMC** [comment]
I a, not kidding, if I am Lieing report me and kick me out of GitHub

**Comment by TDMidkwhatisxd** [comment]
I will lol so hard if Linux get kicked

**Comment by NFGamerMC** [comment]
Okay, remember you all can report me if I kick him

**Comment by TDMidkwhatisxd** [comment]
you wont get banned! ^^ , report useless

**Comment by RocoWayne** [comment]
I have tesseract running with 1.0.5 , 1.0.6 and 1.0.7 and works just fine... Sadly it does not work win 1.0.0 to 1.0.4 :(

**Comment by NFGamerMC** [comment]
That will cause issues

**Comment by TDMidkwhatisxd** [comment]
that wont cause a single issue. Why? There are not extra ports added, just info port that's all.

**Comment by ZizzyZizzy** [comment]
You can build a phar easily yourself using PHP:

```
# cat createphar.php

#!/usr/bin/php
<?php
        if(count($argv) < 3) {
                echo "Usage:\n\ncreatephar.php <output.phar> <unpacked/src/xxx/defaultloader.php>\n";
                exit(1);
        }
        $filename=$argv[1];
        if(file_exists("$filename")) {
                echo  "\tERROR: '$filename' exists. Will not over-write. Delete it first..\n\n.";
                exit(1);
        }
        $defaultstub=$argv[2];
        if(!file_exists("$defaultstub")) {
                echo  "\tERROR: '$defaultstub' not found.\n\nInclude [builddir] in the path - I will strip it out.\n\n";
                exit(1);
        }
        $arr = explode("/", $defaultstub, 2);
        $builddir = $arr[0];
        $defaultstub=preg_replace("#$builddir/#","",$argv[2]);
        $phar = new Phar("./$filename", 0, "$filename");
        $phar->buildFromDirectory("./$builddir");
        $phar->setStub($phar->createDefaultStub($defaultstub));
        exit(0)
?>

```

Assuming you've unpacked the source code to the default directory of Tesseract-master, create a .phar like this:

`createphar.php Tesseract.phar Tesseract-master/src/pocketmine/PocketMine.php`

This also works for plugins!

Courtesy of **Virtual Gladiators Minecraft/Pocketmine Server Hosting.**

**Comment by Aericio** [comment]
kek virtual gladiators

**Comment by jrodr10** [comment]
Thanks you Virtual Gladiators

**Comment by NFGamerMC** [comment]
jrodr, you can ban me if I kick you. You can tell everyone and report me. People need there ci

**Comment by jrodr10** [comment]
I will never make another person Owner again bud sorry.

**Comment by NFGamerMC** [comment]
What about ImagicalGame?
