### ISSUE TITLE
Probleme to connect server

### ISSUE THREAD

**Issue by Barlaf** [TesseractTeam/Tesseract#971]
#### Problem description

Hello, I can not connect to my server. When I connect I receive the message "Disconnect from the server". I then restarted the server several times. A solution to this problem? Cordially, Barlaf

* Tesseract: Tesseract-1.2.1 RottenApple
* PHP: 7.0.10
* Server OS: I don't know
* Game version: 1.0.7
* Server host: HostMyServer

**Comment by AffanStarPure** [comment]
Yes same too I can not connect the Server

**Comment by PluginBOXone** [comment]
Is there a message in the console like "RakLib crashed..." ?

**Comment by Barlaf** [comment]
No, there is no "RackLib crash". The server normally works just can not connect to it

**Comment by PluginBOXone** [comment]
Are you hosting on Linux or Windows?

**Comment by Jestus5225** [comment]
I also have this **problem**!

**Comment by AppleDevelops** [comment]
I'd help but I'm not a part of the repo.

**Comment by Barlaf** [comment]
Her server is on Linux

**Comment by jrodr10** [comment]
Is this due to the protocol hack?

**Comment by AffanStarPure** [comment]
Idk but i cannot in game is said disconnected form Server that no error too

**Comment by AppleDevelops** [comment]
I cannot reproduce it on the latest version.

**Comment by Barlaf** [comment]
Hum... 
I found the problem. This is the PurePerm plugins (the one that handles the permissions) that causes the problem. So a solution because I used PurePerm to use PureChat

**Comment by FienixEC** [comment]
are you using an outdated version of pure perms? i use the latest Perms/Pchat plugins, running the latest tesseract src, on linux OS and do not have that issue. i know theres a pureperms version out there with many issues

**Comment by imjayl** [comment]
Why it would be the pureperm problem?

**Comment by FienixEC** [comment]
I wouldnt think so either @imjayl . Come to think of it, its happened to me 2 times, (happened about 2 hours ago) where i cant connect to my server due to the same issue, i get the same message "unable to connect to world" and i pardon my ip, and im able to join right away. not sure why that happens as my ip doesnt show as banned in my ips.txt file during the time

**Comment by ZaydPE** [comment]
Re-install PurePerms but bump it's API. PurePerms, CustomAlerts and more are widely used plugins with very old API's.

**Comment by MCPEGamerJPatGitHub** [comment]
@ZaydPE Plugins does not seem to be the issue here. I am using a fresh install of Tesseract but the same issue exist.

**Comment by ZaydPE** [comment]
It happened to me, I re-installed outdated API's and then everything was fine. Issue definitely happens because of PurePerms. Try removing PurePerms and joining

**Comment by AffanStarPure** [comment]
I use old version Tesseract 1.0.6 all plugin work for me when Update 1.0.7 not work is said disconnected form Server

**Comment by NFGamerMC** [comment]
Why not switch to BlueLight

**Comment by Barlaf** [comment]
@NFGamerMC BlueLight ? And @imjayl When I remove PurePerm everything works correctly. My version of PurePerm is "1.4.0-INDEV" (I update the API) @FienixEC

**Comment by AffanStarPure** [comment]
So PurePerms Problem Only?

**Comment by Barlaf** [comment]
Yes @AffanStarPure when I delete PurePerm I can join my server

**Comment by AffanStarPure** [comment]
Oh @Barlaf  Thank but where I can get PurePerms Work to on server Tesseract? Should I use old API or the new one? I need link too to get PurePerms

**Comment by Barlaf** [comment]
@AffanStarPure For get open source PurePerm : 
https://github.com/PurePlugins/PurePerms/blob/master/plugin.yml
But me, I delete PurePerm. Idk who poses problem in pureperm

**Comment by FienixEC** [comment]
@Barlaf email me at fienixjp@gmail.com ill send you my version of pureperms, install it and try

**Comment by jrodr10** [comment]
So pureperms bug 🤔

**Comment by DerddyDert** [comment]
I was able to reproduce this using the Pureperms available on poggit. That version is the one that caused the issue.

**Comment by imjayl** [comment]
@DerddyDert im using the oldest pureperms but it's working on the previous tesseract version (1.0.4 to 1.0.6) .

**Comment by caspervanneck** [comment]
yes its plugin bug i wiped my server and it working

**Comment by caspervanneck** [comment]
@Barlaf downgrade pureperms and purechat that shult fix it i can give you the plugins

**Comment by caspervanneck** [comment]
here pureperms fix replact the phar

**Comment by caspervanneck** [comment]
https://drive.google.com/open?id=0B1Cw5aPWlm3iR3BjUEkyMjR0TmM

**Comment by DerddyDert** [comment]
Im running pureperms 1.3.7 since I had the disconnect error. Works great.

**Comment by jrodr10** [comment]
Same I had to redo my perm files. I wonder what the cause it thoe

**Comment by ImagicalGamer** [comment]
Can you please get a PHP debug backtrace and put it on pastebin then put the link here.

**Comment by jrodr10** [comment]
@Barlaf @AffanStarPure @PluginBOXone @Jestus5225

**Comment by imjayl** [comment]
Its not pureperms. I used bluelight to test it.

1.0.6-1.0.7 can join the server with pureperms

**Comment by caspervanneck** [comment]
@imjayl  we arent bluelight so yea

maby some thing have change in Tesseract or pureperms

**Comment by DerddyDert** [comment]
@imjayl You tested with the Pureperms version that reproduces the problem?

**Comment by MCPEGamerJPatGitHub** [comment]
I have no problem using the PurePerms v1.3.3 made for API 2.0.
I can join normally & have no issues.
Maybe you did something wrong?

**Comment by imjayl** [comment]
@DerddyDert Yes

@MCPEGamerJPatGitHub using pureperms & 1.0.7 Tesseract?

**Comment by imjayl** [comment]
Please use the last 1.0.6 Version and change its protocol to 1.0.7 and i will test it if its working with pureperms.

**Comment by MCPEGamerJPatGitHub** [comment]
@imjayl yep, I don't think the new version of pureperms is stable so I use the old version.

**Comment by MCPEGamerJPatGitHub** [comment]
to conclude this is a plugin issue.
we advise for someone to close this issue.

**Comment by imjayl** [comment]
Im using PurePerms 1.4.0. Can you give your copy of the old version?

**Comment by MCPEGamerJPatGitHub** [comment]
@imjayl It is on the old PocketMine forums.
