### ISSUE TITLE
REDSTONE 

### ISSUE THREAD

**Issue by NemanjaMAX** [TesseractTeam/Tesseract#972]
Please add Redstone back, thanks

**Comment by jdongel2004** [comment]
Has many lag.

**Comment by LagHD** [comment]
I think this is already on the ToDo List, hopefully it will be added within the next few months!

**Comment by jrodr10** [comment]
Pretty sure you can enable Redstone in the tesseract.yml file. I'll double check and test

**Comment by AppleDevelops** [comment]
@jrodr10 There isn't one yet, I removed it.

**Comment by jrodr10** [comment]
@AppleDevelops working on this?

**Comment by jrodr10** [comment]
good idea or bad idea @ImagicalGamer

**Comment by AppleDevelops** [comment]
@jrodr10 I have a wip custom build with a Nukkit Redstone system, but I'd like my ownership back

**Comment by LagHD** [comment]
@AppleDevelops Would it be possible to make a Redstone System plugin for Tesseract?

**Comment by ImagicalGamer** [comment]
@LagHD Yes, red stone could be done via plugin.

**Comment by LagHD** [comment]
@ImagicalGamer Would you guys be able to make one for us?!

**Comment by NFGamerMC** [comment]
SPAM

**Comment by jrodr10** [comment]
@NFGamerMC this will be added back soon

**Comment by AppleDevelops** [comment]
lmao

**Comment by junkdude** [comment]
@jrodr10 doesnt know how
