### ISSUE TITLE
INVALID NAME error

### ISSUE THREAD

**Issue by articrevised** [TesseractTeam/Tesseract#98]
when it try to connect to my server i first got "Unable to connect to world" now i get "Invalid Name" and i'm running MC on windows 10 version so can i fix this without changing my Xbox Live Gamertag because i already changed it once and i don't want to pay $10.

help!

**Comment by xZeroMCPE** [comment]
Well, I"ll add a setting that you can turn on and off that lets player with space in there username join. But please be advised that some plugins may break..
