### ISSUE TITLE
No sound again?

### ISSUE THREAD

**Issue by DerddyDert** [TesseractTeam/Tesseract#999]
#### Steps to reproduce the issue

Just did a fresh install of 1.2.1 and noticed there is no sound again. 1.2.0 had sound. What exactly is the issue with sound? Do you guys need help, resources etc? Is there anything that I can do or provide to help with getting sound to function stably? Thanks
#### OS and versions

* Tesseract: Tesseract-1.2.1 RottenApple
* PHP: 7.0.3
* Server OS: Ubuntu
* Game version: 1.0.7
* Server host:
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by jrodr10** [comment]
do you happen to still have the 1.2.0 version that had sound? if so please email it to me in a src.zip file to linuxlogo@hotmail.com

**Comment by DerddyDert** [comment]
I got a phar will that do?

**Comment by Prisane** [comment]
@jrodr10 this merge still sounds works
https://github.com/TesseractTeam/Tesseract/tree/resource-packs

**Comment by ImagicalGamer** [comment]
I'm sure we would have working sounds by now if Linux stopped fucking around and gave the repo back to the owners. Your not making anything better, you've only made Tesseract worse.

**Comment by ImagicalGamer** [comment]
@jrodr10 ^

**Comment by LordJoshie** [comment]
I have an older copy of the 1.0.5 src, if that helps...

**Comment by LordJoshie** [comment]
trash:///src

**Comment by LordJoshie** [comment]
[Tesseract_1.0.5.zip](https://github.com/TesseractTeam/Tesseract/files/949474/Tesseract_1.0.5.zip)

**Comment by Qimie** [comment]
Cant we just use PlaySoundPacket and add range thingy. @AppleDevelops @jrodr10 @ImagicalGamer @jrodr10 @Nought57 @dktapps Lol I'm a beast

**Comment by jrodr10** [comment]
@imagicalgamer I'm already to far in. Let's not focus on who has permission to delete the repo. Since that is the whole reason why I am doing this lol, let's focus on pushing some useful commit. I'm not knowledgeable in PHP per-say but I am not idiotic interns of other languages such as Java and Javascript. There is a player bug here and I'm not sure why it won't let some people connect but it's out here somewhere

**Comment by jrodr10** [comment]
@Qimie possibly create a PR, we'll see if it passed Travis tests if so I'll push it to master

**Comment by jrodr10** [comment]
XD

**Comment by KairusDarkSeeker** [comment]
@jrodr10 bruh there's no bug on the resource packs commit

**Comment by DerddyDert** [comment]
You guys are too funny! The BlameLinux tag? hahaha Anyways, I appreciate your hard work.

**Comment by SuperMaXAleX** [comment]
L-M-F-A-O.
Linux just deleted what I did, so it's normally there aren't any sounds

**Comment by DerddyDert** [comment]
@SuperMaXAleX What did you do?

**Comment by jrodr10** [comment]
@KairusDarkSeeker it wont let players join

**Comment by jrodr10** [comment]
@SuperMaXAleX re add sound

**Comment by KairusDarkSeeker** [comment]
@jrodr10 it does let players join

**Comment by G2PCraft** [comment]
@jrodr10 Can it help u??
https://github.com/TesseractTeam/Tesseract/tree/a191454266fcaca96f821598a2636e636a0e7b59

**Comment by daniktheboss** [comment]
Get your priorities straight. This is same as a player cant mine, sounds are the cherry on top for a server. No sound = lame af server which is gay and no interaction with the world/players.

**Comment by AppleDevelops** [comment]
I'd have that fixed but Mr. Fucktard owning the repo is screwing it over

**Comment by Qimie** [comment]
Yeah. True. I agreed

**Comment by daniktheboss** [comment]
Dear linux, fuck you.

**Comment by Pizzahaet** [comment]
@jrodr10 L

**Comment by KairusDarkSeeker** [comment]
Use nukkit

**Comment by daniktheboss** [comment]
Suck off, so should I just delete every plugin?

**Comment by KairusDarkSeeker** [comment]
@daniktheboss nah just port all of them like I'm going rn

**Comment by AppleDevelops** [comment]
@daniktheboss Use PMMP

**Comment by KairusDarkSeeker** [comment]
@AppleDevelops Good idea

**Comment by AppleDevelops** [comment]
@KairusDarkSeeker It's much faster and better than this

**Comment by AppleDevelops** [comment]
Pretty simple fix.
I wouldn't blame Linux if he'd like to you know, *copy* this.

https://github.com/TesseractTeam-v2/Tesseract/commit/759f870d7bafb340e5845db3d159381cabe27d11
